### ISSUE TITLE
Save To Issue

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1000]
When running rtorrent 0.9.4 the "Save To" option doesn't appear to function.

Rutorrent revision 2600
Rtorrent 0.9.4/0.13.4
Apache 2.2.22
Debian 7 (64 bit)

**Comment by Novik** [comment]
Try to install plugun datadir.
https://github.com/Novik/ruTorrent/wiki/PluginDataDir

**Comment by Pingblue** [comment]
Yes this plugin is already installed.

Downgrading to rtorrent 0.9.3 resolved the issue but would really like to use the latest SVN version of rtorrent.

**Comment by Novik** [comment]
ruTorrent hasn't more any sort of "SVN revision". Try to use development version from github.

**Comment by Pingblue** [comment]
I just tested with the Github version and the "Save to" option still doesn't work with rtorrent 0.9.4.

You can select the location with the "Save to" option but the location is never actually changed.

**Comment by Novik** [comment]
1) You should use develompent version of plygins too.
2) Can't reproduce this. Check web-server error's log, rutorrent errors log etc.
