### ISSUE TITLE
Allow configuration of connection to rutorrent

### ISSUE THREAD

**Issue by krichter722** [Novik/ruTorrent#1009]
Currently `rutorrent` (3.6) only displays a message that the connection to `rtorrent` has not yet been established. I'd be useful to provide a way to configure this configuration and log and the details of the connection attempts if they fail. In case `rutorrent` guesses the connection the feedback for the user should be improved.

**Comment by salvo2002** [comment]
+1

**Comment by Novik** [comment]
Sorry, but i can't make something useful here.
