### ISSUE TITLE
Safari 0.8.3 Issue

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1013]
Rutorrent will not load in Safari 8.0.3 (10600.3.18) OS X Yosemite 10.10.2

I also tried the development version of rutorrent but still cannot connect.

The web server is Apache and nothing is showing in the logs.

When loading rutorrent the page just gets stuck on loading.

**Comment by Novik** [comment]
Sorry, but i havent Safari and havent possibility of obtain it.
1) Try to disable all plugins and check yet once.
2) Check contents of JS console in browser for errors.
3) Of course, you should use development version, problems of stable 0.3.6 is not interesting for me.
