### ISSUE TITLE
change many tracker in same time

### ISSUE THREAD

**Issue by Flayor** [Novik/ruTorrent#1015]
Hi novik,

I wanted to know if it was possible to change the multi torrent tracker same time?

One by one is very long .. especially when there are more than 200.

Where it is a function to do with rtorrent / libtorrent

Thanks

**Comment by Novik** [comment]
It possible. But if you need to change trackers in 200+ torrents, then this is a not task of WebUI. Try to write script or something like that.

**Comment by Flayor** [comment]
The last time I used a script that I deleted all of .torrents rutorrent  :/

ex ici http://puu.sh/g8hvp/2c361cc478.png 

right click on the tracker concerned and change everything at once
