### ISSUE TITLE
Update screenshots plugin to use avconv instead of ffmpeg

### ISSUE THREAD

**Issue by Zumochi** [Novik/ruTorrent#1025]
The screenshots plugin is making use of the `ffmpeg` command from Libav, which has been deprecated for a while.

The 'new' command to use should be `avconv`.

Note: this is for Debian-based distributions only. I am not sure about other distro's.
Perhaps it's an idea to try either of the two? The commands them self are quite similar afaik.

**Comment by JohnFlowerful** [comment]
It appears that the bigger distros (i.e. Ubuntu, Mint) use libav... All I know is that [us Gentoo users prefer ffmpeg](https://forums.gentoo.org/viewtopic-t-1010096-highlight-ffmpeg.html), so having an option to satisfy both groups would be beneficial.

**Comment by alexcoe** [comment]
ffmpeg is not depreciated at all and can still be installed from a repo or built from source along side avconv.

**Comment by Zumochi** [comment]
@alexcoe the _command_ `ffmpeg` from the _package_ Libav is deprecated (to avoid this confusion).
FFmpeg itself is not deprecated.

**Comment by rtorrentuser** [comment]
Just replace the line

$pathToExternals['ffmpeg'] = '';		// Something like /usr/bin/ffmpeg. If empty, will be found in PATH.

with

$pathToExternals['ffmpeg'] = '/usr/bin/avconv';		// Something like /usr/bin/ffmpeg. If empty, will be found in PATH.

in the plugin's conf.php file and be happy...:-)

**Comment by Zumochi** [comment]
Guess I'll stick to that then.

Cheerio.

**Comment by MarkusLange** [comment]
Thanks a lot rtorrentuser
