### ISSUE TITLE
[Enhancement] Dont lose stats when restarting rutorrent

### ISSUE THREAD

**Issue by user1234567891011** [Novik/ruTorrent#1027]
All the stats seem to reset when I have to restart ruTorrent. I.e the Total downloaded/uploaded counters reset to zero.

Would it be possible to make these only reset if the user requests it? Either through the settings menu or via terminal.

**Comment by Novik** [comment]
ruTorrent is a front-end. It hasn't relation to resetting stats. Stats will be resseted, if you restart *rtorrent* i.e. client.

**Comment by user1234567891011** [comment]
Ah ok, I was assuming the stats were stored in ruTorrent. I'll make a request in the rtorrent repository instead. Apologies.
