### ISSUE TITLE
Support for Windows rTorrent in ruTorrent

### ISSUE THREAD

**Issue by iG8R** [Novik/ruTorrent#1030]
Please, could you be so kind as to create working version of ruTorrent for Windows rTorrent (https://rtwi.jmk.hu/wiki/rTorrentOnWindows).
Now, there is an issue with "util.php", e.g.:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65997 bytes) in C:\nginx\html\php\util.php on line 313"

More information about issues:
http://forums.rutorrent.org/index.php?topic=6449.0

**Comment by drmike** [comment]
Looking at the referenced thread, this should probably be closed.  Devs have stated that a version for Windows isn't going to happen and it appears the memory issue was looked into. (That's a server issue anyway)
