### ISSUE TITLE
composer integration

### ISSUE THREAD

**Issue by nelu** [Novik/ruTorrent#1031]
any plans for composer autoload integration in the near future?

**Comment by Novik** [comment]
At this moment - no. Because i doesn't know, what is this ;)

**Comment by nelu** [comment]
php namespaces and this http://www.php-fig.org/psr/psr-4/ with an autoloader like composer (omitting those require/include 's), including files as you use their containing classes.

**Comment by tavy315** [comment]
Almost 4 years later, no composer integration? Instead of using "require", autoloading can be used.

**Comment by nelu** [comment]
some refactoring needs to be done to achieve this
