### ISSUE TITLE
add multiple torrent simultaneously

### ISSUE THREAD

**Issue by Flayor** [Novik/ruTorrent#1032]
Hi,

When I want to add multiple streams simultaneously (10-20) this does not work, it does not add any.

I use the development version

at least with the plugins add a torrent.

In "drag drop" it work

thank you

**Comment by Novik** [comment]
> at least with the plugins add a torrent.

1) What do you mean?
2) What about version of browser?
3) What about web-server errors log?

**Comment by Flayor** [comment]
Sorry for the latence

1) I using the latest version of rutorrent

2) update

3) No error

**Comment by Novik** [comment]
1) Yet once. *How* you tried to add multiple torrents? Describe that, please.
2) Sorry, i don't know anything about browser named 'update'.

**Comment by JohnFlowerful** [comment]
Check php.ini for max_file_uploads. Increase it if it's too low.
