### ISSUE TITLE
[Data Plugin] Torrent name with accent are not handled correctly

### ISSUE THREAD

**Issue by R1kk3r** [Novik/ruTorrent#1034]
If you have a torrent that contains any accent (é, è à, etc) in its filename AND bigger than 2 GB, then you cannot download the file with the Data plugin (Right-click > Download file).

The file "action.php" (from Data plugin) send the file using the function "sendFile()" from "util.php". The latter retrieve the stat of the file using "@LFS::stat()" from "lfs.php". Because integer in PHP are signed, the stat function have two differents mecanisms to retrieve the stat of a file: One for a file smaller than 2GB and the other for one bigger than 2GB. The latter use "exec()" to execute the "stat" command with the filename as argument. Before that, the filename is given to "escapeshellarg()". Unfortunately, "escapeshellarg()" depends on the current locale. If the LC_TYPE is not defined or defined on "en_US.UTF-8" for example, then a filename with accent character will be transformed without the accent and the path will be invalid and the download will not start. So, to resolve the problem, you need to set the locale to another one. In my case, I have put setLocale(LC_CTYPE, "fr_CH.UTF-8") into the config.php.

I don't know if there's a "general" locale? Because the accent is working this way but I'm not sure that a filename with japenese or spanish special character for example will work with the "fr_CH.UTF-8" locale. I think it need more testing...

**Comment by Novik** [comment]
Edit php/utl.php:66, add empty string as second parameter.
```
setlocale(LC_CTYPE, "", "UTF8", "UTF-8", "en_US.UTF-8", "en_US.UTF8");
```
this helps?

**Comment by R1kk3r** [comment]
Not working with the empty string but with "fr_CH.UTF-8" yes (instead of config.php).

**Comment by Novik** [comment]
Do you have a correct configured LANG variable in the www user environment?

**Comment by Novik** [comment]
I add corresponding option ($locale) to the config.php.

**Comment by R1kk3r** [comment]
Yes I have. But it's weird that escapeshellarg() function depends of the locale... Because with my settings to "fr_CH.UTF-8", I am able to download files with special character like é è á but I'm not sure if, for example, I can download a file (bigger than 2GB) with some Portuguese or Greek letter inside its name...
