### ISSUE TITLE
Change DL/UL speed to Mbit?

### ISSUE THREAD

**Issue by Kerwood** [Novik/ruTorrent#1037]
Hi.. Is it possible some how to change the Download/Uploade speed to Mbit/s instead for MByte/s ?

**Comment by Novik** [comment]
Its possible. In theory. But in practice - try to open Settings dialog and check 'Speed Popup List' position. What i should to show here, when user switch from MByte/s to Mbit/s?
Something like 124.56679, 258.235, etc? This is not good thing...
