### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by rahul0705** [Novik/ruTorrent#1040]
The Main Install page in the wiki states that in most distros rtorrent is not built with xmlrpc.This has been false since version [0.7.8 of Ubuntu](http://changelogs.ubuntu.com/changelogs/pool/universe/r/rtorrent/rtorrent_0.8.9-2/changelog) and [all versions of ArchLinux] (https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rtorrent&id=63f9f0b54624bf477a25efd801bc6cdb8b1cad27) (another common distro)

**Comment by alexcoe** [comment]
these are old versions current is 0.9.4/0.13.4

**Comment by rahul0705** [comment]
Agreed they are old version but all new version of these packages do not need to be compile from source. The main [install wiki] (https://github.com/Novik/ruTorrent/wiki/MainInstall) states
>Most distros do not come with rtorrent compiled with xmlrpc-c. ruTorrent REQUIRES rtorrent to be compiled with xmlrpc-c.

is completly incorrect. All versions after 0.7.8 are now built with xmlrpc-c

**Comment by Novik** [comment]
Please, write your own version and make corresponding pull request.

**Comment by rahul0705** [comment]
Github does not have pull requests for the wiki
