### ISSUE TITLE
Не работает авторизация на rutracker.org через loginmgr

### ISSUE THREAD

**Issue by as7lan** [Novik/ruTorrent#1042]
В логах ошибка
 PHP Warning:  fsockopen(): unable to connect to login.rutracker.org:80 (Connection timed out) in /var/www/rutorrent/php/Snoopy.class.inc on line 628
PHP Warning:  fsockopen(): unable to connect to login.rutracker.org:80 (Connection timed out) in /var/www/rutorrent/php/Snoopy.class.inc on line 628
PHP Warning:  fsockopen(): unable to connect to login.rutracker.org:80 (Connection timed out) in /var/www/rutorrent/php/Snoopy.class.inc on line 628
PHP Warning:  fsockopen(): unable to connect to login.rutracker.org:80 (Connection timed out) in /var/www/rutorrent/php/Snoopy.class.inc on line 628
PHP Warning:  fsockopen(): unable to connect to login.rutracker.org:80 (Connection timed out) in /var/www/rutorrent/php/Snoopy.class.inc on line 628

И дествительно. На трекере что-то поменяли и login.rutracker.org сразу скидывает.

**Comment by Novik** [comment]
Лично у меня все работает корректно. А "скидывает" у Вас потому, что Вы выполняете GET по url, на котором разрешен только POST.
Что до строчек лога - не знаю. Смотрите на предмет доступности rutracker.org с Вашего сервера (а не с клиента из под браузера).

**Comment by as7lan** [comment]
Проверил. Работает. Проблем с доступностью нету. Но вот все закачки с этого трекера помечены как удаленые. =( Хотя то не так.

**Comment by Novik** [comment]
В таком случае непонятно, по какой причине соединение с login.rutracker.org у Вас на сервере не проходит.

**Comment by as7lan** [comment]
нашел решение http://rutracker.org/forum/viewtopic.php?t=4578514
удалил ретрекер и действительно проблема решилась.

Теперь вопрос. Это проблема трекера или плагина?

**Comment by Novik** [comment]
Удаление ретрекера играет здесь ровно одним образом. При изменении состава трекеров торрент сначала удаляется, а потом добавляется как новый. Соответственно, плагином заново проверяется статус торрента.
Ровно того же Вы могли добиться, воспользовавшись советом из моего предыдущего комментария.

**Comment by as7lan** [comment]
Решилось. Была локальная проблема.
