### ISSUE TITLE
Updated Wiki

### ISSUE THREAD

**Issue by rahul0705** [Novik/ruTorrent#1043]
I have updated the wiki to reflect new changes in how packages are built.
I had to fork the wiki repo and make changes there. If you want me to make the changes straight in this wiki I can do this.

[The forked wiki repo can be found here](https://github.com/rahul0705/rutorrent-wiki)

**Comment by JohnFlowerful** [comment]
Is such a small change really necessary? You could be adding new info that relates certain systems as discussed [on the forums](http://forums.rutorrent.org/index.php?board=6.0).

**Comment by rahul0705** [comment]
Agreed it's a small change but most people go straight to the wiki when
they download the source code.

Regards,
Rahul Mohandas

--
Sent from Nexus 6
Everyone's self - worth should only be measured by how useful they would be
in a zombie apocalypse

**Comment by JohnFlowerful** [comment]
In reality more people should use their system's package manager to install software. The problem with that is obvious: the majority of distros are binary based, therefore some users must resort to compiling from source to get the desired feature set.

That would be great. The wiki is somewhat lacking in certain departments, namely secure webserver/php setup. If that is going to be part of your 'ansible role' (I have no idea what that means), be sure to include it :)

**Comment by rahul0705** [comment]
just as an FYI ansible is a configuration management tool think of it as a smart install script. It will gather facts and install/configure based on that. More info can be found in http://www.ansible.com/home

**Comment by Novik** [comment]
Really, problem with a projects wiki is a simple. My English is not enough for writing correct documentation. If somebody wants to supprt it on a regular basis, i may add him to projects collaborators.

**Comment by rahul0705** [comment]
I can try to help when I can if that would help out with this project. Also the wiki is editable by the public unless you go to setting and change it to only collaborators can edit the wiki. I found that out through a mistake I made.

**Comment by Novik** [comment]
I would be very grateful.

**Comment by rahul0705** [comment]
So how do we handle this change? Do I just make the change?

**Comment by Novik** [comment]
Yes.

**Comment by rahul0705** [comment]
Change has been made, closing issue. Novik lets discuss later about updating the wiki.
