### ISSUE TITLE
Аналог rutracker_check для nnm-club

### ISSUE THREAD

**Issue by a7lan** [Novik/ruTorrent#1045]
Планируется ли подобный плагин? Очень удобен rutracker_check, особенно когда добавляют новые серии в раздачи. на nnm-club все время приходиться в ручную добавлять торрент.

**Comment by Novik** [comment]
Да сделать то, в принципе, можно. Основная проблема там в том, что с данным трекером постоянно происходят всякого рода мутации. То адрес сменится, то система авторизации. Я умаюсь поддерживать результат. Подумаю.

**Comment by as7lan** [comment]
Сделайте, если не сложно, хотя бы в текущем виде чтоб работало)

**Comment by as7lan** [comment]
Нет новостей?)

**Comment by hapylestat** [comment]
отдельный плагин не нужен, по факту теперь логика по трекерам складируетса в подпапочке плагина plugins/rutracker_check/trackers/, а сам плагин можно переименовать во что то более общее. С другой стороны проблемма поттержки, не могу писать под трекер, которым не пользуюсь....т.к. не знаю его повадок :(

**Comment by a7lan** [comment]
Ну мне бы именно nnm-club) На рутрекере что ни раздача, то закрывается правообладателем, поэтому сейчас чаще всего пользуюсь nnm (особенно при поиске сериалов, а эти раздачи ведь каждую неделю обновляются). Предлагаю и вам начать им пользоваться)

**Comment by rtorrentuser** [comment]
Если всё ещё актуально, то потестите патч прилагаемый... У меня вроде работает... 
[nnmclub.patch.zip](https://github.com/Novik/ruTorrent/files/179211/nnmclub.patch.zip)

**Comment by Novik** [comment]
Извините, но в таком виде - не актуально. Актуально в виде pull request.

**Comment by rtorrentuser** [comment]
Далёк я от этого... Надо будет посмотреть, как это делается... Просто заявителю хотел предложить потестировать...

**Comment by a7lan** [comment]
Спасибо. Сегодня попробую проверить.

**Comment by Novik** [comment]
@rtorrentuser - форкаете проект (кнопка на тулбаре вверху справа) вносите нужные изменения в свою копию, говорите "создать pull request". Два клика мышью, фактически.

**Comment by rtorrentuser** [comment]
Спасибо, попробую...

**Comment by a7lan** [comment]
К сожалению не работает.

**Comment by rtorrentuser** [comment]
Ну, и славненько, что заработало.) У меня с неделю где-то работает без проблем...
