### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type multipart/related:

### ISSUE THREAD

**Issue by ne0ark** [Novik/ruTorrent#1047]
Get file from files doesn't seem to work on chrome beta.

I get the following error in js console:

Resource interpreted as Document but transferred with MIME type multipart/related: "https://site/plugins/data/action.php?hash=E5BE559658AE599E0E613585D534098CF1CC4384&no=0".m.event.trigger @ jquery.js:3(anonymous function) @ jquery.js:3m.extend.each @ jquery.js:2m.fn.m.each @ jquery.js:2m.fn.extend.trigger @ jquery.js:3m.each.m.fn.(anonymous function) @ jquery.js:4theWebUI.getData @ VM19895:1703(anonymous function) @ VM21300:1(anonymous function) @ objects.js:340m.event.dispatch @ jquery.js:3m.event.add.r.handle @ jquery.js:3
jquery.js:4 XHR finished loading: GET "https://site/plugins/autodl-irssi/getlines.php?cid=739003971&_=1428764789855".m.ajaxTransport.send @ jquery.js:4m.extend.ajax @ jquery.js:4autodl_ajax @ AutodlFilesDownloader.js:30AutodlIrssiTab._getNewLines @ AutodlIrssiTab.js:225(anonymous function) @ AutodlIrssiTab.js:145

**Comment by Novik** [comment]
Sorry, but i can't support browser's betas. Try to use stable version of browser.
