### ISSUE TITLE
Правильная сортировка файлов при создании torrent info из файлов

### ISSUE THREAD

**Issue by Jeronyson** [Novik/ruTorrent#1052]
В файле php/Torrent.php есть функция files($files, $piece_length) (строка 454)
В данный момент сортировка реализована следующим образом:
```php
sort( $files );
usort( $files, create_function( '$a,$b', 'return strrpos($a,DIRECTORY_SEPARATOR)-strrpos($b,DIRECTORY_SEPARATOR);' ) );
```
Таким образом сортировка получается в разнобой, а директории в конце.
```
Hash /home/rtorrent/test/file1.txt
Hash /home/rtorrent/test/file12.txt
Hash /home/rtorrent/test/file2.txt
Hash /home/rtorrent/test/file10.txt
Hash /home/rtorrent/test/folder2/file12.txt
Hash /home/rtorrent/test/folder2/file10.txt
Hash /home/rtorrent/test/folder2/file1.txt
Hash /home/rtorrent/test/folder2/file2.txt
Hash /home/rtorrent/test/folder1/file12.txt
Hash /home/rtorrent/test/folder1/file1.txt
Hash /home/rtorrent/test/folder1/file2.txt
Hash /home/rtorrent/test/folder1/file10.txt
Hash /home/rtorrent/test/folder12/file2.txt
Hash /home/rtorrent/test/folder12/file12.txt
Hash /home/rtorrent/test/folder10/file10.txt
Hash /home/rtorrent/test/folder10/file1.txt
Hash /home/rtorrent/test/folder10/file12.txt
Hash /home/rtorrent/test/folder10/file2.txt
Hash /home/rtorrent/test/folder12/file1.txt
Hash /home/rtorrent/test/folder12/file10.txt
```

Правильно будет сортировать человеко-понятным образом (1,2,10,12) с директориями вначале. Предлагаю такой вариант:

Функция sort совсем убирается из этого места.

```php
usort( $files, create_function( '$a,$b', 'return ((substr_count($a,DIRECTORY_SEPARATOR)-substr_count($b,DIRECTORY_SEPARATOR)) != 0) ? -(substr_count($a,DIRECTORY_SEPARATOR)-substr_count($b,DIRECTORY_SEPARATOR)) : strnatcmp($a, $b);' ) );
```

Таким образом получается правильная сортировка:
```
Hash /home/rtorrent/test/folder1/file1.txt
Hash /home/rtorrent/test/folder1/file2.txt
Hash /home/rtorrent/test/folder1/file10.txt
Hash /home/rtorrent/test/folder1/file12.txt
Hash /home/rtorrent/test/folder2/file1.txt
Hash /home/rtorrent/test/folder2/file2.txt
Hash /home/rtorrent/test/folder2/file10.txt
Hash /home/rtorrent/test/folder2/file12.txt
Hash /home/rtorrent/test/folder10/file1.txt
Hash /home/rtorrent/test/folder10/file2.txt
Hash /home/rtorrent/test/folder10/file10.txt
Hash /home/rtorrent/test/folder10/file12.txt
Hash /home/rtorrent/test/folder12/file1.txt
Hash /home/rtorrent/test/folder12/file2.txt
Hash /home/rtorrent/test/folder12/file10.txt
Hash /home/rtorrent/test/folder12/file12.txt
Hash /home/rtorrent/test/file1.txt
Hash /home/rtorrent/test/file2.txt
Hash /home/rtorrent/test/file10.txt
Hash /home/rtorrent/test/file12.txt
```

**Comment by Novik** [comment]
Честно говоря, я не очень понимаю, почему сортировка файлов внутри торрент файла вас заботит. Стандарт ее не оговаривает, к тому же то, что Вы предлагаете, нормально с UTF строками все равно работать не будет.
Оно Вам зачем вообще?
См. так же
https://github.com/Novik/ruTorrent/issues/1001

**Comment by Novik** [comment]
На всякий случай - мой вопрос означает ровно то, что написано, т.е. я не понимаю, зачем это нужно. Если Вы можете аргументировать "зачем" - соотв. сортировку я реализую.

**Comment by Jeronyson** [comment]
@Novik есть клиенты, которые при приеме торрент-файла проверяют файлы в том порядке, в котором они указаны в торрент-файле. А также на некоторых торрент-трекерах при нажатии на "Список файлов" отсутствует сортировка и они там отображают в том же порядке, что и в torrent файле.
Технически - ни на что не влияет, я не спорю. Это лишь вопрос эстетики

**Comment by Novik** [comment]
> есть клиенты, которые при приеме торрент-файла проверяют файлы в том порядке, в котором они указаны в торрент-файле

Собственно, *все* клиенты так делают, иначе получится другой хеш. Либо я не понял, о чем Вы.

> А также на некоторых торрент-трекерах при нажатии на "Список файлов" отсутствует сортировка

ОК, я посмотрю, что там можно сделать.

**Comment by Jeronyson** [comment]
@Novik , моя неточность про "есть". Это актуально для торрентов с сериалами, например. Вместо того чтобы проверять по порядку 1-2-3-4-5, будут проверять по порядку 3-2-1-4-5 (это лишь пример). Опять же - технически совсем ничего страшного.

**Comment by Novik** [comment]
Переделал, с natsort-ом простым образом не сделать, к сожалению.

**Comment by Jeronyson** [comment]
@Novik спасибо!
