### ISSUE TITLE
Plugin Data doesn't work correctly

### ISSUE THREAD

**Issue by Lussien** [Novik/ruTorrent#1053]
The plugin "Data" download the file with a size of 0byte.
I've tried with many browser and client OS, but always the same problem.
I've also tried with 3 different debian server, but same problem.

OS: debian 7.8
apache2 vers 2.2.22-13+deb7u4
php5 vers 5.4.39-0+deb7u2

**Comment by Novik** [comment]
Try to configure your web-server by the normal way.
http://forums.rutorrent.org/index.php?topic=6383.msg17329#msg17329

**Comment by Lussien** [comment]
Ok, thanks. I've found some solutions if someone will have the same problem.

v3.6 
Solution 1) Disable XSendFile module from apache: a2dismod xsendfile
Solution 2) Add to the end of /etc/apache2/apache.conf 
XSendFile on
XSendFilePath /var/www/rutorrent_path
XSendFilePath /absolutePath/where/torrent/files/were/downloaded

v3.7
1) Easly change in /var/www/rutorrent/conf/config.php 
 $canUseXSendFile = true;
to
 $canUseXSendFile = false;

Thanks for the support
