### ISSUE TITLE
Columns widen on update, causes fatal error

### ISSUE THREAD

**Issue by Vermilingua** [Novik/ruTorrent#1064]
As seen [here](https://a.pomf.se/amtqqa.png), the info columns will widen on each poll automatically, ad infinitum. That screenshot doesn't give a great indication, but for me, at least, it happens. 
If, after this, I resize the columns, after a page refresh, or navigating to the page at a later time, [this](https://a.pomf.se/cqrwhs.png) happens, and will happen on every refresh until `rutorrent/share/settings` is cleared.
[A gif showing the resizing in action (30 seconds)](https://a.pomf.se/ayedce.gif)

**Comment by Novik** [comment]
What about ruTorrent version, browser version?

**Comment by Vermilingua** [comment]
Ah, sorry, didn't realize my version was so outdated. On 3.0, Chrome 42.
Closing, but will reopen if issue persists.
