### ISSUE TITLE
Create torrent error

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1067]
Hi!

The last weeks i am experiencing some problems with the builtin "Create torrent options". I am doing the things like usual. I select a file, then check the private box, insert the announce url, after all of these steps the Console tab pops up and an "Error" string is returned without any explanation further. Is this happening only to me? Does someone have a solution or experiencing this kind of problem?

OS: Debian 7
rutorrent Version: 8d6ed8d19678990433fdde9337e90f5491ca0e77 (master)

**Comment by Micdu70** [comment]
Hello @gala132,

You can check in the "create" plugin folder ( <WEBSERVER_PATH>/rutorrent/plugins/create/ ) if the *.sh files have execute permission.

![check-execute-permission-create](https://cloud.githubusercontent.com/assets/8136676/7553244/85e60d76-f6ec-11e4-948d-0beb1aae67db.png)

If it's not ok:
- chmod +x *.sh
- Then reload rutorrent web page and try again.

If it was already ok, you can try to use an external program for creating .torrent file
( like "mktorrent" ):
- Install the program.
- Configure in the conf.php file. ( if mktorrent: 
![use-external-program-create](https://cloud.githubusercontent.com/assets/8136676/7553252/65d6d9b0-f6ed-11e4-9dc4-7dcfb478143f.png)
)
- Then reload rutorrent web page and try again.

;)

**Comment by gala132** [comment]
Hi!
Thanks for the comments and suggestions.
If i set an external program it is working again, but the .sh scripts already have the execute rights and it is not working with the default createtorrent. It is weird although.

**Comment by Novik** [comment]
> after all of these steps the Console tab pops up and an "Error" string is returned without any explanation further

Show to me screenshot with this message, please.

**Comment by Eriner** [comment]
I'm having a similar sounding error, may or may not be the same. Error on create attempt:

`/usr/share/webapps/rutorrent/share/users/username/settings/tasks/144019724255d7aa7a3845a1.15178500/start.sh: line 12: /usr/share/webapps/rutorrent/plugins/create/1.sh: No such file or directory`

**Comment by PanDoreS** [comment]
@Eriner I think you've already fixed your issue. I encountered the same.
Quick note for myself in the future if I do the same mistake :
- Check your create config file in "plugin/create/conf.php"
- $useExternal is incorrect, it is _false_ or equal to the external torrent program creator (string value), not _true_.

I'm going to bed, bye.
