### ISSUE TITLE
Seeding torrent deleted when tracker edited

### ISSUE THREAD

**Issue by OrpheeGT** [Novik/ruTorrent#1072]
Hello,

I currently have an issue with ruTorrent...
When I try do edit a tracker from a torrent i'm seeding (like to change the private key) the files from the torrent are wiped and the download is started again from scratch...

It seems to happens only with torrent added with ruTorrent...

I have a watch folder directly in rTorrent configuration, if I edit the tracker with ruTorrent on it, no issue, files are still here and tracker is well edited... I just need to force a file check and it is OK

The bug seems to happen only on torrents I added with ruTorrent...

I tried to "stop" torrent before editing it, but it wipes the files... when I try to force the check, it stays at "pause" and on the folder, files are empty...

Do you know why ?

happens on 3.6 and 3.7 too...

Using rTorrent: 0.9.4/0.13.4

Thank you

**Comment by OrpheeGT** [comment]
Hi again,

I added a new torrent with TransDrone (Android). Then, after successfull download and seeding, i edited it with ruTorrent to change the tracker info, and it worked well.

So the bug seems to only happens when torrents are added with ruTorrent GUI...

**Comment by Novik** [comment]
#1565
