### ISSUE TITLE
[Cookies] Некоторые трекеры не понимают куки

### ISSUE THREAD

**Issue by omgiafs** [Novik/ruTorrent#1074]
Здравствуйте.
Проблема с kinozal.tv (например).

Куки имеются и корректно добавлены, раньше это работало.

Проблема: Rutorrent не скачивает torrent-файл по ссылке, т.е http://dl.kinozal.tv/download.php?id=1341098 выдает html-страницу раздачи.

Это было очень удобно - указывать только ссылку на торрент, вместо того чтобы сохранять и загружать файлы в rutorrent, прошу починить :)

**Comment by Novik** [comment]
Если общий подход (куки) не работает ввиду особенностей конкретного  трекера, то необходим частный. Т.е. добавление конкретного трекера в плагин LoginMgr. Для kinozal сделал, пользуйте.
