### ISSUE TITLE
[Feature Request]Add sortable date/time column "Last Active" to main activity pane

### ISSUE THREAD

**Issue by Corin-EU** [Novik/ruTorrent#1078]
The main activity pane has numerous data columns including date/time "Created On".

It would be extremely useful to have another date/time column (with ascending/descending sorting capability) "Last Active" shewing when  the torrent being downloaded or seeded was last active.

Please consider adding this column to the main activity pane.

**Comment by Micdu70** [comment]
This feature is not possible to add because rTorrent doesn't have this function ( without adding a schedule rule in the rtorrent config file ).

**Comment by Corin-EU** [comment]
Thanks for the response.

I guess I should have first requested the rtorrent developers to add this capability (which is featured in transmission / transmissiongui).
