### ISSUE TITLE
extratio plugin priority issue when adding a new torrent

### ISSUE THREAD

**Issue by kouze** [Novik/ruTorrent#1079]
Hi,

I'm facing an issue with extratio.

I have mutliple rules defined in my rutorrent. Mutliple rules could potentially match the same torrent. The logic would be that the plugin, when adding a new torrent, look at all rules by order, from top to bottom, and when there is a match, apply the rule then exit.

Unfortunately, it seems that when defining 2 rules, the first one with "tracker contain" option, the second one with "label contain" option, both matching my torrent, only the second one is applied to newly added torrent.

If I remove the second rule with "label contain" option, the first rule is correctly applied.

I was not able to fix the issue myself, but I suspect a probable first issue with function checkLabels in rules.php where there is a call $rule = $this->getRule( $label, null ); where null should be the tracker list.

Thanks

**Comment by Novik** [comment]
Now only the first rule should be applied (you need to one-time change something in rules for fix have effect). Check, please.

**Comment by kouze** [comment]
Hi,

I tried to un-comment this line during my testing but the result is that I'm not able to re-organize the rule after. If I try to move up or down a rule, the rule moves back to the previous place.

Thanks.

**Comment by Novik** [comment]
Err, this is not so simple ;) Will think.

**Comment by Novik** [comment]
Can't reproduce this issue now.
Please
1) Send to me your ratiorules.dat (located in ruTorrent/share/settings or ruTorrent/users/USERNAME/share/settings depends of configuration) or describe your rules here.
2) Send to me concrete torrent
3) Parameters of torrent addition (i.e. label)

novik65[at]gmail.com

**Comment by kouze** [comment]
Hi there,

the issue is strange. I'll send you the details and how to replicate it with screenshots

Thanks,

**Comment by Novik** [comment]
Thanks for detailed report.
Try to use new version of changes.

**Comment by kouze** [comment]
Hi Novik,

for me your changes fix the issue!

Thanks a lot for your support :)
