### ISSUE TITLE
ruTorrent license

### ISSUE THREAD

**Issue by vktr** [Novik/ruTorrent#1082]
I'm interested in using an embedded version ruTorrent as the frontend for [Hadouken](https://github.com/hadouken/hadouken).

Under what license can I use ruTorrent?

**Comment by alexcoe** [comment]
GNU GPL v3

**Comment by vktr** [comment]
Thanks!

**Comment by iShift** [comment]
@vktr add license file in the root of this repo

**Comment by nemobis** [comment]
> add license file in the root of this repo

Yes please, otherwise it's useless. :(

**Comment by Novik** [comment]
Added.
