### ISSUE TITLE
Please add TehConnection and Animebytes to the Rutorrent search plugin

### ISSUE THREAD

**Issue by JPoom** [Novik/ruTorrent#1084]
Was told to make the request here.  Would be happy to provide an invite if needed.

Amazingly helpful plugin, thank you again.

**Comment by AceP1983** [comment]
I would be willing to make one up for tehconnection if you can provide me with an invite.

**Comment by JPoom** [comment]
Sure can you let me know your email?  I've never used Github before, not sure how to msg.

**Comment by AceP1983** [comment]
There is no private messaging here but you can register on the rutorrent forums and message me.

**Comment by JPoom** [comment]
Alright I've messaged you there.

**Comment by alexcoe** [comment]
Send me Animebytes I take a look http://forums.rutorrent.org/index.php?action=profile;u=1530

**Comment by JPoom** [comment]
Cheers, messaged you there.

**Comment by alexcoe** [comment]
AnimeBytes added to loginmgr and exsearch plugins,

**Comment by JPoom** [comment]
That was fast, thanks a lot!

**Comment by Novik** [comment]
If your still needs TehConnection implementation, send to me invite for it, please.
novik65[at]gmail.com

**Comment by Novik** [comment]
TehConnection was added (corresponding code to the login manager was added too)
