### ISSUE TITLE
JS error preventing trackers listing

### ISSUE THREAD

**Issue by ivanozerov** [Novik/ruTorrent#1087]
JS error: [undefined : 5841] TypeError: undefined is not an object (evaluating 'domain.match')

when loading ruTorrent from browser. This is with latest from Github.

**Comment by alexcoe** [comment]
Have you cleared your browsers cache?

**Comment by ivanozerov** [comment]
Yes, I have. Issue persists with multiple browsers.

**Comment by Novik** [comment]
I think, you have a torrent with an incorrect (or strange) announce.
Corresponding code is placed in the plugins 'tracklabels' and 'history'. Try to temporary remove its (i guess, after that interface will be loaded normally) and check torrents.
Or give to me access to your ruTorrent interface (if you can do that, of course). 
novik65[at]gmail.com
