### ISSUE TITLE
Grab the link Torrent file or magnet link if the person add a link to a post from a website torrents

### ISSUE THREAD

**Issue by hlcb** [Novik/ruTorrent#1090]
I modified the file code "addtorrent.php" to become more convenient to use now to enter a torrent if the person add a link from the post instead of the torrent file or link magnet is made a request in the post url and then is performed the capture link torrent file or magnet link. What do you think of this?

**Comment by frantzz** [comment]
Will only work on public trackers that doesn't require an account to be able to download .torrent files.

**Comment by hlcb** [comment]
Yes, initially it will be only with sites that do not require login. After you can enter the login data in a configuration file to work with private sites. I will send my contribution later.
