### ISSUE TITLE
Scheduled speed limit not respected

### ISSUE THREAD

**Issue by mark-owen** [Novik/ruTorrent#1091]
Hi,

I'm using rutorrent as a front-end and I'm not sure if it comes from rutorrent or rtorrent but when I set up the speed limits (from the Scheduler on rutorrent), these are not respected by rtorrent if I do no have the web ui page open in my browser.

I tried to add:

execute = {sh,-c,/usr/bin/php /var/www/ruTorrent/php/initplugins.php tom &}

to my .rtorrent.rc file as is recommended in the rutorrent wiki but it didn't change anything.

Is this fixable, somehow?

PS: I'm posting a copy of this thread to rtorrent's github.

**Comment by Novik** [comment]
Your ruTorrent user really have name 'tom'?

**Comment by mark-owen** [comment]
No, I simply pasted the command from your wiki page here but I adapted it to my system in my .rtorrent.rc file. The issue doesn't come from there.

**Comment by Novik** [comment]
Try to read wiki. 'tom' - is a name of user. If you haven't such user, then you add an incorrect line.

**Comment by mark-owen** [comment]
Read again: "I adapted it to my system"

My line is correct, the issue does NOT come from there.

**Comment by Novik** [comment]
Try to run this line (/usr/bin/php /var/...) manually. And check results.
Also paste here contents of your .rtorrent.rc.

**Comment by mark-owen** [comment]
I'll give you a bit more information: my user running rtorrent is 'vnc' and rutorrent's path is /var/www/html (run as www-data user).

If I run '/usr/bin/php /var/www/html/php/initplugins.php vnc &' as vnc, I get no error. Same as root.

Here is my .rtorrent.rc: http://pastebin.com/YrDrZzWe

**Comment by Novik** [comment]
Can't understand you. From one side

> I'll give you a bit more information: my user running rtorrent is 'vnc'

Form another

> execute = {sh,-c,/usr/bin/php /var/www/html/php/initplugins.php &}

1) I can't see user name in this string. If you use multi-user configuration of rtorrent then user name must be present in this line.
2) 'rtorrent user' hasn't relation to this at all. *ruTorrent* user is required.

**Comment by mark-owen** [comment]
So it should be: execute = {sh,-c,/usr/bin/php /var/www/html/php/initplugins.php www-data &}

as www-data is rutorrent's user. Correct?

**Comment by Novik** [comment]
Yet once. Try to read wiki.
If you have multi-user configuration then you have an authorization dialog. If you have an authorization dialog then you have user for it. *This* is a your user.
https://github.com/Novik/ruTorrent/wiki/Config#multiuser-and-singleuser-configuration

**Comment by mark-owen** [comment]
Ok I get it. I have a single user configuration, therefore my command should be:

execute = {sh,-c,/usr/bin/php /var/www/html/php/initplugins.php &}

**Comment by Novik** [comment]
Yes. Don't forget to restart rtorrent after changing config and check result.

**Comment by mark-owen** [comment]
I does seem to work, now. Thank you, you can close this issue.
