### ISSUE TITLE
Please add Bibliotik, Myanonamouse, Waffles

### ISSUE THREAD

**Issue by JPoom** [Novik/ruTorrent#1092]
Would be handy if someone can add these to the rutorrent search plugin.  Can provide invites for the last two if needed.

**Comment by Novik** [comment]
> Can provide invites for the last two if needed.

You may send its to novik[at]gmail.com

**Comment by Novik** [comment]
UPD: novik65[at]gmail.com sorry ;)

**Comment by JPoom** [comment]
Cheers man.

**Comment by Novik** [comment]
Just for info. 
I got your invitation for Waffles and Myanonamouse.
I don't forget about this.
Sorry for such large delay.

**Comment by JPoom** [comment]
No worries man, no rush, take your time.

By the way I noticed that Animebytes and TehConnection were added.  I'm on a feral seedbox and not sure how to update the extsearch plugin (when installing through SSH it says 'file exists').  Please excuse my ignorance.

**Comment by bhavicp** [comment]
Open a ticket to Feral to ask on how to upgrade (or delete the current folder first, and then pull from Git - But if ruTorrent is old, there might be dependences from the plugin on other parts)

**Comment by Novik** [comment]
Myanonamouse was added.
