### ISSUE TITLE
ruTorrent 3.7 (and 3.6) does not work on Safari 9 beta

### ISSUE THREAD

**Issue by Frizlab** [Novik/ruTorrent#1094]
I don't know if it's a problem related to Safari or ruTorrent, but the website does not work on the latest beta of Safari (Version 9.0 (11601.1.43)).
Works well on FireFox and Chromium.

I'm available to give more informations if needed.

**Comment by Novik** [comment]
Sorry, but beta versions of browsers are not supported.

**Comment by Frizlab** [comment]
I understand, I'll see with the WebKit team directly. Thanks.

**Comment by piratx** [comment]
Well now Safari is out of beta is there a new version?

**Comment by Novik** [comment]
May be. But not from me. I haven't access to Safari and Mac.

**Comment by Frizlab** [comment]
FWIW, here's a more thorough description of the problem I had (still have but I found a workaround).

Setup:
   - multi-user rutorrent; user authentication is done via Basic http authentication (standard).
   - Safari 9, iCloud Keychain enabled, password for my user is in the keychain.

When opening rutorrent, I'm told no connection could be made to the rtorrent RPC service.

Upon investigation, it appears that some requests are sent unauthenticated to the server by Safari. Which leads to the fail (the default config file is read instead of the one of my user).

Workaround: _Remove_ your user/pass from Mac OS X keychain (not in the preferences of Safari, directly in the Keychain App). Enter user/pass to connect to the website manually.

This really seems like a Safari bug. Should be sent to the WebKit team I guess.

**Comment by Novik** [comment]
Thanks for detailed description.
