### ISSUE TITLE
rarbg.to

### ISSUE THREAD

**Issue by sayroni** [Novik/ruTorrent#1100]
hi novik
do you can add rarbg.to on public engine?...

thanks.

**Comment by Novik** [comment]
Add to what?

**Comment by miguelsvieira** [comment]
I'm guessing OP meant adding rarbg.to the public trackers available on the search box -- which would be cool indeed!

**Comment by Kcchouette** [comment]
hi @Novik, this issue can be close as rarbg is now available with PR #1559
