### ISSUE TITLE
Files > Get File doesn't work on 

### ISSUE THREAD

**Issue by bStyler** [Novik/ruTorrent#1106]
Hello there,

I'm using ruTorrent 3.7 (rTorrent 0.9.4)

I've been testing out the 'Get File' option on a torrent that I downloaded, in order to HTTP download it to my desktop.
![2015-09-01_1723](https://cloud.githubusercontent.com/assets/7829256/9606825/5f476e76-50ce-11e5-9fa8-90cb21d41572.png)

Unfortunately, it downloaded a 0kb size file, instead of the actual file.
I get the same results in Chrome and Firefox.

Please advise, thanks!

**Comment by Novik** [comment]
Configure x-sendfile feature on your web server by the normal way, or set 
$canUseXSendFile = false;
in the ruTorrent config.

**Comment by bStyler** [comment]
Hi, thank you for the fast response @Novik !

- Can you please advise how it's done on nginx?
- Which web server would you normally recommend for ruTorrent?

Many thanks :)

**Comment by Novik** [comment]
If you use nginx, then, AFAIK, x-sendfile feature is not a source of your problem.
This has relation to apache only.
Describe situation more detail, please.

> Which web server would you normally recommend for ruTorrent?

Any ;) I use lighttpd on ASUS router and apache on desktop.

**Comment by bStyler** [comment]
Thank you for the response @Novik !

1) Interestingly, as you said nginx web server is indeed working well, while apache2 doesn't. I'll stick to nginx then.
2) I also noticed that loginmgr plugin that comes out of the box with ruTorrent is making the initial ruTorrent page load to be very very slow. This is clearly out of the scope of this issue, but I thought I'd let you know!
