### ISSUE TITLE
request: option to disable delete data (all)

### ISSUE THREAD

**Issue by 215** [Novik/ruTorrent#1107]
This option appears to wipe the contents of the directory containing the files from a single torrent (regardless if the they belong to that torrent) . I have a few folders that contain data from multiple torrents, and this option is scary, I've already wiped data from about 25 torrents with one mis-click.

**Comment by Micdu70** [comment]
Hello,
Today, I added a way to enable/disable this in the "plugins.ini" file ( in the "conf" directory ), with a "canForceRemove" flag. ( Maybe there is a better way ^^ )
I will create a git patch if you are interested. =)

**Comment by Novik** [comment]
Added.
https://github.com/Novik/ruTorrent/issues/1169
