### ISSUE TITLE
Uncaught SecurityError

### ISSUE THREAD

**Issue by manasb** [Novik/ruTorrent#1108]
Hello,

I am running rutorrent from source on FreeBSD 10 with lighttpd. I am experiencing this error when trying to add a .torrent file.

```
[08.09.2015 22:22:20] JS error: [http://127.0.0.1:9999/rutorrent2/js/content.js : 72] Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://127.0.0.1:9999" from accessing a cross-origin frame.
```

Please look into this.

Thanks,
Manas

**Comment by manasb** [comment]
I am running the lighttpd server in a remote location. I SSH into the machine and set up a couple of Port Forwards - including one to access lighttpd: `-L 9999:127.0.0.1:80`

Then I open http://127.0.0.1:9999 in my web browser and try to add a torrent through the console.
I have tried changing the port that lighttpd listens on to 9999 (while changing the relevant `ssh` argument) but that has not worked.

**Comment by Novik** [comment]
Try something like this:
http://www.gubatron.com/blog/2011/11/29/lighttpd-allow-access-control-allow-origin-headers-on-the-server-status-page/

**Comment by manasb** [comment]
That seems like it would work. I had switched to nginx some time back to get around this issue. Thanks for the update.
