### ISSUE TITLE
Plugin will not work...

### ISSUE THREAD

**Issue by CtrlSystem** [Novik/ruTorrent#1109]
screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg)
mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo)

Any idea why i get this and how to fix it?

Ty.

**Comment by Novik** [comment]
Diagnostic is a self-described. Install ffmpeg and mediainfo.

**Comment by CtrlSystem** [comment]
Thanks, Novik
