### ISSUE TITLE
Shortcut in conflict with Firefox

### ISSUE THREAD

**Issue by uoltah** [Novik/ruTorrent#1111]
Hi, 
I am using Firefox 40, and every time I press Ctrl+P or Ctrl+Shift+P shortcuts, it shows me the Settings panel of rutorrent instead of Print / Incognito Mode.
Is there a way to disable or change the Ctrl+P shortcut?
Thanks

**Reproducing the bug:**
1. Start latest Firefox version, get in the rutorrent interface.
2. Press Ctrl+P or Ctrl+Shift+P

**Comment by alexcoe** [comment]
You can change the control key (currently 80 / P) in js/webui.js
Change the case value on line 260
