### ISSUE TITLE
History plugin not working

### ISSUE THREAD

**Issue by adam900710** [Novik/ruTorrent#1113]
Hi all,

Recently, I upgraded my download box from rutorrent 3.6 to 3.7, everything seems to be good,
but the history plugin seems to be broken.
It always shows the error "Bad response from server: (200 [parsererror,gethistory]".

The apache and rutorrent config are not changed.

Any help?
Thanks

**Comment by Micdu70** [comment]
Hi @adam900710 

You can try to clear the history data, removing this file =>
rutorrent/share/users/<username>/settings/history_data.dat

Then reload ruTorrent page. ;)

**Comment by sadok** [comment]
@Micdu70, yes. It works =)

**Comment by adam900710** [comment]
@Micdu70 Fix confirmed, thanks a lot!!

**Comment by enoch85** [comment]
Fixed it for me too, just to confirm.
