### ISSUE TITLE
Torcache.net RSS Feeds

### ISSUE THREAD

**Issue by jo-ha** [Novik/ruTorrent#1115]
RSS feeds that use torcache.net to host .torrent files are no longer working.  

Example RSS feed:
https://kat.cr/usearch/debian%20amd64%20netinst%20category%3Alinux/?rss=1

Example log output:
[17.09.2015 16:02:33] Error loading torrent. (https://torcache.net/torrent/C3E36BB32D7B8F1B89DCB003575F89EC859CF198.torrent?title=[kat.cr]debian.8.2.0.amd64.netinst.iso)

**Comment by harupong** [comment]
I had the same problem, but it's working now. According to [this discussion](https://forums.sonarr.tv/t/unable-to-download-torrent-files-through-torcache/6920), torcache seems to have done something to fix the problem.

@jo-ha Why not give it a try, and close this issue if it works?

**Comment by jo-ha** [comment]
Confirmed that it seems to have been fixed on their end.
