### ISSUE TITLE
Support for http2

### ISSUE THREAD

**Issue by Frizlab** [Novik/ruTorrent#1117]
I’ve tried activating http2 on my server with rutorrent, but it does not work. Apparently there’s a problem with XHR responses being parsed poorly when http2. Is it possible to look into it? Thanks!

**Comment by Flayor** [comment]
Hi

Do you have https on your rutorrent server ?

**Comment by BaalMcKloud** [comment]
https is not http2

https://en.wikipedia.org/wiki/HTTP/2

**Comment by Flayor** [comment]
BaalMcKloud yes i know,

But HTTP2 protocol work only in https :)

**Comment by Frizlab** [comment]
Yes I have https :) But http2 does not work

**Comment by Flayor** [comment]
What is your web server nginx or apache ? and this version ?

**Comment by Frizlab** [comment]
I’ve tried again, now it works 🙂
Sorry for not answering sooner, been a bit busy!
