### ISSUE TITLE
Tasks Folder Stops Rutorrent From Loading

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1122]
I noticed if a user unpacks the majority of torrents automatically on completion this is recorded in the tasks then the tasks folder fills up causing rutorrent not to load.

I understand that the logging to tasks can be disabled in the unpack plugin configuration to solve the issue.

**Comment by wangxu94** [comment]
I'm having the same issue as well, but I don't see an option in the unpack plugin configuration to disable logging to tasks. I just have a cron job to clear the tasks folder every couple of hours.
