### ISSUE TITLE
tracker label icons not showing

### ISSUE THREAD

**Issue by maxadamo** [Novik/ruTorrent#1123]
I have php-5.6.4 and I was not seeing the icons on the left pane of the tracker/label section. 
It looks like this was not working properly: sendFile( $name, "image/png" ); 

Inside the file _**action.php**_

**I replaced this one**: 
sendFile( $name, "image/png" ); 

**with**: 
header("Content-type: image/png");
passthru("cat $name");

**and replaced this one**:
sendFile( $name, "image/x-icon" );

**with**: 
header("Content-type: image/x-icon");
passthru("cat $name");

I don't know if there is a better way, as I am not a PHP progammer, but I can say that it started working.

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/issues/1106

**Comment by maxadamo** [comment]
thanks :)
