### ISSUE TITLE
Please set these tracker to private.

### ISSUE THREAD

**Issue by profess79** [Novik/ruTorrent#1125]
It's private and count download, upload, ratio

but rutorrent show that are public tracker.

http://www.nongpink.com/my.php
http://ann.nongpink.com/k2.php?passkey=xxxxxxxxxxxxxxxxxxxxx

https://www.tt-torrent.com/index.php
https://get-seeders.com/2.1.php?passkey=xxxxxxxxxxxxx

https://www.filezaap.com/
http://announce.tang-mo.com/announce/xxxxxxxxxxxxxxxxxxxxxxxx

http://www.zodzai.com/
http://bitzz.ninja/a/130.18ce7489186de6660ac87e84cc7097f0

http://www.loadtorrentfile.com/uplo
http://www.loadtorrentfile.com/announce.php?passkey=xxxxxxxxxxxxxxxxxxxxxxxxx

Thank you very much.

**Comment by Micdu70** [comment]
Done. =P

**Comment by profess79** [comment]
![04](https://cloud.githubusercontent.com/assets/14905839/10211232/37c8967c-681b-11e5-9a23-0457ac4a5667.png)


Some tracker still public.

**Comment by Micdu70** [comment]
For my side, I tested all your tracker's URL, all matching private tracker...

![](https://puu.sh/kuq7p/bebb50fc6a.png)

**Comment by profess79** [comment]
OK. Thank you very much.
