### ISSUE TITLE
PHP Warning: uisettings.json

### ISSUE THREAD

**Issue by bStyler** [Novik/ruTorrent#1128]
Greetings,

One of my ruTorrent clients keeps generating this error:

``` javascript
PHP Warning:  rename(/var/www/rutorrent/share/users/user/settings/uisettings.json.tmp,/var/www/rutorrent/share/users/user/settings/uisettings.json): No such file or directory in /var/www/rutorrent/php/setsettings.php on line 20
```

While I am just filtering my active torrents by DL column or so.

Please advise how I can fix this recurring warning.

Many thanks!

**Comment by Micdu70** [comment]
Hello,

I have this warning sometimes too... I really don't understand why...
