### ISSUE TITLE
cant edit any tracker

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1130]
i get this error when I want to edit trackers for any torrent 
"Source torrent file for this download not found"

**Comment by Novik** [comment]
Diagnostic is a self-explained, IMHO.

**Comment by harkor** [comment]
I have the same problem and all my .torrent are in "/var/www/rutorrent.zeus/share/users/<user>/torrents".

**Comment by Donokami** [comment]
same problem. i don't understand why, my permissions seems to be good

**Comment by lonecrane** [comment]
+1

**Comment by YamashitaRen** [comment]
> Diagnostic is a self-explained, IMHO.

Could be better IMHO.
` ls -l /usr/share/webapps/rutorrent/share/`
`drwxrwxrwx 1 root root 2144 24 sept. 23:29 torrents`

torrent file is obviously in the torrent directory ;)
