### ISSUE TITLE
Пустая колонка "Добавлен" 3,7

### ISSUE THREAD

**Issue by AutopilotNN** [Novik/ruTorrent#1134]
В 3.7 в списке закачек перестала отображаться дата добавления закачки. В 3.6 все работает. В истории дата добавления есть. 
Заметил давно. Проверил на текущей ветке.

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/wiki/PluginSeedingtime

**Comment by AutopilotNN** [comment]
На момент проверки плагины что были в архиве были все включены и этот тоже. Колонка была, но была пустой. Сейчас я физически вынес все плагины из каталога и добавлял постепенно. После seedingtime колонка появилась и оказалась заполнена. После добавления всех плагинов колонка осталась и даты на пропали. И вроде все работает. 
Открыв раннюю версию 3,7 я снова увидел столбец без дат. 
Но в обновленной даты есть. Спасибо. Извиняюсь за беспокойство.
