### ISSUE TITLE
Support for mobile browsers

### ISSUE THREAD

**Issue by mcandre** [Novik/ruTorrent#1135]
Could the default ruTorrent view be optimized for mobile browsers?

* [ ] Vertical layout on small screens
* [ ] Bigger buttons
* [ ] Don't rely on right-click context menu

**Comment by alexcoe** [comment]
https://github.com/carlosjdelgado/rutorrentMobile

**Comment by mcandre** [comment]
Thanks for the plugin link!

It would be better if ruTorrent simply offered a mobile-friendly layout out of the box.
