### ISSUE TITLE
Torrent Auto Uploader

### ISSUE THREAD

**Issue by CtrlSystem** [Novik/ruTorrent#1136]
I thing here must be the place in which i will get detailed information about Torrent Auto Uploader. 
I want to use it, but didnt get info to can run it. Searching in web, but still nothing... I thing you must know what i need to can run it? I already buy dedicated server. Any info which you provide will be helpful.

Thanks a lot.

**Comment by Novik** [comment]
Sorry, but I can't understand, what is you mean.
Try to check links for browser's plugins here - http://xirvik.com/downloads
May be, this is a what you want.

**Comment by CtrlSystem** [comment]
I am sorry for my bad english. Maybe this will give you more information : https://www.janhouse.lv/uploader/

**Comment by Novik** [comment]
I don't know anything about this feature. Try to ask about it from it's author.

**Comment by CtrlSystem** [comment]
Yes, i contact him via email and skype, but still didn't get reply...
Anyway thanks for your time.
