### ISSUE TITLE
[Feature req] Support the <folder> tag in RSS feeds

### ISSUE THREAD

**Issue by Kourkis** [Novik/ruTorrent#1141]
Currently when setting up a RSS feed using the RSS Manager, we can set the path of the downloaded file, and set if the torrent's name is added to path. It would be nice if the **folder** RSS tag was supported, it indicates where a file should be downloaded.

For example, if the download directory is *downloads/*, the new RSS entry downloading is *ShowName SXXEXX.mp4* and the **folder** tag is **<folder>ShowName</folder>**, instead of placing the file in *downloads/* ruTorrent would place the file in **downloads/ShowName/**.
This is useful for feeds that display torrents for single files, allowing to organize a library neatly.
An example of a website that uses the folder tag is shanaproject.com.

I've migrated from Deluge on my laptop to ruTorrent on my NAS, and this is the only thing missing.

Here is an example of RSS feed containing the folder tag:

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>Shana Project RSS</title>
    <link>http://www.shanaproject.com/follows/</link>
    <description>Secure releases for xxxxxx</description>
    <atom:link href="http://www.shanaproject.com/feeds/secure/user/xxxxx/XXXXXXXX/" rel="self"></atom:link>
    <language>en-us</language>
    <lastBuildDate>Tue, 03 Nov 2015 10:22:58 +1100</lastBuildDate>
    <ttl>10</ttl>
    <item>
      <title>JK Meshi! - 5 [720p][HorribleSubs]</title>
      <link>http://www.shanaproject.com/download/116465/?uid=31839&amp;key=1M67ET0NVS</link>
      <description>[HorribleSubs] JK Meshi! - 05 [720p].mkv</description>
      <pubDate>Tue, 03 Nov 2015 10:22:58 +1100</pubDate>
      <guid>http://www.nyaa.se/?page=download&amp;tid=752206</guid>
      <folder>JK Meshi!</folder>
    </item>
  </channel>
</rss>
```

**Comment by Novik** [comment]
AFAIK, 'folder' tag is a not a part of any standard. Please, show me RFC or something like this, where this tag is described.

**Comment by Kourkis** [comment]
It is not part of a standard, it is still useful though, but I can understand why you wouldn't want to implement it.

**Comment by Novik** [comment]
OK, may be you have an examples of *real* trackers feeds with this tag?

**Comment by Kourkis** [comment]
Sorry, I don't, I've only come across this tag on this website.
