### ISSUE TITLE
Option in unpack plugin conf to disable console display

### ISSUE THREAD

**Issue by methilnet** [Novik/ruTorrent#1143]
The unpack plugin need a setting in the conf file to disable the activity console from showing up.
Current behavior is annoying and counter productive.
How about auto jumping to the task tab if there is a problem instead else run quietly?

**Comment by Novik** [comment]
> Current behavior is annoying and counter productive.

Describe more detail, please - what is wrong? You want to manually unpacking 100+ archives in parallel mode? Or what?

> How about auto jumping to the task tab if there is a problem instead else run quietly?

Try to comment line plugins/unpack/init.js:147 (noclose: true).

**Comment by methilnet** [comment]
I do have sometime up 30 files to unpack into different folders. I dont mind clicking each one to unpack since they go all in a different folder.

Each time the task console popup displaying the current activity detail.
That fine if you need to know what going on. But having to close that windows every time is annoying.
Been able to just start the task without the activity console showing up would be great.
It can be a simple checkbox under the path text box saying "dont display activity console"

commenting line 147, it auto close the task console after the job is done is also nice.
Can we get all that stuff into the plugin config section?
Something like : console display behaviour : drop down with popup, auto close, dont display.
