### ISSUE TITLE
The downloaded field doesn't show accurate information

### ISSUE THREAD

**Issue by jantjo** [Novik/ruTorrent#1144]
I did open with rtorrent previously but found it the field in rutorrent.
https://github.com/rakshasa/rtorrent/issues/349#issuecomment-153843256

I've noticed that the downloaded field doesn't show the accurate amount of data actually download and seems to be more of a bit representation of the percentage complete download.

The scenario is if you download a file from tracker A and it's 200Kb, it should show 200Kb and 100% complete. If you add the same file from tracker B, it does a check on the file and it finds that you either have 100% of the original or maybe missing 2%, once the check is done and download is complete it will still show that you downloaded 200Kb which is false.

ScreenShot in ruTorrent showing the downloaded amount but is false, actually showing torrent size.
https://whatimg.com/i/elYnty.png

Confirmed within rtorrent.
Prime - Download: 0.0 KB / 8.8 GB
Prime+X (Delta files or 100% match)
Download: 0.0 KB / 2.2 MB
Download: 0.0 KB / 2.3 MB
Download: 0.0 KB / 0.0 KB

**Comment by Novik** [comment]
In this column you can see value, directly received from rtorrent (d.get_bytes_done=). 
Sorry, but I can't understand - what is you want from me.

**Comment by Micdu70** [comment]
Hi @jantjo 

You put those lines:

**Comment by jantjo** [comment]
@Micdu70 

When you open rtorrent, press the right key on a active torrent, user down key to highlight info and it will show the correct stats.

 Upload:             0.0 KB /  24.0 GB
               Download:           0.0 KB /  32.0 MB
               Skipped:            0.0 KB / 480.6 KB
               Preload:          0 / 0 / 0

**Comment by jantjo** [comment]
@Novik 

The value that your pulling is not correct field as it's not showing the accurate downloaded bytes. as I mentioned to @Micdu70 to see the correct stats in rtorrent.

Here is the prime torrent. under the download field it shows 8.8GB, at the very bottom it show "Done 9023.6MB" which im guessing is the field your pulling from.
https://whatimg.com/i/PanwAl.png

Here is the prime+1. showing the same "Done" file size but the download is only 31.9MB,
https://whatimg.com/i/GJMdnr.png

**Comment by jantjo** [comment]
maybe "d.get_down_total", "d.down.total" might be the better field to pull this information?

**Comment by Novik** [comment]
May be. But ruTorrent use d.get_bytes_done.

**Comment by jantjo** [comment]
that good that your ok giving false information to your users.

**Comment by jantjo** [comment]
FYI. Your history plugin is codded correctly as it shows proper information, but not the main one.

**Comment by Micdu70** [comment]
@jantjo The issue with what you want is when you restart rtorrent, rtorrent doesn't save the "real" downloaded info. ( All torrents show => Download: 0.0 KB / 0.0 KB )

**Comment by Micdu70** [comment]
@jantjo I did a pull request for rtorrent, you can try to change those 2 files and recompile rtorrent.

Then, for ruTorrent, you need to replace "d.get_bytes_done" by "d.get_down_total" in those 4 files:

js/rtorrent.js
plugins/history/history.php
plugins/feeds/action.php
plugins/httprpc/action.php

Should work! :+1:
