### ISSUE TITLE
[Feature Request] DiskSpace plugin for 2 or more mount points/hdds

### ISSUE THREAD

**Issue by eugenenv** [Novik/ruTorrent#1146]
as title says, let the DiskSpace plugin display stats for 2 or more drives

**Comment by Novik** [comment]
I can't see a normal UI solution for this.

**Comment by eugenenv** [comment]
Well, right now i've made 2 copies of plugin, it required some code changes in copied one.
Seems ok for me, only device overlay would be nice.

![1](https://cloud.githubusercontent.com/assets/13846366/11560972/110c2f94-99d5-11e5-87a5-032ac1ad772a.PNG)

**Comment by xcymax** [comment]
Can you supply your code / guide for this @eugenenv ? Would love to get something like this going for my set up.

**Comment by TMTYD** [comment]
Hi

I have managed to show a disk space for each mountpoint, but he still does not show me the graphics for the disk where can I find the one?

**Comment by espiman** [comment]
Hi. 

Can you supply your code / guide for this? Would love to get something like this going for my set up.

Thank you
