### ISSUE TITLE
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

### ISSUE THREAD

**Issue by nikolakhs** [Novik/ruTorrent#1154]
I have this error. rtorrent is running, I see the processes

also in log file:
> [:error] [pid 1612] [client 127.0.0.1:56564] PHP Warning:  fopen(/var/www/rutorrent/share/users/rtorrent/settings/uisettings.json): failed to open stream: No such file or directory in /var/www/rutorrent/php/getsettings.php on line 7, referer: http://127.0.0.1/rutorrent/

and when running "rtorrent" from terminal I get: Could not read resource file: ~/.rtorrent.rc

> my rtorrent.rc file:

max_downloads_global = 0
max_uploads_global = 0
min_peers = 30 
max_peers = 150 
min_peers_seed = -1 
max_peers_seed = -1

max_uploads = 150

download_rate = 0
upload_rate = 0

directory = /home/rtorrent/downloads/manual

session = /home/rtorrent/downloads/.session
port_range = 51103-51103 
port_random = yes

# Directories
schedule = watch_directory,5,5,load_start=/home/rtorrent/downloads/watch/*.torrent
schedule = untied_directory,5,5,stop_untied= 
schedule = low_diskspace,5,10,close_low_diskspace=2000M 

# Networking
network.scgi.open_port = 127.0.0.1:51102
network.http.ssl_verify_peer.set=0

use_udp_trackers = yes 
encryption = allow_incoming,enable_retry,prefer_plaintext
network.max_open_files.set = 191 
network.max_open_sockets.set = 1536 
network.http.max_open.set = 32 
network.send_buffer.size.set = 4M 
network.receive_buffer.size.set = 4M
dht = disable
peer_exchange = no

check_hash = no
pieces.preload.type.set = 1
max_memory_usage = 3500M

# The following line initialises rutorrent plugins without needing to open the web interface
execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php rtorrent &}

> and the config.php file
<?php
	// configuration parameters

	// for snoopy client
	@define('HTTP_USER_AGENT', 'Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0', true);
	@define('HTTP_TIME_OUT', 30, true);	// in seconds
	@define('HTTP_USE_GZIP', true, true);
	$httpIP = null;				// IP string. Or null for any.

	@define('RPC_TIME_OUT', 5, true);	// in seconds

	@define('LOG_RPC_CALLS', false, true);
	@define('LOG_RPC_FAULTS', true, true);

	// for php	
	@define('PHP_USE_GZIP', false, true);
	@define('PHP_GZIP_LEVEL', 2, true);

	$schedule_rand = 10;			// rand for schedulers start, +0..X seconds

	$do_diagnostic = true;
	$log_file = '/tmp/errors.log';		// path to log file (comment or leave blank to disable logging)

	$saveUploadedTorrents = true;		// Save uploaded torrents to profile/torrents directory or not
	$overwriteUploadedTorrents = false;     // Overwrite existing uploaded torrents in profile/torrents directory or make unique name

	$topDirectory = '/';			// Upper available directory. Absolute path with trail slash.
	$forbidUserSettings = false;

	$scgi_port = 51102;
	$scgi_host = "127.0.0.1";

	// For web->rtorrent link through unix domain socket 
	// (scgi_local in rtorrent conf file), change variables 
	// above to something like this:
	//
	// $scgi_port = 0;
	// $scgi_host = "unix:///tmp/rpc.socket";

	$XMLRPCMountPoint = "/RPC2";		// DO NOT DELETE THIS LINE!!! DO NOT COMMENT THIS LINE!!!

	$pathToExternals = array(
		"php" 	=> '',			// Something like /usr/bin/php. If empty, will be found in PATH.
		"curl"	=> '',			// Something like /usr/bin/curl. If empty, will be found in PATH.
		"gzip"	=> '',			// Something like /usr/bin/gzip. If empty, will be found in PATH.
		"id"	=> '',			// Something like /usr/bin/id. If empty, will be found in PATH.
		"stat"	=> '',			// Something like /usr/bin/stat. If empty, will be found in PATH.
	);

	$localhosts = array( 			// list of local interfaces
		"127.0.0.1", 
		"localhost",
	);

	$profilePath = '../share';		// Path to user profiles
	$profileMask = 0777;			// Mask for files and directory creation in user profiles.
						// Both Webserver and rtorrent users must have read-write access to it.
						// For example, if Webserver and rtorrent users are in the same group then the value may be 0770.

	$tempDirectory = null;			// Temp directory. Absolute path with trail slash. If null, then autodetect will be used.

	$canUseXSendFile = true;		// Use X-Sendfile feature if it exist

	$locale = "UTF8";

**Comment by Micdu70** [comment]
You said:

"[...] when running "rtorrent" from terminal I get: Could not read resource file: ~/.rtorrent.rc"

So it's not ruTorrent issue, but rtorrent issue. ( Check permission and presence of the .rtorrent.rc file )

**Comment by nikolakhs** [comment]
File exists, needs other permissions?
http://i.imgbox.com/KpvAwoWZ.jpg

**Comment by Micdu70** [comment]
Seems okay, now be sure to start rtorrent with "rtorrent" user.

**Comment by nikolakhs** [comment]
I'm 100% sure I start it with rtorrent user, webmin in processes shows rtorrent as user

**Comment by Novik** [comment]
What about rtorrent version?
