### ISSUE TITLE
rutracker_ check

### ISSUE THREAD

**Issue by rtorrentuser** [Novik/ruTorrent#1157]
После последних изменений в плагине, перестала работать автоматическая проверка обновления торрентов по заданному интервалу. По вызову вручную через меню работает.

**Comment by Novik** [comment]
Надеюсь, что поправил, проверяйте. Правда, в связи с грядущей блокировкой rutracker понятия не имею, как оно вообще будет работать.

**Comment by rtorrentuser** [comment]
По заданному интервалу для Рутреккера стал проверять, но только для него - для Кинозала по интервалу всё равно почему-то не проверяет, хотя вручную проверяет... Что до блокировки, да, если нет способа запустить всё это через прокси какой-нибудь, то работать, наверное, не будет.

**Comment by Novik** [comment]
Вероятно связано с https://github.com/Novik/ruTorrent/issues/1170
Посмотрите еще раз, пожалуйста.

**Comment by rtorrentuser** [comment]
Нет, увы... По расписанию (раз в час по умолчанию) Кинозал всё равно не проверяет... По крайней мере, судя по времени последней проверки на закладке "Общее"...

**Comment by rtorrentuser** [comment]
Присмотрелся попристальнее и понял, кажется, почему обновления по трекеру "kinozal.tv" не проверяются автоматически по заданному интервалу. С некоторых пор "в теле" торрент-файлов "kinozal.tv" трекер не "...кinozal.tv.." , а "...torrent4me.com...". И в перечне трекеров в веб-интерфейсе ruTorrent "кinozal.tv" значится как "torrent4me.com".

**Comment by Novik** [comment]
Понятно, у меня с данного трекера только старые торренты со старыми же аннонсами. Смотрите новую версию.

**Comment by rtorrentuser** [comment]
Да, спасибо: вроде стал проверяться - по крайней мере судя по "счётчику"... Вот только заметил, что теперь ежечасно проверяет и по трекерам, для которых эта функция не поддерживается... Раньше, вроде, такого не было... Не критично. но всё же...

**Comment by Novik** [comment]
Поправил. По крайней мере, надеюсь, что.

**Comment by rtorrentuser** [comment]
Да, вроде работает! Спасибо! Может заодно иконку кинозальную в tracklabels добавить для torrent4me,com, чтоб было видно, к какому трекеру относится?

![torrent4me com](https://cloud.githubusercontent.com/assets/1167563/12483955/cb01925e-c068-11e5-97b8-7b4973c28bbd.png)

**Comment by Novik** [comment]
Добавил.
