### ISSUE TITLE
Менеджер рассылок вырезает порт из URL закачки торрент-файла

### ISSUE THREAD

**Issue by omgiafs** [Novik/ruTorrent#1158]
Пример:
Ссылка на скачивание торрента в RSS имеет вид:
http://nas:8099/torrentmonitor/torrents/[kinozal.tv]_1234567.torrent

В рассылках получаем URL загрузки: 
http://nas/torrentmonitor/torrents/[kinozal.tv]_1234567.torrent

Соответственно, ничего не качается. Можно и без порта с nginx поизвращаться, но здесь дело не в nginx.

**Comment by Novik** [comment]
Насколько я могу судить по коду (и по отстутствию жалоб на подобное поведение) никто ничего не вырезает. Фрагмент фида приведите, пожалуйста.

**Comment by omgiafs** [comment]
Вот, пожалуйста. Весь тестовый фид:
```xml
<rss version="0.91">
<channel>
<title>TorrentMonitor RSS</title>
<link>http://nas:8085/tmon/rss/</link>
<language>ru</language>
<lastBuildDate>Fri, 20 Nov 2015 16:41:37 +0700</lastBuildDate>
<item>
<title>1. [kinozal.tv]_1381406.torrent</title>
<pubDate>Fri, 20 Nov 2015 16:41:37 +0700</pubDate>
<link>
http://nas:8085/tmon/torrents/[kinozal.tv]_1381406.torrent
</link>
</item>
<item>
<title>2. [kinozal.tv]_1385943.torrent</title>
<pubDate>Fri, 20 Nov 2015 16:41:32 +0700</pubDate>
<link>
http://nas:8085/tmon/torrents/[kinozal.tv]_1385943.torrent
</link>
</item>
<item>
<title>3. [kinozal.tv]_1377834.torrent</title>
<pubDate>Fri, 20 Nov 2015 15:48:51 +0700</pubDate>
<link>
http://nas:8085/tmon/torrents/[kinozal.tv]_1377834.torrent
</link>
</item>
</channel>
</rss>
```

**Comment by Novik** [comment]
![2015-11-20_13h51_35](https://cloud.githubusercontent.com/assets/1230409/11298078/d504fe46-8f8d-11e5-8c94-8c1a30a8e7fe.png)

**Comment by Novik** [comment]
![2015-11-20_13h52_54](https://cloud.githubusercontent.com/assets/1230409/11298115/fb8552be-8f8d-11e5-9abb-cc00545677f9.png)

**Comment by Novik** [comment]
Полагаю, вопрос исчерпан?

**Comment by omgiafs** [comment]
Хотелось бы. У меня 
![image](https://cloud.githubusercontent.com/assets/7763953/11298177/d96b0a4e-8faf-11e5-9b92-14a4b01d9b30.png)
Версия
![image](https://cloud.githubusercontent.com/assets/7763953/11298264/4e7f9b74-8fb0-11e5-80f6-a2a8a61a105c.png)

**Comment by Novik** [comment]
Извините, но каждый сам кузнец своей системы и своего счастья. Попробуйте использовать версию ruTorrent и плагина с гит. Хотя, AFAIK, изменений в плагин не вносилось уже очень давно, и дело, скорее всего, в настройках Вашей системы, а не в плагине.
Ничем больше помочь не могу.
