### ISSUE TITLE
Delay start until nfs share is mounted

### ISSUE THREAD

**Issue by TeHashX** [Novik/ruTorrent#1159]
Installed rutorrent v3.6 and it's all fine but if I restart server all torrents are pausing and I guess because nfs folder from /etc/fstab is not mounted yet.
Startup script is rtorrent.service in systemd
````
[Unit]
Description=rtorrent (in tmux)
[Service]
Type=oneshot
RemainAfterExit=yes
User=odroid
ExecStart=/usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
ExecStop=/usr/bin/tmux kill-session -t rtorrent
[Install]
WantedBy=default.target
````
How can I delay this script for 10-20 seconds?
Thanks

**Comment by Micdu70** [comment]
Your problem has nothing to do with ruTorrent... ruTorrent is a web interface...

**Comment by tuplink** [comment]
As this really isn't a ritorrent issue, I did have this issue with ritorrent. As long as your rtorrent config file is on the NFS share. You could edit the init.d script. After the #!/usr/bash.  You could start a loop then do a check to see if the file exist.
Not sure if my script is correct but Google can help with bash scripts

Something like 
FILE=/location/rtorrent.rc
NFSUP=0
while [  $NFSUP -ne 1 ]; do
            if [ -f $FILE ]; then
              NFSUP=1
           else
            echo "NFS not up"
           fi             
done

**Comment by tuplink** [comment]
Forgot should probably add a sleep 5 with the NFS not up
