### ISSUE TITLE
Safari doesn't save settings

### ISSUE THREAD

**Issue by PanDoreS** [Novik/ruTorrent#1160]
Hi!

I moved my default browser to Safari and I'm getting an issue with ruTorrent :/
It doesn't save the intern settings for ruTorrent, like the theme, or showing speed in the title.
The webpage reload, but nothing has change and the settings keep getting back to the default one.
On Chrome, I have no issues at all.
I use ruTorrent 3.7 on Safari 9.0.1 (11601.2.7.2).

Is it a know problem? Does I have to modify some settings on Safari?

Thanks !

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/issues/1094
