### ISSUE TITLE
Script can be messed up if username is part of other usernames?

### ISSUE THREAD

**Issue by geocoo** [Novik/ruTorrent#1161]
Hi there, thanks for your AWESOME script it has saved me hours of reading and complicated setup.

But I noticed something possibly a bit wrong.

I think the grep which finds the system user also finds users where the sys user is a component of the other users, it may not just be the grep but something is off for sure.

EG: I made a user 't' and it really messed with the script.
I included the output below.
Plus I don't think things were setup correctly, I couldn't find the config files etc etc.

So basically i made another user with a unique name and it worked perfectly, but I think this is a bug none-the-less.

Script: Output when I chose system user as 't':

Installation is complete.

Your downloads folder is in /root
/var/list
/nonexistent
/home/matt
/staging
/nonexistent
/home/t/Downloads
Sessions data is /root
/var/list
/nonexistent
/home/matt
/staging
/nonexistent
/home/t/.rtorrent-session
rtorrent's configuration file is /root
/var/list
/nonexistent
/home/matt
/staging
/nonexistent
/home/t/.rtorrent.rc

If you want to change settings for rtorrent, such as download folder, etc.,
you need to edit the '.rtorrent.rc' file. E.g. 'nano /root
/var/list
/nonexistent
/home/matt
/staging
/nonexistent
/home/t/.rtorrent.rc'

I should add the output from a working unique user:

Installation is complete.

Your downloads folder is in /home/unique/Downloads
Sessions data is /home/unique/.rtorrent-session
rtorrent's configuration file is /home/unique/.rtorrent.rc

If you want to change settings for rtorrent, such as download folder, etc.,
you need to edit the '.rtorrent.rc' file. E.g. 'nano /home/unique/.rtorrent.rc'

So, thanks again for the wonderful work, I am up and running it all happily now thanks to you!

**Comment by geocoo** [comment]
I should add, the output from a workng unique user:

Installation is complete.

Your downloads folder is in /home/unique/Downloads
Sessions data is /home/unique/.rtorrent-session
rtorrent's configuration file is /home/unique/.rtorrent.rc

If you want to change settings for rtorrent, such as download folder, etc.,
you need to edit the '.rtorrent.rc' file. E.g. 'nano /home/unique/.rtorrent.rc'

**Comment by Novik** [comment]
ruTorrent I do not have any sort of install script.
