### ISSUE TITLE
Magnet links work, Torrent Files do not

### ISSUE THREAD

**Issue by ThePraeceps** [Novik/ruTorrent#1162]
Hey,
I am able to add torrents via a magnet link, or adding the torrent file to rtorrent's watch folder works too. Trying to add torrent files via the web ui, fails however.
The torrent files aren't large enough to go over the php limit and I raised it regardless. I cannot get rutorrent or php to log any errors.

Any ideas?

**Comment by Novik** [comment]
> Trying to add torrent files via the web ui, fails however.

What about diagnostic? Can you see something on interface as result of torrent addition?

> I cannot get rutorrent or php to log any errors.

Check existence (and contents) of file /tmp/error.log.

**Comment by ThePraeceps** [comment]
Hey,
Thanks for the response, here's a picture of the error message
http://imgur.com/Zu3HCeG.jpg
Just a "failed to add torrent" message

No error log despite it being listed in my conf.
Here's my conf in case I missed something
http://pastebin.com/NCnCsCPf

Thanks!

**Comment by Novik** [comment]
```
 //$XMLRPCMountPoint = "/RPC2"; // DO NOT DELETE THIS LINE!!! DO NOT COMMENT THIS LINE!!!
```
???

**Comment by ThePraeceps** [comment]
Odd, I don't remember doing that myself.
However it doesn't have seemed to fix the issue.
I've updated the config below.
http://pastebin.com/1CWs28dx

**Comment by Novik** [comment]
> Odd, I don't remember doing that myself.

Try to use a normal version of ruTorrent and plugins.
Now you use an ancient  version with a strange patches in config.

**Comment by ThePraeceps** [comment]
Sure I updated to 3.7 but I still have the same issue,
Any other ideas?

**Comment by manasb** [comment]
@ThePraeceps Are you using lighttpd by any chance?

**Comment by ThePraeceps** [comment]
@manasb Nah, Apache.
