### ISSUE TITLE
ratio/day/week/month at zero for almost all torrents, nothing on traffic graph. How to purge the data?

### ISSUE THREAD

**Issue by tuxayo** [Novik/ruTorrent#1164]
The clear button in the traffic graph doesn't help.
I can't find where does the data comes from. The traffic plugin, rutorrent, rtorrent or libtorrent?

- libtorrent 0.13.6-1
- rtorrent 0.9.6-2
- rutorrent 3.7-4

**Comment by Novik** [comment]
You *already* have a zero data. What do you mean under the words 'purging' here? What is your problem?

**Comment by tuxayo** [comment]
> You *already* have a zero data.

Odly there is some data, but it's not consistent. Ratio/week at zero despite a ratio/day > 0.
![screen shot 2015-12-28 at 18 12 58](https://cloud.githubusercontent.com/assets/2678215/12022499/7f822bbc-ad90-11e5-986c-f446407ddc0e.png)
![screen shot 2015-12-28 at 18 14 45](https://cloud.githubusercontent.com/assets/2678215/12022500/7f8557f6-ad90-11e5-9c8a-23667aaf0acd.png)

> What do you mean under the words 'purging' here?

I'm not sure but I think that started after I gave a try to master version some time ago, then I went back to stable. But since I have those stat problems. I suspect that some stored data has issues that could be solved by clearing it.

New torrents also have those issues.

**Comment by tuxayo** [comment]
@Novik Is there details that is could provide to investigate why this happens?

**Comment by Novik** [comment]
Yet once. This is a normal behavior.
Plugin collect 3 types of data - global, per tracker and per torrent.
Ratios per day and etc columns are shown on the bases of per torrent statistic.
If you want to clear it - select all torrents and clear statistic for its.

**Comment by tuxayo** [comment]
> Yet once. This is a normal behavior.

Which part is normal behavior? The problem that I have is that there is not longer usable information provided by the ratio/day/week/month columns.

> If you want to clear it - select all torrents and clear statistic for its.

Sorry I can't find how to do it.

**Comment by Novik** [comment]
> Which part is normal behavior?

All parts.

> Sorry I can't find how to do it.

What you "can't to find"? 
How to select all torrents? Click on torrent list and press Ctrl-A. 
How to clear statistic for its? Select corresponding position in the control near the button 'Clear' and press this button.

**Comment by tuxayo** [comment]
Problem solved, I had a permission issue on `settings/trafic/last.csv`.

Now everything is fine.

![capture d ecran_2016-04-05_12-19-14](https://cloud.githubusercontent.com/assets/2678215/14278570/ac6baf64-fb28-11e5-9973-513fa68f2007.png)

Sorry that we didn't understood each other and thanks a lot for your time on that issue and for making ruTorrent!
It's a great software and that particular feature of ratio/day/weeks/month helps me a lot managing my torrents, it's seems you are the only one to have it. :)

**Comment by jtvd78** [comment]
@tuxayo I'm curious what your file permission problem was. I'm having this same problem, and I'm trying to find out how to fix it. 

Thanks

**Comment by tuxayo** [comment]
@jvandort sorry for the massively late response: I think I just changed the owner the "right one" (the one of my http server maybe? I don't remember and for you it might be different) or maybe I just changed the permissions for "group" and "others". Also check for the directory permissions to reach the file.
