### ISSUE TITLE
JS error: [rutorrent/js/common.js : 143] Uncaught TypeError: $.event.inheritedfix is not a function

### ISSUE THREAD

**Issue by linkpad** [Novik/ruTorrent#1165]
Hello, I've installed rutorrent and I get this error in the rutorrent log.
"JS error: [rutorrent/js/common.js : 143] Uncaught TypeError: $.event.inheritedfix is not a function"
There's nothing I can do, it slow down the UI because the error is spammed.

I use the latest rutorrent.

**Comment by linkpad** [comment]
Issue fixed, it was a conflict from a google chrome extension. Sorry for the false issue !

**Comment by memento** [comment]
Hey, I have the exact same problem.
Which extension was it conflicting with ?

**Comment by linkpad** [comment]
It was an adware I found in my programs, which was making js error on purpose. It was really a pain to delete it, no antivirus/antiadware ect.. was able to detect it, but you can see it on "programs" in windows.

**Comment by memento** [comment]
Ok, thanks. 
What malware ..?

**Comment by Novik** [comment]
This possible with any malware, which make embedding of yet one copy of jQuery to the every page, for example.

**Comment by Novik** [comment]
Or this may be browser's extension with a non-accurate code. Try to use another browser and check results.

**Comment by memento** [comment]
Yeah, I came to those conclusions, already. No clue.

**Comment by user1234567891011** [comment]
Cool, fix was to disable "Hide my Adblocker" extension in Chrome

**Comment by memento** [comment]
Good for you ! :)
I don't have the "Hide my Adblocker" extension in Chrome, though. And I have that probem in chrome and firefox.

**Comment by Demicro** [comment]
RecaptchaParser 1.1 this userscript cause the same problem

https://openuserjs.org/scripts/datnvt2712/RecaptchaParser_1.1
