### ISSUE TITLE
Ratio Plugin Issues

### ISSUE THREAD

**Issue by bjay1404** [Novik/ruTorrent#1166]
Hello, 

Everytime I reboot rTorrent, all of my torrents that already have a ratio of over 1 are stopped, but they shouldn't be according to their ratio groups. All of the torrents are in Ratio Group 8 have insane numbers like min of 90k and max of 20x and the other two fields with as many 9s as I can fit. I'm using the release version from 3.7, not the current git pull. Please help! I use the program with a VPN so it has to reboot a lot and I want to make sure it works.

**Comment by bjay1404** [comment]
This might be related - as I am using CP
https://github.com/RuudBurger/CouchPotatoServer/issues/2905

**Comment by bjay1404** [comment]
Any suggestions?

**Comment by Novik** [comment]
Something bad with your configuration. Try to read project's wiki. And paste configuration files (ruTorrent config.php, rtorrent.rc etc) here.

**Comment by bjay1404** [comment]
rtorrent config - http://pastebin.com/YS4Vgfth

rutorrent config http://pastebin.com/8KBjsR02

**Comment by Novik** [comment]
> execute = {sh,-c,/usr/bin/php /var/www/html/ruTorrent/php/initplugins.php SCRUBBED &}
> execute = {sh,-c,/usr/bin/php /var/www/html/ruTorrent/plugins/autotools/init.php &}
> execute = {sh,-c,/usr/bin/php /var/www/html/ruTorrent/plugins/autotools/autotools.php &}
> execute = {sh,-c,/usr/bin/php /var/www/html/ruTorrent/plugins/autotools/watch.php &}

You call initplugins for user SCRUBBED. 
But what is you mean in the other three lines?

**Comment by bjay1404** [comment]
I was having issues with autotools at one point and that seemed to help.
I'll try commenting them out.

**Comment by bjay1404** [comment]
That didn't fix the issue unfortunately.

**Comment by Novik** [comment]
> I was having issues with autotools at one point and that seemed to help.

These lines can't help. And you must restart rtorrent after it's removing.

1) Describe your configuration. You have one user (SCRUBBED) and one rtorrent instance? Or several users?
2) Paste here your ratio configuration.

**Comment by bjay1404** [comment]
Only one user and rtorrent instance.

Ratio.Dat: http://pastebin.com/ECihMYLP
Ratio.conf http://pastebin.com/GFy3Nsmp

**Comment by Novik** [comment]
> All of the torrents are in Ratio Group 8 have insane numbers like min of 90k and max of 20x and the other two fields with as many 9s as I can fit.

Ratio Group 8 haven't something like this, as I may see. And? What is your problem?

**Comment by bjay1404** [comment]
My main issue is that torrents are not following the ratio groups. When I
reboot my server and the rtorrent program all the of the torrents with a
ratio above 1 are listed as finished when I want them to seed. I simplified
my ratio configurations to only allow ratios of 1500+ and it still doesn't
work. Does that make more sense?

**Comment by Novik** [comment]
As result.
Your description in the ticket hasn't relation to your current configuration files. 
Your rtorrent configuration files contain an errors.
Please, create a new issue with a correct description and attach a correct configuration files to it.
