### ISSUE TITLE
Log warnings with PHP 7 "only variable should be passed by reference in php/util.php"

### ISSUE THREAD

**Issue by rfnx** [Novik/ruTorrent#1168]
Hello,

Since I upgraded to php 7.0.1, everytime I visit my ruTorrent interface I get this message in the log : 

```
PHP Notice:  Only variables should be passed by reference in php/util.php on line 548
```

The message appears 7 times. However, ruTorrent seems to work very weel with php 7.

Bye. Thanks for your awesome work ! Happy new year !

**Comment by Novik** [comment]
Thanks.
