### ISSUE TITLE
Plugin rutracker_ check

### ISSUE THREAD

**Issue by freemandigger** [Novik/ruTorrent#1170]
PHP 5.3.10

В plugins/rutracker_check/trackers/rutracker.php и plugins/rutracker_check/trackers/kinozal.php проверка загрузки торента по коду ответа не срабатывает т.к. `$client->status` это `string(3) "200"`, а у вас условие проверяет `int`
```php
if ($client->status !== 200) return (($client->status < 0) ? ruTrackerChecker::STE_CANT_REACH_TRACKER : ruTrackerChecker::STE_DELETED);
```
в anidub.php такой проблемы нет т.к. там используется сравнение без проверки типа.
Достаточно либо добавить `intval` либо использовать `!=` вместо `!==`

**Comment by Novik** [comment]
Спасибо.
