### ISSUE TITLE
screenshots plugin is not generating previews.

### ISSUE THREAD

**Issue by bStyler** [Novik/ruTorrent#1172]
Greetings Novik,

1) I have the latest ruTorrent 3.7 version with Screenshots plugin 3.70.
2) My rTorrent/ruTorrent runs on Ubuntu 15.04
3) I installed ffmpeg, this is my current version:
ffmpeg --version
ffmpeg version 2.5.9-0ubuntu0.15.04.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
4) These are my screenshots settings:
http://screencast.com/t/HgTipsGUZO

My issues is that screenshots are being created, but there is no thumbnail/preview in the creation process, here is a short video capture I made: http://screencast.com/t/Pou11vYaeab

Please advise.

Many thanks!

**Comment by Novik** [comment]
What happens, if you press button 'Save' or 'Save all'? Do you will have a correct file as result of this operation?

**Comment by bStyler** [comment]
Hi @Novik, thank you for the reply.

1) When I click "Save" I it downloads a 0KB size JPEG or PNG file, that can't be opened.
2) When I click on  "Save All" I do have the currect files, in a .tar archive:
https://gyazo.com/efb032672c2af212aaa22b0f6e14be05
The files are valid and look good.
3) And as I previously mentioned, in all cases, thumbnails don't appear.

I hope this helps troubleshooting further.

Thank you!

**Comment by Novik** [comment]
Disable usage of XSendFile feature in the ruTorrent config.php (set $canUseXSendFile variable to false).
Check https://github.com/Novik/ruTorrent/issues/945 for details.

**Comment by bStyler** [comment]
You have been very helpful and I confirm that screenshots now work perfectly well. Thank you @Novik !
I'll make sure to escalate that information to my colleagues.
