### ISSUE TITLE
filedrop throws error

### ISSUE THREAD

**Issue by delize** [Novik/ruTorrent#1174]
ruTorrent: v3.7
rtorrent: v.0.9.4
libtorrent: 0.13.4
Google Chrome: Version 47.0.2526.111 m

When trying to upload torrents via drag and drop methods (either 1 or 7), I get the following error message:
[16.01.2016 19:30:00] Plugin filedrop: Your browser does not support HTML5 file uploads. Plugin was disabled.

According to my research, Chrome should be supported with this plugin, maybe something has changed in the way HTML5 uploads are handled, but it would be nice to get this supported again.

**Comment by Micdu70** [comment]
What is your OS version ? Is it a "N" Edition ? Because your issue comes from your computer / software configuration, not from Google Chrome / ruTorrent plugin.

**Comment by delize** [comment]
The server is Ubuntu 14.04 LTS, the client is Windows 10 Pro.

Not the "N" edition, just a normal Windows 10 Pro.
Chrome Plugins: uBlock origin, HTTPS Everywhere, pushbullet, chromeipass, xmarks, lazarus, and vanilla cookie manager. ANd of course the default chrome add-ons (Drive, Gmail, etc)

**Comment by Novik** [comment]
Sorry, but I can't reproduce this with a same software.
1) Try to temporary disable chrome plugins and add-ons.
2) Try to use development version of ruTorrent and it's plugins.

**Comment by delize** [comment]
I don't know what the problem was, but it doesn't seem to be occurring anymore. Apologies for the bug report, not sure what happened there.

**Comment by boli** [comment]
On my browser, this error will appear when the page is served through http

but the error does not appear when it is served through https
