### ISSUE TITLE
Feeds missing from Web Gui, but still working.

### ISSUE THREAD

**Issue by Deadringers** [Novik/ruTorrent#1175]
After several reboots/restarts of my server and web/rtorrent services I noticed that my RSS feeds are not showing in the Web GUI any longer.
BUT, my RSS feeds are still working, and the rules to auto download torrents that match my rules are still active.

I've checked and the RSS plugin is enabled and loaded:
http://imgur.com/FXRWwqW

When I look under: /var/www/rutorrent/share/settings/rss/cache

I see a few files:

*A file with many letters/numbers that is my RSS feed* e.g. 827dndkj233j43n12343n2
data
filters
history
info

Everything here "looks good" but then again I don't know what I'm looking for.

e.g. my filter names, RSS feed names and links are all there.
The RSS feed (long filename with letters/numbers) also contains the latest rss feed and looks like it should work.

Any idea why it's missing from the GUI? 
And how do I fix this?

Delete the contents of "/var/www/rutorrent/share/settings/rss/cache" and re-create my feeds?

**Comment by Novik** [comment]
I think, the last file - 'info' - is corrupted. This is list of all your feeds and it used for showing information in GUI.

> Delete the contents of "/var/www/rutorrent/share/settings/rss/cache" and re-create my feeds?

For example.

**Comment by Deadringers** [comment]
I've removed those files (saved somewhere else incase I need them) and restarted the apache process.

all seems to be working for the moment so we'll see. 

Thanks for the feedback!
