### ISSUE TITLE
(Feature) labels should be able to be added to all 3 types in "add torrent" modal

### ISSUE THREAD

**Issue by timelf123** [Novik/ruTorrent#1177]
Currently you can only add a label before the torrent starts with the top option

![Labels](https://i.imgur.com/9JXEYdk.png)

**Comment by Novik** [comment]
Can't understand you, sorry, What wrong?

**Comment by user1234567891011** [comment]
I believe he is wanting to have the "Label:" option for "Torrent file:" and "Torrent URL:" so that you can apply a label to a torrent being added via file or url.

**Comment by Novik** [comment]
Label (and all checkboxes with a Directory control) is applied for the both cases.

**Comment by user1234567891011** [comment]
Good to know! 
Auto adding torrents is better :+1:

**Comment by timelf123** [comment]
My mistake, the label applies to all methods!
