### ISSUE TITLE
Adding > 20 torrent files fails

### ISSUE THREAD

**Issue by krichter722** [Novik/ruTorrent#1181]
When adding > 20 torrent files only the first 20 are added and the rest is quietly ignored whereas the dialog says `n files selected` (where `n` is the number of selected files).

experienced with 59153b2

**Comment by Novik** [comment]
How you add these torrents?

> dialog says n files selected

Attach a screenshot, please.

**Comment by Leifern** [comment]
The same happends when I add more than 20. Adding by clicking on the earth sign top left -> Browse(Non-English language, but i guess its browse) -> Selects over 20 torrents and only 20 of them gets added. Debian 8 with rTorrent 0.9.6/0.13.6

**Comment by KyleSanderson** [comment]
I actually frequently encounter this unfortunately whenever a torrent name contains &. I too thought it was a number.

**Comment by Novik** [comment]
Configure your PHP properly.

http://php.net/manual/en/ini.core.php#ini.max-file-uploads
