### ISSUE TITLE
Torrent list not yet available, connection to rTorrent not established

### ISSUE THREAD

**Issue by CtrlSystem** [Novik/ruTorrent#1183]
I have a one problem and hope to can get help to resolve it. Few times per day, mostly when i stop some torrents and after that start it again and when have more torrents in my seedbox i get this error:
Torrent list not yet available, connection to rTorrent not established.
In the Log : No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.
[screenshot from 2016-01-22 23 21 35](https://cloud.githubusercontent.com/assets/14192127/12523371/1bea07fe-c15f-11e5-9784-036e799dc09d.png)
Via ssh client i type the command : screen rtorrent
and everything running normal. But the problem are I am not 24/7 on my PC to watch when I get this error... and when the error are shown all torrents are not continued seeding.... its to bad... any suggest how i can resolve this....? Thanks!

Kind Regards,
CtrlSystem

**Comment by Novik** [comment]
I think this mean - your rtorrent instance was crashed.

**Comment by CtrlSystem** [comment]
Yes, rtorrent was crashed, but this is a few times per day... any idea how i can resolve this? :(

**Comment by Novik** [comment]
Lets assume, you visit to your doctor with a words "Doctor, I was ill inside!".
How do you think, what he answer to you? I think - something like "To the morgue"...

System characteristics? 
rtorrent version?
rtorrent config?
ruTorrent version?

**Comment by manasb** [comment]
rtorrent can be unstable. For a simple workaround that simply restarts rtorrent every time it crashes, you can write a script. Note that this does not fix the underlying issue.

**Comment by alincocio** [comment]
Same issue here! Did anybody find a solution? I have this uncommented in my `rtorrent.rc`: `network.scgi.open_port = 127.0.0.1:5000`. If I do comment it out rtorrent starts. but I can't access it through RuTorrent. 
```
May 27 18:43:27 $HOSTNAME systemd[1]: Starting rTorrent System Daemon...
May 27 18:43:27 $HOSTNAME systemd[1]: Started rTorrent System Daemon.
May 27 18:43:27 $HOSTNAME rtorrent[44031]: rtorrent: Error in option file: ~/.rtorrent.rc:110: SCGI already enabled.
May 27 18:43:27 $HOSTNAME systemd[1]: rtorrent.service: Main process exited, code=exited, status=255/EXCEPTION
May 27 18:43:27 $HOSTNAME systemd[1]: rtorrent.service: Failed with result 'exit-code'.
```
And inside rutorrent I it says: Torrent list not yet available, connection to rTorrent not established.
