### ISSUE TITLE
Load bar in the lower status bar doesn't explain what it measures

### ISSUE THREAD

**Issue by krichter722** [Novik/ruTorrent#1185]
The label and the tooltip only display `n %` which could be CPU load, I/O load, system load, etc.

experienced with 59153b2

**Comment by Micdu70** [comment]
The plugin is called "cpuload", the description is "This plugin adds a CPU Load indicator to the bottom bar". But..., on linux-bases systems,  it's displaying `n %` of the "load average" (system load), depending of the number of CPU core(s) you have. It should auto-detect the number of CPU core on linux ( If you have 1 core => 100% = 1.00 of load average, if you have 2 cores => 100% = 2.00 of load average, etc. ). But you can configure manually the number of CPU core in the conf.php file.

I really don't know if this plugin displays the % CPU average on windows systems, but it should I think.

**Comment by krichter722** [comment]
> The plugin is called "cpuload", the description is "This plugin adds a CPU Load indicator to the bottom bar". But..., on linux-based systems, it's displaying n % of the "load average" (system load), depending of the number of CPU core(s) you have. It should auto-detect the number of CPU core on linux ( If you have 1 core => 100% = 1.00 of load average, if you have 2 cores => 100% = 2.00 of load average, etc. ). But you can configure manually the number of CPU core in the conf.php file.

Yes, I know. The issue (see title and text) is about explaining that intuitively to the user, e.g. enhance the tooltip text.
