### ISSUE TITLE
Implement Packages for Unpack plugin which utilise Multi Core CPU

### ISSUE THREAD

**Issue by dannyti** [Novik/ruTorrent#1186]
Reference:  https://github.com/Novik/ruTorrent/tree/master/plugins/unpack

With the newer and better servers in use, Can we implement and use Compression/Decompression Packages which are designed for multi threaded operation using all the cores of CPU.

Here's a in depth analysis of multi core using packages for compression and decompression:
http://utappia.org/parallel-compression-decompression-files-multicore-multithreaded-cpu.html

Only RAR has the multi threaded capability for decompression and compression. The unrar and unzip programs and their commands can be adjusted accordingly. 

Thanks.

**Comment by PulsedMedia** [comment]
I suggest this would be as an option, not the only mode of operation.
In some environments it's BETTER that not all resources are consumed by single action, ie. shared systems

This can consume all the CPU time while consuming all the I/O resources, leading to a situ where only the compression/decompression progresses, while everything else is timing out.
