### ISSUE TITLE
Append to Pathname When Unpacking Torrent Data

### ISSUE THREAD

**Issue by RonnyJ** [Novik/ruTorrent#1191]
After upgrading ruTorrent from 3.6 to 3.7, unpack plugin no longer appends Torrent Name and/or Torrent Label to pathname when unpacking torrent data.

Tried to tick off/on Torrent Label and/or Torrent Name under Settings - Unpack, but file is still unpacked directly to directory specified.

rTorrent 0.9.6, libtorrent 0.13.6, ruTorrent 3.7

Tried to downgrade unpack plugin to 3.6, and then Torrent Name and/or Torrent Label was appended as it should.

**Comment by Novik** [comment]
Show me screenshot with your unpack settings, please.

**Comment by RonnyJ** [comment]
![unpack_settings](https://cloud.githubusercontent.com/assets/17077797/13374325/a17be7fa-dd81-11e5-800a-cb76013c962d.jpg)

**Comment by Novik** [comment]
I can't reproduce this.
1) Try to use ruTorrent version from github.
2) If you made any changes in the plugin's conf.php, please, paste its here.
3) This has relation to the auto unpack feature, or to manual unpacking too?

**Comment by RonnyJ** [comment]
I grabbed the latest ruTorrent from GitHub, same result. 
Also, no changes has been made to unpack plugins conf.php.

It is related to manual unpacking only. Auto unpack works and creates subfolder, but manual unpacking does not.

**Comment by Novik** [comment]
Fixed.

**Comment by RonnyJ** [comment]
That did the trick. Thanks a lot. Working now (=
