### ISSUE TITLE
JS error: [http://IP/rutorrent/js/common.js : 143] Uncaught TypeError: $.event.inheritedfix is not a function

### ISSUE THREAD

**Issue by user1234567891011** [Novik/ruTorrent#1192]
Since starting the latest update, I get this error in the log tab:
JS error: [http://IP/rutorrent/js/common.js : 143] Uncaught TypeError: $.event.inheritedfix is not a function

I have tried checking out common.js as well as loading it from a backup file I made some months ago with no fix. All permissions are correct/same as they were before the update. 

Any suggestions would be appreciated (other than to re-install and start again from the beginnig for now)

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/issues/1165

**Comment by user1234567891011** [comment]
Opps, thanks. I will look into it, weird that it starts after updating...

**Comment by user1234567891011** [comment]
Cool, fix was to disable "Hide my Adblocker" extension in Chrome"
