### ISSUE TITLE
Sort by 'Added' Causes Multiple-Added Torrents to Jump Around.

### ISSUE THREAD

**Issue by Joshmannn** [Novik/ruTorrent#1193]
When I sort by the **"Added"** column , I notice that torrents which were added all together (gives them the same time stamp) seem to dance around each other in terms of order. Now, I know if torrents are added one at a time, they will have different time stamps and this problem does not happen but adding a bunch of torrents at the same time never use to be an issue.

**Comment by Novik** [comment]
Use second sorting (Shift+Click on another column's header) for avoid this.
