### ISSUE TITLE
rutracker_ check

### ISSUE THREAD

**Issue by rtorrentuser** [Novik/ruTorrent#1194]
После "пожизненной блокировки" "Кинозала" появилась проблема: адрес, по которому скачивается сам торрент-файл, не блокирован, а вот адрес, по которому
проверяется хэш - блокирован. При очередной проверке обновления плагин
безуспешно пытается проверить хэш по заблокированному адресу и
перескакивает ниже - к скачке торрент-файла. То есть при каждой проверке
скачиваются абсолютно все торрент-файлы, вне зависимости от того,
обновлялись ли они. Но на треккере есть лимит по скачанным торрентам, который таким образом моментально выбирается...
	Я заметил, что после реального обновления на треккере "Кинозал",
торрент в веб-интерфейсе "краснеет" и помечается в закладке "General",
как незарегистрированный (Tracker Status:	Tracker: [Failure reason "unregistered torrent"]). 

Нельзя ли это использовать как "костыль", чтоб избежать описанного выше поголовного скачивания торрент-файлов: то есть непосредственно перед скачиванием торрент-файла дополнительно проверять и скачивать только при условии, что он помечен, как незарегистрированный?

**Comment by Novik** [comment]
1) Нет, данный ответ трекера использовать никак нельзя.
2) Как это не странно, у меня с недавних пор http://kinozal.tv не заблокирован и все корректно работает. Причем как для старых раздач (с трекером *.kinozal.tv) так и для новых (с трекером torrent4me.com)
Более того, описанной ситуации - 

> Адрес, по которому скачивается сам торрент-файл, не блокирован, а вот адрес, по которому
проверяется хэш - блокирован

в принципе быть не может, потому что оба адреса принадлежат одному домену (kinozal.tv).
Возможно, я что-то делаю не так, или у Вас имеет место быть какой-то странный особый случай?

**Comment by rtorrentuser** [comment]
Понял... Возможно, это, конечно, специфика провайдера... Мой вот страницу "http://kinozal.tv/details.php?id=..." исправно блокирует, а против "dl.kinozal.tv/download.php?id=..." ничего не имеет и позволяет скачивать...

**Comment by Novik** [comment]
Очень странно. Посмотрю.

**Comment by rtorrentuser** [comment]
Да, сосбенности провайдера... Проверил на Йоте - она блокирует оба...

**Comment by Novik** [comment]
Поправил ошибку в плагине авторизации для кинозала, если соотв. URL не блокированы - теперь будет работать штатно.
Если блокированы - не знаю, чего делать. Там только прокси поможет.
Можете попробовать вписать соотв. параметры в файл php/Snoopy.class.inc, переменные 
$proxy_host и $proxy_port.
Но это, понятно, 1) хак 2) если прокси требует авторизацию - работать не будет.
Больше ничего пока сделать не могу, буду думать.

**Comment by rtorrentuser** [comment]
Вариант с $proxy_host и $proxy_port очень даже хорошо работает. Спасибо за подсказку!
Попутно, пока не забыл, в Tracklabels  в иконках треккеров предлагаю переименовать "rutracker.org.png"  в "rutracker.cc.png"  и добавить иконку "nnm-club.info.png":
![nnm-club info](https://cloud.githubusercontent.com/assets/1167563/13391049/3a3eec50-dee3-11e5-9e31-93929d5ad4a2.png)

**Comment by Novik** [comment]
Вы это сами вполне можете сделать. Делаете fork репозитария, производите нужные изменения, оформляете pull request.
