### ISSUE TITLE
Error loading torrents via RSS using HTTPS

### ISSUE THREAD

**Issue by reyder** [Novik/ruTorrent#1196]
Yesterday I added RSS with HTTPS and torrents getting error loading (4). Changed to https and it works again.

**Comment by Novik** [comment]
I add rss with a https links on regular basis. And all works OK. Try to submit more details.
URL of your feed, for example. ruTorrent version. Etc.

**Comment by bbashy** [comment]
@reyder May need to add this to .rtorrent.rc (if you don't add the root certs)

```
# ignore errors for cacerts
network.http.ssl_verify_peer.set=0
```
