### ISSUE TITLE
fast resume not working and file select button not apper

### ISSUE THREAD

**Issue by ChuLiqiang** [Novik/ruTorrent#1197]
I want use different torrent file(include same file but from different trackers) to seeding same file.
I want to skip hash check by use fast resume.but it is not working.should i add some plugins to fast resume.
![image 3](https://cloud.githubusercontent.com/assets/2747722/12999846/85790cb2-d18e-11e5-81d3-704a479cfd02.png)

**Comment by Novik** [comment]
1) https://github.com/Novik/ruTorrent/wiki/Plugin_getdir
2) 'Fast resume' option is intended for skipping hash check when you already have torrent's data. And this data is a correct.
