### ISSUE TITLE
fast resume not working

### ISSUE THREAD

**Issue by ChuLiqiang** [Novik/ruTorrent#1198]
I am ture i have all data for a torrent. but fast resume not working when add a torrent for that file.
Can you tell we where to find the problem in my environment. I install ruTorrent in my 
wifi R6300v2 router(by entware). I use lighhttp(should i add some access permission to it?) to  run ruTorrent. ruTorrent fast resume feature base some software?

**Comment by Novik** [comment]
This means - data is incorrect or your doesn't specify correct path to it.

> ruTorrent fast resume feature base some software? 

https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent_fast_resume.pl
