### ISSUE TITLE
trying to add rss feeds

### ISSUE THREAD

**Issue by simon92922** [Novik/ruTorrent#1202]
I'm trying to add rss feeds but nothing seems to be working correctly, i add a label and it doesnt apply.

it comes back as "null"
this is the details it returns

[22.02.2016 00:24:05] Description URL: null
[22.02.2016 00:24:05] Download URL: null

RSS feeds have appeared a couple of times but whenever i double click on one to add it to downloads the below error appears:

[22.02.2016 00:16:30] JS error: [http://192.168.0.11:3030/js/jquery.js line 2 > eval : 2536] TypeError: theWebUI.rssItems[obj.id] is undefined

Could anybody shed some light on this please?

**Comment by simon92922** [comment]
![rtorrent](https://cloud.githubusercontent.com/assets/17394410/13206685/0307265a-d8fb-11e5-9266-1ff32370118c.png)

**Comment by Novik** [comment]
What about URL of your feed, ruTorrent version etc?
