### ISSUE TITLE
distribution of available download rate doesn't take into account priority after increasing the download limit

### ISSUE THREAD

**Issue by krichter722** [Novik/ruTorrent#1204]
Steps to reproduce:

- add multiple (e.g. 10) torrents and let connections be established so that available download rate is at the maximum and distributed over multiple files (e.g. 10% for each).
- set a download limit (e.g. to 1/2 of the available download rate) and wait until the limit adjusts
- set the priority of one torrent to a higher value than all others (e.g. highest)
- unset the limit

Expected behaviour: The available download rate is given to the file with the highest priority either exclusively (e.g. `55 % = 1-(9 * (10 %/2))`) or at least with higher priority, i.e. > 10 %.

Observed behaviour: Available download rate is distributed randomly to torrents.

experienced with 2869b3b

**Comment by Novik** [comment]
ruTorrent is not a bittorrent client. 
ruTorrent is a WebUI for it.
https://github.com/rakshasa/rtorrent/issues
