### ISSUE TITLE
ratio rules extratio not adding ratio groups to labels from sickrage

### ISSUE THREAD

**Issue by drew156651** [Novik/ruTorrent#1207]
ive set everything up in sick rage to add label to tv to torrents well it shows up in rtorrent but rules say if torrent label contains tv then set to a certain group but never does but its labeled.

**Comment by drew156651** [comment]
if i add a torrent and select the label it works but not if sickrage adds it with the tv label.

**Comment by Novik** [comment]
Sorry, but I can't understand - what is you want. Words like 'ive', 'sickrage' etc are unknown for me.
Please, try to write on the normal language.

**Comment by drew156651** [comment]
sick rage is basically like sick beard it automatically downloads torrents and sends them to rtorrent. i have setup it up to use a label which is tv but when sick rage loads the torrent in rtorrent with the proper label the ratio rules is not catching it.

**Comment by drew156651** [comment]
but if i add the torrent myself and label it it will apply the ratio group

**Comment by Novik** [comment]
And this is a normal behavior. ruTorrent can't know, when some external program changes label of torrent. This external program must say to ruTorrent about that.
