### ISSUE TITLE
Not checking for settings/rss directory existing on rss update

### ISSUE THREAD

**Issue by PulsedMedia-Aleksi** [Novik/ruTorrent#1208]
PHP Warning:  touch(): Unable to create file /home/****_/www/rutorrent/share/settings/rss/update.lock because No such file or directory in /home/**_**/www/rutorrent/php/lock.php on line 26

Somewhere should be something along the lines:

if (!file_exists('share/settings/rss')) mkdir('share/settings/rss', 0666, true);

last bit is for recursive so even share & settings directories are created if they do not exist.

**Comment by PulsedMedia** [comment]
Also question, why does ruTorrent at all do file locking? Is this for multiuser variation?
