### ISSUE TITLE
Scheduler not launching unless WebUI open

### ISSUE THREAD

**Issue by kr4ft** [Novik/ruTorrent#1209]
Hi,

I'm using ruTorrent and rTorrent on my Raspberry Pi 2 running OpenELEC. I have the scheduler plugin enabled and configured to only download in off-peak periods.

Unfortunately these restrictions are not enforced in rTorrent until I open the WebUI page. If the WebUI page is subsequently closed then after about an hour rtorrent will cease to respect the restrictions. 

I can verify this by running rTorrent over SSH (using  `dtach -a /tmp/rtorrent.dtach -z`) and then opening the WebUI.

I've added the following line to my rtorrent.rc file but I still doesn't work. 
`execute = {sh,-c,/storage/.kodi/addons/service.downloadmanager.rTorrent/bin/php /storage/.kodi/addons/service.downloadmanager.rTorrent/rutorrent/php/initplugins.php &}`

php location determined by `which php`

Webauth is turned off, I only have a single ruTorrent user. 

Any ideas?

**Comment by alexcoe** [comment]
You have a space between bin and file paths, replace that with a comma.

**Comment by kr4ft** [comment]
I've tried adding a comma like this
`execute = {sh,-c,/storage/.kodi/addons/service.downloadmanager.rTorrent/bin/php,/storage/.kodi/addons/service.downloadmanager.rTorrent/rutorrent/php/initplugins.php &}`

Unfortunately it doesn't work. Is the comma supposed to go somewhere else?

**Comment by kr4ft** [comment]
I think I've fixed it. It appears to have been a time zone issue. But I do not understand why the problem occurred, given it was correctly set in the `php.ini`

Initially the scheduler in the WebUI was not following the correct timezone, so I had to edit the `date.timezone` setting in the `php.ini` file. This corrected the scheduler in the WebUI. 

But when I executed `/storage/.kodi/addons/service.downloadmanager.rTorrent/bin/php /storage/.kodi/addons/service.downloadmanager.rTorrent/rutorrent/php/initplugins.php` over ssh manually, it advised me that `date.timezone `was not set and instead defaulting to UTC. Obviously it is set, it just seems that the plugin can't read the `php.ini` file.

So I added `date_default_timezone_set('my/timezone');` into the top of the `settings.php` file. Now the scheduler seems to work without the WebUI.

**Comment by Novik** [comment]
>  the plugin can't read the php.ini file.

Plugin hasn't relation to this. You should configure your php cli correctly. 
Point: system has *two* php.ini. One for web-server module and one for standalone usage of php.

**Comment by kr4ft** [comment]
Interesting. 
When I run `find / -name php.ini`, it only finds one php.ini in `/storage/.kodi/addons/service.downloadmanager.rTorrent/bin/php.ini`

Any ideas where the other one might be? Do I need to create it?

**Comment by Novik** [comment]
Try to check documentation.
http://php.net/manual/en/configuration.file.php

**Comment by kr4ft** [comment]
`php --ini` doesn't work on my console.

If I launch a php info page using `<?php phpinfo(); ?>`, it reports:
Configuration File (php.ini) Path	/storage/.kodi/userdata/addon_data/tools.php/etc
Loaded Configuration File	/storage/.kodi/addons/service.downloadmanager.rTorrent/bin/php.ini

This doesn't make much sense as tools.php/etc doesn't exist.

**Comment by Novik** [comment]
> If I launch a php info page using <?php phpinfo(); ?>

If you launch a php info page using <?php phpinfo(); ?> the you view an information for web-server module. Not for cli. 

> php --ini doesn't work on my console.

Sorry, but this is your own problem. It hasn't relation to ruTorrent.

**Comment by kr4ft** [comment]
I see.

When I ran `php -i | grep "Loaded"` it reports
Loaded Configuration File (none) 

Seems like there is no php.ini file. 
Now I just need to figure out where to create it.

Any ideas?

**Comment by Novik** [comment]
php -i | grep "Configuration"

**Comment by kr4ft** [comment]
Ahah! I created the folders in that file path and copied the php.ini file over. 

It all works now! 

Thanks so much!
