### ISSUE TITLE
add torrent in stopped state by default

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1210]
is this possible?
I use bittorrent webui in firefox to add torrents to rutorrent.
can I make it so that the torrent that are added are not started automatically?

**Comment by Micdu70** [comment]
Hello,
If this browser's add-on doesn't have an option to add torrents in 'paused state', (the "Remote Torrent Adder" extension for Chrome have it) you should try to contact the developper to add this.

**Comment by rezad1393** [comment]
I meant this for rtorrent or rutorrent not the browser addon.
I am searching for an option that I could set and it would always (no matter the mechanism for adding the torrent) add them in stopped stated( as in not even creating the files for torrent , just add them to the list)

**Comment by jappish84** [comment]
@rezad1393 you can do this by simply changing whatever is after "load." to "normal" in the .rtorrent.rc file as below. Maybe this is just for watch-dir? idk

# Watch a directory for new torrents, and stop those that have been
# deleted.
schedule = watch_directory,10,10,load.**normal**=/path/to/watch/*.torrent

**Comment by rezad1393** [comment]
no
that is for watch folder.
not for adding torrents from other apps to rutorrent.
this is not rutorrent fault.
the app that i use is a firefox extension that send the torrent to rutorrent. but it doesn't have any option  to set the added torrent mode to stopped.
if rutorrent had an option for this ( or even rtorrent) that made it that every thing that was added was added in stopped state that would be great.

**Comment by Novik** [comment]
Try to use normal FF extension. For example, https://addons.mozilla.org/en-US/firefox/addon/xirvik-torrent-to-seedbox-uplo/

**Comment by rezad1393** [comment]
sorry for misunderstanding . when I said the app I use , I wanted to say an addon on firefox application.
