### ISSUE TITLE
autotools stops working when ....

### ISSUE THREAD

**Issue by raven-au** [Novik/ruTorrent#1212]
Hi,

I had a problem where the autotools plugin stopped working, at least the auto label and the auto move.

If the torrent download location is changed in the ruTorrent configuration but not the rTorrent rc file autotools auto label and auto move stop working (don't know if auto watch if affected).

I think this is because autotools uses the setting from the rTorrent rc file, rather than the ruTorrent configuration, to match the initial path of the incoming torrent and if that fails it gives up.

I think it a little odd that  autotools uses the rTorrent rc setting in preference to the ruTorrent configuration, but ideally both probably should be checked before giving up.

**Comment by Vastlee** [comment]
Just ran into a similar issue. The auto-move works, but the add label stopped.

![image](https://user-images.githubusercontent.com/7232810/55683569-1e982f80-58f6-11e9-89e0-fb130c561a51.png)
