### ISSUE TITLE
what does the traffic plugin colors mean?

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1217]

**Comment by Wyall** [comment]
Why don't you share your newly gained knowledge? Found this looking for the same thing

**Comment by Novik** [comment]
Data for the previous (darker) and current (lighter) period.

**Comment by Wyall** [comment]
That makes sense, thanks!

**Comment by bermudi** [comment]
can I get a better explanation? If I understand correctly one color is for the previous period while the other is for the current one, right? If that is the case how come my graph shows one color in-between the other? this would mean either: current-previous-current or previous-current-previous. What is going on?

https://screenshots.firefox.com/qJWsjzOqnKb1HDQH/bermudi.com

**Comment by Micdu70** [comment]
If current value is null = display previous value
If current value not null = display current value

That's how it seems to work.

**Comment by bermudi** [comment]
yeah, this doesn't answer my question in any way. the graph is essentially showing 3 different periods or one period being broken up in two by the other which defies the "previous/current" description.

**Comment by rezad1393** [comment]
from 17 of yesterday to 24,which would be previous , then from 00 today to 17 today which would be current period.
if you stop rtorrent and later in week start it again it would write over the stats.
basically the last period is written in darker color and then as it is running it overwrites then old stats with the new stats and then as one period ends (24pm or last day of month for monthly display) then the older period become dark.
