### ISSUE TITLE
NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1219]
Logged into ruTorrent this morning to find this:

Bad response from server: (0 [error,getplugins]) [Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: https://<EDITED>.com/rutorrent/js/jquery.js :: .send :: line 5" data: no]

OS is Ubuntu 14.04 - webserver has access to the right folders/files, no permissions have been changed. Anyone else seeing this?

**Comment by pairughdocks** [comment]
ERROR: 2016/03/23 17:29:31 [error] 7683#0: *298 FastCGI sent in stderr: "PHP Warning:  fopen(/var/nginxroot/rutorrent/share/users/pairughdocks/settings/uisettings.json): failed to open stream: No such file or directory in /var/nginxroot/rutorrent/php/getsettings.php on line 7" while reading response header from upstream, client: 130.156.111.2, server: example.com, request: "POST /rutorrent/php/getsettings.php HTTP/1.1", upstream: "fastcgi://unix:/etc/phpcgi/php-cgi.socket:", host: "example.com", referrer: "https://example.com/rutorrent/"

File is located at path, and owned by "nginx"

pairughdocks@deathstar:/var/nginxroot/rutorrent/share/users/pairughdocks/settings$ ls -lah
total 112K
drwxrwxrwx 5 nginx        nginx        4.0K Mar 23 18:11 .
drwxrwxrwx 4 nginx        nginx        4.0K Mar 23 17:29 ..
-rw-rw-rw- 1 nginx        nginx          56 Mar 23 17:29 cpu.dat
drwxrwxrwx 2 pairughdocks pairughdocks 4.0K Mar 23 18:13 erasedata
-rw-rw-rw- 1 nginx        nginx         42K Mar 23 18:11 extsearch.dat
-rw-rw-rw- 1 nginx        nginx        5.1K Mar 23 18:11 loginmgr.dat
drwxrwxrwx 3 pairughdocks pairughdocks 4.0K Mar 23 18:00 rss
-rw-rw-rw- 1 nginx        nginx         25K Mar 23 18:11 rtorrent.dat
-rw-rw-rw- 1 nginx        nginx        1.8K Mar 23 18:11 scheduler.dat
drwxrwxrwx 4 pairughdocks pairughdocks 4.0K Mar 23 18:00 trafic
-rw-rw-r-- 1 nginx        nginx        2.1K Mar 23 17:29 uisettings.json

**Comment by pareshchouhan** [comment]
+1, exactly same error 
```
07.06.2016 23:53:23] WebUI started.
[07.06.2016 23:54:29] Bad response from server: (0 [error,getplugins]) [Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: https://insertIpHere/rutorrent/js/jquery.js :: .send :: line 5" data: no]
```

**Comment by pareshchouhan** [comment]
okay this is way too complicated, when I logged into my VPS via a terminal, I got lots of error, (I had access to a virtual terminal, which I used to look into the problem), when the system booted It asked me to run fsck manually apparently something was wrong with different inodes on device :/ 
Could be something similar with you.
