### ISSUE TITLE
ruTorrent not saving settings - Synology

### ISSUE THREAD

**Issue by kzendra** [Novik/ruTorrent#1220]
DSM216 v5.2 (now v6.0)
I open settings of ruTorrent in web page, change port in connection tab and press OK.
After that, there is still yellow exclamation mark showing that I'm not connectable (router is configured proprely). I place mouse pointer over exclamation mark and it shows me port from default random range.

After restarting ruTorrent (or entire DSM), settings are back to default port range.

**Comment by Novik** [comment]
This is a correct behavior.
1) Port can't be changed without restart of rtorrent.
2) All other changes in rtorrent parameters are valid during current session only. For making its permanent, you should edit rtorrent's config file.

**Comment by kzendra** [comment]
Whys is there a possibility to change something if it can't be saved?
Sorry, but I work as programmer for last 16 years with customers and for me that logic is somewhat wrong.

**Comment by Novik** [comment]
> Whys is there a possibility to change something if it can't be saved?

For test purposes, for example.
Server's part of ruTorrent haven't access to the rtorrent config file. At all.
