### ISSUE TITLE
Add support for 7zip in unpack

### ISSUE THREAD

**Issue by GoodOmens83** [Novik/ruTorrent#1225]
Synology has completely removed the unzip binary from their OS in transition to using 7zip

Could we add support for the 7z binary in place of unzip?

**Comment by smreka** [comment]
I am also a Synology user and would really love this. Synology removed unzip in DSM 6.0 and instead uses 7zip.


Best regards,

Tom

**Comment by whytedwarf** [comment]
I'd take a look here haven't tested it but looks like it should work.
[https://github.com/isaactolstoi/ruTorrent/commit/009af4504a525e700cbf84f3e793212ebdaf9ce6](https://github.com/isaactolstoi/ruTorrent/commit/009af4504a525e700cbf84f3e793212ebdaf9ce6)

**Comment by Novik** [comment]
Test it and make pull request, please.
