### ISSUE TITLE
rutorrent won't work on firefox since v45

### ISSUE THREAD

**Issue by gputier** [Novik/ruTorrent#1227]
Hello
Rutorrent dosent work with plugin httprpc rpc & trafic plugin since v45 of firefox;
When i downgrade to v44, i have no problem.

**Comment by Micdu70** [comment]
Hello
No issue here with Firefox v45(.0.1), so it's specific with your Firefox installation / modules.

**Comment by gputier** [comment]
Hi.
Thx for reply.
I have 600 customers with this bug....

**Comment by Novik** [comment]
v45(.0.1), v46.0b4 - all works correctly.
Try to add more details. For example, ruTorrent version. What is you mean under the words 'Rutorrent dosent work'. Etc.

**Comment by gputier** [comment]
HI

https://gyazo.com/ef54c785ba8821d9bf9527b813155b61
But i have the problem with all version of rutorrent.
The bug is caused by plugins "rpc" "httprpc" & "trafic".
When i remove these plugin's, i do not have this error. But seedbox can't
work without RPC, so my brain burning;

Any idea ?

2016-03-29 9:23 GMT+02:00 Novik <notifications@github.com>:

**Comment by gputier** [comment]
Hey

https://gyazo.com/65d7565ca601ebe2bd50e02dbc1d6e66

2016-03-29 10:38 GMT+02:00 Guillaume Putier <putier.guillaume@gmail.com>:

**Comment by Novik** [comment]
1) You need only one plugin from two - httprpc or rpc.
2) You have an incorrect (or modified) installation of ruTorrent.

**Comment by gputier** [comment]
When i remove rpc, the problem is the same.
I do not have a modified installation of rutorrent...

2016-03-29 10:49 GMT+02:00 Novik <notifications@github.com>:

**Comment by gputier** [comment]
With a fresh install of rutorrent, same problem.
