### ISSUE TITLE
Geoip plugin not work

### ISSUE THREAD

**Issue by giveup** [Novik/ruTorrent#1239]
env info:
lighttpd
php5 with json
latest rutorrent with geoip plugin
cannot see the country flag
![qq20160408-0 2x](https://cloud.githubusercontent.com/assets/2897585/14359011/211be3ba-fd22-11e5-8f47-5b2af34b2cfc.png)

**Comment by rtorrentuser** [comment]
Check if geoip plugin is enabled and loaded.
![untitled](https://cloud.githubusercontent.com/assets/1167563/14360076/411d9e80-fcfd-11e5-96cc-582f588d5c2b.jpg)

**Comment by Micdu70** [comment]
More infos:

ruTorrent GeoIP plugin requires PHP geoip extension to be installed and enabled in your php.ini configuration (http://puu.sh/o9FYQ/39d29f7d73.png) => https://github.com/Novik/ruTorrent/wiki/PluginGeoIP

Example for Debian / Ubuntu =>

Download the latest geoip database:
$ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz

Extract it:
$ gunzip GeoIP.dat.gz

Create the GeoIP folder:
$ sudo mkdir -v /usr/share/GeoIP

Move the database file in the GeoIP folder:
$ sudo mv -v GeoIP.dat /usr/share/GeoIP/GeoIP.dat

And install the php5-geoip extension:
$ sudo apt-get install php5-geoip

Then the webserver need to be restarted (or if you use PHP-FPM, restart PHP-FPM).

**Comment by giveup** [comment]
Well, I don't know that geoip need php5-geoip extension,It's my fault.
Thank you！@rtorrentuser @Micdu70
