### ISSUE TITLE
date(): It is not safe to rely on the system's timezone settings.

### ISSUE THREAD

**Issue by GoodOmens83** [Novik/ruTorrent#1241]
Working on getting ruTorrent to work with lighttpd and noticed a lot of these warnings in my log:

`2016-04-09 23:26:05: (mod_fastcgi.c.2520) FastCGI-stderr: PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /volume1/@appstore/lighttpd/www/rutorrent/php/util.php on line 566`

Still works perfectly despite the warning - but should ruTorrent do something like `date_default_timezone_set('America/Chicago');` where the user can select their time zone?  Silly that php requires setting this.....

**Comment by Novik** [comment]
This means - you should set timezone in the php.ini. And haven't relation to ruTorrent itself.
