### ISSUE TITLE
Ratio feature request.

### ISSUE THREAD

**Issue by Wob76** [Novik/ruTorrent#1245]
Would it be possible to add an extra action to the ratio groups? 

I am trying to look for a way to work around the fact that ratio's don't have a minimum time setting. If you could have the Action apply a new Ratio Group then this could solve the problem.

For example,

Rule 1 - Time,h = 48, Action: Set Ratio Group 2
Rule 2 - Whatever % and Time,h you normally use, Action: Remove Data (All)

This way the torrent would see for at least 48 Hours, and longer if after rule 2 is applied these rules are not yet met.

I think it should be possible, as there is the stop and clear group action, I did have a look at the code, but I'm not a programmer so it was beyond me.

Thanks.

**Comment by PhasecoreX** [comment]
I still think this would be a very nice feature to have. Another solution would be to add another column to the settings that has a dropdown containing `OR` and `AND`, which would indicate whether you want the time AND seed% to be true, or you want either of them to be true (which is default right now)
