### ISSUE TITLE
Use unar instead unrar in unpack

### ISSUE THREAD

**Issue by oszi** [Novik/ruTorrent#1248]
Because of the licensing issue with unrar it would be nice to use [unar](https://unarchiver.c3.cx/commandline) instead.
It could also handle all [supported formats](https://unarchiver.c3.cx/formats).

**Comment by xombiemp** [comment]
What is the licensing issue?

**Comment by oszi** [comment]
"It has use-restrictions that make it GPL-Incompatible and non-free. On top of that, the license requires that you agree to these use restrictions, or you must remove the software (source and binary) from your hard disks."

It affects me because it cannot be shipped in CentOS or Fedora. People using these distributions have to bundle it themselves or use a third-party repo just for unrar. On second thought, completely replacing unrar may not be good for everyone but falling back to unar would be much appreciated.

**Comment by ArtyumX** [comment]
Agreed.
