### ISSUE TITLE
History plugin problem again and again

### ISSUE THREAD

**Issue by senki** [Novik/ruTorrent#1251]
After updated to 3.7 error appear in log:

```
Bad response from server: (0 [error,gethistory])
```

Based on issue  #1113, I deleted the `history_data.dat` file, but after a couple of hour history is not working anymore and this error reappear.

**Comment by Windkracht8** [comment]
Can you share your history_data.dat? The answer might be in there.

**Comment by senki** [comment]
I totally forget this. It is working for months. I'm not sure what changed my best guess is where a high load on the server. 

Sorry for not close the issue.
