### ISSUE TITLE
Remove and Delete Data does not delete data

### ISSUE THREAD

**Issue by ormanya** [Novik/ruTorrent#1254]
When I choose Remove and Delete Data from the context menu in rutorrent, the data is not deleted.
The following error is reported in rtorrent:
Event 'event.download.erased' failed: Bad return code.

I have reviewed similar issues and have not been able to fix the problem.
I am currently running rutorrent 3.7 and rtorrent 0.9.6

**Comment by priyavadan** [comment]
having the same problem

**Comment by Novik** [comment]
Try to use github version of ruTorrent. And don't forget to restart rtorrent after upgrade.
