### ISSUE TITLE
Feature: set specific interface binding for web actions

### ISSUE THREAD

**Issue by xsmile** [Novik/ruTorrent#1256]
For actions like checking ports the interface should be configurable. In theory the interface could be read from the rTorrent configuration "bind = [...]".

**Comment by Novik** [comment]
It already configurable. See $httpIP variable in the config.php

> In theory the interface could be read from the rTorrent configuration

In theory - yes. But in practice we may have situation, when rtorrent is down and we can't obtain corresponding value.
