### ISSUE TITLE
RSS downloads don't behave exactly as manual downloads

### ISSUE THREAD

**Issue by afeblot** [Novik/ruTorrent#1260]
ruTorrent 3.6 - rTorrent:0.9.2/0.13.2
Downloads triggered from the rss plugin seem to not be handled as manual downloads:

- The are not logged in the history tab (added, completed events)
- When displayed in the global torrent list, some info are missing (time since completion, "added" time) although I'm not sure this is just related to RSS, as some other downloads also miss those informations.

**Comment by Novik** [comment]
Sorry, but ancient versions of ruTorrent is interested for me. Try to use git version.
