### ISSUE TITLE
Retrackers plugin not removing all specified trackers

### ISSUE THREAD

**Issue by jappish84** [Novik/ruTorrent#1262]
Ok, so I wrote about this problem before, here: http://forums.rutorrent.org/index.php?topic=6701.0

but since I was on an old version I figured that was the problem. I just now installed a fresh new, updated system with latest rtorrent/rutorrent and retrackers plugin, but I'm still getting exactly the same problem as described in the forum post above.

Just one of the two trackers I add is being deleted, pasted from post:

 I'll try to illustrate the behaviour:

if I insert in this order: 

http**s**://TrackerA
http://TrackerB

then only **Tracker B** will be **removed**
if I reverse the order: 

http://TrackerB
http**s**://TrackerA

then only **Tracker B** will be **removed** again

If I input just http**s**://TrackerA in the "remove announces"

then  https://TrackerA will be removed

If I input just http://TrackerB in the "remove announces"

then http://TrackerB will be removed

**Comment by Novik** [comment]
I think, reason is a simple. Your torrent has only two trackers. And you tried to remove both. This can't be done, because torrent should have a correct announce.

**Comment by jappish84** [comment]
Thanks for the reply! So I guess it's really odd that it has been working for years, and suddenly just stopped, without me updating anything... 

Thanks again for sharing the reason on why this happens.

Any idea why rtorrent fairly often crashes after the update on the trackers has been made, and during hash checking?

**Comment by Novik** [comment]
> has been working for years, and suddenly just stopped, without me updating anything

It worked for years with a same torrents? Really? ;)

> Maybe because I'm running it on rpi?

I think, reason is insufficient of memory + aggressive configuration of rtorrent.

**Comment by jappish84** [comment]
sorry for the late reply @Novik . Yeah, it has been working for years with the same torrents. Weird glitch I guess?

Is it possible to add an option to retracker-plugin to just disable the trackers listed, instead of deleting them. Shouldn't this eliminate the need for the rebuilding of the torrent, and also not require a hash-check of the files?

Thanks again for your awesome work with my favorite torrent client!

**Comment by jappish84** [comment]
Ah that's to bad. Yeah, I've tried to figure out how to do that but I'm just not good enough with programming. 

Thanks =)

**Comment by jappish84** [comment]
@Novik sorry I didn't post this earlier when I first wrote about it a few post above. This is the output of rtorrent retrackers fails, and crashes rtorrent. Not sure if this helps you in any way

`Caught internal_error: DownloadWrapper::receive_hash_done(...) Was not expecting non-NULL hash.
/usr/local/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKSs+0x198) [0xb6d18628]
rtorrent(_ZN7torrent14internal_errorC1EPKc+0x34) [0x5321c]
/usr/local/lib/libtorrent.so.19(+0x9bf3c) [0xb6d8ef3c]
/usr/local/lib/libtorrent.so.19(+0x9ccd4) [0xb6d8fcd4]
/usr/local/lib/libtorrent.so.19(+0x7520c) [0xb6d6820c]
/usr/local/lib/libtorrent.so.19(_ZN7torrent15signal_bitfield4workEv+0x88) [0xb6d60af0]
/usr/local/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x1f0) [0xb6d61100]
rtorrent() [0x20548]
/lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x114) [0xb69a5294]
`

Thanks for all your hard work, keep it up!
