### ISSUE TITLE
RSS plugin does not respect setgid 

### ISSUE THREAD

**Issue by lscat** [Novik/ruTorrent#1265]
This is my setup:

`chgrp "rutorrent_group" ./rutorrent/share/{settings,torrents,users}`
`chmod 2070 ./rutorrent/share/{settings,torrents,users}`
`$profileMask = 0770 @ ./rutorrent/conf/config.php`

RSS feeds will update and respect setgid "rutorrent_group" at fresh install until the browser is not closed.

When I close the browser, re-open rutorrent site, RSS info file (.rutorrent/share/settings/rss/cache/info) will change its permissions to rtorrent_user:rtorrent_user, and the feeds disappear.

Can this be solved so that ".rutorrent/share/settings/rss/cache/info" respects setgid?

**Comment by Novik** [comment]
Can be. Move rtorrent_user to the rutorrent_group.
