### ISSUE TITLE
setting dialog shows incorrect when use rpc plugin

### ISSUE THREAD

**Issue by colinhd8** [Novik/ruTorrent#1267]
when
1.enable the rpc plugin 
2.disable httprpc plugin
3.not set network.bind_address in rtorrent
then the setting dialog shows incorrect because the return value of network.bind_address ignored by the source:
rtorrent.js 799~804
	for(;i<255; i++)
	{
		var s = this.getValue(values,i).replace(/(^\s+)|(\s+$)/g, "");
		if(s.length)
			break;
	}
and it results like this:
correct:
q1   a1
q2   a2
q3   a3
......

incorrect:
q1   a2
q2   a3
q3   a4
.......

**Comment by Novik** [comment]
> 3.not set network.bind_address in rtorrent

And in this case we will see '0.0.0.0' in the corresponding place of answer.
I can't to reproduce this. What version of rtorrent you are use?

**Comment by colinhd8** [comment]
Now i can't reproduce this too. And i always use the latest source from the rtorrent github when i test it. I think this can be close now.
