### ISSUE TITLE
[Feature request] Pause for ...

### ISSUE THREAD

**Issue by Kyle2142** [Novik/ruTorrent#1268]
A feature common to many torrent clients, the ability to pause a torrent for a specified amount of minutes
(per torrent basis)

**Comment by bjay1404** [comment]
This would be a great feature!

**Comment by Novik** [comment]
May be... But I should remind you that ruTorrent - is not a torrent client...

**Comment by Kyle2142** [comment]
It's a scripting front end, is it not?

**Comment by Novik** [comment]
Yes, it is. And some functionality can't be done by easy way on this level.

**Comment by Kyle2142** [comment]
I'm just saying, you can pause all torrents based on schedule, so setting a timer for one shouldn't be difficult, and it would put rutottent even closer to being a real client
