### ISSUE TITLE
ScreenShoot plugin not working

### ISSUE THREAD

**Issue by duramato** [Novik/ruTorrent#1271]
When using the screenshoot plugin from the UI , it doesn't generate the SS, and just shows http://imgur.com/GYXUlCv.
Using ffmpeg from cmd, works and does generate a valid SS

**Comment by abixalmon** [comment]
Do you have ffmpeg installed?
try ```which ffmpeg```

**Comment by jaivitesh** [comment]
http://prntscr.com/baw055 
plz help

**Comment by Micdu70** [comment]
@jaivitesh You should create a new issue for your problem (different than this one)... but you only need to start/restart rtorrent for your case...

**Comment by jaivitesh** [comment]
How can i restart my rtorrent

**Comment by duramato** [comment]
I've solved my issue,  yes I had ffmpeg installed and working but I was using the 3.7 plug-in on 3.6
