### ISSUE TITLE
rutorrent doest finish loading

### ISSUE THREAD

**Issue by akasoldats** [Novik/ruTorrent#1272]
hi - I just grabbed 3.6 rev2404 and installed it but when I attempt to view the site rutorrent hangs at the loading phase. 

rtorrent is running, but in /tmp/errors I get the attached error. I have installed rutorrent before but this particular error is quite new to me. 

[errors.txt](https://github.com/Novik/ruTorrent/files/275932/errors.txt)

**Comment by Micdu70** [comment]
Hello, the /tmp/errors file is not what you should read to found why rutorrent interface not load... Look in the error log file of your webserver.

**Comment by akasoldats** [comment]
That has been equally unhelpful thus far. :/  See below, I have changed the domain / IPs for privacy reasons. 

I believe the files in question should be auto created on first launch, right?

That has been equally unhelpful thus far :/
[Sat May 21 17:19:30.315878 2016] [ssl:warn] [pid 16769] AH01909:  https://10.10.10.11/rutorrent/:443:0 server certificate does NOT include an ID which matches the server name
[Sat May 21 17:19:30.319263 2016] [mpm_prefork:notice] [pid 16769] AH00163: Apache/2.4.18 (Ubuntu) mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_scgi/1.13 OpenSSL/1.0.2g-fips configured -- resuming normal operations
[Sat May 21 17:19:30.319273 2016] [core:notice] [pid 16769] AH00094: Command line: '/usr/sbin/apache2'
[Sat May 21 17:28:06.732732 2016] [:error] [pid 16776] [client 10.10.10.10:50875] PHP Warning:  fopen(/var/www/rutorrent/share/users/akasoldats/settings/uisettings.json): failed to open stream: No such file or directory in /var/www/rutorrent/php/getsettings.php on line 7, referer:  https://10.10.10.11/rutorrent/
[Sat May 21 17:33:17.134144 2016] [:error] [pid 16774] [client 10.10.10.10:50945] PHP Warning:  fopen(/var/www/rutorrent/share/users/akasoldats/settings/uisettings.json): failed to open stream: No such file or directory in /var/www/rutorrent/php/getsettings.php on line 7, referer:  https://10.10.10.11/rutorrent/
[Sat May 21 17:34:27.503237 2016] [:error] [pid 16776] [client 10.10.10.10:51007] PHP Warning:  fopen(/var/www/rutorrent/share/users/akasoldats/settings/uisettings.json): failed to open stream: No such file or directory in /var/www/rutorrent/php/getsettings.php on line 7, referer: https://10.10.10.11/rutorrent/

**Comment by Micdu70** [comment]
Yes, but it should not be a problem... Do you have installed the plugins? ( You should have these directories in ' /var/www/rutorrent/plugins ' => https://github.com/Novik/ruTorrent/tree/master/plugins )

**Comment by Novik** [comment]
First of all, don't use ancient version of ruTorrent.

**Comment by akasoldats** [comment]
Sorry guys...  I grabbed development and it resolved my problem.
