### ISSUE TITLE
extratio and httprpc

### ISSUE THREAD

**Issue by Wob76** [Novik/ruTorrent#1276]
Hi,

I am having a problem with extratio and httprpc.

I have 3 rules created, in this order (but I have moved them around to test)
1) is based on the torrent label
2) is if one of the trackers is public
3) is if all trackers are public

I have a 3rd party application talking to rutorrent via httprpc. It sets a label as part of its interaction.

The problem I have is that the rule based on label is not being applied if the torrent comes in via httprpc. I can manually remove and readd the label and that rule will apply.

I found a thread (http://forums.rutorrent.org/index.php?topic=6716.0) that suggested some edits to action.php of httprpc, which had no effect, my thoughts are that this is still notifying rtorrent, and not rutorrent.

My guess is that the Label is being added after the initial run of extratio, so rule 2 or 3 are applied, the label is then added but extratio is not aware of the change.

Since both extratio and httprpc are rutorrent plugins I was hoping they could be made to play a little nicer together?

Thanks,
Wob

**Comment by Novik** [comment]
> The problem I have is that the rule based on label is not being applied if the torrent comes in via httprpc.

Reason is a simple. Changing of labels with a external source is not supported.

> my thoughts are that this is still notifying rtorrent, and not rutorrent.

This is an incorrect suggestion. In theory, this fix should help in your case.

> Since both extratio and httprpc are rutorrent plugins I was hoping they could be made to play a little nicer together?

They played nice together (AFAIK). For case, when labels is changed with ruTorrent.
