### ISSUE TITLE
labels being removed automatically

### ISSUE THREAD

**Issue by bobbintb** [Novik/ruTorrent#1278]
I am having an issue with labels being removed automatically. Sonarr will send a magnet link to rtorrent with the 'sonarr' label. I have not been able to identity the circumstances for which this happens but occasionally the label with automatically be removed and the torrent stopped, sometimes before the .torrent file is downloaded. I suspect it might have something to do with the autolabel feature in rutorrent but am not sure. The behavior seems very random and it's hard to keep the sequence of events straight.

**Comment by Novik** [comment]
> I suspect it might have something to do with the autolabel feature in rutorrent but am not sure. 

Disable corresponding plugin and check result.

**Comment by bobbintb** [comment]
It was never turned on.

**Comment by Novik** [comment]
If it never turned on - then ruTorrent has not relation to this issue, sorry.
