### ISSUE TITLE
Difference between getLogin and getUser functions in php/util.php

### ISSUE THREAD

**Issue by ArtyumX** [Novik/ruTorrent#1280]
Hi,
I'm developing a ruTorrent plugin and I need to fetch the username of the current logged in user.
Normally I would use `$_SERVER['PHP_AUTH_USER']` but I don't want to reinvent the wheel, I mean if Novik already created a function to fetch the username, I'd like to use this function.
When I echo getLogin() or getUser() both return the username, but I would like to know the difference between both functions ? Which one should I use ?

Thanks.

**Comment by Novik** [comment]
As you may see in code, getUser checks configuration variable $forbidUserSettings, getLogin - not.
I.e. in single-user mode getUser will returns empty string. getLogin always will returns username.

**Comment by ArtyumX** [comment]
Oh, that was obvious, I don't know why I couldn't figure it out.
Thanks :)
