### ISSUE TITLE
Can't create torrent because tackers box is disabled 

### ISSUE THREAD

**Issue by psycholyzern** [Novik/ruTorrent#1286]
I can't write any tracker into the the box because it is disabled.
It happened suddenly. Rtorrent crashed, so I restarted it back. Then this happen.

![](http://keepimg.com/images/PicsArt_07-01-02.55.45.jpg)

**Comment by Novik** [comment]
First of all, do not use ascient versions of ruTorrent and plugins.

**Comment by psycholyzern** [comment]
I am using rutorrent 3.7 cloned git with latest commit.
Btw I figured out what caused that. It turns out that I have reached maximum seeded torrent which is 50 (default).
I increased the amount and the tracker box is editable again. 
Thanks
