### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by VJean-dev** [Novik/ruTorrent#1289]
баг в определении прокси:

файлы: /js/content.js и /php/methods-0.9.4.php
`"set_http_proxy"	:	{ name: "network.http.proxy_address.set", prm: 1 },`
`"set_proxy_address"	:	{ name: "network.http.proxy_address.set", prm: 1 },`

"set_proxy_address" это настройка "network.proxy_address.set", отвечающая за весь траффик проходящий через прокси. "http_proxy" - только для http трафика.
правильный код: /js/content.js https://github.com/Novik/ruTorrent/pull/1290
`"get_proxy_address"	:	{ name: "network.proxy_address", prm: 0 },`
`"set_proxy_address"	:	{ name: "network.proxy_address.set", prm: 1 },`
/php/methods-0.9.4.php https://github.com/Novik/ruTorrent/pull/1291
`"get_proxy_address"	=>	array( "name"=>"network.proxy_address", "prm"=>0 ),`
`"http_proxy"		=>	array( "name"=>"network.http.proxy_address", "prm"=>0 ),`
`"set_proxy_address"	=>	array( "name"=>"network.proxy_address.set", "prm"=>1 ),`

еще вопрос: Snappy надо настраивать отдельно (/php/Snappy.class.inc), чтобы работал с прокси или есть скрытый конфиг в /conf/config.php ? насколько понял, все запросы и скачки из клиента проходят через него.

**Comment by Novik** [comment]
Отдельно.
