### ISSUE TITLE
Send heartbeat to rtorrent so that the session keep active

### ISSUE THREAD

**Issue by enoch85** [Novik/ruTorrent#1295]
I have big issues with keeping ruTorrent running web ui running. It seems like I have to stay logged in to keep the session active. If I close my SSH terminal, the connection to ruTorrent is closed.

I've tried screen + cron + script but with no luck, when I reboot or close my SSH window ruTorrent dies.

Idk, but would it be possible to send a heartbeat to rTorrent with php via the HTTPRPC Plugin?

**Comment by Novik** [comment]
ruTorrent, httprpc and heartbeat hasn't relation to your problem.
You should use screen for starting rtorrent as service. Try to use google for checking - how.

**Comment by enoch85** [comment]
JFTR it turns out I had to login from the hypervisor (wun it on a VM), rather than from a SSH terminal as the screen session terminates when I close the window. Just in case any one else has the same issue.
