### ISSUE TITLE
Rows under Columns not aligned properly with Header

### ISSUE THREAD

**Issue by AliAlGallaf** [Novik/ruTorrent#1298]
It looks like this can be easily fixed using css but I'm not sure how. Column text is not positioned properly as seen in the screenshot below.

![ruTorrent Screenshot](http://i.imgur.com/6v4oipE.png)

**Comment by Novik** [comment]
1) Do not use ancient versions.
2) If after upgrade this problem will present, then open new ticket and write something about your browser version.
