### ISSUE TITLE
[Feature Request] Show Peers as plain response or json

### ISSUE THREAD

**Issue by scriptzteam** [Novik/ruTorrent#1299]
I will load http://mysite/plugins/httprpc/action_get.php?mode=prs&hash=SOMEHASH

and response will be plain response or json of peers is that possible? :)

Want to cache peers

**Comment by Novik** [comment]
I think, yes. Sorry, this is a strange (IMHO) request, it is useless for all others and I haven't time for this.
But you can to write your own plugin.

**Comment by scriptzteam** [comment]
Already did it thx ;)
