### ISSUE TITLE
PHP Notice:  Undefined offset in file /plugins/trafic/stat.php

### ISSUE THREAD

**Issue by SckyzO** [Novik/ruTorrent#1300]
Hello, no big issue for me just little error in my log : 

The array $stat is not set maybe, i'm not dev, just admin sys :)

[ ... ]

[Tue Jul 12 23:26:05.677170 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:26:05.677386 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:26:05.677548 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:26:05.677626 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:26:05.677772 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:26:05.677843 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63903] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838003 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838291 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838402 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838448 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838541 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:41:05.838585 2016] [:error] [pid 15797] [client xxx.xxx.xxx.xxx:63938] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975250 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975470 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975583 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975654 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975800 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Tue Jul 12 23:56:05.975875 2016] [:error] [pid 15798] [client xxx.xxx.xxx.xxx:63958] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110133 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110361 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110477 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110525 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110624 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:11:06.110670 2016] [:error] [pid 15804] [client xxx.xxx.xxx.xxx:64137] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235123 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235340 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 19 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235447 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235494 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 30 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235586 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 169, referer: https://rutorrent.mywebsite.fr/
[Wed Jul 13 00:26:06.235631 2016] [:error] [pid 15794] [client xxx.xxx.xxx.xxx:64204] PHP Notice:  Undefined offset: 41 in /var/www/html/rutorrent.mywebsite.fr/plugins/trafic/stat.php on line 171, referer: https://rutorrent.mywebsite.fr/

**Comment by Novik** [comment]
This means - one (or several) of your .csv files with a traffic statistic is invalid.
