### ISSUE TITLE
Signup for rutorrent support forum is broken

### ISSUE THREAD

**Issue by troyheron** [Novik/ruTorrent#1304]
No matter what email address I use to sign up, the activation email never arrives and it's definitely not in spam. This is the only place I figured might get the admin's attention.

**Comment by Novik** [comment]
Sorry, but I haven't a control under the server with forum.

**Comment by troyheron** [comment]
Maybe you can answer my question here?

I'm having troubles with the RSS plugin. Once I add a feed and enable it by adding a filter, not long after the RSS context menu becomes inaccessible. All I get is the usual torrent one so I'm unable to add/remove/manipulate RSS feeds at all. This seems to happen once all the items listed in the RSS list are started. Only way I can get it back again is by deleting the files in <rutorrent-path>/share/settings/rss/cache/. Of course this is not very helpful.

**Comment by troyheron** [comment]
Nevermind. Can you delete this issue?
