### ISSUE TITLE
Default to a specific download strategy

### ISSUE THREAD

**Issue by gbdoin** [Novik/ruTorrent#1305]
Hi,

I would love to be able to default to the "leading chunk first" download strategy for video files, or even all files if the former is too complicated. I couldn't find any plugin or info on how to enable that. Is there any development to integrate this option? If not, is there any documentation or help that you guys could provide? If my understanding is correct, this would need to be sent as an RPC command to rtorrent, but I am not familiar with that at all.

Thanks :)

**Comment by gabo77** [comment]
Actually this is very easy. One only has to set something like this in rtorrent.rc:

file.prioritize_toc.set=1
file.prioritize_toc.first.set = {*.avi,*.mp4,*.mkv,*}

It would be nice if this could be integrated to the webui! What do you think?
