### ISSUE TITLE
Some Error in ruTorrent v3.7 (chrome developer tools)

### ISSUE THREAD

**Issue by Gosokan** [Novik/ruTorrent#1306]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.  jquery.js:4

Refused to execute script from 'https://seedbox-server/plugins/filemanager/settings.js.php' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Browser: Google Chrome 51.0.2704.103 m
Server: Ubuntu 14.04 64-bit, nginx/1.11.2, php-fpm 5.5.9

Seems issue appear only when served from https (with http2 protocol) because most of modern browser support http2

**Comment by Novik** [comment]
This is a third-party plugin. Try to ask from his author.
