### ISSUE TITLE
500 Error, Get Plugins

### ISSUE THREAD

**Issue by bjay1404** [Novik/ruTorrent#1307]
Hi,

I've decided to go from 3.7 to the latest commit. Everything is working fine with my 3.7 version. I'm on Ubuntu 16.04. I cloned the repo and moved the share file and set the permissions but I'm getting this error. 

Bad response from server: (500 [error,getplugins]) Internal Server Error

So i started to look in my apache logs and I found this- looks like I'm using PHP7. Some help would be great! 

[Fri Aug 05 11:15:54.731121 2016] [:error] [pid 31895] [client 10.10.10.xyz:63303] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/rutorrent/plugins/_task/task.php:142\nStack trace:\n#0 /var/www/html/rutorrent/plugins/_task/task.php(155): rTask::tail('/var/www/html/r...')\n#1 /var/www/html/rutorrent/plugins/_task/task.php(210): rTask::processLog('/var/www/html/r...', 'log', Array, 0, 0)\n#2 /var/www/html/rutorrent/plugins/_task/task.php(278): rTask::check('14504911685674b...')\n#3 /var/www/html/rutorrent/plugins/_task/task.php(297): rTaskManager::obtain()\n#4 /var/www/html/rutorrent/plugins/_task/init.php(5): rTaskManager::cleanup()\n#5 /var/www/html/rutorrent/php/getplugins.php(495): require_once('/var/www/html/r...')\n#6 {main}\n  thrown in /var/www/html/rutorrent/plugins/_task/task.php on line 142, referer: http://10.10.10.56/rutorrent/

**Comment by Novik** [comment]
Try to install mb_string extension.
http://php.net/manual/en/mbstring.installation.php

**Comment by bjay1404** [comment]
That worked, thank you!!!

**Comment by fieldju** [comment]
Thanks, had the same issue. I am pretty sure this issue can get closed?

**Comment by kdantas** [comment]
Hi, I installed in a Ovh dedicated server rTorrent/ruTorrent my seedbox. Everything were ok, but now I can´t start my WebGUI ruTorrent. It show the follow error:

[09.05.2017 07:26:28] WebUI started.
[09.05.2017 07:26:29] Bad response from server: (500 [error,getplugins]) Internal Server Error

How to solve this problem?

I already reset the server and the rtorrent seedbox but is keeping the same error.

**Comment by hergonoway** [comment]
Hello, same here :(( @kdantas : did you fixed the problem ?

**Comment by s-c-o-o-t** [comment]
did you guys delete the .rlock from .sessions dir ?
