### ISSUE TITLE
Is possible implement this option "Check hash after download" individually?

### ISSUE THREAD

**Issue by hlcb91** [Novik/ruTorrent#1311]
Check the hash after downloading for very large torrents, it takes a lot and because of that I usually disable this, but smaller torrents I like to check to make sure the download was completed in fact.

Check the hash after the download is really necessary? What is the probability that a complete download is missing something? I have a fear when I add torrent sites with very high speeds and to use a normal HD, I get this fear that some data is lost.

I can Unchecking this box safely or is recommended to leave marked?

**Comment by Novik** [comment]
Sorry, but this option has relation to the bittorent *client*. I.e. rtorrent. 
ruTorrent - is a WebUI.
