### ISSUE TITLE
Erase data plugin not working on NFS mount

### ISSUE THREAD

**Issue by liquidox** [Novik/ruTorrent#1312]
After hours of trying of pulling my head out, trying to figure out why Erase data is not deleting Torrent files, I decided to try change the download folder to a local drive, instead of a NFS mount. This worked.

Note that the log will say this:
[21.08.16 23:26:19] erasedata: Successfully delete file /mnt/storage/torrents/completed/ubuntu-16.04.1-server-amd64.iso

Even though the file remains. So somehow PHP unlink is returning 0 while the files remain? Very strange.

File ownership and permissions are correct. And note that it works perfectly fine on a local drive, just not on the NFS mount.

**Comment by liquidox** [comment]
Ok new day of testing, seems it's not an issue with NFS, but possibly the "copy after completion" script messing with the delete system, to be continued.

**Comment by EsEnZeT** [comment]
This issue is still valid

**Comment by EsEnZeT** [comment]
#2066

try
