### ISSUE TITLE
When I add a torrent with content(multiple files) over 160GB via rutorrent, no task is started.

### ISSUE THREAD

**Issue by stevenjtx** [Novik/ruTorrent#1313]
However, the torrent could be loaded successfully via rtorrent 'watch' dir indeed. May I know if there is any restriction, like torrent file size limitation, when loading torrent via rutorrent ? thanks.

**Comment by stevenjtx** [comment]
anyone can help ? pls

**Comment by Novik** [comment]
Check max file size for uploaded files in the php settings (max_upload_size etc).
