### ISSUE TITLE
Do not show a status of Downloading if all files with a priority are 100%

### ISSUE THREAD

**Issue by marathonser** [Novik/ruTorrent#1315]
If you have multiple files, and set one file priority to "Don't Download" and the other files are all 100%, then the status remains as "Downloading". It would be nice to show those as a status of "Completed".

**Comment by Novik** [comment]
Sorry, but I disagree with you.

**Comment by Pxx64** [comment]
Hi Novik, found this issue via search, while current behavior could be fine as default, what about adding an option for showing such torrents as Seeding/Queued/Completed/whatever?
It is confusing to see such torrents as Downloading, when there are no download is/will be happening. This is especially bad when you are sorting torrents by status, and then you need manually "filter out" those which are actually completed from those which are not

**Comment by Pxx64** [comment]
Hi Novik, found this issue via search, while current behavior could be fine as default, what about adding an option for showing such torrents as Seeding/Queued/Completed/whatever?
It is confusing to see such torrents as Downloading, when there are no download is/will be happening. This is especially bad when you are sorting torrents by status, and then you need manually "filter out" those which are actually completed from those which are not

**Comment by Pxx64** [comment]
Hi Novik, found this issue via search, while current behavior could be fine as default, what about adding an option for showing such torrents as Seeding/Queued/Completed/whatever?
It is confusing to see such torrents as Downloading, when there are no download is/will be happening. This is especially bad when you are sorting torrents by status, and then you need manually "filter out" those which are actually completed from those which are not
