### ISSUE TITLE
Bad response from server: (200 [parsererror,getplugins])

### ISSUE THREAD

**Issue by Debisn8** [Novik/ruTorrent#1320]
1) Rutorrent forums doesnt send activation e-mail, I have there the same username.
2) I installed ruTorrent with an auto install script from https://github.com/Kerwood/Rtorrent-Auto-Install
-I have wordpress etc. installed on my server all is working fine. Im accessing rutorrent via rutorrent.mywebsite.com
-Im getting a huge block of errors but the very first one is
Bad response from server: (200 [parsererror,getplugins]) <?php require_once( "util.php" ); require_once( "settings.php" ); function pluginsSort($a, $b) { $lvl1 = (float) $a["info"]["plugin.runlevel"]; $lvl2 = (float) $b["info"]["plugin.runlevel"]; if($lvl1>$lvl2) return(1); if($lvl1<$lvl2)	return(-1); return( strcmp($a["name"],$b["name"]) ); } function getFlag($permissions,$pname,$fname) ...
-Continues like this, I have found on internet similar or the same issues, reinstalling php5 did not help.
-My plugins directory is empty, share/settings, share/users directories are also empty.

Im using Debian 8 with apache. Would be glad for any tips!

**Comment by Novik** [comment]
Try to configure php on your web-server by normal way. Your web-server returns script's body instead evaluate it.

**Comment by Debisn8** [comment]
All my websites/forums are working and they use php, so I dont really know what the problem is with php, I tried reinstalling it but it said it is up to date, nothing to install. How can I troubleshoot the problem? What might be causing it? What line/variable shall I examine?

**Comment by Kerwood** [comment]
Fixed the issue.. @Debisn8 had webmin installed and that messes with the default php configuration..
Added `AddType application/x-httpd-php .php` to the vhost file and it works now.

```
...
<Directory "/var/www/html/rutorrent">
        AddType application/x-httpd-php .php
        AuthName "Tits or GTFO"
        AuthType Basic
        Require valid-user
        AuthUserFile /var/www/html/rutorrent/.htpasswd
</Directory>
...
```
