### ISSUE TITLE
JS Error: Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Verbosa** [Novik/ruTorrent#1321]
Hello, I am getting a JS Error: Uncaught TypeError: Cannot read property 'match' of undefined error whenever I load my rtorrent. I've been able to bypass the error by disabling my tracklabels plugin, but that still leaves me without the list of trackers. Is there any way you can help me fix this issue? I'm using version 0.96 of RuTorrent and v3.7 of Rtorrent. Thanks!

**Comment by Novik** [comment]
First of all, try to use development versions of ruTorrent core and plugins.

**Comment by Verbosa** [comment]
Hello again, Novik. I went back to confer with the seedbox company support people I've been dealing with regarding this matter and they updated the "tracklabel" plugin to the newest version, but the error is still occurring. Any other suggestions? Thank you.

**Comment by Novik** [comment]
Yet once. Try to use development versions of **ruTorrent core** and **all plugins**.
