### ISSUE TITLE
Editing RSS feed causex RSS Manager to forget feed source limits

### ISSUE THREAD

**Issue by anoma** [Novik/ruTorrent#1326]
If you edit a feed to change the feed URL this causes  any rules in the RSS manager to forget the `RSS` feed associated with it.

Best served with example. 
You have two feeds:

```
http:server1/rss.php
http:server2/rss.php?search=bob
```

You set a RSS Manager rule to download all but only from feed `server2`.

If you now edit the `server2` feed in any way, say:

`http:server2/rss.php?search=bob+jane`

The RSS manager rule forgets that the dowload all rule is set for feed `server2` only.

Result, you now have RSS manager downloading everything from every feed.

Bad, thats an account killer.

**Comment by Novik** [comment]
Fixed, check.

**Comment by anoma** [comment]
Confirmed. RSS features appear to work as before and altering a feed no longer cause RSS manager to forget anything.

Appreciated.
