### ISSUE TITLE
Sorting Peers/Seeds Column

### ISSUE THREAD

**Issue by jota-mylogins** [Novik/ruTorrent#1329]
Hi first of all thanks to all developers/contributors working on rutorrent.
Second, sorry for my bad english.
Now the issue/request:

I have found that the sorting of peers / seeds column is incorrect.
I uploaded two screenshots, the first and second qBittorrent ruTorrent.
RuTorrent apparently does not sort the numbers in parentheses.

qBittorent screenshot:
http://i.imgur.com/v7KKeen.jpg
ruTorrent screenshot:
http://i.imgur.com/BdaB5PA.jpg

I find this useful when I need to delete a torrent (for free space reasons). I usually choose the torrents with more seeds.
I think the screenshots help, but I hope I've explained that clearly.
Thanks again, and sorry about my english.

**Comment by allixx** [comment]
Before opening pull request I'd like to discuss how exactly seeds/peers sorting should work.
Each peers/seeds cell contains a number of currently connected peers and a number of total peers in square brackets.
Judging by the screenshot provided above, qBittorrent sorts by currently connected peers first and by total peers second.
My own preference is to sort by total peers only.
What's your take on this?
