### ISSUE TITLE
ruTorrent not saving .rtorrent.rc changes

### ISSUE THREAD

**Issue by Fourdee** [Novik/ruTorrent#1331]
As per: https://github.com/Fourdee/DietPi/issues/543#issuecomment-251079498

Changing the port setting (and various other settings) in ruTorrent interface, does not save changes on service restart.

LLSP stack

```
FP_DIETPI_USERDATA_DIRECTORY='/mnt/dietpi_userdata
```

rTorrent Service with custom config location ```-n -o import=```:
```
cat << _EOF_ > /etc/systemd/system/rtorrent.service
[Unit]
Description=rTorrent
After=network.target

[Service]
User=root
Type=forking
KillMode=none
ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent -n -o import=$FP_DIETPI_USERDATA_DIRECTORY/.rtorrent.rc
ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent
WorkingDirectory=%h

[Install]
WantedBy=multi-user.target
_EOF_
```

Permissions on ```.rtorrent.rc```:
```
root@DietPi:~# ls -lha $FP_DIETPI_USERDATA_DIRECTORY
total 16K
drwxrwxr-x  3 root     root     4.0K Oct  3 11:53 .
drwxr-xr-x 12 root     root     4.0K Sep 29 14:01 ..
drwxrwxr-x  3 root     root     4.0K Oct  2 15:13 downloads
-rwxrwxr-x  1 www-data www-data 3.6K Oct  2 17:33 .rtorrent.rc
```

**Comment by Micdu70** [comment]
Hello,

The ruTorrent front-end has no feature to modify the `.rtorrent.rc` file (rtorrent config file): It only changes settings of the current rtorrent instance.

**Comment by Fourdee** [comment]
@Micdu70 

> It only changes settings of the current rtorrent instance.

Explains alot, thanks. 

Although, I cant be the 1st person this has happened to, maybe a notification in the settings explaining "Settings applied here will only affect the current instance of rTorrent. Restarting rTorrent will reset the settings."?

No plans to make saving to ```.rtorrent.rc``` a feature in the future?

Either way, ticket resolved and answered. I'll mark as closed.
