### ISSUE TITLE
JS error: [https://<IP>/rutorrent/ : 475] Uncaught TypeError: Cannot read property 'ajax' of undefined

### ISSUE THREAD

**Issue by Codgedodger** [Novik/ruTorrent#1333]
OS - Ubuntu 14.04 LTS

This error pops up every 2-3 seconds so it get annoying quickly. All of the functions and downloads work perfectly just keep getting this error. Restarted service, reinstalled ruTorrent issue still persists. 

JS error: [https://<IP>/rutorrent/ : 475] Uncaught TypeError: Cannot read property 'ajax' of undefined

**Comment by Codgedodger** [comment]
Please close this ticket. It was an issue with a plugin with my Chrome browser. Very odd. It's fixed now.

**Comment by radonthetyrant** [comment]
Can you elaborate which plugin it was?

**Comment by mariotacke** [comment]
I used uBlock Origin and after disabling and reloading it worked for me. 🤷‍♂ I also re-enabled it afterwards and it still works...

**Comment by tirrorex** [comment]
I have the same issue not related to ublock origin. Thought it came from my reverse proxy until i tried to run rutorrent on safari.
Will edit my comment once i found out what causes the bug for future users that might look for a solution
