### ISSUE TITLE
JS Error: Uncaught TypeError: Cannot read property 'started' of undefined

### ISSUE THREAD

**Issue by destpat** [Novik/ruTorrent#1335]
hey, I am getting a JS Error: Uncaught TypeError: Cannot read property 'started' of undefined error whenever I load my rtorrent. I'm using version 0.96 of RuTorrent and v3.7 of Rtorrent. 

Thank : )

**Comment by asavah** [comment]
Check this https://github.com/Novik/ruTorrent/issues/1333

Check if your browser has any weird extensions.
Using master here, no errors whatsoever.

**Comment by NamesJoeyWheeler** [comment]
I'm having this problem too.
I have tried multiple browsers and devices, but I still get this error.
How can I fix this?
