### ISSUE TITLE
DataDir plugin(save to) resets torrent stats

### ISSUE THREAD

**Issue by hannsen** [Novik/ruTorrent#1341]
Hey, so when I select some torrent in my rutorrent and move the files with  "Save To" (while having "move files" and "fast resume" ticked) the torrent gets treated as if it was newly added. All ratio, added and other stats get lost.

When I untick fast resume that does not occur. not so bad, but unnecessary long rechecking times are the result of that.

**Comment by Novik** [comment]
This is a normal behavior. Because for "fast resume" we remove torrent and readd it.
I don't know, how to avoid rehashing by another way.

**Comment by hannsen** [comment]
rtorrent does not support file moving? weird

every client i had until now could do it.

**Comment by koblack** [comment]
Duplicate of #1277
