### ISSUE TITLE
Add File button broken in Safari (Sierra)

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1347]
There appears to be an issue with the add file button when accessing rutorrent through Safari 10.0.1(12602.2.14.0.7) in macOS/Sierra

Click the Add Torrent... button > Click the browse button and select your .torrent file and now when you click the add file button nothing happens.

No errors appear in the log.

**Comment by sblacksg** [comment]
ruTorrent 3.7 with Safari 10.0, same problem.  Need to refresh the page to be able to add another torrent.

**Comment by RobbieL811** [comment]
Having the same issue.  Even tried updating to Safari Technology Preview.  Still same issue.  Refreshing the page also solves the issue.
