### ISSUE TITLE
php version and curl problems

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1353]
I'm using rtorrent and rutorrent on a archlinux PC

eraserdata and datadir plugin won't work with php 7

So I change to php 5.3, eraserdata works but datadir remains broken.

Another problem comes with php 5.3
```
rss: Some functionality will be unavailable. Webserver user can't access external program (curl).
```

**Comment by scoobynz** [comment]
At the terminal type `which curl`

paste the result into your config.php (/var/www/rutorrent/conf/config.php in the path to externals array.

Mine is; `"curl"  => '/usr/bin/curl',`
