### ISSUE TITLE
web workers support

### ISSUE THREAD

**Issue by nelu** [Novik/ruTorrent#1356]
any plan for web workers for the ajax calls? its 2016 & browsers are moving ff

**Comment by mariotacke** [comment]
What's the point? How would it improve the current situation?

**Comment by nelu** [comment]
well, will offload the main thread (where all code is being ran right now).
example:
instead of "blocking" the main thread (ui thread) with ajax requests,
instead the ajax call can be done from a separate thread and the request
response is being sent as a event to the main UI thread to update the view.
this was a simple example...
anyhow to another good example on how you can have performance benefits
from webworkers, is Ace Text Editor (js), which is a pretty advanced text
editor on web

mobile devices will benefit mostly (the ui will be more responsive)

**Comment by mariotacke** [comment]
Not sure if you understand how ajax works, but it is non-blocking. The requests are made in ajax fashion, see https://github.com/Novik/ruTorrent/blob/master/js/rtorrent.js#L1099. Also check out the [docs](http://api.jquery.com/jQuery.get/) on ajax. Webworkers would do little to speed this up but introduce lots of complexity,
