### ISSUE TITLE
Please add two New Features!

### ISSUE THREAD

**Issue by AnythingOldSchool** [Novik/ruTorrent#1359]
Hello, I use RuTorrent via seedbox. There are two features I highly suggest should be added, and would make our torrent experience easier. The first is to add a feature that would allow us to use direct hash# IDs. Reason why this is so important, is because trackers have become unbearable with links that forward to ads, and the relentless back-end pops. I almost feel violated at times the ads are so bad. Having said that, The ability to copy and past hash# tag ids instead of using magnet links would be HUGE help in my opinion.

The second thing is, since I've been using RuTorrent, I have not seen any new public trackers added to the search feature. Is there any possibility that this can be done? Or does there exist a site that has special scripts I can use to easily create/add them? Thanks..

PS... Demonoid has a new address demonoid.pw

**Comment by Evililim** [comment]
hello, I try to access to demonoid.pw, but it's down.
