### ISSUE TITLE
ruTorrent ignores CIFS network shares

### ISSUE THREAD

**Issue by palacinka** [Novik/ruTorrent#1360]
when I successfully mount network drive like this:
` mount -t cifs -o user=usr,password=pass,noperm //172.16.0.5/downloads3 /opt/rtorrent/download/2TB`

ruTorrent stops seeing mounted folder 2TB in listing (it sees it only when umounted). But it does not seem like permission issue.
CIFS network share for some reason is not supported, why?

**Comment by Novik** [comment]
Sorry, but ruTorrent can't seeding at all. Because it is web interface, not torrent client. Try to use proper repository.

**Comment by palacinka** [comment]
well i wrote **seeing**  not seeding

**Comment by Novik** [comment]
Sorry. I think, this is a permission issue. 
Show me output of command
stat /opt/rtorrent/download/2TB after mounting operation.

**Comment by palacinka** [comment]
after mount:

stat /opt/rtorrent/download/2TB/
  File: ‘/opt/rtorrent/download/2TB/’
  Size: 8192            Blocks: 16         IO Block: 16384  directory
Device: 22h/34d Inode: 281474976710696  Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-12-03 07:46:57.851598500 -0500
Modify: 2016-12-03 07:46:57.851598500 -0500
Change: 2016-12-03 07:46:57.851598500 -0500
 Birth: -

**Comment by Novik** [comment]
> Access: (0755/drwxr-xr-x) Uid: ( 0/ root) Gid: ( 0/ root)

As you may see, this resource is non-writable for all, except root.
You really launch rtorrent under root user?

**Comment by palacinka** [comment]
OK sorry that is my mistake.

No, I run rtorrent under its own user, but it seems I cannot mount network share under anything else except root (mount: only root can use "--options" option). And under root I cannot change permissions of that share.

Anyway this is not related to ruTorrent then. Sorry for bothering you

**Comment by palacinka** [comment]
If anyone find it useful

when you mount CIFS share with  proper  uid  and gid  like this then ruTorrent will see mounted folder properly:

`mount -t cifs -o user=usr,password=pass,uid=rtorrent,gid=rtorrent //172.16.0.5/downloads3 /opt/rtorrent/download/2TB`
