### ISSUE TITLE
Proper center alignment of default theme progress indicator text

### ISSUE THREAD

**Issue by allixx** [Novik/ruTorrent#1363]
It's much nicer visually and aesthetically to have center-aligned text in progress indicators, instead of left: 40% hack. Tested in Firefox and Chrome.

[stable.css.diff.txt](https://github.com/Novik/ruTorrent/files/643993/stable.css.diff.txt)

**Comment by mariotacke** [comment]
You should open a pull request instead of attaching the patch diff. It would be easier to see the differences and it integrates well into the existing workflow.
