### ISSUE TITLE
[Suggestion] Custom Window Title - For Easy Switching

### ISSUE THREAD

**Issue by Qwerty-Space** [Novik/ruTorrent#1368]
Hello,

I run multiple rTorrent installs and use ruTorrent on my seedbox, and it would be great if we could name the tab to something so we know which tab to go to for what we want.  Because at the moment they're all called "ruTorrent vXXXX" etc.

Thank you!

**Comment by Novik** [comment]
[set_title.tar.gz](https://github.com/Novik/ruTorrent/files/716226/set_title.tar.gz)

Set your title in the plugin's conf.php.
