### ISSUE TITLE
rutorrent just deleted my long term seeding torrents after i changed their label

### ISSUE THREAD

**Issue by hannsen** [Novik/ruTorrent#1369]
So i put my long term seeding torrents in another group.
then it somehow enabled ratio groups for those torrents (why?) and deleted all of them because they were over their seedtime. I have no idea why it would change the ratio group when you change the group of the torrent, but now  I lost quite some data

**Comment by Novik** [comment]
> I have no idea why it would change

Sorry, but I have no idea too.
