### ISSUE TITLE
php/test.sh -- security concern over file being made world readable and world writeable by default

### ISSUE THREAD

**Issue by Corin-EU** [Novik/ruTorrent#1370]
In the script php/test.sh, there are two chmod statements

``chmod 0666 "$2$1.found"``

As a general security rule, files should never by default be made world writeable and as they may also contain sensitive information (eg passwords), should not be world readable, so these statements should be 

``chmod 0660 "$2$1.found"`

or use a parameter for the permission set in a configuration file which the system administrator can set as appropriate (eg maybe even just 0600).

**Comment by Novik** [comment]
> be made world writeable and as they may also contain sensitive information

This file has zero size.
