### ISSUE TITLE
RSS broken

### ISSUE THREAD

**Issue by mariotacke** [Novik/ruTorrent#1371]
I updated to latest and it appears that it broke my RSS feeds. It could no longer retrieve the feeds I had set up for a very long time. I rolled back to b14a20a45f816d8edc61c01a4d06204ba514f0ea and it worked fine again. I am wondering if anybody else experienced something similar? Not sure what the Snoopy stuff is but it seems like it messed with my configuration.

**Comment by anoma** [comment]
You are not alone. I was scratching my head until I seen this and rolled back to https://github.com/linuxserver/docker-rutorrent/releases/tag/45 and now it works.
