### ISSUE TITLE
extsearch plugin IPTorrents engine not working

### ISSUE THREAD

**Issue by skiski456** [Novik/ruTorrent#1373]
Their website appears to have changed, how do you enable debug output for plugins?

**Comment by skiski456** [comment]
I fixed it,  updated the categories and the regex pattern.
[IPTorrents.zip](https://github.com/Novik/ruTorrent/files/669949/IPTorrents.zip)

**Comment by sa7mon** [comment]
@skiski456 Can you make a pull request with these changes?

**Comment by rtorrentuser** [comment]
Fixed
