### ISSUE TITLE
Extsearch engines

### ISSUE THREAD

**Issue by esbeone** [Novik/ruTorrent#1377]
Hi,

I am new to rutorrent and would like some help.

I have some engines like extratorrent that dont return results whereas piratebay or mininova are working .
Does anyone manage to get results from extratorrent  ? 

I found this :      https://github.com/Novik/ruTorrent/blob/master/plugins/extsearch/engines/ExtraTorrent.php , but i am not sure whether the problem is from this file or not.

I saw this thread  :  https://github.com/Novik/ruTorrent/issues/1373and thought maybe extratorrent need some modifications.

Please let me know.

Thanks for your help.

**Comment by domdorn** [comment]
probably they've changed some html markup on ExtraTorrent and the plugin needs an update.

**Comment by Novik** [comment]
Fixed.
