### ISSUE TITLE
rss and rutracker_check plugins don't work + upload fail

### ISSUE THREAD

**Issue by noraj** [Novik/ruTorrent#1380]
Hello,

I checked:
+ ruTorrent Wiki
+ open and close issues
+ archlinux rutorrent [wiki](https://wiki.archlinux.org/index.php/RuTorrent)

And I can't solve this two problems:

```
rss: Some functionality will be unavailable. Webserver user can't access external program (curl).
rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory (/home/sdbox/.session/).
```

I made a manual install and [here](http://rawsec.ml/en/archlinux-install-rtorrent-rutorrent/) is the full install process I wrote (you'll have all info on the blog post).

**Comment by noraj1337** [comment]
I have no error when adding a torrent from an URL by I get `Failed to add torrent.` when adding a torrent from upload.

http user (nginx) has read/execute access to `/home/sdbox/.session/`. I even tried to give him write.

**Comment by noraj1337** [comment]
By adding `/home/sdbox/.session` into `open_basedir` of `/etc/php/php.ini` I no longer have this error:
```
rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory (/home/sdbox/.session/).
```
But I still can't add torrent via upload.

**Comment by scoobynz** [comment]
At the terminal type which curl

paste the result into your config.php (/var/www/rutorrent/conf/config.php in the path to externals array.

Mine is; "curl" => '/usr/bin/curl',

**Comment by noraj1337** [comment]
My `/usr/share/nginx/html/rutorrent/conf/users/username/config.php` is as follow:

```
<?php

$pathToExternals['curl'] = '/usr/bin/curl';
$topDirectory = '/home/username';
$scgi_port = 5000;
$scgi_host = '127.0.0.1';
$XMLRPCMountPoint = '/SDBOX';
$tempDirectory = '/usr/share/nginx/html/rutorrent/tmp/';
```

**Comment by scoobynz** [comment]
I dont really know then sorry. Have you also got /usr/bin/ in the base_opendir?

**Comment by noraj1337** [comment]
Putting `/usr/bin/` in `base_opendir` in a security wekness.
