### ISSUE TITLE
Reboot rtorrent from rutorrent ?

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1383]
is there any plugin to reboot rtorrent from the rutorrent gui ?

**Comment by Flayor** [comment]
No but if you want i can a build one

**Comment by ArtyumX** [comment]
@Flayor Interested.

**Comment by gre1423** [comment]
@Flayo it would be great

**Comment by sir-hashpipe** [comment]
There is a plugin called Starter that can do this that is used by some seedbox providers. It's not so easy to some by online though.
