### ISSUE TITLE
AutoTools Move issue

### ISSUE THREAD

**Issue by taobataoma** [Novik/ruTorrent#1390]
I create a new LABEL(such as 'abc') when i add a torrent on Add Torrent Window，then  Set the complete folder in Settings->AutoTools(such as /volume1/video/Movie) and checked AUTOMOVE checkbox，I want it Move the complete torrent files to /volume1/video/Movie/abc, how can I do it?
can use some template var in folder value(such as /volume1/video/Movie/{LABEL})?

**Comment by isaactolstoi** [comment]
Check the checkbox "Add torrent's label to path" in the automove settings. It  automatically adds the label which is set on the torrent. No need for a special template variable
