### ISSUE TITLE
Upload ETA

### ISSUE THREAD

**Issue by Windkracht8** [Novik/ruTorrent#1391]
So I have rtorrent setup to automatically remove a torrent after the ratio has hit 200 (ratio.min.set=200). As I want to share my part, but also want to cleanup old stuff. With this in mind I was missing an Upload ETA column. Today I took some time to create it and want to share the diff with anybody interested in doing the same.

This patch assumes the httprpc plugin and a ration of 200. For automatic removal of torrent you will have this in your configuration:
#Stop on ratio
ratio.enable=
ratio.min.set=200
system.method.set = group.seeding.ratio.command, d.close=, d.erase=

And in my case also a call to a script for an email notification:
system.method.set_key = event.download.erased,handle_erase,"execute={/usr/local/bin/torrentremoved,$d.get_name=,$d.get_directory=,$d.get_size_bytes=,$d.get_ratio=}"

Then apply this patch:
[ul_eta.txt](https://github.com/Novik/ruTorrent/files/687699/ul_eta.txt)

**Comment by Windkracht8** [comment]
[uploadeta.zip](https://github.com/Novik/ruTorrent/files/703168/uploadeta.zip)

Rewrite to make it a plugin.

**Comment by enoch85** [comment]
Can you add this as a plugin by default?

**Comment by Windkracht8** [comment]
I am not sure what you mean, also I am not a contributor of ruTorrent, I can not add it to the main branch. I've got it in my branch: https://github.com/Windkracht8/ruTorrent/tree/master/plugins/uploadeta So I could create a pull request.

**Comment by enoch85** [comment]
@Windkracht8 
>I could create a pull request.

Please do.

**Comment by Windkracht8** [comment]
https://github.com/Novik/ruTorrent/pull/1420
