### ISSUE TITLE
Incorrect values displayed in 'Settings'. 

### ISSUE THREAD

**Issue by rtorrentuser** [Novik/ruTorrent#1396]
Что-то поменялось в текущей версии rTorrent по сравнению с крайним релизом, что даёт вот такой эффект, как на картинках. Слева - с релизом rTorrent, справа - с текущей версией rtorrent. Настройки rtorrent в обоих случаях идентичны, ruTorrent - свежий....
![01](https://cloud.githubusercontent.com/assets/1167563/21932853/b2536c22-d9b3-11e6-910b-2ae476f4a2b7.jpg)
![02](https://cloud.githubusercontent.com/assets/1167563/21932854/b2547360-d9b3-11e6-85cf-721e487bd23c.jpg)
![03](https://cloud.githubusercontent.com/assets/1167563/21932852/b251de52-d9b3-11e6-8467-33c0b430de88.jpg)
![04](https://cloud.githubusercontent.com/assets/1167563/21932855/b256f69e-d9b3-11e6-949f-28d46b7754f9.jpg)
![05](https://cloud.githubusercontent.com/assets/1167563/21932856/b257eed2-d9b3-11e6-9642-35b4d97a1cf6.jpg)

**Comment by Novik** [comment]
На свежесть плагина httprpc смотрите.

**Comment by Novik** [comment]
Без понятия, честно говоря. У меня все показывает корректно в любых сочетаниях, причем как для rtorrent 0.8.6 так и для 0.9.6.
Соотв. функция - https://github.com/Novik/ruTorrent/blob/master/js/rtorrent.js#L789 с момента релиза 3.7 не менялась.

**Comment by rtorrentuser** [comment]
С релизом 0.9.6 всё корректно показывается в любых сочетаниях, некорректно (исключая HttpRPC) - с текущей версией с Гитхаба... Где-то что-то автор rTorrent там на пути от релиза до текущего состояния поменял, насколько я понимаю...

**Comment by Novik** [comment]
Текущая ветка master у него вообще не компилируется. 
Anyway, поправил, смотрите.

**Comment by rtorrentuser** [comment]
Да, всё корректно теперь во всех трёх вариантах. Спасибо!
Что до текущей ветки libtorrent/rtorrent, то автор там что-то намудрил, как он сам писал, и пока рабочая ветка feature-bind:
https://github.com/rakshasa/libtorrent/tree/feature-bind
https://github.com/rakshasa/rtorrent/tree/feature-bind
