### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by CoFix** [Novik/ruTorrent#1398]
delete this

**Comment by isaactolstoi** [comment]
2 & 3 can be done with the patch i proposed tonight in https://github.com/Novik/ruTorrent/pull/1264
together with the unpack plugin

**Comment by CoFix** [comment]
I redownload autotools plugin but cant see any different. 

What does mean undefined ?

**Comment by Evililim** [comment]
@CoFix the 2 & 3 are in unpack plugin udpate. For 4 and 5, I think you should use a software like FileBot or other.

**Comment by CoFix** [comment]
It cannt be fix what i want. I need fully plugin with it. I can pay who can do this :)

**Comment by CoFix** [comment]
@isaactolstoi 

If possible can you add delete options when torrent opened from rar. I mean all rar files will delete when files out from rar. I know i cant seed old torrent files but this maybe will be in options.

Append to Pathname When Unpacking Torrent Data
Torrent Label
Torrent Name
Delete All Old Rar Files

**Comment by xombiemp** [comment]
Delete old rar files is already possible.  In the unpack conf.php set
`$deleteAutoArchives = true;`

**Comment by CoFix** [comment]
Any good news about my request ?
