### ISSUE TITLE
Error when opening settings

### ISSUE THREAD

**Issue by xombiemp** [Novik/ruTorrent#1400]
After updating to the latest commit, when I try to open the settings I get the following in the log:
`[02/02/2017 08:53:13] JS error: [undefined : 238] TypeError: null is not an object (evaluating '$$('enable_label').checked = ( theWebUI.autotools.EnableLabel == 1 )')`

@isaactolstoi do you think this might be due to your commit #1264 ?

**Comment by isaactolstoi** [comment]
Probably, would be quite a coincidence if it happened now because of something else.
Yes. I managed to commit a merge conflict, sorry about that. Should be fixed in  #1401

**Comment by xombiemp** [comment]
d70dc756839b05febb9f099da58ac6858a16ad19 fixed the problem.  Thanks
