### ISSUE TITLE
Reset "recent trackers"

### ISSUE THREAD

**Issue by japester-dk** [Novik/ruTorrent#1402]
Isn't there any way to reset the "recent trackers" when creating a torrent. I can't seem to get rid of/modify the one in my list.
Please don't give me a too complex code, coz I'm a newbie :)

**Comment by Micdu70** [comment]
Hello, you can only clear the "Recent trackers" list with deleting the "rtrackers.dat" file in '.../ruTorrent/share/users/{username}/settings/' directory.

If you need more help, just ask. ;-)

**Comment by japester-dk** [comment]
Thanks champ. This was exactly what I needed :)
