### ISSUE TITLE
Need documentation for how to install RPC Plugin or HTTPRPC Plugin 

### ISSUE THREAD

**Issue by scottchiefbaker** [Novik/ruTorrent#1405]
I'm attempting to setup an OSS Torrent mirror using ruTorrent CentOS 7 or Fedora 25. Unfortunately those distros don't ship with SCGI any more. Attempting to setup RPC or HTTPRPC is leading to a lot of headaches. There is very little documentation on how to configure them to interface with them:

https://github.com/Novik/ruTorrent/wiki/PluginRPC
vs
https://github.com/Novik/ruTorrent/wiki/PluginHTTPRPC

Is there another place for setup instructions?

**Comment by Novik** [comment]
These plugins hasn't any special configurations.

**Comment by scottchiefbaker** [comment]
How do I enable one of them? How do I configure rTorrent to talk to HTTPRPC instead of using a SCGI socket? 

I'm having trouble tracking down the setup instructions to enable one of these communication methods.

**Comment by Novik** [comment]
> How do I enable one of them? How do I configure rTorrent to talk to HTTPRPC instead of using a SCGI socket?

https://github.com/Novik/ruTorrent/wiki/Plugins

"Every plugin has his own directory inside ruTorrent/plugins.."

**Comment by scottchiefbaker** [comment]
I've got a vanilla setup of ruTorrent running on my CentOS 7 box. The only plugin I have in my plugins directory is `HTTPRPC`. rTorrent is running and seeding a bunch of Linux ISOs. When I load ruTorrent I get:

> No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

I assume I need to setup something in `conf/config.php` to tell it talk to to HTTPRPC?

**Comment by xombiemp** [comment]
Make sure you have network.scgi.open_port = 127.0.0.1:5000 in your rtorrent.rc.

Other than that, there is nothing to setup for the HTTPRPC plugin.

**Comment by scottchiefbaker** [comment]
In 2017 on a modern PC, are there any real advantages to one plugin over the other?

**Comment by scottchiefbaker** [comment]
I misunderstood the purpose of how to use this. I think I got it now.
