### ISSUE TITLE
Share/Settings not accepting ratio.dat & ratiorules.dat?

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#1413]
Hi,

A few years ago on a previous build I was able to insert ratio/ratiorules.dat files from a users settings directory into the share/settings directory and they would become default for all users but I can't seem to get it to work on new setup.

Does anybody have any idea what issue could be or how to resolve?   I'm trying to set same settings for all users/new users without needing to put the settings in the users/settings folder each time.

Thanks

**Comment by ILLYAG** [comment]
bump
