### ISSUE TITLE
Rutorrent external app config

### ISSUE THREAD

**Issue by edge33** [Novik/ruTorrent#1414]
I'm running Centos 6 and nginx
$pathToExternals = array(
                "php"   => '',                  // Something like /usr/bin/php. If empty, will be found in PATH.
                "curl"  => '/usr/bin/curl',                     // Something like /usr/bin/curl. If empty, will be found in PATH.
                "gzip"  => '',                  // Something like /usr/bin/gzip. If empty, will be found in PATH.
                "id"    => '',                  // Something like /usr/bin/id. If empty, will be found in PATH.
                "stat"  => '/usr/bin/stat',                     // Something like /usr/bin/stat. If empty, will be found in PATH.
        );

I don't understand why I need to manually set the path for the curl and stat executables in order to get rutorrent plugins working. I mean, I don't need to set the path for id, gzip, and php, why ? Is it maybe due to nginx user permission to run specific apps ?

**Comment by mmalisz** [comment]
Maybe your $PATH  doesn't store paths in which curl and stat have been installed.
