### ISSUE TITLE
Add Torrent Dialog Box - No Option to change Directory

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1415]
HI,
I have set up a new installation of RuTorrent, but when I try to add a torrent the dialogue box doesn't have 
the change directory button.

My server...
CentOS Linux release 7.3.1611 (Core)
PHP 7.0.15
nginx/1.10.3
selinux = enforcing (but problem persists even when disabled)

I thought maybe it was a permissions issue, so I have set permissions on all web Directories and Files to 777 and disabled selinux, but the problem persists.

![rut](https://cloud.githubusercontent.com/assets/25935281/23177318/451524a6-f85e-11e6-9e2a-87f298bfa5d2.png)

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/wiki/Plugin_getdir

**Comment by DonCor** [comment]
ah ok thanks, I wondered if it was that.
I have the plugins in /rtorrent/plugins but they're not loading for some reason.
Now I know its because of that I can figure it out.
Thanks
