### ISSUE TITLE
upgrade from v3.6 to 3.7

### ISSUE THREAD

**Issue by noorbertt** [Novik/ruTorrent#1419]
Hi,

I did follow this step by step to install rtorrent and rutorrent : 
http://www.htpcguides.com/install-configure-rtorrent-and-rutorrent-on-debian/ -> https://github.com/Kerwood/Rtorrent-Auto-Install

There is a way to upgrade to 3.7? How?

**Comment by Flayor** [comment]
@noorbertt Just download the github project ...

**Comment by tool-maker** [comment]
You might pick up some unstable updates if you just take the git repository?

===

I used a zip file version, and I kept the URL I used:

https://bintray.com/artifact/download/novik65/generic/ruTorrent-3.7.zip

I think I got that originally by using the link "Stable version" on the main page, which takes you here:

https://bintray.com/novik65/generic/ruTorrent

I don't see a path to the URL I saved, but there is a link to this:

https://bintray.com/novik65/generic/ruTorrent/3.7

Then a link to here:

https://dl.bintray.com/novik65/generic/

You can click on "ruTorrent-3.7.zip". This yielded an identical file.

Also I had saved a link to this:

https://bintray.com/novik65/generic/ruTorrent/3.7#files

Clicking "ruTorrent-3.7.zip" there also produced the same file.

I have no idea why this package is so hard to find now, Worrisome though.

**Comment by Flayor** [comment]
@tool-maker No You should not delete the .git, if you do that, you can't do the update with git pull

**Comment by tool-maker** [comment]
I just meant that if you compare them, everything is the same.

I took noorbertt's question to mean, "How do you obtain release 3.7, without all of the changes made since then?".

The master branch has moved on since that commit anyway. So unless you intend to fork rutorrent this is a moot point anyway.

**Comment by noorbertt** [comment]
thx all =) all good now

**Comment by jm134** [comment]
for label with big didn't work please help how to get bunch of torrent files based on label
