### ISSUE TITLE
Plugins Can't start operation?

### ISSUE THREAD

**Issue by mo641534** [Novik/ruTorrent#1422]
Hi,recently I got this error,and I don't know how to fix it ?
![1](https://cloud.githubusercontent.com/assets/17099117/23585910/d61999c2-01c4-11e7-8ef4-09bff3c1f726.png)
![2](https://cloud.githubusercontent.com/assets/17099117/23585911/d61f9dcc-01c4-11e7-8357-da3298e97365.png)

Thank u guys very much!

**Comment by s-c-o-o-t** [comment]
Yes, I just ran into the same problem. It was working fine and Everything, just get the same error now, ive tried searching and all cant seem to find the solution ::(

**Comment by Novik** [comment]
1) Check webserver's errors log.
2) Try to set config variable $tempDirectory to the something existing directory with permissions 0777.
