### ISSUE TITLE
extratio doesn't function after instatlling

### ISSUE THREAD

**Issue by djmed2** [Novik/ruTorrent#1424]
rtorrent 0.9.6
rutorrent 3.5

I have both dependencies for extratio, both of them work. Once I add the extratio directory to my plugins and restart rtorrent I do get 'ratio rules' under the plugins context menu but when clicking it I get a '500 error, getratiorules' it also breaks labels when I interact with labels I get a '500 error, checklabels'. Any suggestions on how to fix this?

**Comment by alpinewinter** [comment]
I'm having the same issue

**Comment by custardcreamdream** [comment]
Which version of the plugins do you have?
