### ISSUE TITLE
Cannot delete files from ruTorrent?

### ISSUE THREAD

**Issue by emacsomancer** [Novik/ruTorrent#1425]
Seemingly in the last month I seem to have lost the ability to "Remove and Delete Data" from ruTorrent. I can remove torrents (without removing data/files), but selecting "Remove and Delete Data" or "Remove and Delete Data (all)" does nothing (it does not remove torrent or data or bring up a confirmation alert).

**Comment by tuxayo** [comment]
It might be related to #1451
