### ISSUE TITLE
Add support for mktorrent features in create plugin

### ISSUE THREAD

**Issue by tombs007** [Novik/ruTorrent#1426]
In mktorrent >=1.1 a feature has been add:
-s                : add source string embedded in infohash

Please add support for this feature in the Create Torrent dialog box

**Comment by tombs007** [comment]
Any chance in getting support for this added?

**Comment by Novik** [comment]
For which reason you need this?

**Comment by tombs007** [comment]
Certain trackers I upload at require it.

**Comment by Novik** [comment]
I.e. this is not public feature, this required by you only. Try to write your own plugin.
