### ISSUE TITLE
PHP7 Deprecated functionality

### ISSUE THREAD

**Issue by carbinefreak** [Novik/ruTorrent#1427]
I'm getting these warnings with:
php 7.0.15
apache 2.4.25
rutorrent 3.7

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; rXMLRPCParam has a deprecated constructor in /var/www/localhost/htdocs/rutorrent/php/xmlrpc.php on line 6

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; rXMLRPCCommand has a deprecated constructor in /var/www/localhost/htdocs/rutorrent/php/xmlrpc.php on line 21

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; rXMLRPCRequest has a deprecated constructor in /var/www/localhost/htdocs/rutorrent/php/xmlrpc.php on line 70

**Comment by Flayor** [comment]
Ho

Can you tell me more information ?

How yiu get this errors ?

**Comment by Novik** [comment]
Try to use development version of ruTorrent from git.
