### ISSUE TITLE
 Bad response from server: (500 [error,list])

### ISSUE THREAD

**Issue by From2750** [Novik/ruTorrent#1428]
Dedi server from Hetzner
Debian jessie

I can't get it to work. its will not load any torrent,
i have google and somebody says that to fix the problem you have to change the memory_limit to 1024 in php.ini
i have try that and that did not help.

after i try with the php.ini and that not solve my problem i type
screen -r rtorrent
Then type 0 so see all active torrent, then i close then all with ctrl+k

that still dont help, know i dont know what else to do?
i have just restart my rutorrent

~$ sudo systemctl status rtorrent@from2750.service
● rtorrent@from2750.service - rTorrent
Loaded: loaded (/etc/systemd/system/rtorrent@.service; enabled)
Active: active (running) since Sat 2017-03-18 16:13:03 CET; 5min ago
Process: 2197 ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
Process: 2212 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
Process: 2210 ExecStartPre=/bin/rm -f /home/%I/.sessions/rtorrent.lock (code=exited, status=0/SUCCESS)
Main PID: 2215 (screen)
CGroup: /system.slice/system-rtorrent.slice/rtorrent@from2750.service
├─2215 /usr/bin/SCREEN -d -m -fa -S rtorrent /usr/bin/rtorrent
└─2216 /usr/bin/rtorrent

my .rtorrent.rc file look like this
# -- START HERE --
directory.default.set = /home/from2750/torrents/rtorrent
encoding.add = UTF-8
encryption = allow_incoming,try_outgoing,enable_retry
execute.nothrow = chmod,777,/home/from2750/.config/rpc.socket
execute.nothrow = chmod,777,/home/from2750/.sessions
network.port_random.set = yes
network.port_range.set = 7684-9184
network.scgi.open_port = localhost:7684
network.tos.set = throughput
pieces.hash.on_completion.set = no
protocol.pex.set = no
schedule = watch_directory,5,5,load.start=/home/from2750/rwatch/*.torrent
session.path.set = /home/from2750/.sessions/
throttle.global_down.max_rate.set = 0
throttle.global_up.max_rate.set = 0
throttle.max_peers.normal.set = 100
throttle.max_peers.seed.set = -1
throttle.max_uploads.global.set = 100
throttle.min_peers.normal.set = 1
throttle.min_peers.seed.set = -1
trackers.use_udp.set = yes
# -- END HERE --	

i have run
update
upgrade

**Comment by Pingblue** [comment]
Have you tried to delete the tasks folder? I have seen this message before when the tasks log gets large.

This can be found in the web folder normally at /var/www/rutorrent/share/users/your_username/tasks
