### ISSUE TITLE
Delete This

### ISSUE THREAD

**Issue by CoFix** [Novik/ruTorrent#1429]
Delete This

**Comment by Flayor** [comment]
What do you want ?

You want upload a file in a tracker directly with ruTorrent ?

**Comment by CoFix** [comment]
Yes, when files downloading finished, it will auto upload to my tracker correct category.

@Flayor Can you do that?

**Comment by Flayor** [comment]
Well, maybe it's possible, but what the name of the tracker, if there're not API it's not possible ..

**Comment by CoFix** [comment]
My tracker is www.worldofp2p.net

Nope, I dont have any API for it
