### ISSUE TITLE
Where is forum?  Donation.  Suggestions

### ISSUE THREAD

**Issue by Papoulka** [Novik/ruTorrent#1441]
Writing here because forums.rutorrent.org seems 'dead'.  Will be glad to know of a replacement.

Thanks very much for rutorrent.  I use it daily and it's great.

--> Is there a Paypal or Bitcoin donations page?

I have two suggestions:

1)  Even if I sort by a non-dynamic field like 'Label', the list of torrents constantly cycles, switching places.  This makes it hard to keep selections, step through torrents etc.  It would be great if this can be stopped.

2)  In torrent size fields I'd like'MB' to be presented in red, to be more distinct from 'KB'.  Or bold, or any other method.

Thanks again.

**Comment by Novik** [comment]
> --> Is there a Paypal or Bitcoin donations page?

See start page of project.

> Even if I sort by a non-dynamic field like 'Label', the list of torrents constantly cycles, switching places. 

This may happens, if both primary and secondary sorting values are equal for some rows.
You may change primary sort with click on the corresponding column's header.
You may change secondary sort with shift+click on the corresponding column's header.
By default system use first column for secondary sort.
