### ISSUE TITLE
File Type When Adding: All Files

### ISSUE THREAD

**Issue by Joshmannn** [Novik/ruTorrent#1444]
Greetings,

I find now when I want to add a torrent file, "All Files (*.*)" is the only option available in the drop-down box. The .Torrent option from the file type drop-down box is gone. Is there any way to get that back?

**Comment by Joshmannn** [comment]
I can do that, yes but the .Torrent option from the file type drop-down box is gone. Is there any way to get that back?

**Comment by Novik** [comment]
First of all, check development version from git.
If problem still present - please, paste here information about ypur browser version and OS.
