### ISSUE TITLE
erasedata plugin: No error message when issuficient permissions on Rutorrent folder

### ISSUE THREAD

**Issue by tuxayo** [Novik/ruTorrent#1451]
In my case Rutorrent is installed in `/usr/share/webapps/rutorrent`

When I `chown -R http:torrent /usr/share/webapps/rutorrent`
So the rtorrent user (which is different from the Rutorrent/webserver one) can also access it.
Then erasing data works.

When I put back wrong permissions with `chown -R http:http /usr/share/webapps/rutorrent`.
Then the data is **silently** not erased.

Related to #1259

**Comment by notojak** [comment]
After the last update, the files are not deleted again
Permissions to the rutorrent directory are correct...

What`s wrong ?

**Comment by tuxayo** [comment]
Which OS/Distribution? In my case I **suspect** a packaging issue in the [Arch Linux AUR package](https://aur.archlinux.org/packages/rutorrent-git/) which made me fix few times the permissions after an update.

**Comment by notojak** [comment]
dist: Debian 9
Server restart, solved the problem... 

Maybe some problem with permissions, I do not know.

**Comment by YamashitaRen** [comment]
Same issue @tuxayo. I think you are onto something, I am using AUR's package too.
