### ISSUE TITLE
ruTorrent not obeying throttle speeds set in .rtorrent.rc

### ISSUE THREAD

**Issue by hollanbm** [Novik/ruTorrent#1452]
```
#Global upload and download rate in KiB, `0` for unlimited (`download_rate`, `upload_rate`)
throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb   = 0
```

When using these settings in your .rtorrent.rc, this specifies an unlimited max upload/download rate. The problem with this is, that if you have this set, upon first launch of ruTorrent your "unlimited" setting will be reverted to the default "unlimited" speed in ruTorrent, which is 102400 KB.

To test this, use the settings above and launch rtorrent in the console. Notice in the bottom left that it will say [Throttle off/off KB]. Now launch ruTorrent and observe the console, your throttle settings will change to [Throttle 102400/102400 KB].

Going back into ruTorrent settings-> Connection-> Bandwidth Limitation settings and setting respective values back to 0 will produce the intended functionality, and remove the throttle limits.

This is a small bug which will not affect most. But for those that it does, it can be rather annoying remembering to set this after a reboot or restart of rTorrent.

**Solution:**
To fix this problem, modify the following file, rutorrent/plugins/throttle/throttle.php

```
<?php
require_once( dirname(__FILE__)."/../../php/xmlrpc.php" );
require_once( $rootPath.'/php/cache.php');
eval(getPluginConf('throttle'));

@define('MAX_SPEED', 100*1024*1024);

class rThrottle
...
```

needs to be changed to 

```
<?php
require_once( dirname(__FILE__)."/../../php/xmlrpc.php" );
require_once( $rootPath.'/php/cache.php');
eval(getPluginConf('throttle'));

@define('MAX_SPEED', 0);

class rThrottle
...
```

The reason this solution works is located in this function, same file.
```
public function obtain()
	{
		$req = new rXMLRPCRequest( array(
			new rXMLRPCCommand( "get_upload_rate" ),
			new rXMLRPCCommand( "get_download_rate" ) ));
		if($req->run() && !$req->fault)
		{
			$req1 = new rXMLRPCRequest();
			if($req->val[0]==0)
				$req1->addCommand(new rXMLRPCCommand( "set_upload_rate", MAX_SPEED ));
			if($req->val[1]==0)
				$req1->addCommand(new rXMLRPCCommand( "set_download_rate", MAX_SPEED ));
			if((($req->val[0]==0) || ($req->val[1]==0)) &&
				(!$req1->run() || $req1->fault))
				return(false);
			return($this->correct());
        	}
		return(false);
	}
```
I do not know why this change was made, but it looks like it was intentional, if the speeds come back as 0, then set them to the max_speed.

**Comment by Novik** [comment]
We can't have zero MAX_SPEED.
See https://github.com/Novik/ruTorrent/wiki/PluginThrottle#some-non-obvious-points for details.

**Comment by hollanbm** [comment]
Can the case be made to increase MAX_SPEED from 100M to 1000M?

**Comment by Novik** [comment]
AFAIK, this may be done. But in this case you should to change function 'updateStatus' in the file webui.js too.
Try and make pull request, if all will be OK, please.

**Comment by hollanbm** [comment]
Done

**Comment by Pingblue** [comment]
The Throttle plugin is not installed on my rutorrent but the speed is still limited 100MiB

How could I increase this to 1000MiB ?

**Comment by hollanbm** [comment]
git pull to get the latest changes

otherwise just set your speeds after launching

**Comment by Pingblue** [comment]
I'm running the latest from Github. 

I set 0 in the rtorrent.rc and the speed appears to be limited to 100MiB but if I set the speed to 307200 in the rtorrent,rc I get 300MiB but this is the largest value that can be set in the rtorrent.rc.

Is there any option to set 1000MiB in rutorrent ?

**Comment by hollanbm** [comment]
I don't think you're running the latest

check the contents of throttle.php and webui.js

https://github.com/Novik/ruTorrent/pull/1470

**Comment by Pingblue** [comment]
Throttle Plugin is not installed but webui.js changes have been applied.

Pingblue@server:/var/www/rutorrent/js# grep self.total.rateUL webui.js
                $("#stup_limit").text((self.total.rateUL>0 && self.total.rateUL<1000*1024*1024) ? theConverter.speed(self.total.rateUL) : theUILang.no);
Pingblue@server:/var/www/rutorrent/js# grep self.total.rateDL webui.js
                $("#stdown_limit").text((self.total.rateDL>0 && self.total.rateDL<1000*1024*1024) ? theConverter.speed(self.total.rateDL) : theUILang.no);

**Comment by hollanbm** [comment]
Where the asterisks removed when you posted?

1000*1024*1024

**Comment by Pingblue** [comment]
It looks like I can only set the value to "No Limit" if the throttle plugin is installed.
