### ISSUE TITLE
Warning: XMLRPC call is failed. in chrome and IE

### ISSUE THREAD

**Issue by lovewangbo** [Novik/ruTorrent#1459]
Hi, I install libtorrent 0.13.6, rtorrent 0.9.6 and rutorrent 3.7 in debian 8.1 using shell script: 
https://github.com/yjcn/Rtorrent-Auto-Install_IPv6_Support. Then rutorrent 3.7 is obtianed by git clone https://github.com/Novik/ruTorrent.git. Now I can only access the hostip/rutorrent with firefox. 
With firefox 53.0.2 64bit, rutorrent reports in log that 

> [20.05.2017 22:49:01] WebUI started.
> [20.05.2017 22:49:05] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
> [20.05.2017 22:49:05] mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo).
> [20.05.2017 22:49:07] Unpack plugin: rTorrent user can't access 'unrar' program.

In chrome 58.0.3029.110 (64-bit) its log reports that

> [20.05.2017 22:30:46] WebUI started.
> [20.05.2017 22:30:48] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
> [20.05.2017 22:30:48] mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo).
> **[20.05.2017 22:30:49] Bad response from server: (500 [error,list]) Warning: XMLRPC call is failed.**
> [20.05.2017 22:30:49] Unpack plugin: rTorrent user can't access 'unrar' program.

I can add torrent by rutorrent successfully (rutorrent's long reports that, and I verify this in terminal via SSH), but the panel of rutorrent does not list any torrent at all. For the torrents added by terminal via SSH, rutorrent can not list them as well.

And in IE 11.1198.14393.0 its log reports in that 

> [20.05.2017 22:31:38] WebUI started.
> [20.05.2017 22:31:46] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
> [20.05.2017 22:31:46] mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo).
> [20.05.2017 22:31:49] JS error: [ : 28] Expected identifier, string or number
> [20.05.2017 22:31:49] JS error: [ : 28] Expected identifier, string or number
> [20.05.2017 22:31:49] JS error: [http://23.105.201.205/rutorrent/js/plugins.js : 190] 'console' is undefined
> [20.05.2017 22:31:49] Unpack plugin: rTorrent user can't access 'unrar' program.
> [20.05.2017 22:31:51] JS error: [ : 1] Syntax error
> **[20.05.2017 22:31:52] Bad response from server: (500 [error,list]) Warning: XMLRPC call is failed.**
> The situation is totally the same as with chrome.

**Comment by Novik** [comment]
I think, you compile rtorrent without XMLRPC support. Check projects wiki for details.
