### ISSUE TITLE
Unable to add https rss: "Error loading feed"

### ISSUE THREAD

**Issue by perokopotato** [Novik/ruTorrent#1461]
Unable to add rss that starts with https, any "http" I can add with out any problems. I have tried TorrentLeech, IPT and TorrentDay. They all fail, other torrent clients do not have the same problem.
Ubuntu 16.04 LTS with latest rutorrent/rtorrent installation
![capture](https://cloud.githubusercontent.com/assets/18622945/26287503/4e9334ea-3e7d-11e7-8414-b292e2543faa.PNG)

**Comment by Bl0ub** [comment]
I have the same issue with other trackers. My config : 
Synology DSM 6.1 with Apache 2.4 and php 7.
I can add http rss feed but https does not work with the same error : Error loading feed.

**Comment by perokopotato** [comment]
Can you tell me where is the location of the original file?

**Comment by Bl0ub** [comment]
rutorrent/php/Snoopy.class.inc

**Comment by perokopotato** [comment]
To be precise: /var/www/rutorrent/php/Snoopy.class.inc
It appears it still works on ubuntu 14.04 but is broken on 16.04

**Comment by perokopotato** [comment]
It works with your file. I also read that people withe "modified" snoopy file had problems auto refreshing rss?

**Comment by Bl0ub** [comment]
No, my rss are updating correctly with this file (do not know if this file is implicated in updating rss feed).

**Comment by acee2bee** [comment]
Bl0ub this appears to work on 16.04 at this time. Thanks

**Comment by Rumik** [comment]
I'm having the same issue running 3.7 on QNAP. Is there a solution that doesn't involve me tinkering around with the file system?

**Comment by simcye** [comment]
Having the same issue, can't find any log files with more detailed information
running the latest dev version which seems to be 87f7b9e by the filename

**Comment by simcye** [comment]
Having the same issue
latest rutorrent dev release 87f7b9e
rtorrent 0.9.6
ubuntu 16.04.2 LTS
apache 2.4.18

**Comment by rlagarde** [comment]
Same issue on rutorrent 3.7 from the synology community package (DSM 6.1.3)
Using the Snoopy.class.inc from @Bl0ub didn't help

**Comment by bsdcpp** [comment]
this is not about the file Snoopy.class.inc
that's a mistake made by the maintainer of the synology DSM spk, you can refer to [this](https://github.com/Novik/ruTorrent/issues/1622#issuecomment-354458637) issue, I've solved this problem by just add a slash in the configuration file.
