### ISSUE TITLE
temp directory from config file isn't checked for trailing slash and writability

### ISSUE THREAD

**Issue by tuxayo** [Novik/ruTorrent#1463]
In my case, getTempDirectory() returns `/usr/share/webapps/rutorrent/tmp`

It should have a trailing slash so this breaks some things.

~~It's set to null in the config file.~~ ← see next comment

After adding some traces, I've found that the global $tempDirectory is already set to this value. So the rest of getTempDirectory() doesn't run and it doesn't add a slash.

https://github.com/Novik/ruTorrent/blob/3b15b5df9e52a60e73f68d9fb6139dcc948ae0d6/php/util.php#L660

1. Any idea of how $tempDirectory ended up with a bad value?

2. Would a patch checking if $tempDirectory is writable and has a trailing slash be accepted?

**Comment by tuxayo** [comment]
The bad tempDirectory value was actually due to a packaging error: https://aur.archlinux.org/packages/rutorrent-git/#comment-597711

And I was looking at the template config file in /etc instead of the actual one /usr/share/webapps/rutorrent

I'm glad to have finally found this out, it's been more than a year since I first had the issue: #1164

So, can I still submit a patch like proposed in 2. ? To add more robustness against such a config errors.

**Comment by Novik** [comment]
Yes, of course you can.
