### ISSUE TITLE
Unable to download/load torrents from URL

### ISSUE THREAD

**Issue by passthestyles** [Novik/ruTorrent#1464]
I have installed rtorrent 0.9.6/0.13.6 with ruTorrent 3.7 on Ubuntu 16.04.2 LTS

The issue is similar to this:
https://github.com/rakshasa/rtorrent/issues/553

Logs are empty, and it gives me the error as such:
> [2017-05-27 22:03:41] https://privatetracker.com/torrents.php?action=download&id=12345&authkey=MY_AUTH_KEY&torrent_pass=MY_TORRENT_PWD - Failed to add torrent. Can't retrieve URL.

This is after a brand new install of Ubuntu and rtorrent/rutorrent/etc.  (it was working before, and I just had to reinstall Ubuntu server and start over from scratch).  

Notes:

- This seems to affect some private trackers, not all.
- The same URL that doesn't load in rutorrent, loads fine in utorrent (via URL) on my home machine.
- The same URL also downloads a torrent just fine in any browser on my home machine (regardless of whether I am logged in or not, though it shouldn't matter as it has AUTHKEY and TORRENTPWD in the URL).
- wget -o torrent.torrent "URL" and curl -o torrent.torrent "URL" works fine (able to download the torrent) from seedbox with rutorrent installed
- autodl-irssi can download torrents just fine (not sure if related, but the irssi grabs the same URL)
- loading via Torrent Upload, or watch directory works fine (probably unrelated).
- Loading via URL in rtorrent itself works fine (so don't think it is a rtorrent issue, but that of rutorrent?)

Any help would be appreciated

**Comment by passthestyles** [comment]
Ok, I figured it out.

With the help of some people, I was able to narrow it down to the Snoopy class.

When Snoopy ran the exec command in PHP to execute the curl command, it would give me a curl error 56.

But if I ran the same curl command in the command line manually, it would run fine (and 2 files would be created as expected)

But I happened to run into another error with RSS, saying it could not load RSS feeds.

I ran into this:

https://github.com/Novik/ruTorrent/issues/1247#issuecomment-282255372

And, so I reverted back to an older version of Snoopy.

And voila, it fixed both the RSS issue, and this issue.

So there is definitely an issue with the Snoopy class.

**Comment by Novik** [comment]
I revert recent changes in Snoopy class, try to check result now, please.

**Comment by Bl0ub** [comment]
No, this version is not working as well. It throw an Error loading feed when trying to load an rss feed.
The only one which works for now is this one : 
http://s000.tinyupload.com/download.php?file_id=55052263713770627460&t=5505226371377062746065676

**Comment by passthestyles** [comment]
@Novik Thanks.  This looks to fix the issue too.  I was using the commit @ https://raw.githubusercontent.com/Novik/ruTorrent/36cdfc4cd92b5903c2f8bc8981ef05d3380d5b02/php/Snoopy.class.inc 

Something to note:  If I run the command manually in command line, with the "-0" flag, it works.  But php seems to error out with the error 56.  So not sure

@Bl0ub Are you sure?  This still loads the SSL RSS Feeds.  Also, make sure you aren't running into it caching either (sometimes, I would make changes to Snoopy, but it would still cache the old version)

**Comment by laitosko** [comment]
Tried both, changes by @Novik and the one linked by @Bl0ub. Can't get RSS feeds to load URL's anymore. With curl I am able to obtain feed content.

Any ideas? Just re-installed everything with 0.9.6/0.13.6 w/ v3.8

**Comment by tuxity** [comment]
I had exactly the same problem, and the issue wasn't related to rutorrent. 
My `/tmp` partition was full 😕
