### ISSUE TITLE
Running on a SSL host causes JavaScript error

### ISSUE THREAD

**Issue by a20eac1d** [Novik/ruTorrent#1465]
Latest ruTorrent version, running on a NGINX web server with all requests being redirected to a secure connection. Maybe it has something to do with me redirecting all traffic to the www-version?

ruTorrent error:
`[30.05.2017 15:08:14] JS error: [https://www.mydomain.com/rutorrent/js/content.js : 72] Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://www.mydomain.com" from accessing a cross-origin frame.`

NGINX configuration:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name mydomain.com;

        return 301 https://www.$server_name$request_uri;
}
```

**Comment by a20eac1d** [comment]
Console shows the error:

`Refused to display 'https://www.mydomain.com/rutorrent/php/addtorrent.php?result[]=Success&name[]=UDEMY_NGINX_BEGINNER_TO_ADVANCED_TUTORIAL-kEISO%20%5BIPT%5D.torrent&' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Comment by norrkin** [comment]
It's telling you what the error is.

In your config you have add_header X-Frame-Options "DENY";

Try changing it to SAMEORIGIN
