### ISSUE TITLE
torrent properties from plugins not always available after a9c6aed

### ISSUE THREAD

**Issue by xombiemp** [Novik/ruTorrent#1467]
In the rutorrentMobile project the array of torrent objects is retrieved using 
`theWebUI.requestWithTimeout("?list=1&getmsg=1",`
https://github.com/xombiemp/rutorrentMobile/blob/master/init.js#L967

The torrent properties from plugins, for example addtime and seedingtime from the seedingtime plugin, have always been a part of the torrent objects.

After this commit https://github.com/Novik/ruTorrent/commit/a9c6aed74cb1b3ba7d60b1c7513f46e3eec8869c it is inconsistent and most of the time the torrent objects do not contain the properties that are added by plugins. This is breaking some functionality in the mobile plugin, like sorting by add time and displaying the current ratio group.

How can I fix this plugin to account for the changes in this commit?

**Comment by Novik** [comment]
Sorry, but I don't know. This is your code.
IMHO you should to write something like

plugin.config = theWebUI.config;
theWebUI.config = function(data)
{
	plugin.config.call(this,data);
	// here your plugin initialization
}

**Comment by xombiemp** [comment]
Thanks for the suggestion.  I don't really understand what it is doing, but I wrapped the plugin.init() call in the code you provided and it is working like I would expect now.  Is this basically making the plugin.init() call wait for theWebUI to initialize completely or something?

**Comment by Novik** [comment]
This function (theWebUI.config) doing webui initialization. Some plugins overwrite it too. 
As result, for catching moment "all initialization of core and plugins is finished" you should
1) set plugin.runlevel in the plugin.info to the highest value
2) overwrite theWebUI.config and make initialization of your code after the call of parent.

**Comment by xombiemp** [comment]
Thanks for the help!  I was able to hack enough together to get it working again.
