### ISSUE TITLE
HTTP RPC api documentation

### ISSUE THREAD

**Issue by apollon-daedalus** [Novik/ruTorrent#1469]
Hi,

This is not necessarily for just the author, any info is helpful.

I am attempting to write an app that would interact with this HTTP RPC and I was curious if there is any documentation anywhere for this plugin's rest calls.

Thanks for your time.

**Comment by mariotacke** [comment]
Not exactly what you were asking but docs for the xmlrpc to rtorrent can be found here: https://github.com/mdevaev/emonoda/wiki/rTorrent-XMLRPC-Reference

**Comment by ArtyumX** [comment]
You can take this repo as example : https://github.com/v0l/rtorrent-json
