### ISSUE TITLE
Router Crash by ruTorrent

### ISSUE THREAD

**Issue by SomeoneElseHasMyName** [Novik/ruTorrent#1476]
Been using Rutorrent on my Synology 415+ for several years now.

On May 15th, my router started rebooting 10-15 times a day with no record in the log files. First I isolated the device, which turn out to be my NAS. So after turning off the various modules in Synology, I've isolated further to rutorrent. Disabling ruTorrent, the issue goes away.

Enabling rutorrent and it starts again.  I have uninstalled ruTorrent, rebooted, checked for malware, viruses, etc., and reinstalled rutorrent. Still the same issue, even though there are no torrents downloading or seeding.

Any assistance would be great!

**Comment by anoma** [comment]
Typically this results when a low end router exhausts some counter or table and cant gracefully handle the over run.

Torrents can consume quite a large number of  connections vs the actual used bandwidth all of which can stay open for a very long time exacerbating the situation.

Obviously this is a total guess given how hard this would be to debug and there are other scenarios that are more malicious but if it was me i would start there with wireshark.

**Comment by SomeoneElseHasMyName** [comment]
Thanks, worked out it was a particular tracker that was using port 1337 - removed and no issues for 2 days now.
