### ISSUE TITLE
"setsettings.php" flood request when scrolling in "Files" tab (and others) containing 100 and more lines/rows (IE and Chrome, no issue in Firefox)

### ISSUE THREAD

**Issue by Micdu70** [Novik/ruTorrent#1478]
Hello,

Everything was said in the title, except that this flood can freeze all other requests and errors like "The request to rTorrent has timed out" pops.

EDIT: Happening when there is 100 and more lines/rows.

Screenshots (Chrome Browser):

During scroll:
![setsettings-flood-during-scroll](https://user-images.githubusercontent.com/8136676/27785158-fef583d0-5fdc-11e7-9ed0-a7fdf3a06607.png)

After some seconds:
![setsettings-flood-after](https://user-images.githubusercontent.com/8136676/27785157-fef114da-5fdc-11e7-9a13-7cc14add3371.png)

And if too much "setsettings.php" request:
![setsettings-flood-timed-out](https://user-images.githubusercontent.com/8136676/27785159-ff1618e8-5fdc-11e7-9cbf-b85586fdb267.png)

**Comment by Micdu70** [comment]
Hm... I found a fix for this, please advise. ;-)

**Comment by Novik** [comment]
I hope, fixed.
