### ISSUE TITLE
Bad response from server: (200 [parsererror,getplugins]) SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by k3kz0r** [Novik/ruTorrent#1490]
Using rtorrent 0.9.4/0.13.4 on Ubuntu 16.04
ruTorrent version is a brand new git clone from today, 3.7 i think.
Apache2 as webserver.

I updated Apache2 and PHP (5.6) today to the newest versions (PHP 7) by using apt-get and since then, rutorrent gives me this error:
`[12.07.2017 10:39:57] WebUI started.
[12.07.2017 10:39:58] Bad response from server: (200 [parsererror,getplugins]) SyntaxError: Unexpected token <`

Reinstalling PHP and ruTorrent afterwards didnt help.
I have no userconfig files that could be misconfigured.

**Comment by Micdu70** [comment]
Hello,

This error means that PHP is not loaded (for ruTorrent files, or maybe all the files).

Try to enable the PHP module in apache like this: a2enmod enable php7.0
Then restart apache with: apachectl -k restart or apache2ctl -k restart, or with service / systemctl command

And refresh ruTorrent page with CTRL + F5 or clean the cache browser. ;)

**Comment by Merlincool** [comment]
I have got same issue, how do you suggest to do in ngnix? I am using php 7.0
