### ISSUE TITLE
lastest update

### ISSUE THREAD

**Issue by flier56** [Novik/ruTorrent#1500]
seeing this error after latest update
[Thu Jul 20 14:17:23 2017] [error]  PHP Fatal error:  Arrays are not allowed in class constants in /home/public/www/rutorrent/plugins/extsearch/engines/YggTorrent.php on line 17,

**Comment by Micdu70** [comment]
Hello, I recommend you update your PHP version to 5.6 or more. ;-)

**Comment by flier56** [comment]
ok thanks
