### ISSUE TITLE
Save path incomplete

### ISSUE THREAD

**Issue by pgera** [Novik/ruTorrent#1505]
In the latest version of rutorrent, the save path in the column as well as the general tab just shows the download directory, and not the entire path including the name of the downloaded file/directory. i.e., It shows something like /home/user/files/ instead of /home/user/files/foo.iso. Not sure if this is intentional. I think there should be at least some place where the entire path is displayed.

Screenshots in this issue: 
https://github.com/arakasi72/rtinst/issues/237

I think this was changed as a part of this commit:
https://github.com/Novik/ruTorrent/commit/84e6f7fcde31bce925ce0218c504d19e0744f205

**Comment by Micdu70** [comment]
"Entire path" = "Save path" + "torrent's name"  now, no ?
"Save path" = Where torrent's data is now (root location).

To me, I don't find any good reason to revert this commit.

**Comment by norrkin** [comment]
I'm still on v3.7 because of this.

Having that full path including the file name is great information to know.  I use it all the time to copy the path of the file and then use scp to grab the file.

**Comment by pgera** [comment]
>"Entire path" = "Save path" + "torrent's name" now, no?

Right now, there is no place where the entire path is displayed in the web ui (see screenshot). Also, entire path is not the same as save path + torrent's name. It should be save path + dir_name that torrent creates. Torrent can be foo.torrent that creates a directory bar. The save path should be /home/user/files/bar. The general tab in the web-ui is a good place to show that next to "Save As". As @norrkin said, this is very handy for copy paste for scp/rsync.

**Comment by Micdu70** [comment]
Are you okay to keep the "Save path" column, but revert back "Save as" info so? It's just one line to change. (in 'js/webui.js' - line 2166)

**Comment by pgera** [comment]
I don't think this is fixed yet. I still see the same result.

**Comment by pgera** [comment]
@Micdu70 , are you able to see the full path in any installation  ? AFAIK, this is not resolved yet.

**Comment by Micdu70** [comment]
@pgera 
- Torrent with one file: http://puu.sh/x98vp/092a0ac530.png
- Torrent with a directory: http://puu.sh/x98GU/40e5f993b2.png

**Comment by norrkin** [comment]
This has been working for me since @Micdu70 made this change https://github.com/Novik/ruTorrent/commit/8fc34959f91a6e6b99d0865fc36a50852e7cf3f9

**Comment by pgera** [comment]
Thanks. It looks like it was a cache issue. It works for me too.
