### ISSUE TITLE
throttle problem

### ISSUE THREAD

**Issue by boistordu** [Novik/ruTorrent#1508]
[https://github.com/Novik/ruTorrent/issues/1452](url)

`throttle: Plugin failed to start.`

I'm running last version and i've put this on my .rtorrent.rc 
`#upload_rate = 0
throttle.global_up.max_rate.set_kb = 300`

neither of them worked.
So what should I do? change the max speed in throttle.php ?

**Comment by Micdu70** [comment]
Hello, 

Why did you refer to #1452 issue?

You can remove "#upload_rate = 0" in .rtorrent.rc and keep only "throttle.global_up.max_rate.set_kb = 300".

What is your rtorrent/libtorrent version and how you installed them?
