### ISSUE TITLE
Updated RuTorrent, error until deleted YggTorrent.php

### ISSUE THREAD

**Issue by EnduringGuerila** [Novik/ruTorrent#1509]
I had v3.7 and updated everything to v3.8

I found in the error log something like:
'plugins/extsearch/engines/YggTorrent.php unable to load arrays'

I do not have the exact error anymore. Once I deleted YggTorrent.php and launched rutorrent successfully, the error log was deleted.

**Comment by Micdu70** [comment]
=> #1500
