### ISSUE TITLE
Configure /plugins/diskspace

### ISSUE THREAD

**Issue by EnduringGuerila** [Novik/ruTorrent#1511]
This is not really an issue. 
I am trying to set this to show how much space is left on my raid array instead of my other internal drive (it isn't even showing my system drive).

The documentation doesn't really explain how to modify this conf and I am not very familiar with PHP.

**Comment by EnduringGuerila** [comment]
https://github.com/Novik/ruTorrent/wiki/PluginDiskspace

This isn't particularly helpful either

**Comment by TMTYD** [comment]
Hi

So under /conf/conf.php at topDirectory you set your download directory, in the folder /plugins/diskspace/conf.php, there you put under $ partitionDirectory your Raid or HDD
