### ISSUE TITLE
Include a "tracker message" column

### ISSUE THREAD

**Issue by lostnihilist** [Novik/ruTorrent#1521]
Obviously a feature request. When there are a lot of torrents with error messages from the tracker, it would be nice to be able to see a lot of them at once and sort by the message to be able to more easily take bulk actions on the basis of the message. Of course, this field would typically be blank when torrents do not have any errors

**Comment by Micdu70** [comment]
You can juste add this line: https://github.com/Micdu70/ruTorrent/commit/21a1d75d0d4dac2d19ceaac9e7c27edb426847e2

**Comment by C74K** [comment]
dont work this method

**Comment by Novik** [comment]
If you need a tracker message column, then you may to write your own plugin for that.
