### ISSUE TITLE
Ban option should be for all torrents.

### ISSUE THREAD

**Issue by drmike** [Novik/ruTorrent#1524]
Greetings:

This may open some discussion on the topic with both pros and cons on it and I realize that.

Going under the Peers tab for a torrent, a right click -> ban on an IP address only bans that peer for that single torrent.  I feel that it should be an across all torrents ban.

I have a very lengthy explanation as to what's occurring that I can add but don't feel it's necessary.  Be happy to if that's needed.  Long story short I have a single peer trying to download 23 torrents at the same time from a private tracker and they know they're supposed to be doing this one at a time.

Thank you for your time,
-drmike

**Comment by Novik** [comment]
Sorry, but this is a rtorrent issue. ruTorrent is a WebUI, and it can't to correct the behavior of client.
