### ISSUE TITLE
rutorrent with modern frontend framework

### ISSUE THREAD

**Issue by colinhd8** [Novik/ruTorrent#1525]
First thanks for the great project, i really love it. 

And does there have a plan to rewrite rutorrent with modern frontend framework? If so, it will so cool. 

Of course there will have many many work to do.  Hope someday it will become truth.

**Comment by tynan-cr** [comment]
Check this out https://github.com/jfurrow/flood

**Comment by colinhd8** [comment]
Oh, good news. Thank you for share the useful information. @tynan-cr
