### ISSUE TITLE
Offset between table header data content e.g. Ratio/day contains added date

### ISSUE THREAD

**Issue by tuxayo** [Novik/ruTorrent#1528]
After updating to v3.x-git~68a94d97 r2030 2017-08-10 I've got the following issue.

Ratio/day contains added date.
Ratio/week contains the Ratio/day data. Ratio/month data is in the DOM, but not visible.
The coloring is offset and doesn't match the columns. (nice new feature BTW!)

![screenshot_2017-08-13_00-53-37](https://user-images.githubusercontent.com/2678215/29244788-1a6503b6-7fc2-11e7-956f-20b619e6d845.png)

When adding the "Added" column, the table is consistent. (except for the coloring)
![screenshot_2017-08-13_00-53-52](https://user-images.githubusercontent.com/2678215/29244789-1e2bd36c-7fc2-11e7-9628-0cdbd4b5580b.png)

When I remove the "Added" column, the table stay consistent until the next update. Few seconds later it got back to the state of the first screenshot.

**Comment by Micdu70** [comment]
Don't have this issue...
And there is no ratio coloring feature with included/official plugins of ruTorrent.
Check in "Plugins" tab, where you can disable the 3rd party plugin that causes this issue. ;-)
