### ISSUE TITLE
using $_SERVER['PHP_SELF'] does not honor $topDirectory

### ISSUE THREAD

**Issue by thewisenerd** [Novik/ruTorrent#1533]
in a similar issue to https://github.com/Novik/ruTorrent/issues/1530

using ```dirname($_SERVER['PHP_SELF'])``` with ```$topDirectory``` configuration causes 404 errors when ruTorrent/ isn't actually present in ```$topDirectory``` and server handles requests ( see linked issue for more details ).

This is being used in four places;

https://github.com/Novik/ruTorrent/blob/master/plugins/source/action.php#L13
https://github.com/Novik/ruTorrent/blob/master/plugins/data/action.php#L33
https://github.com/Novik/ruTorrent/blob/master/php/addtorrent.php#L99
https://github.com/Novik/ruTorrent/blob/master/plugins/feeds/action.php#L111

By far, I've only run into 404's on addtorrent.php ; (because I've only used it) but there's a possibility that 404's might be triggered on othes too.

```
192.168.1.xx - - [xx/Aug/2017:xx:xx:xx +xxxx] "GET /php/addtorrent.php?result[]=Success&name[]=xxx& HTTP/1.1" 404 38
```

@Micdu70 used relative paths to fix #1530 ; which might be applicable in these cases too.

**Comment by Micdu70** [comment]
Hello (again ^^),

https://github.com/Novik/ruTorrent/blob/master/plugins/feeds/action.php#L111 = should not be a problem.

Others files are fixed in PR #1534 ;)
