### ISSUE TITLE
Add a loginmgr for Yggtorrent

### ISSUE THREAD

**Issue by Paulli42** [Novik/ruTorrent#1536]
Hi !

I would like to help adding Yggtorrent to the loginmgr since cookies expire after 2 hours and the next visit using a browser invalidate the session_id.
I modified the loginmgr account from torrentleech for something I think should work, but now I need to tell extsearch that it should login before searching. I didn't find out how I can do that, I only found mention of the cookie in the file for yggtorrent.

Does anyone have an idea how to make it work ?

[YggTorrent.txt](https://github.com/Novik/ruTorrent/files/1253502/YggTorrent.txt)

**Comment by Matthe95** [comment]
Hello,

I'm sorry, I can't help you.

Have you find any solution?

**Comment by Novik** [comment]
> Does anyone have an idea how to make it work ?

First of all you should change line 
```
public $defaults = array("public" => false, "page_size" => self::PAGE_SIZE, "cookies" => "yggtorrent.com|ci_session=XXX");
```
to 
```
public $defaults = array("public" => false, "page_size" => self::PAGE_SIZE, "cookies" => "auth"=>1);
```
in the search engine.

**Comment by Matthe95** [comment]
Still an error on my side but wait him because I'm not sure is that I do everything correctly.

I have changed the two files like he said and I like you say.

**Comment by Micdu70** [comment]
I try on my side to do this and I don't succeed too...

**Comment by Arakmar** [comment]
I'm a bit late but I implemented that a while ago with some hacks due to loginmgr limitations but it's working. I'll try to clean up my code a bit and do a PR soon.

Anyway, it's currently totally broken because of Cloudflare, there are working workarounds but I don't think it's mergable ;)

**Comment by Matthe95** [comment]
any news @Arakmar ?

**Comment by Arakmar** [comment]
Sorry I was a bit busy last week.
It just needs some more tests and it'll ready, so probably in the next days !

**Comment by Matthe95** [comment]
Ok thanks :)

**Comment by Arakmar** [comment]
I think we can now close this one :)

**Comment by Matthe95** [comment]
Yes :)

Thanks a lot to you.
