### ISSUE TITLE
Issue With Extsearch Latest Update

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1537]
I upgraded Rutorrent to the latest version from Github but rutorrent no longer loads and the message below appears.

Bad response from server: (500 [error,getplugins]) Internal Server Error

Once I remove the Extsearch plugin rutorrent then rutorrent loads without any issue.

Taken from Apache error log.
PHP Parse error:  syntax error, unexpected '.', expecting ')' in /var/www/rutorrent/plugins/extsearch/engines/YggTorrent.php on line 9, referer: https://mydomain.com/rutorrent/

OS : Debian 7 64bit
Web Server: Apache/2.2.22 
PHP Version: PHP 5.4.45-0+deb7u10

**Comment by Pingblue** [comment]
Just removing the /var/www/rutorrent/plugins/extsearch/engines/YggTorrent.php file appears to resolve the issue.

**Comment by Novik** [comment]
Try now,

**Comment by Pingblue** [comment]
Yes that solves the issue, thanks

**Comment by Matthe95** [comment]
I can't download with ygg with le last update.

My cookie is like that yggtorrent.com|ci_session=********************************;

My account on ygg works.

any idea?

**Comment by Novik** [comment]
See #1536

**Comment by Matthe95** [comment]
Okay, so, there is no solution available yet?

I will follow #1536 because I'm not very good to help.

Thanks
