### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by richardsky** [Novik/ruTorrent#1538]
After using ruTorrent effectively for several years I am no longer getting any torrent search results.
I have restarted the service on seedboxco.net but still no results.
Any help with this would be most appreciated.

**Comment by foppkn** [comment]
I am having same issue. I also hsbe bern using rutorrent successfully for many years. Pls fix issue.

**Comment by Pingblue** [comment]
The issue is related to the majority of public trackers going offline, the public tracker list needs updating in extsearch but there are not many left.

rarbg.to should be added.

**Comment by Micdu70** [comment]
> rarbg.to should be added.

It's seams impossible to add it because this site is using a "strong" browser checker. The only way is to use their API (torrentapi.org) but... good luck to add it in ruTorrent.

**Comment by Banksy07** [comment]
Any update on above please? This has gone on for way too long now.

**Comment by Pingblue** [comment]
Not really much anyone can do if the public trackers are not available.

The private trackers work well in Extseach, Couchpotato and Sonarr are also options.

**Comment by Banksy07** [comment]
Thank you for the update, but how can I use an alternative torrent search  and also how can I download my torrents on Seedboxco please?

Sent from my iPhone

On 2 Sep 2017, at 17:27, Pingblue <notifications@github.com<mailto:notifications@github.com>> wrote:


Not really much anyone can do if the public trackers are not available.

The private trackers work well in Extseach, Couchpotato and Sonarr are also options.
