### ISSUE TITLE
Suggestion: Duplicate Button

### ISSUE THREAD

**Issue by theskyishigh** [Novik/ruTorrent#1541]
Pardon the intrusion, but since the forums (http://forums.rutorrent.org/) seem to be offline, I thought this might be the next mort appropriate place for a suggestion/request.

Has someone considered adding a "duplicate" button next to the "Add" and "Delete"buttons in the RSS Manager? It would make setting up RSS rules much easier.

With my limited understanding of PHP/CSS/HTML, I have figured out what would need to be done, but it would take me a very long time to do it. Could someone else please add this functionality?

**Comment by Novik** [comment]
In RSS manager you can't have two feeds with a same URL. 
Please, describe case of usage of this feature.
