### ISSUE TITLE
Is this work on older pc

### ISSUE THREAD

**Issue by alixcan** [Novik/ruTorrent#1547]
Hi,

I have 10 years old pc with p4 cpu and 2 gb ram,
Is it possible to work with cent-os or ubuntu ?

Can you give me hint ?

Thanks

**Comment by Novik** [comment]
It works on my router Asus RT-N16. This is a very old PC ;)

**Comment by alixcan** [comment]
I have Airties 5650 modem / router how could i install on that :)
