### ISSUE TITLE
Bottombar Torrentport shows orange, no explanation.

### ISSUE THREAD

**Issue by hagabla** [Novik/ruTorrent#1548]
Since today the torrent port indicator in the bottom bar shows an orange warning signal with no explanation. I get what green and red means, but orange? The wiki says nothing about it.

**Comment by Micdu70** [comment]
Orange = The port checker website did not respond...
A recent git commit (8 days ago: https://github.com/Novik/ruTorrent/commit/3024e8f8dbfce2e9d7b26b8abfefc95a5f41846b#diff-74b8c69f5102c8f5eafd8ba5a4e9e8f4 ) helps to avoid that state.

**Comment by hagabla** [comment]
That's what I thought, thank you! Could maybe do a mouseover popup thingie? When it's red/green you can mouseover.

**Comment by Micdu70** [comment]
It should display "$port_number: Port status is unknown" if no response, actually.

**Comment by hagabla** [comment]
Did not for me.

**Comment by Novik** [comment]
> Did not for me.

This means: port checking is in process; in this stage we have not information about port number and it's status. And, as result, we can't to show something.
