### ISSUE TITLE
ruTorrent 3.8 doesn't take Torrents Files over 1MB

### ISSUE THREAD

**Issue by kogoromori** [Novik/ruTorrent#1550]
Hi There,

im using rtorrent 0.9.6 with rutorrent 3.8 together with nginx.
i can't add Torrents with an filesize of 1MB or higher, i don't get any error-msg. it just don't add anything.

i already changed those lines in my active php.ini:
`upload_max_filesize = 64M
max_file_uploads = 200
post_max_size = 128M`

restarted nginx after that, but it doesn't change anything.
hope somebody can help.

**Comment by Novik** [comment]
Possible reasons of this:
1) ruTorrent and rtorrent are placed on the different hosts. Or
2) Something bad with your .torrent file. In this case I need it for saying something.

**Comment by Pingblue** [comment]
As far as I know XMLRPC protocol has a 1MB limit

Torrents over 1MB in size need to be uploaded through FTP or another method to a watch folder.

Torrents of this size are rare and normally due to a small piece size being used when creating the torrent.

**Comment by Novik** [comment]
> As far as I know XMLRPC protocol has a 1MB limit

This is a limit for request size. In this case ruTorrent will operate with a file name (.load) instead file contents (.load_raw).
But this can't be done, when ruTorrent and rtorrent are placed on the different hosts.

**Comment by milesbenson** [comment]
ruTorrent and rtorrent are placed on the same host in my case, but i cant add torrents over 1mb either. This was no problem with 0.9.7.
