### ISSUE TITLE
cachedEcho extremely slow due to / full & gzip -> Performance improvement possibility

### ISSUE THREAD

**Issue by PulsedMedia** [Novik/ruTorrent#1551]
getPlugins.php was not loading on a machine with low load, but / filesystem full.

Issue was traced to cachedEcho gzip routines. I guess a check for disk full should be implemented.

It probably happens because of the use of a temp file and passthru to shell execute compressing the data!

PHP has built-in function for this, and you do not need to write it to a file first: http://php.net/manual/en/function.gzcompress.php

Should also probably contain a filesystem check if there is free disk space AND option to do in /dev/shm (directly within ram!) instead.

For example do this in getTempDirectory:

if (file_exists('/dev/shm') && is_writable('/dev/shm')) return '/dev/shm';   // return SHM as the temp directory

Further if i recall right lighttpd, apache etc. can do ALL of the function contents automagicly if configured to / sysadmin wants to.

To compress data content size should be configurable too, 2KiB sounds a bit lowish these days, and should more be in the ballpark of 16KiB.

**Comment by Novik** [comment]
> PHP has built-in function for this,

This is not "built-in function" This is extension. And this extension may be absent.

> Should also probably contain a filesystem check

If you disk is full - you are fucked up. And troubles with a function cachedEcho in this case will be one of last things for you.

> Should also probably contain a filesystem check if there is free disk space AND option to do in /dev/shm (directly within ram!) instead.

You always wellcome with a corresponding pull request.

**Comment by PulsedMedia** [comment]
You can check if it exists first, then use built-in, if not, then use external. Also you do not need to save it first as a file, you can just get the data from stdin :)

> If your disk is full - you are fucked up. And troubles with a function cachedEcho in this case will be one of last things for you.

It is a simple fix, but this slow down should not happen, at the very least it should throw an error "Disk full", or simply stop execution there, or preferrably skip the compression.

> You always wellcome with a corresponding pull request.

You want me to make an patch for you? That'd be first, link me to process details (i have not directly contributed code in the past). This should be an quick 10min job.

**Comment by Novik** [comment]
> That'd be first, link me to process details

Try to read something about github and it functionality. Forking, pull requests etc.
