### ISSUE TITLE
RSS:  Error loading torrent. 

### ISSUE THREAD

**Issue by kisaragiHiyo** [Novik/ruTorrent#1554]
rTorrent 0.9.2/0.13.2
ruTorrent dev v3.8-75

The rss feed url is 
[http://sukebei.nyaa.si/?page=rss&c=1_4&f=0](url)
After adding it to rss feed , some items " Error loading torrent. " 
[19.09.2017 19:08:24] Error loading torrent. (https://sukebei.nyaa.si/download/2355658.torrent)

![Image of Yaktocat](https://i.imgur.com/Hh2AVYL.png)

**Comment by Micdu70** [comment]
That's not a RSS issue, this link doesn't work itself in ruTorrent. (so rtorrent?)

I don't understand why...

**Comment by kisaragiHiyo** [comment]
Thanks for your reply!
I contacted to the admin of nyaa.si. And he said add the "&magnets" to the end of feed url can get the magnet URL in RSS.
Now, although I still don't konw the reason why some of the ".torrent" URLs can't work It works well!
Thank you!

**Comment by Novik** [comment]
Fixed.
