### ISSUE TITLE
AutoMove Move twice the same file.

### ISSUE THREAD

**Issue by ascodeur** [Novik/ruTorrent#1557]
AutoMove Move twice the same file to the configured finished download path.

My default download directory is on the local server (ie. /home/rtorrent/torrents).
I don't set "hash checking after download".

On download finish,  automove send the file to a netwok (smb) finished folder. (ie. /nas/media)

But when sending file is finish, automove send egain the same file overwriting before completing moving .

So, it took twice the time to move a file.

Perhaps it can help, I configured a ratio group to only remove file on webui when download finish after some upload ratio. (not remove data).

**Comment by Novik** [comment]
Paste here your rtorrent.rc, please.

**Comment by ascodeur** [comment]
scgi_port = 127.0.0.1:5001
encoding_list = UTF-8
port_range = 45000-65000
port_random = yes
check_hash = no
directory = /home/torrentuser/torrents
session = /home/torrentuser/.session
encryption = allow_incoming, try_outgoing, enable_retry
schedule = watch_directory,1,1,"load_start=/home/torrentuser/watch/*.torrent"
schedule = untied_directory,5,5,"stop_untied=/home/torrentuser/watch/*.torrent"
schedule = espace_disque_insuffisant,1,30,close_low_diskspace=500M
use_udp_trackers = yes
dht = off
peer_exchange = no
min_peers = 40
max_peers = 100
min_peers_seed = 10
max_peers_seed = 50
max_uploads = 15
max_downloads_global = 4
execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php torrentuser &}

**Comment by sparky3387** [comment]
I had this exact same issue, it was caused by there being two users with AutoMove enabled, deleting the unused user and restarting rtorrent fixed the issue
