### ISSUE TITLE
guide to using PluginAutotools?

### ISSUE THREAD

**Issue by newdietpi** [Novik/ruTorrent#1558]
I need helping figuring out how to set labels for certain trackers so I could auto move when completed to folders such as Movies, TV etc.

**Comment by Dam4rusxp** [comment]
There's this wiki page which explains a lot: https://github.com/Novik/ruTorrent/wiki/PluginAutotools

I do have a question which isn't explained there however. What format does the content of the "Skip torrents that contain files matching pattern" field need to have? Should that be regex like the one above? I's like to exclude all rar files using that.

**Comment by Novik** [comment]
All patterns are regex.
