### ISSUE TITLE
Errors in rutorrent log.

### ISSUE THREAD

**Issue by rtorrentuser** [Novik/ruTorrent#1560]
[26.09.17 09:40:37] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data>
<value><struct><member><name>methodName</name><value><string>throttle.global_up.max_rate.set</string></value></member><member><name>params</name><value><array><data>
<value><string></string></value>
<value><string>343539712000</string></value>
</data></array></value></member></struct></value>
<value><struct><member><name>methodName</name><value><string>throttle.global_down.max_rate.set</string></value></member><member><name>params</name><value><array><data>
<value><string></string></value>
<value><string>343539712000</string></value>
</data></array></value></member></struct></value>
</data></array></value></param></params></methodCall>
[26.09.17 09:40:37] Status: 200 OK
Content-Type: text/xml
Content-Length: 610

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><array><data>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Throttle rate must be between 0 and 2^30.</string></value></member>
</struct></value>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Throttle rate must be between 0 and 2^30.</string></value></member>
</struct></value>
</data></array></value></param>
</params>
</methodResponse>

Presumably something is wrong in
https://github.com/Novik/ruTorrent/commit/55542352db03f3e1c0dc94f899dc20c73296c293#diff-813bf8295a271be03f7a0fe797ee4697

**Comment by Novik** [comment]
Please, paste content of log in a normal form. Use triple backticks (```) for this.

**Comment by rtorrentuser** [comment]
```
[26.09.17 12:01:42] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data>
<value><struct><member><name>methodName</name><value><string>throttle.global_up.max_rate.set</string></value></member><member><name>params</name><value><array><data>
<value><string></string></value>
<value><string>343539712000</string></value>
</data></array></value></member></struct></value>
<value><struct><member><name>methodName</name><value><string>throttle.global_down.max_rate.set</string></value></member><member><name>params</name><value><array><data>
<value><string></string></value>
<value><string>343539712000</string></value>
</data></array></value></member></struct></value>
</data></array></value></param></params></methodCall>
[26.09.17 12:01:42] Status: 200 OK
Content-Type: text/xml
Content-Length: 610

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><array><data>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Throttle rate must be between 0 and 2^30.</string></value></member>
</struct></value>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Throttle rate must be between 0 and 2^30.</string></value></member>
</struct></value>
</data></array></value></param>
</params>
</methodResponse>
```

**Comment by Novik** [comment]
Fixed, try now.

**Comment by rtorrentuser** [comment]
No errors now. Thanks!
