### ISSUE TITLE
torrent deleted whene tracker edited

### ISSUE THREAD

**Issue by aminomaboul** [Novik/ruTorrent#1565]
hi,
can you guys tell us when the issue  #1072 will be cleared
it's hanging from 2015
i've got my download stoped because of my ratio, when i changed the privet key, everything has gone
you're doing a great job
thanks in advance
regards

**Comment by aminomaboul** [comment]
sorry,
i don't know how but i added the letter 'y' to my P.key
that's why the download couldn't restart
just want to tell you it work fine for me, the torrent was added within the rutorrent GUI
i use rutorrent V3.8
you can close the issue #1072 once and for all ;)
thanks

**Comment by eramdam** [comment]
Sorry to bump such an old topic but I'm having the same issue:

- adding a torrent with ruTorrent
- trying to edit the tracker of it, the edition seems to work (no erors in the Log tab nor in the log files)
- the torrent completely vanishes from the UI, never to be found again

Is that feature supposed to work on the current `master` branch or am I using it in a wrong way? 😕
