### ISSUE TITLE
Add a torrent either dragging or using Add button, fails

### ISSUE THREAD

**Issue by dofino** [Novik/ruTorrent#1566]
Hello, rutorrent acknowledged the torrent with a green message but torrent did not start; nothing happened. Only one file from Cinemageddon gave me this issue.
I have a server from tal0ne and everything is going fine.
I tried to attach the file to this message but it is a torrent file, hence, not supported here.
Any clue ? Thanks in advance.

**Comment by Micdu70** [comment]
Hello,
First: Never give .torrent file from private tracker, in public!
If you see the torrent in rutorrent's torrent list, then rutorrent is working fine but it should be rtorrent related issue.
If you want, I would like to try your .torrent file on my rutorrent seedbox.

**Comment by dofino** [comment]
I forgot to say I am already cross-seeding the movie, "La fille de Dracula",  on 2 different private trackers. The torrent file, the 3rd one, came from CG, another private.

I've been cross-seeding on 3 different trackers with no problem. Could it be a bug with CG ?

Opened a ticket at tal0ne but as they did not create rutorrent they said, I was redirected to your site

Her's the file, attached.

Thanks for taking the time to response to my demand.

________________________________
De : Micdu70 <notifications@github.com>
Envoyé : 10 octobre 2017 08:49:33
À : Novik/ruTorrent
Cc : dofino; Author
Objet : Re: [Novik/ruTorrent] Add a torrent either dragging or using Add button, fails (#1566)


Hello,
First: Never give .torrent file from private tracker, in public!
If you see the torrent in rutorrent's torrent list, then rutorrent is working fine but it should be rtorrent related issue.
If you want, I would like to try your .torrent file on my rutorrent seedbox.

**Comment by Micdu70** [comment]
Didn't receive attached file, I think it doesn't work by security, on
GitHub.

Send the .torrent to: Micdu70@gmx.fr

2017-10-10 19:02 GMT+02:00 dofino <notifications@github.com>:

**Comment by dofino** [comment]
I'll removed extension from the file and you will only have to rename it with "torrent" extension.


If it does not work, forget about it; not cross-seeding a torrent from CG will not be the end of the world.


Many thanks for your time.

________________________________
De : Micdu70 <notifications@github.com>
Envoyé : 10 octobre 2017 13:37:41
À : Novik/ruTorrent
Cc : dofino; Author
Objet : Re: [Novik/ruTorrent] Add a torrent either dragging or using Add button, fails (#1566)

Didn't receive attached file, I think it doesn't work by security, on
GitHub.

Send the .torrent to: Micdu70@gmx.fr

2017-10-10 19:02 GMT+02:00 dofino <notifications@github.com>:

**Comment by Micdu70** [comment]
Torrent has been added successfully, torrent is working if "Cross-seeding" is NOT ticked. If ticked, tracker gives this error: "Torrent not registered with this tracker (04)".

**Comment by dofino** [comment]
Strange, because I've been cross-seeding many files on that sever. So, it is certainly not ticked in server's settings. I've renounced to find a solution as it only happened once.

Thanks for having checked that file for me.

________________________________
De : Micdu70 <notifications@github.com>
Envoyé : 9 novembre 2017 15:21:59
À : Novik/ruTorrent
Cc : dofino; Author
Objet : Re: [Novik/ruTorrent] Add a torrent either dragging or using Add button, fails (#1566)


Torrent has been added successfully, torrent is working if "Cross-seeding" is NOT ticked. If ticked, tracker gives this error: "Torrent not registered with this tracker (04)".
