### ISSUE TITLE
problem interface on Safari

### ISSUE THREAD

**Issue by Matthe95** [Novik/ruTorrent#1572]
Hello,
I have a problem that appeared in safari very recently. I would say during the last update. It's a problem with interface. As it is quite complicated to explain and that I am not very good in English, I join you a screen.
I do not have the same problem on chrome.
I'm using Safari 10.0.3 on OS X 10. 12.

<img width="473" alt="capture d ecran 2017-10-30 a 21 40 21" src="https://user-images.githubusercontent.com/22984481/32194546-f9ca16dc-bdba-11e7-8e8c-fb1cc370603e.png">

An idea to fix that?

Thanks :)

**Comment by Novik** [comment]
> An idea to fix that?

No. Safari is unaccessible for me. May be, somebody from collaborators?

**Comment by igorkas** [comment]
Dealing with the same issue here. Same instance renders properly in Chrome though...
Any collaborators able to help?

**Comment by DjKiDD** [comment]
I too suffer from rendering issues as described for columns

**Comment by milesbenson** [comment]
same issue here in v3.8
no issue with v3.7

**Comment by milesbenson** [comment]
copied over all js from old version and now everything is working again. i guess https://github.com/Novik/ruTorrent/issues/1478 is the problem.

**Comment by herve88** [comment]
Thank you j have the same problem how I can adjust thanks

**Comment by Novik** [comment]
I made several changes, please, check.

**Comment by xombiemp** [comment]
That fixed it for me.  Thanks!

**Comment by milesbenson** [comment]
Thanks, is working great with the new change 👍
