### ISSUE TITLE
Spectrogram plugin

### ISSUE THREAD

**Issue by maximuml** [Novik/ruTorrent#1576]
Hi! Where you can find Spectrogram plugin? Thanks!

**Comment by Novik** [comment]
This plugin was written by private request of @alexcoe .
In theory I can include this plugin to the public repo, but in practice I need his permission.

**Comment by maximuml** [comment]
It was available for free on http://rutorrent.org/svn/spectrogram/trunk 
a long time ago

**Comment by Novik** [comment]
Added, check result.
