### ISSUE TITLE
Automove why relative directory

### ISSUE THREAD

**Issue by jgwallace3** [Novik/ruTorrent#1577]
From the description of automove: "The downloaded torrent data files are transferred to the directory, which is set in configuration, with the **same directory structure relative to directory specified in variable directory** of rtorrent.rc file and then started for seeding."

Why? If I download to **~/downloads/incoming** and based on label want to copy (via automove) to **~/sync**, it doesn't work and I don't understand why it's not supported?

**Comment by PrinterElf** [comment]
Agree on this - please add an option to disable the relative path check.
`//------------------------------------------------------------------------------
// !! this is a feature !!
// ($rel_path == '') means, that $base_path is NOT a SUBDIR of $directory at all
// so, we have to skip all automove actions
// for example, if we don't want torrent to be automoved - we save it out of $directory subtree
//------------------------------------------------------------------------------`

If I don't want at torrent to be moved automatically, then I don't give it a label which is going to get caught by automove.
