### ISSUE TITLE
Spectogram plugin no loaded

### ISSUE THREAD

**Issue by notojak** [Novik/ruTorrent#1581]
> [14.11.2017 18:30:10] spectrogram: Plugin will not work. rTorrent user can't access external program (sox).

The SOX program is installed on my system.

Platform: Debian 9
ruTorrent 3.8
rtorrent 9.6.0

**Comment by Micdu70** [comment]
Was fixed 10 hours ago. Update your rutorrent installation with git command. =)

**Comment by notojak** [comment]
ok, thank You, works fine
