### ISSUE TITLE
Select files Before Download

### ISSUE THREAD

**Issue by sayroni** [Novik/ruTorrent#1583]
hi.
i want select my Favorite file from files of  a torrent before download and only downlaod them like utorrent.
please help and check this...

**Comment by Micdu70** [comment]
Hello, just do these steps:

1) In "Add Torrent" window, tick "Don't start torrent automatically". Then add torrent with a torrent file or an URL.
2) Select added torrent in ruTorrent, click on "Files" tab below. Select one - or more with 'CTRL' key - file(s)/folder(s) you want to NOT download.
3) Right-click on selected file(s)/folder(s) > Priority > Don't Download
4) "Start" the torrent and voilà! :)

**Comment by sayroni** [comment]
thanks - but download 1 or 2 kb of files when select DONT download and calculate whole of files size and waste my HDD !

**Comment by Micdu70** [comment]
It's a rtorrent issue, check this: https://github.com/rakshasa/rtorrent/issues/588
