### ISSUE TITLE
Torrent goes to pausing state when torrent is automoved

### ISSUE THREAD

**Issue by phrozen2** [Novik/ruTorrent#1585]
When using Auto Tools, upon completion of the download the torrent data is moved and the torrent re-added but for some reason, autotools is not able to follow the new path.

Whenever it re-adds the torrent, it goes to Pausing state and shows the path as /dev/sdt1 23139(random string of numbers)/home/username/downloads/

not sure why this is happening as permissions are correct on the folders.

This only ever happens sometimes and is not consistent.

**Comment by sn1124** [comment]
I'm having the same issue. Happens maybe 1 out of every 10 times. However, it happens on torrents that don't match the filter either. I'm using the label filter: "/(series|movies)/i" which I got from a YouTube video. Maybe that has something to do with it? I'm going to try just "/series|movies/"
