### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'rTorrent' of undefined" while rtorrent is running

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1588]
rtorrent seems to be running okay and my torrents are reporting without issue but when I access the web interface, the torrents aren't visible and when I click on any of the "State" links, I get "Uncaught TypeError" issues in the logs.

Running Ubuntu 17.10

EDIT: It seems that I can still add torrents successfully but I can't see the status of anything within rtorrent. I'm assuming this is a configuration that needs to be pointed to the right place but I'm not sure where.

**Comment by stumpylog** [comment]
Were you ever able to resolve this issue?

I'm on ruTorrent v3.8 and rTorrent 0.9.6 and am seeing something very similar

**Comment by jimwald1221** [comment]
I had to reinstall but I believe it was because I also installed php7.1 and
it took over a bunch of things instead of 7.0.
