### ISSUE TITLE
File priority is not reset when torrent is deleted

### ISSUE THREAD

**Issue by baz357** [Novik/ruTorrent#1589]
Let's say there's a big torrent where only a few files were downloaded:

- remove torrent (and delete data)
- add the same torrent again with the "Don't start the download automatically" option
- check the "Files" tab for that torrent and you'll see that the previous file priority is still visible, it even looks like the files are still there

Would be great if this could be fixed! :)

**Comment by Novik** [comment]
I hope, this fixed, check please.

**Comment by baz357** [comment]
Sadly, I can't check this, I'm still on v3.7. :( Maybe I should ask my seedbox provider for an update...

P.S.: I noticed that versions 3.7 and 3.8 are not mentioned on https://github.com/Novik/ruTorrent/wiki/Versions
