### ISSUE TITLE
Display of DL/ UL rates

### ISSUE THREAD

**Issue by baz357** [Novik/ruTorrent#1591]
The speed seems to be calculated as an average of the last x seconds. I often find the displayed values to be confusing. I suggest to drop the amount of seconds used for this calculation, and to maybe even drop the calculated/displayed value to zero if the torrent/ all selected files have been downloaded fully.

**Comment by Novik** [comment]
ruTorrent is a not bittorrent client. ruTorrent is a WebUI for bittorrent client. As result, ruTorrent doesn't calculate speed.
If client say 'we have non-zero UL/DL speed for this torrent' then ruTorrent will show corresponding value.

**Comment by baz357** [comment]
Oh, yes, that makes sense!
