### ISSUE TITLE
Searching option adds after a while random torrents in the list

### ISSUE THREAD

**Issue by ylzhan** [Novik/ruTorrent#1594]
Hello,

Sorry if it's a dupe issue and also sorry for the title for the issue. English is not my first language. So correct me if needed.

Info : rutorrent 3.6 with rtorrent 0.9.6

When I search in torrent list on rutorrent it gives the correct list but after a while rutorrent begins to add random torrents (not all of them but only few like 2-3) that have nothing to do with the search keyword.

**Comment by Novik** [comment]
1) Current version of ruTorrent is 3.8. Ascient versions are not interesting for me.
2) Sorry, but I can't understand - what is you mean. Please, check your issue on the 3.8 and try to write more details. May be, screenshots will helps?

**Comment by ylzhan** [comment]
Basically when I was searching for something, ruTorrent showed me the relevant torrents but after few seconds it started to add random torrents in the results.

New version of rutorrent is not impacted by this issue.
I guess this issue can be closed.
