### ISSUE TITLE
PROPOSAL for new plugin: "auto-remove torrents"

### ISSUE THREAD

**Issue by baz357** [Novik/ruTorrent#1598]
Not sure where to propose a new plugin, hope here is a good place.

This new plugin would have these settings:
- minimum free HD space to keep
- torrent label(s) where torrents are auto-removed (and deleted)
- delete criteria: oldest/ newest first

This way, you would never run out of HD space while helping to seed lots of torrents, even when not keeping an eye on your seedbox.

**Comment by amlopin** [comment]
+1

**Comment by Rick7C2** [comment]
There is a plugin for Deluge called Auto Remove Plus.
https://forum.deluge-torrent.org/viewtopic.php?t=47243

It would be awesome if rutorrent had a plugin like that!

**Comment by SteveMalso** [comment]
http://www.torrent-invites.com/seedbox-tutorials/302161-autodl-irssi-enhancement-check-imdb-rating-disk-space-b4-downloading-torrent.html
