### ISSUE TITLE
Get File feature not allowing segmented downloading in 3.8

### ISSUE THREAD

**Issue by winedog** [Novik/ruTorrent#1599]
I routinely use the 'Get File' option in the lower pane of a torrent to download files from within a torrent and this worked just fine in 3.7 with multi-part segmentation download tools like Internet Download Manager (IDM).  IDM would grab the file and could open up 8 segments to quickly download the file.

However, in 3.8 segments try to open and immediately fail most of the time and only the primary segment will download.  Other times, it will slowly open all 8 segments, download some portion of them and start to stall / timeout and then it will finally drop all the segments.  You can see what it looks like here:

![image](https://user-images.githubusercontent.com/2958553/33788382-c87e4586-dcd6-11e7-9a7a-5c594aa9c2b1.png)

I've testing on 3 different internet connections and 3 totally different computers all using IDM and it keeps happening.  It all occurred when my server was upgraded to 3.8 last week.

**Comment by Novik** [comment]
1) Corresponding functions was not changed during ~ 2 years and it's works for me.
2) Check $canUseXSendFile variable in the config file. If it's value is true, and you use Apache web-server with 'mod_xsendfile' extension, then file delivery is served on the web-server level. Otherwise - on the php level.

**Comment by winedog** [comment]
Thanks! This helped us figure out where the problem was and it was a custom code issue which we have managed to resolve
