### ISSUE TITLE
YGG doesn't work

### ISSUE THREAD

**Issue by Matthe95** [Novik/ruTorrent#1604]
Hello,

When I try to search on the search bar, I perfectly get the results of YGG but I can't download them. It worked before.

Anyone has the same problem?

Is it possible that the problems come with the fact that the website is now https://ww1.yggtorrent.com/ And not "www"?

Thanks and sorry from my English !

**Comment by jbleonesio** [comment]
I got the same issue.

It is related to the variable "ygg_sess" contained in yggtorrent cookie that changes every few hours. You can try by setting this variable in your rutorrent cookie and it will work for a short time.

On way to fix this problem would be to automatically connect to yggtorrent account using login/password to retrieve this value prior to launch a new download, but I don't know if this can easily be achieved in rutorrent...

**Comment by Kcchouette** [comment]
@Novik you can close this issue :)
For me it has been fixed in https://github.com/Novik/ruTorrent/commit/90325bdfec49f7acae89d85f1ea3478b2d9256dc
