### ISSUE TITLE
Bottom Bar Info as per rtorrent

### ISSUE THREAD

**Issue by scoobynz** [Novik/ruTorrent#1606]
Hello,

I see this topic [issue#354](https://github.com/Novik/ruTorrent/issues/354) which has been closed. I'm asking this same question again as I'm aware that rtorrent has undergone significant change since 2014.

Is the answer still the same? It would be good to have the same info as rtorrent - I find this useful in tuning rtorrent etc.

**Comment by Novik** [comment]
This is still same, sorry. But you are free for implementing corresponding features (drag-n-drop etc) inside your own plugin.
