### ISSUE TITLE
Bad response from server:

### ISSUE THREAD

**Issue by gcifuentes95** [Novik/ruTorrent#1609]
Well, I just installed ruttorrent with rtorrent in a Apache server, but I only get the following message:  Bad response from server: (200 [parsererror,getplugins]) SyntaxError: expected expression, got '<'" in the Logger. 

What is happening?

Additionally, my PHP version is the 7.1, and I have a Virtualmin instalation in the same server.

**Comment by Novik** [comment]
Try to configure php by the normal way.

**Comment by s-c-o-o-t** [comment]
Hello,
This error means that PHP is not loaded (for ruTorrent files, or maybe all the webserver files).
Try to enable the PHP module in apache like this: a2enmod enable php7.0
Then restart apache with: apachectl -k restart or apache2ctl -k restart, or with service / systemctl command
And refresh ruTorrent page with CTRL + F5 or clean the cache browser. ;)

**Comment by edmondww** [comment]
I have same problem, "Bad response from server: (200 [parsererror,getplugins]) SyntaxError: expected expression, got"

I have find reason ,becouse my web port is no 80. change reten to 80 port can fix it.
