### ISSUE TITLE
Inconsistent code formatting

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1612]
I still think you should enforce a coding style across the codebase, as you don't like PSR-2, maybe you can find something else. There are many instances where the code is badly formatted, for example spaces and tabs are often mixed together:
https://gist.githubusercontent.com/Hyleus/735a0b4f06c1eb6774edc21198b8d067/raw/033387ca39d00a9af04ae25619869ebd9c28b72b/gistfile1.txt
(𝕊=space, 𝕋=tab).

**Comment by tavy315** [comment]
I guess you are free to fork and eventually do a pull request.
