### ISSUE TITLE
got a small error after create plugin update

### ISSUE THREAD

**Issue by flier56** [Novik/ruTorrent#1615]
Merge pull request #1613 from Micdu70/patch-9
after lang update seeing undefined in create new torrent window,also in file source is highlighted.

![create](https://user-images.githubusercontent.com/9010706/34363278-b791e942-ea48-11e7-8cb0-11dd616f870e.PNG)

![create 2](https://user-images.githubusercontent.com/9010706/34363281-bf9435fa-ea48-11e7-9aa2-2b8fc175f244.PNG)

**Comment by Micdu70** [comment]
Don't have this issue. Try to clean your web browser cache and/or do a clean ruTorrent install from git.

**Comment by flier56** [comment]
Thanks for your time clearing my browser cache fixed the error.
