### ISSUE TITLE
Window "Create torrent"-hidden buttons

### ISSUE THREAD

**Issue by notojak** [Novik/ruTorrent#1616]
The buttons  are not visible, hidden under the window beam.
The problem occurs in every browser (Opera, MS Edge, Firefox, etc)
Graphics in the attached link:
[https://i.imgur.com/rvzl53c.png](https://i.imgur.com/rvzl53c.png)

**Comment by Micdu70** [comment]
The "undefined" text for non-english language and hidden buttons have been fixed yet.
Update your ruTorrent installation with `git pull` command.

**Comment by notojak** [comment]
I updated ruTorent,  language set by English.

stndard skin : 
[https://i.imgur.com/eLLxn0n.png](https://i.imgur.com/eLLxn0n.png)

custom skin:
[https://i.imgur.com/3WU85va.png](https://i.imgur.com/3WU85va.png)

**Comment by Micdu70** [comment]
> Update your ruTorrent installation with `git pull` command.

If already done, clear your browser's cache (manually or with a sofware like 'Ccleaner').

**Comment by notojak** [comment]
ok , well done 
[https://i.imgur.com/MsvSS4M.png](https://i.imgur.com/MsvSS4M.png)

Thanks fo Your help
