### ISSUE TITLE
Rss with ssl problem found

### ISSUE THREAD

**Issue by bsdcpp** [Novik/ruTorrent#1622]
https://github.com/Novik/ruTorrent/blob/872fdb5d83d0495e373883c31bff293d4e0b35d7/php/util.php#L699

https://github.com/Novik/ruTorrent/blob/872fdb5d83d0495e373883c31bff293d4e0b35d7/php/util.php#L704

Hi, When I added a rss url with https, rutorrent will alert an error, it cannot work.
Then some people say replace the php/Snoopy.class.inc with old version will be fine.

After diff these two versions, I found the problem at php/Snoopy.class.inc Line 449,500. it get work like this:
```php
$headerfile = uniqid(getTempDirectory()."/rutorrent-https-hdr-"); 
$contfile = uniqid(getTempDirectory()."/rutorrent-https-bdy-");
```
Then I found getTempDirectory used a lot, at last,
I foud php/util.php 704 should cause the problem, it lost the slash ‘/’ when enter the break situation.

I think the 704 line should be moved the end before return Statement. 
https://github.com/Novik/ruTorrent/blob/872fdb5d83d0495e373883c31bff293d4e0b35d7/php/util.php#L704

```php
--- php/util.php.ori    2017-12-29 14:16:37.284517861 +0800
+++ php/util.php        2017-12-29 14:16:45.686518022 +0800
@@ -677,7 +677,7 @@
                }
                if(empty($tempDirectory))
                        $tempDirectory = getProfilePath().'/tmp';
-               $tempDirectory = addslash( $tempDirectory );
        }
+       $tempDirectory = addslash( $tempDirectory );
        return($tempDirectory);
 }
```

**Comment by Novik** [comment]
Fragment from config.php:

$tempDirectory = null;			// Temp directory. Absolute path **with trail slash**. If null, then autodetect will be used.

And?

**Comment by bsdcpp** [comment]
Woo, the author comes here, how exciting.
yes, this is code fragment from synology's DSM package:
```php
$tempDirectory = '/usr/local/rutorrent/tmp';            // Temp directory. Absolute path with trail slash. If null, then autodetect will be used.
```

It seems you have announced that absolute path must have a trial slash, that's the packages maintainer's  mistake, thank you for you answer, it's important for us to read every comments of every configuration file.

**Comment by Novik** [comment]
>  it's important for us to read every comments of every configuration file.

No problem, you are welcome.

**Comment by bsdcpp** [comment]
Hi, this issue is the same as this https://github.com/Novik/ruTorrent/issues/1461

**Comment by alxlaxv** [comment]
Hello @bsdcpp 
Same issue as you but the value was 'null'.
I changed it to `"$tempDirectory = '/usr/local/rutorrent/tmp/';"` and I still have the same issue.
Any hint?
Thanks
