### ISSUE TITLE
/var/www/rutorrent/share/users/usernamehere/settings/tasks#

### ISSUE THREAD

**Issue by s-c-o-o-t** [Novik/ruTorrent#1627]
/var/www/rutorrent/share/users/usernamehere/settings/tasks#

is it ok to delete these, what is the purpuse of them ? and causes ? of not running properly? 

drwxrwxrwx 6 www-data www-data 4096 Jan  3 06:19 .
drwxrwxrwx 9 www-data www-data 4096 Jan  3 23:23 ..
drwxrwxrwx 2 www-data www-data 4096 Nov 30 22:44 15120773305a207812edc512.57272820
drwxrwxrwx 2 www-data www-data 4096 Dec  5 06:10 15124505855a262a198b28f7.26894138
drwxrwxrwx 2 www-data www-data 4096 Dec  5 06:11 15124506805a262a788b47c0.15894283
drwxrwxrwx 2 www-data www-data 4096 Dec  5 06:48 15124528285a2632dc452e84.12823964

i have over 200 +

**Comment by Pingblue** [comment]
This is the data which fills the tasks tab, you can delete the contents of this folder.
