### ISSUE TITLE
Autodl-irssi stops working until I install an update

### ISSUE THREAD

**Issue by holygamer** [Novik/ruTorrent#1631]
I setup Autodl-irssi and it was working fine for a couple of days then it stopped working. I killed ruTorrent then I forced an Autodl-irssi update via SSH. Then it was working again. 

Does Autodl-irssi automatically stop working when there's a new update available? Why would I need to update it if it was already working fine?

**Comment by s-c-o-o-t** [comment]
those are just updates, you dont have to update it. Its for trackers update, and it does work fine when you decide to update it threw webgui or from ssh

**Comment by s-c-o-o-t** [comment]
23:50 -!- Irssi: Changes in autodl-irssi v2.0.1:
23:50 -!- Irssi: [Commits](https://github.com/autodl-community/autodl-irssi/compare/community-v2.0.0...community-v2.0.1)
23:50 -!- Irssi:
23:50 -!- Irssi: ### Changed
23:50 -!- Irssi:
23:50 -!- Irssi: * Revert "Allow overriding torrent action settings in a filter without needing to set them all".
23:50 -!- Irssi: Changes in autodl-trackers v268:
23:50 -!- Irssi: [Commits](https://github.com/autodl-community/autodl-trackers/compare/community-v267...community-v268)
23:50 -!- Irssi:
23:50 -!- Irssi: ### Added
23:50 -!- Irssi:
23:50 -!- Irssi: * Add 2160p resolution to AnimeBytes.
23:50 -!- Irssi: * Add 2160p resolution to BIT-HDTV.
23:50 -!- Irssi: * Add 2160p resolution to BTN.
23:50 -!- Irssi: * Add 2160p resolution to Morethan.tv.
23:50 -!- Irssi: * Add 2160p resolution to Nebulance.
23:50 -!- Irssi: * Add 2160p resolution to PassThePopcorn.
23:50 -!- Irssi: * Add 2160p resolution to SWARM.
23:50 -!- Irssi:
23:50 -!- Irssi: ### Updated
23:50 -!- Irssi:
23:50 -!- Irssi: * Update network name for My Anonamouse.
23:50 -!- Irssi: * Update network name for Redacted.
23:50 -!- Irssi:
23:50 -!- Irssi: ### Removed
23:50 -!- Irssi:
23:50 -!- Irssi: * Remove The Dark Syndicate.
Day changed to 06 Jan 2018
23:50 -!- Irssi: A new autodl version is available! Type /autodl update to update or /autodl whatsnew.
23:50 -!- Irssi: A new trackers version is available! Type /autodl update to update or /autodl whatsnew.
Day changed to 07 Jan 2018

**Comment by holygamer** [comment]
OK but I installed and set up Autodl-irssi for the first time. It was working fine for a couple of days then the log in RuTorrent said something like couldn't connect to Autodl-irssi or something. Why would that happen? 

I was downloading from IP Torrents. But I updated Autodl-irssi then it worked again.

What was the point of your changes post?

**Comment by s-c-o-o-t** [comment]
Sometimes its never the updates that make youre autodl-irssi to work or even load up, Other things can cause it. what exactly did you do ? you just typed /autodl update ?

**Comment by s-c-o-o-t** [comment]
how do you load up ur autodl-irssi? from ssh ?

**Comment by holygamer** [comment]
I remember now.  I think I got this error in the ruTorrent log tab: 
Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Error getting files listing: Error: Could not connect: (111) Connection refused

So I ran this command in SSH:
wget -qO ~/install.autodl.sh http://git.io/oTUCMg && bash ~/install.autodl.sh

The program then worked again.

**Comment by s-c-o-o-t** [comment]
Yeah, usually you get that error when something is wrong with autodl-irssi, password , port , etc

**Comment by Novik** [comment]
Autodl-irssi is a third-party plugin. Ask from his author.
