### ISSUE TITLE
Plugin will not load [rutorrent v3.8]

### ISSUE THREAD

**Issue by piperun** [Novik/ruTorrent#1635]
When I try to enable any plugin it either switches between:

(if Extern == '/usr/bin/mktorrent')
`create: Plugin will not work. rTorrent user can't access external program (php).`
or (if Extern == '')
`create: Plugin will not work. Webserver user can't access external program (mktorrent).`

Depending on whenever or not I've added (in this case create plugin) anything in the Extern variable in the config.php file.

Things I've tried so far:

- chmod the entire rutorrent dir with a+rwx
- tested test.sh with no errors
- tested running said command as that user (and it worked)
- checked that $PATH has said path to program needed
- checked that rtorrent user can write to rutorrent/share (it can)

All users (rtorrent, php & www) share each others group.

**Comment by s-c-o-o-t** [comment]
Try Starting from here: l10n: update for create plugin #1613

**Comment by s-c-o-o-t** [comment]
Ok i had the exact problem just fixed it: Try these steps  👍 
ive tried configureing to Mktorrent aswell that didnt work.  This proccesses fixed it somehow. Perhaps there was something missing . You must be in root 👍 

root@usernamehere:/usr/local/bin# rutupgrade
Installed version: 3.8
   Latest version: 3.8
Do you wish to continue? y

Installing version 3.8 of rutorrent
Your existing rutorrent folder will be moved to /root/rutorrent_old

If you are not happy with the upgrade you can restore the old version, by rerunning this script

Installing Rutorrent 3.8
Setting permissions, Starting services
root@usernamehere:/usr/local/bin#

Refreshed browser and tried and no more errors.

**Comment by piperun** [comment]
Thanks, I'll look into this soon!
Since I'm currently very busy.

**Comment by piperun** [comment]
I'm not using rtinst so I downloaded it from github instead weird thing is:

Once I downloaded and replaced the old folder with the new one and reloaded the webpage I get the typical "can't connect to rtorrent, is rtorrent running?", which actually had create plugin loaded somehow, but once I setup RPC and have rutorrent work, create plugin gives the same error as before.

**Comment by piperun** [comment]
Also when I look into /tmp/errors.log I see this:

`[27.01.18 19:31:54] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>execute</methodName><params>^M
<param><value><string>sh</string></value></param>^M
<param><value><string>/var/www/html/rutorrent/php/test.sh</string></value></param>^M
<param><value><string>unrar</string></value></param>^M
<param><value><string>/var/www/html/rutorrent/share/settings/109210865</string></value></param>^M
</params></methodCall>
[27.01.18 19:31:54] Status: 200 OK^M
Content-Type: text/xml^M
Content-Length: 315^M
^M
<?xml version="1.0" encoding="UTF-8"?>^M
<methodResponse>^M
<fault>^M
<value><struct>^M
<member><name>faultCode</name>^M
<value><i4>-503</i4></value></member>^M
<member><name>faultString</name>^M
<value><string>ExecFile::execute(...) Fork failed.</string></value></member>^M
</struct></value>^M
</fault>^M
</methodResponse>^M
`

**Comment by tashkas1** [comment]
apt-get install php
apt-get install mktorrent
