### ISSUE TITLE
git pull error

### ISSUE THREAD

**Issue by s-c-o-o-t** [Novik/ruTorrent#1639]
remote: Counting objects: 1200, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 1200 (delta 709), reused 721 (delta 698), pack-reused 465
Receiving objects: 100% (1200/1200), 195.41 KiB | 0 bytes/s, done.
Resolving deltas: 100% (935/935), completed with 260 local objects.
From https://github.com/Novik/ruTorrent
   a05d022..d13e4f4  master     -> origin/master
 * [new tag]         v3.8       -> v3.8
Auto-merging plugins/xmpp/plugin.info
Auto-merging plugins/xmpp/lang/pl.js
Auto-merging plugins/xmpp/lang/no.js
Auto-merging plugins/xmpp/XMPPHP/XMLStream.php
Auto-merging plugins/xmpp/XMPPHP/Roster.php
Auto-merging plugins/uploadeta/plugin.info
Auto-merging plugins/uploadeta/lang/uk.js
etc....etc......... Then I get this error on some of them : 

CONFLICT (modify/delete): plugins/extsearch/images/ExtraTorrent.png deleted in d13e4f4608eaa59e7420c2ade5549e5ae9d15e5e and modified in HEAD. Version HEAD of plugins/extsearch/images/ExtraTorrent.png left in tree.
CONFLICT (modify/delete): plugins/extsearch/engines/Torrent411.php deleted in d13e4f4608eaa59e7420c2ade5549e5ae9d15e5e and modified in HEAD. Version HEAD of plugins/extsearch/engines/Torrent411.php left in tree.
Auto-merging plugins/extsearch/engines/ScC.php
Auto-merging plugins/extsearch/engines/RUTracker.php
Auto-merging plugins/extsearch/engines/Nyaa.php
Auto-merging plugins/extsearch/engines/NNMClub.php
Auto-merging plugins/extsearch/engines/IPTorrents.php
CONFLICT (modify/delete): plugins/extsearch/engines/ExtraTorrent.php deleted in d13e4f4608eaa59e7420c2ade5549e5ae9d15e5e and modified in HEAD. Version HEAD of plugins/extsearch/engines/ExtraTorrent.php left in tree.
Auto-merging plugins/extsearch/engines.php
Auto-merging README.md
CONFLICT (modify/delete): .htaccess deleted in d13e4f4608eaa59e7420c2ade5549e5ae9d15e5e and modified in HEAD. Version HEAD of .htaccess left in tree.
Automatic merge failed; fix conflicts and then commit the result.

what do i do ?
then when i try this i get : 
root@bt:/var/www/rutorrent/share/users/bt# git pull
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
root@bt:/var/www/rutorrent/share/users/bt#

No idea what those Hints are Heh

**Comment by Novik** [comment]
Try to read something about git. 
Your problem has not relation to ruTorrent.
