### ISSUE TITLE
Link to Malware Spectrogram plugin #1576

### ISSUE THREAD

**Issue by Sub-7** [Novik/ruTorrent#1640]
Here is a link to Malwaresite, please delete it
https://github.com/Novik/ruTorrent/issues/1576

User:  maximuml commented on 13 Nov 2017 
It was available for free on h**p://rutorrent.org/svn/spectrogram/trunk
a long time  ago

**Comment by dlabrie** [comment]
I second this. Luckily, pi-hole caught it.
