### ISSUE TITLE
extsearch issue with cloudflare after commit 0aa88bd...

### ISSUE THREAD

**Issue by pgera** [Novik/ruTorrent#1641]
I'm seeing a strange issue with cloudflare where rutorrent doesn't load after this commit: https://github.com/Novik/ruTorrent/commit/0aa88bd0bbb253d13079723c40551ef97380656d

It just keeps spinning. Something is possibly not reachable and is on the critical path ? Disabling extsearch makes rutorrent load correctly.

**Comment by Novik** [comment]
> I'm seeing a strange issue with cloudflare

Which relation cloudflare may have to ruTorrent? You have host with ruTorrent, protected with cloudflare? Something else?

> It just keeps spinning

spinning where? On the load screen?

**Comment by pgera** [comment]
> Which relation cloudflare may have to ruTorrent? You have host with ruTorrent, protected with cloudflare? 

Yes, that's the only connection. I have CF in front of the host. This issue somehow manifests when I access it through CF. If I access the host directly, it loads. 

> spinning where? On the load screen?
Yes, on the load screen. The issue is a bit strange. The only thing I have identified is that it's related to extsearch. I never use that plugin; so I've just disabled it for now.

**Comment by foo25amc** [comment]
I've also encountered this issue today as well following installation of ruTorrent on a fresh server.

The web GUI will load after approximately 5-10 minutes via Cloudflare, but loads immediately via the server IP. Disabling extsearch did the trick for me too.

**Comment by JustARandomGuyHere** [comment]
I can confirm too. Disabling extsearch fixed it.
