### ISSUE TITLE
Hide hidden files in directory select box

### ISSUE THREAD

**Issue by gauthier-delacroix** [Novik/ruTorrent#1642]
I'm using a rtorrent/rutorrent docker container, which places some config files in the download directory.
These config files are under hidden subdirectories (.rtorrent, .rutorrent, .log).

Is there a way to avoid displaying these hidden directories in the directory select box, when adding a torrent ?

**Comment by Novik** [comment]
Without changes - no.

**Comment by gauthier-delacroix** [comment]
Ok, but I'm really not able to provide a PR for this.
I'll try to find a way to split both contents in different directories though rtorrent config.
