### ISSUE TITLE
nfo plugin

### ISSUE THREAD

**Issue by TMTYD** [Novik/ruTorrent#1643]
I found the following error message from Apache in error.log:

`
PHP Fatal error:  Uncaught Error: Call to undefined function ereg_replace() in /var/www/ru/plugins/nfo/action.php:60\nStack trace:\n#0 /var/www/ru/plugins/nfo/action.php(92): dos_format('    \\xDC\\xDC\\xDC       \\xDC...', true)\n#1 /var/www/ru/plugins/nfo/action.php(100): viewNFO()\n#2 {main}\n  thrown in /var/www/ru/plugins/nfo/action.php on line 60, referer: https://nas/
[Thu Jan 25 10:06:08.438374 2018] [core:info] [pid 3263] [client x.x.x.x.x:4040] AH00128: File does not exist: /var/www/ru/plugins/nfo/lang/de.js, referer: https://nas/
`

**Comment by Novik** [comment]
This is a third-party plugin. Try to ask his author.
