### ISSUE TITLE
Tasks right click error

### ISSUE THREAD

**Issue by TMTYD** [Novik/ruTorrent#1644]
Hi

If I make a right-click in the Tasks tab, the following message appears:

![js error](https://user-images.githubusercontent.com/29516076/35383520-d05e9f56-01c2-11e8-9dd4-21a659b3eb27.png)

**Comment by Novik** [comment]
I can't to reproduce this.
Try to remove all third-party plugins and use development version of ruTorrent.

**Comment by TMTYD** [comment]
i use the development version, i have refresh the page and its ok
