### ISSUE TITLE
rtorrent pointing into /root dir

### ISSUE THREAD

**Issue by s-c-o-o-t** [Novik/ruTorrent#1645]
i seem to have a problem , in web-gui shows %21 used 
/dev/root        20G  3.1G   16G  17% /

which the actually drive is 
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  3.1G   16G  17% /
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G   13M  2.0G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda1       487M   23M  435M   5% /boot
/dev/sda3       1.8T   75M  1.7T   1% /home
tmpfs           393M     0  393M   0% /run/user/1000

any ideas how to change for rutorrent or rtorrent to point into /dev/sda3       1.8T   75M  1.7T   1% /home .
Or what i did wrong. thanks.

**Comment by bhavicp** [comment]
There's a setting in config.php in conf folder.

 $topDirectory = "<path>";                 // Upper available directory. Absolute path with trail slash. I.e "/home"

**Comment by Novik** [comment]
Try to read yet once:

> $topDirectory = ""; // Upper available directory. **Absolute path with trail slash.**

P.S. Original config.php doesn't contain words 'I.e "/home"'.
