### ISSUE TITLE
 $topDirectory = '/';

### ISSUE THREAD

**Issue by s-c-o-o-t** [Novik/ruTorrent#1646]
What should this be set to:  $topDirectory = '/';  
that is what i have in config.php
in web-gui i see %20 used , which i havent added anything, i think its looking in /root mount dir 
Filesystem      1K-blocks    Used  Available Use% Mounted on
/dev/root        20026236 3204504   15781400  17% /
devtmpfs          2007320       0    2007320   0% /dev
tmpfs             2009136       0    2009136   0% /dev/shm
tmpfs             2009136   13148    1995988   1% /run
tmpfs                5120       0       5120   0% /run/lock
tmpfs             2009136       0    2009136   0% /sys/fs/cgroup
/dev/sda1          498532   22932     445341   5% /boot
/dev/sda3      1901536420   76728 1804844220   1% /home
tmpfs              401828       0     401828   0% /run/user/1000

How can i change the path to /dev/sda3      1901536420   76728 1804844220   1% /home  which i want

**Comment by Novik** [comment]
$topDirectory = '/home/';

**Comment by s-c-o-o-t** [comment]
Thank You, Had That idea in Mind, Wanted to Double shure 💯

**Comment by s-c-o-o-t** [comment]
[27.01.2018 12:39:06] FILE MANAGER: Directory does not exist : /

**Comment by Novik** [comment]
This is third-party plugin. Try to ask from his author.

**Comment by s-c-o-o-t** [comment]
If you dont mind, What is the non third party? link?
