### ISSUE TITLE
[Feature Request] Checking And Updating Through Web-Ui

### ISSUE THREAD

**Issue by zero77** [Novik/ruTorrent#1649]
Can you please add support for checking and installing updates through the web-ui.
Possibly by just running a shell script, that checks for updates either for the web-ui or plugins, and if available it installs it automatically.
Thanks

**Comment by Feriman22** [comment]
Run the shell script on the server instead by crontab. The possibility to execute shell script from web-ui is a huge security issue.

Alternative is apticron, which is notify you by email when update is available.
