### ISSUE TITLE
(ExtSearch) TorrentDay, IPTorrents, TorrentLeech... all not working

### ISSUE THREAD

**Issue by VilDegard** [Novik/ruTorrent#1655]
Hello,

The **extsearch** scripts for TorrentDay, IPTorrents and TorrentLeech used to work.
Now after an update to 3.8, I see a clear blank in any search inquiries on this trackers. 
Public trackers are fine, some other private trackers are fine too.
I've filled out the cookies right, along with the identification asked for TorrentLeech... still nothing.

Anyone having an idea on how to fix this please?

Thanks

**Comment by tonyp1983** [comment]
I get no results from TD and I'm not sure how CP gets results for that site but TD seem to have moved away from there API all together. SickRage recently updated their method of searching TD, [here](https://github.com/SickRage/SickRage/commit/24036496310f36bdb8b585056fe7b39ca990d3b7) not sure if this helps.

**Comment by VilDegard** [comment]
Hi @tonyp1983 , 

Thanks for you reply. I've edited my post in case it was not clear enough, it's the **extsearch plugin** that interests me more than the interactions with CP and SR.

I prefer to use Jackett with IPTorrents and TorrentDay (this one not working at the moment) on CP.

Hopefully someone here can help fix the scripts for these trackers...
