### ISSUE TITLE
Cannot save directly to network drives

### ISSUE THREAD

**Issue by Acans** [Novik/ruTorrent#1659]
Hi there,

I've recently switched my home torrent client from uTorrent to rTorrent/ruTorrent after many years as using it for my seedbox. However I've noticed an issue due to the way my storage works at home. My storage is on another home server, and shares to the other machines in the house.

Now I've mounted the shares to /media/share1 etc in Debian and can cd/ to them no issues, however I cannot Add a Torrent to start downloading directly to those shares, with or without starting.

However, I can just check don't start downloading automatically and leave the download directory as /home/user/rutorrent/download, than right click > save to and select /media/share1/directory and hit save. Than I can either start the download, or if the files are already there, do a force recheck than start seeding them, so rTorrent defiantly as access to the directory's :\

A quick google service hasn't gotten me far unfortunately so I'm left to assume it's a bug in the initial add torrent feature.

**Comment by scoobynz** [comment]
Sounds to me like you need to set "topdirectory" in config.php.

**Comment by Acans** [comment]
I just checked, my topdirectory was comment out :\.

I've just set it to "/" and when I go to rutorrent I can now save to more places (it shows my .rissi and .autodl folders now where it didn't before hand) however it still only lets me go back as far as /home/user/ directory. Still can't be saved directly to mounted drives.

**Comment by scoobynz** [comment]
Add symbolic links to the media drives in your /home/user/ directory. If you cant see them make sure the permissions on the newly created symbolic links are correct.

**Comment by Acans** [comment]
Hi there,

I did what you said and added my mount points to /home/user/media/share.

Although once the mount has been made, you can no longer "see' the directory in the drop down in ruTorrent (weird) but you can SUCCESSFULLY save torrents by manually typing the into the box /home/user/media/share. Plus Force Rechecked worked instantly too :D Happy days!
