### ISSUE TITLE
Ctrl+a doesn't work 

### ISSUE THREAD

**Issue by checktravis** [Novik/ruTorrent#1662]
In chrome / windows 10, while mouse-focused in torrent list, ctrl+a doesn't seem to do anything. It doesn't function as described in the help menu (Select All)

Ctrl+z doesn't deselect either.

Shift selecting works.

Is this the intention?

**Comment by tashkas1** [comment]
it works for me, what version do u use?

**Comment by checktravis** [comment]
3.8, in docker.

It seems to be working now, may have been a fluke.

**Comment by checktravis** [comment]
Looks like it is the Official chrome that has the issue, Version 65.0.3325.181 (Official Build) (64-bit)

I installed Canary Version 67.0.3381.1 (Official Build) canary (64-bit) and ctrl+a works as expected.

It's just rutorrent though, Select All works in the location bar and when selecting content on other sites.

This is on Windows 10 Pro 1709, OS Build 16299.309; clean install of both browsers with no extensions.
