### ISSUE TITLE
New version of rTorrent api prevents proper identification of listening ports

### ISSUE THREAD

**Issue by liaralabs** [Novik/ruTorrent#1663]
The rTorrent dev has pushed a new API (10) that deprecates the command `network.listen.port` and replaces it with `network.port`. If using random port assignment, ruTorrent will simply assume the port opened by ruTorrent is the first port of the range, rather than the actual port itself. This causes ruTorrent to assume the port isn't open and also causes the check_port plugin to show a closed status (because it's checking the wrong port)

My solution was to add a check to php/settings.php for the new API v10 and assign a new port variable if it's found. Everything appears to be functioning correctly, though I haven't tested for backwards compatibility yet.

[network.port.txt](https://github.com/Novik/ruTorrent/files/1798250/network.port.txt)

**Comment by Novik** [comment]
Corresponding code was added, check, please.

**Comment by liaralabs** [comment]
All in all looks good so far; however I am noticing that in Settings > Connection > "Open Listening Port" doesn't seem to be checked, despite you adding the RPC call for it. Perhaps another variable conflict somewhere?

**Comment by Novik** [comment]
I hope fixed, check now please.

**Comment by liaralabs** [comment]
It seems that checkbox still isn't getting ticked -- have restarted php-fpm/rtorrent to ensure that there isn't a caching issue somewhere.

**Comment by Micdu70** [comment]
I think httprpc plugin requires an update... @Novik check my PR
