### ISSUE TITLE
Extracting archive with unpack works but not with file manager extract

### ISSUE THREAD

**Issue by Sonic3R** [Novik/ruTorrent#1666]
Hi,

I had some files, archives, `.rar` which cannot be extracted using `FileManager > Extract` method, but if I use `Files > Unpack`, it will work.

What's difference between them ?

**Comment by Novik** [comment]
Unpack - is a standard plugin.
Filemanager - is a third party plugin. I don't know anything about it. Try to ask from his author.

**Comment by Sonic3R** [comment]
Thanks for clarification

**Comment by Sonic3R** [comment]
There is a possible way to use `unpack` if I have file name and directory to where to extract ? I see that is based on hash... I want to extract a torrent programatically. Only I know so far is folder path ...

**Comment by Dediseedbox** [comment]
Have you checked the path for the external is listed in the /rutorrent/plugins/filemanager/conf.php

For example,
`$pathToExternals['rar'] = '/usr/bin/rar';`
