### ISSUE TITLE
3.7: IRC Servers -> server settings -> SSL enabled but isn't shown

### ISSUE THREAD

**Issue by baz357** [Novik/ruTorrent#1668]
When you go to IRC Servers -> server settings -> and enable SSL for a server, confirm with OK and then open the same settings again, SSL is being shows as disabled (the checkmark is missing). But using the Backup option you'll find that SSL is still enabled. It's just the checkmark that's missing in the UI.

I could only confirm this issue for ruTorrent 3.7.

**Comment by Novik** [comment]
No one official plugins (and ruTorrent core too) doesn't contain something like 'IRC Servers'.
I.e. you use third-paty plugin.
Try to ask from his author.
