### ISSUE TITLE
Rutorrent v3.7: Remove and Delete Data doesnt remove unpacked files

### ISSUE THREAD

**Issue by nadoxq8** [Novik/ruTorrent#1669]
hi,

my Remove and delete data option in the right l click menu, doesnt remove the unpacked files in the directory. it used to work few months ago. but now it doesn't. 

my seedbox is constantly downloading freeleech files  and seeding them then auto deleting. however, it doesnt delete the extracted file.

**Comment by Novik** [comment]
This is correct behavior.
