### ISSUE TITLE
auto move doesn't always work

### ISSUE THREAD

**Issue by bobbintb** [Novik/ruTorrent#1671]
It seems auto move doesn't always move torrents after the downloads it complete. I haven't found any reason why some do and some don't. I have my default download folder set to /mnt/user/server/downloads and it is set to move completed downloads to /mnt/user/server/complete but files end up in both. I look at the completed and seeding torrent and many of them are still in /mnt/user/server/downloads.

**Comment by thehomerepot** [comment]
My automove has not been working lately either. Unfortunately, my log files don't contain anything useful in them. If I manually move directories in the WebUI the torrents move without issue.

Is there any logging I can enable/gather from somewhere to understand what's happening?

**Comment by bobbintb** [comment]
I think it has to do with the "hash check after completion" setting. I haven't had an issue since I disabled that. I have some large files so I'm thinking there is a timing issue or conflict between the two.

**Comment by thehomerepot** [comment]
I haven't changed anything but one of my torrents today moved without issue. It really seems intermittent for me. I'll try disabling the hash check and see if I get any more un-moved  torrents.

**Comment by thehomerepot** [comment]
I disabled hash checks but I still get random torrents not moving to the completed folder. So far, it seems limited to compressed torrents that should be unpacking, but also aren't.

**Comment by bobbintb** [comment]
None of my torrents are packed. It's probably a combination of the two for you. Basically anything that might cause a delay in completion is causing it, I think. Hash check or unpacking or both.

**Comment by thehomerepot** [comment]
Unfortunately I have no way of validating that. There are no logs that I can find. Additionally, if it was waiting for unpacking to complete, I'd expect the torrent to be unpacked, but in the wrong folder. In my situation, they are neither moved nor unpacked.

**Comment by thehomerepot** [comment]
For some reason this has been happening with increased frequency in the last week.

Does anyone know how to find or enable logs that would show why both unpacking and moving torrents is failing?

**Comment by bobbintb** [comment]
I tired to find some logging info within the program but couldn't find any.  I found this but haven't looked into it:
https://github.com/Novik/ruTorrent/wiki/Config

**Comment by thehomerepot** [comment]
The log file in that config is setup, however it doesn't log anything relevant.

**Comment by RaymondSchnyder** [comment]
This is still an issue till today.

**Comment by inside83** [comment]
> This is still an issue till today.

Today too
Maybe it's because I have thousands of torrents loaded (but not active).
I keep them so I don't download the same stuff again.

**Comment by slyre1337** [comment]
> > This is still an issue till today.
> 
> Today too
> Maybe it's because I have thousands of torrents loaded (but not active).
> I keep them so I don't download the same stuff again.

I have that issue frequently as well with only 200-400 torrents loaded

**Comment by xombiemp** [comment]
I've never had this issue.

**Comment by Biztactix-Ryan** [comment]
I find this issues seems to happen every 2-3 weeks with the hosting I use.
I find that rebooting the rtorrent instance fixes it

It's likely not just AutoMove, I also find that it doesn't unpack, so it's something like the trigger to perform the functions on complete torrents doesn't happen.
It's not a permissions issue or anything as if I manually click Save to.. then I can move it to the right folder, Then if I hit unpack, it also works, so it's not that it's not working, Just that it doesn't get triggered.

I use this Script to run a quick restart
`kill "$(pgrep -fu "$(whoami)" "/usr/local/bin/rtorrent")"
for pid in $(pgrep -fu "$(whoami)" "php-fpm"); do kill $pid; done
/usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf
sleep 10
screen -dmS rtorrent rtorrent`

**Comment by slyre1337** [comment]
> I find this issues seems to happen every 2-3 weeks with the hosting I use.
> I find that rebooting the rtorrent instance fixes it
> 
> It's likely not just AutoMove, I also find that it doesn't unpack, so it's something like the trigger to perform the functions on complete torrents doesn't happen.
> It's not a permissions issue or anything as if I manually click Save to.. then I can move it to the right folder, Then if I hit unpack, it also works, so it's not that it's not working, Just that it doesn't get triggered.
> 
> I use this Script to run a quick restart
> `kill "$(pgrep -fu "$(whoami)" "/usr/local/bin/rtorrent")" for pid in $(pgrep -fu "$(whoami)" "php-fpm"); do kill $pid; done /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf sleep 10 screen -dmS rtorrent rtorrent`

exactly the same for me

**Comment by kicker83** [comment]
I have the same issue. Automove stops moving files from incoming to completed, but it occurs randomly and for different types of files.

**Comment by BlayZin** [comment]
idk why it happens but it seems that also the "added" and "finished" information aren't being added when it happens.
It's really annoying because you can't really rely on it anymore. I guess it is time to look for other alternatives

**Comment by Soulflyzz** [comment]
Hello,

I have this bug as well and it's completely random when it chooses to do this has anyone found a solution yet?

**Comment by CrashLaker** [comment]
same issue here. afaik it's completely random for me too

**Comment by inside83** [comment]
> same issue here. afaik it's completely random for me too

yeah
unfortunately I had to switch to qbittorrent because there was so many not-moved-but-finished torrents mixed with unfinished it's hard to keep track

**Comment by rwojsznis** [comment]
Same, I tried restarting rutorrent container on my NAS on daily basis as suggested above, but I think that somehow made things even worse; finally I gave up, installed transmission and added [unpackerr](https://github.com/davidnewhall/unpackerr) on top - I'm much happier person now 😜 

Thanks for the good run all the collaborators of ruTorrent!
