### ISSUE TITLE
How to setup unix domain socket + HTTPRPC 

### ISSUE THREAD

**Issue by 8549** [Novik/ruTorrent#1672]
Hi, i'm a bit confused about rtorrent/rutorrent configuration. I'd like to make ruTorrent and rTorrent communicate via Unix sockets (more secure than TCP). My web server doesn't have a SCGI module so i'd like to use the HTTPRPC plugin.

- rTorrent is configured to communicate via socket as described [here](https://github.com/rakshasa/rtorrent/issues/696#issuecomment-369880069), 
- HTTPC plugin is manually enabled in conf/plugins.ini (and rpc has been disabled as well)
- `/var/www/rutorrent/` is the root folder for ruTorrent
- `$XMLRPCMountPont = "/plugins/httprpc/action.php";` in conf/config.php
- $scgi_port = 0 and $scgi_host = "unix:///tmp/.rtorrent.sock"; in conf/config.php
- rTorrent is run as `rtorrent` user, the webserver that serves ruTorrent is run as `www-data` user; both users are in the same group 
- .rtorrent.sock has 770 permissions
- ruTorrent is served with HTTP Basic Auth

When i browse to ruTorrent it says 

> No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

When i try via command line with

    XMLRPC_TRACE_XML=1 xmlrpc https://mydomain.com/rutorrent/plugins/httprpc/action.php -username=user -password=pass system.listMethods
i can see that the HTTPRPC plugins answers `false`.

How do i make it work? Thanks in advance.

**Comment by Novik** [comment]
> $XMLRPCMountPont = "/plugins/httprpc/action.php"; in conf/config.php

For which reason you set this? Plugin doesn't require something like that.

1) Does your rtorrent compiled with xmlrpc support?
2) Try to use port instead socket. Does this have effect?

**Comment by Novik** [comment]
2. Don't know really. May be your web server configure for usage of private tmp folder? Try to move socket location to the another directory. This directory must be accessible from your web server (see open_basedir etc).

**Comment by 8549** [comment]
I changed the socket location to another folder but it still doesnn't work. If i set permissions to 777 it works, but it should with just 770 permissions. Any idea?

**Comment by Novik** [comment]
Sorry, but I don't know - how this may happens if all your conditions, listed above are true.
Try to check permissions manually. For example, something like

sudo -u www-data echo 123 > /path_to/.rtorrent.sock

Are you will see message 'Permission denied'? Same command with rtorrent user.

**Comment by 8549** [comment]
Unix sockets can't be accessed with echo/cat, it gives `bash: /var/lib/rtorrent/.rtorrent.sock: No such device or address`
Using` echo system.listMethods | nc -U /var/lib/rtorrent/.rtorrent.sock` doesn't give any error and silently returns 0. If i listen to the socket i can see the messages passing.

I feel we could get to the root of the problem if HTTPRPC displayed a meaningful error message instead of replying "false".

**Comment by xombiemp** [comment]
The root of the problem is obviously permissions, since it works with 777.  Try to set the group apache runs as to the shared group.
Edit /etc/apache2/envvars and change:
export APACHE_RUN_GROUP=thegroup
