### ISSUE TITLE
erasedata plugin doesn't erase data (+ workaround)

### ISSUE THREAD

**Issue by twistedfall** [Novik/ruTorrent#1675]
Hi,

When trying to remove torrent together with all its data the torrent is removed, but the data remains there forever. I'm using ruTorrent git 0a0ca99a85c8ee87f6ddfc7b849a532e9a22e40a and rtorrent 0.9.6-2build1 from Ubuntu 16.04. 

After debugging a bit I have found that it happens because `fin.sh` script to rename .tmp to .list file is never called. Why exactly is it not called is not yet clear to me, but removing the condition (`branch`) before the command to call `fin.sh` seems to fix it.

So if you change the line 14 in `plugins/erasedata/init.php`:
```php
getCmd('branch=').getCmd('d.get_custom5').'=,"'.getCmd('execute').'={'.$thisDir.'/fin.sh,'.$listPath.',$'.getCmd('system.pid').'=,$'.getCmd('d.get_hash').'=,$'.getCmd('d.get_base_path').'=,$'.getCmd('d.is_multi_file').'=,$'.getCmd('d.get_custom5').'=}"')),
```
to just
```php
getCmd('execute').'={'.$thisDir.'/fin.sh,'.$listPath.',$'.getCmd('system.pid').'=,$'.getCmd('d.get_hash').'=,$'.getCmd('d.get_base_path').'=,$'.getCmd('d.is_multi_file').'=,$'.getCmd('d.get_custom5').'=}')),
```
removing data with torrent will work again. I have also checked and removing torrent without removing data works too.

Patch here: [erasedata.patch.txt](https://github.com/Novik/ruTorrent/files/1866421/erasedata.patch.txt)

**Comment by barchan** [comment]
same problem with me, but this patch doesn't help.

Debian 9.4, NGINX 1.14.0, PHP 7.0.27-0+deb9u1, rtorrent 0.9.6-2+b1 and ruTorrent 3.8 (latest git version).

When I try delete torrent with data, I get message: Event 'event.download.erased' failed: Bad return code. And data don't removed.

P.S: same setup on Debian 8.10 + rtorrent/libtorrent (installed from source) work fine on 15 servers.

Waiting official update. Thanks!

**Comment by laitosko** [comment]
Experiencing similar issues. Cannot delete data via UI. 
Debian 8.10, apache2, PHP 5.6.33-0+deb8u1, rtorrent 0.9.6/0.13.6 ruTorrent 3.8

rturrent spamming the following. No spaces in _system.method_ lines.
>  Scheduled command failed: erasedata**servername**: Bad return code.

**Comment by Novik** [comment]
> So if you change the line 14

Your changes will have one side effect - torrents data will be removed even if you select 'Delete' (i.e. without data) command.
