### ISSUE TITLE
Ratio Problems

### ISSUE THREAD

**Issue by josjaf** [Novik/ruTorrent#1678]
Hi, I'm having some problems with Ratio Groups. My first group is called seed, which is basically 
9999,9999,9999,-1. For some reason, the torrents aren't respecting the groups. All of my torrents are stopped that have a ratio of above 1.0. I have no idea why this is happening. Please help! :)

**Comment by w4hnsinn** [comment]
First off, the easiest/default way to achieve unlimited seeding is to **not apply any ratio group at all**.
But, I assume you already knew that, so you must have a specific reason why you need to achieve the "default" behavior by means of a ratio group instead.

I'm always struggling with ratio groups myself, so take my advice here with a grain of salt, but have you tried something like:
`9999	0	0	-1`

This (I believe) should seed to a ratio of 99.99, no matter what.
