### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by tashkas1** [Novik/ruTorrent#1681]
i get variuose times Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down? i noticed that rtorrent sometimes stucks and cant be used..

**Comment by aminomaboul** [comment]
happend to me 5 days ago,
the RPC server's port (5000) was open. but for a reason i dont know, can't respond to request
you can test 
xmlrpc -username=XXX -password=XXX localhost system.listMethods
all i remember i did is:
killall rtorrent
then
start rtorrent directly from terminal
then
systemctl restart nginx php-fpm rtorrent 
but this is definitely a rtorrent issue not rutorrent

**Comment by tashkas1** [comment]
Failed.  Call failed.  HTTP response code is 404, not 200.  (XML-RPC fault code -504)

**Comment by byte916** [comment]
I have the same problem, I use apache2 and libxml version is 2.9.3+dfsg1-1

**Comment by tashkas1** [comment]
well i have easier this paing becouse there is bug in rtorrent i have added in rtorrent.rc this line
schedule2 = session_save, 1200, 43200, ((session.save)
