### ISSUE TITLE
Unable to sort columns when clicking

### ISSUE THREAD

**Issue by LaMpiR** [Novik/ruTorrent#1685]
I've had this problem before, but was able to click it with the middle wheel on the mouse and it would be again clickable for sorting.

Now, that doesn't work as well.

Win10 
Chrome 65.0.3325.181
ruTorrent 3.8

**Comment by LaMpiR** [comment]
When I went to see which version am I using of the Chrome, it got updated to 66.0.3359.117, but still the same problem.

**Comment by xombiemp** [comment]
Works fine for me on Windows 10 and same version of Chrome.

**Comment by scoobynz** [comment]
I've had this issue in the past. Clearing browser cache fixed.

**Comment by koblack** [comment]
Unable to sort columns when clicking once #1195
Fix table sorting in chrome #1637
