### ISSUE TITLE
Ratio Groups not working?

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1686]
Hello,
using rTorrent 0.9.6/0.13.6 on my Synology DS216play.
Want to stop seed torrents after 48h but it doesn't work. Can you check it if something is bad?
Thank you.

![snimka obrazovky 2018-04-18 o 22 46 10](https://user-images.githubusercontent.com/20722830/38957288-7ec38632-435a-11e8-8c30-6c355e3007a1.png)

**Comment by xombiemp** [comment]
Change the minimum upload (UL,MB) to 0.  Then, no matter how much you've uploaded it will stop after 48 hours.

**Comment by USRGH** [comment]
tried it but it still doesn't work.

**Comment by USRGH** [comment]
bump

**Comment by xombiemp** [comment]
Works for me.  Are you sure your torrent is assigned to that ratio group?  You'd have to manually set it because you don't have a Default ratio group set.

**Comment by USRGH** [comment]
you're right, didn't assign torrents to that group. Already assigned, so all torrents are in ratiogroup0 (for test). In this case a lot of torrents must stop because of 48h time but torrents still work fine. Maybe I need to restart rutorrent?
