### ISSUE TITLE
Bad response from server: (500 [error,getplugins]) Internal Server Error on Archlinux ARM (NAS Zyxel NSA310)

### ISSUE THREAD

**Issue by arti74** [Novik/ruTorrent#1690]
Hello. I have the problem to make work rutorrent on my NAS Zyxel NSA310 (archlinux ARM system). All services: php-fpm, nginx and rtorrent seem to work properly (status is OK), but when I put ip of the NAS: 192.168.1.74/rutorrent - I get the error like in the title. I don't know what to do now. Permissions forced as 777, etc.

NGINX conf:

> user http;
> worker_processes  1;
> events {
>     worker_connections  1024;
> }
> http {
>     include       mime.types;
>     default_type  application/octet-stream;
>     sendfile        on;
>     keepalive_timeout  65;
>     server {
>         listen 80;
> #listen 127.0.0.1:80;     
> server_name  localhost;
>         root /usr/share/nginx/html;
>         location / {
>             index  index.html index.htm;
>         }
>         location ~ \.php$ {
>             fastcgi_pass   unix:/run/php-fpm/php-fpm.sock;
>             fastcgi_index  index.php;
>             include        fastcgi.conf;
>         }
>         location /RPC2 {
>             include scgi_params;
>             scgi_pass localhost:5000;
>         }
>         error_page   500 502 503 504  /50x.html;
>         location = /50x.html {
>             root   /usr/share/nginx/html;
>         }
>     }
> }
Rutorrent version: 
rutorrent-git r2151.4c08688d-1 (I couldn't make it work on the regular rutorrent package - got error 500 and 502, also connected with "getplugins") 

Some issue in the ngingx (as I see now)
`Apr 24 23:42:07 alarm systemd[1]: Starting A high performance web server and a reverse proxy server...
 Apr 24 23:42:07 alarm systemd[1]: nginx.service: Can't open PID file /run/nginx.pid (yet?) after start: No such file or directory
 Apr 24 23:42:07 alarm systemd[1]: Started A high performance web server and a reverse proxy server.
 Apr 24 23:43:15 alarm nginx[329]: 2018/04/24 23:43:15 [error] 333#333: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  Declaration of rxmlrpcfix::run() should be compatible with rXMLRPCRequest::run($trusted = true) in /usr/share/webapps/rutorrent/plugins/filemanager/xmlfix.php on line 67" while reading response header from upstream, client: 192.168.1.5, server: localhost, request: "GET /rutorrent/php/getplugins.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "192.168.1.74", referrer: "http://192.168.1.74/rutorrent/"`
 
Below the rtorrent config yet:

> Instance layout (base paths)
> method.insert = cfg.basedir, private|const|string, (cat,"rtorrent/")
> method.insert = cfg.watch,   private|const|string, (cat,(cfg.basedir),"watch/")
> method.insert = cfg.logs,    private|const|string, (cat,(cfg.basedir),"log/")
> method.insert = cfg.logfile, private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
> 
> Create instance directories
> execute.throw = bash, -c, (cat,\ "builtin cd \"", (cfg.basedir), "\" ",\ "&& mkdir -p .session download log watch/{load,start}")
> 
> network.port_range.set = 55540-55540
> network.port_random.set = no
> 
> dht.mode.set = disable
> protocol.pex.set = no
> trackers.use_udp.set = no
> 
> throttle.max_uploads.set = 100
> throttle.max_uploads.global.set = 2250
> 
> throttle.min_peers.normal.set = 20
> throttle.max_peers.normal.set = 60
> throttle.min_peers.seed.set = 30
> throttle.max_peers.seed.set = 80
> trackers.numwant.set = 80
> 
> protocol.encryption.set = allow_incoming,try_outgoing,enable_retry
> 
> network.http.max_open.set = 50
> network.max_open_files.set = 600
> network.max_open_sockets.set = 300
> 
> pieces.memory.max.set = 1800M
> network.xmlrpc.size_limit.set = 3M
> 
> session = /home/rtorrent/.session
> directory = /home/rtorrent/
>
> encoding.add = utf8
> system.umask.set = 0027
> network.http.dns_cache_timeout.set = 25
> schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace, 1000M))
> schedule2 = watch_directory_TV, 22, 10, "load.start=/home/rtorrent/.torr/TV/*.torrent,d.directory.set=/home/rtorrent/TV/"
> schedule2 = watch_directory_Movies, 23, 10, "load.start=/home/rtorrent/.torr/Movies/*.torrent,d.directory.set=/home/rtorrent/Movies/"
> schedule2 = watch_directory_Music, 24, 10, "load.start=/home/rtorrent/.torr/Music/*.torrent,d.directory.set=/home/rtorrent/Music/"
> schedule2 = watch_directory_Apps, 25, 10, "load.start=/home/rtorrent/.torr/Apps/*.torrent,d.directory.set=/home/rtorrent/Apps/"
> schedule2 = watch_directory_Sport, 26, 10, "load.start=/home/rtorrent/.torr/Sport/*.torrent,d.directory.set=/home/rtorrent/Sport/"
> 
> log.open_file = "rtorrent", ~/log/rtorrent.log
> log.open_file = "tracker", ~/log/tracker.log
> log.open_file = "storage", ~/log/storage.log
> log.open_file = "torrent", ~/log/torrent.log
> 
> log.add_output = "info", "rtorrent"
> log.add_output = "critical", "rtorrent"
> log.add_output = "error", "rtorrent"
> log.add_output = "warn", "rtorrent"
> log.add_output = "notice", "rtorrent"
> log.add_output = "debug", "rtorrent"
> 
> log.add_output = "dht_debug", "tracker"
> log.add_output = "tracker_debug", "tracker"
> 
> log.add_output = "storage_debug", "storage"
>  
> log.open_file = "rtorrent.dht_debug.log", (cat,/home/rtorrent/log/rtorrent.dht_debug.log)
> log.add_output = "dht_debug", "rtorrent.dht_debug.log"
>  
> log.open_file = "rtorrent.tracker_debug.log", (cat,/home/rtorrent/log/rtorrent.tracker_debug.log)
> log.add_output = "tracker_debug", "rtorrent.tracker_debug.log"
>  
> log.open_file = "rtorrent.critical.log", (cat,/home/rtorrent/log/rtorrent.critical.log)
> log.add_output = "critical", "rtorrent.critical.log"
>  
> log.open_file = "rtorrent.error.log", (cat,/home/rtorrent/log/rtorrent.error.log)
> log.add_output = "error", "rtorrent.error.log"
>  
> log.open_file = "rtorrent.warn.log", (cat,/home/rtorrent/log/rtorrent.warn.log)
> log.add_output = "warn", "rtorrent.warn.log"
> 
> scgi_port = 127.0.0.1:5000

Any help is greatly appreciated.

**Comment by arti74** [comment]
I changed some syntax on the /usr/share/webapps/rutorrent/plugins/filemanager/xmlfix.php file - too much of "}", and now I have this error again:
> Bad response from server: (500 [error,getplugins]) Internal Server Error

Additionally can't check the plugins in UI, when I click on the settings icon in rutorrent, the result is:
> JS error: [http://192.168.1.74/rutorrent/js/webui.js : 762] TypeError: this.systemInfo is undefined

**Comment by arti74** [comment]
I'll try to downgrade php to php56 today...

**Comment by Novik** [comment]
Sorry, bu I can't understand - what is you want.
"I made changes in sources and program stop working".
Revert your changes.
Don't use unsupported third-party plugins like 'filemanager'.
Etc.

**Comment by arti74** [comment]
I just want to confirm that everything works good on the php56...
@Novik - I'm grateful for your great job on rutorrent. 
Those third-party plugins are enabled default when installing rutorrent on archlinux. I disabled some, that I will not use.
