### ISSUE TITLE
rtorrent-ps and xmlrpc-c

### ISSUE THREAD

**Issue by latumus** [Novik/ruTorrent#1691]
im running rtorrent-ps which is compiled against xmlrpc-c 1.48.00
yet rutorrent returns the error:
[24.04.2018 17:29:34] rTorrent is compiled with incorrect version of xmlrpc-c library, without i8 support. Version must be >= 1.11. Some functionality will be unavailable.
rtorrent-ps developer stated "there is no to_kb in modern rtorrent" he feels the issue lies there within rutorrent

**Comment by Novik** [comment]
Sorry, but I don't know anything about 'rtorrent-ps". ruTorrent doesn't support them.
Try to use normal rtorrent.

**Comment by latumus** [comment]
ok it's sorted i found out they have a -D option to allowed deprecated commands but i think this still needs to be fixed for future releases because you are expecting to_kb commands etc which isnt supported anyways and your error handling is off it should just reply "command not found" instead of assuming a lower version

**Comment by MimisK13** [comment]
Just to confirm this is still reproducible in 2026.

Setup:
- rTorrent 0.16.x
- ruTorrent latest
- xmlrpc-c >= 1.4x
- Docker (Alpine-based image)

ruTorrent still reports:
"rTorrent is compiled with incorrect version of xmlrpc-c library, without i8 support"

Even though xmlrpc-c is recent and functionality is not affected.
This appears to be the same false-positive detection discussed above (deprecated command probing).

Not requesting a fix — just documenting that this warning still appears and is harmless, to avoid confusion for new users.
