### ISSUE TITLE
What is the Default port (ssh) it installs to if not specified in rutorrent?

### ISSUE THREAD

**Issue by s-c-o-o-t** [Novik/ruTorrent#1697]
What is the Default port it installs to if not specified in rutorrent?

**Comment by Novik** [comment]
Sorry, but I can't understand you.
ruTorrent is not provide any SSH capabilities.

**Comment by s-c-o-o-t** [comment]
What I mean, When you install rtorrent the port you connect to the shell

**Comment by Novik** [comment]
This has not relation to the ruTorrent.
