### ISSUE TITLE
Plugins Slow Download Speeds

### ISSUE THREAD

**Issue by freeagent1384** [Novik/ruTorrent#1703]
When I disable all the plugins in plugins.ini setting enabled = no I can reach speeds over 8MBps however when the plugins are enabled highest download rate is around 500 KBps.  I've tried to remove all the plugins from the plugins folder then adding them one by one and there are a few that have no effect on speed (like _getdir or scheduler) and there are others which as soon as I refresh and load the plugin slow things back down (like _task and erasedata).

I also attempted to clone a fresh copy of rutorrent but this didn't change the behavior.  I don't see any significant resource utilization and disk IO is well within range.

Server is running on a dedicated Debian 9.4 box using Stable fully updated and an nginx server on 2 cores with 2GB of RAM

**Comment by Novik** [comment]
We have a lot of plugins, and most of them to register various hooks in rtorrent, use rtorrent's scheduler etc. And, of course, this is not good for perfomance.
If you will read wiki (https://github.com/Novik/ruTorrent/wiki/Plugins) , then you may to find one phrase:

Attention! Please install only those plugins you really need.

**Comment by freeagent1384** [comment]
If I had 20 plugins installed and resources were capping out I would agree with you and feel like quite the fool for missing your quote.  However, when going from three plugins to four has no impact on resources but my maximum download speed is reduced from 8 MBps to 500 KBps I suspect something else is going on but lets just assume it's as you say.
