### ISSUE TITLE
Debian9 weird read/execute access

### ISSUE THREAD

**Issue by pwpx2** [Novik/ruTorrent#1709]
This is quite weird. It's my first time installing rutorrent/rtorrent on debian 9 stretch and already it is giving me problems.
I did exactly the same steps as when installing on debian 7&8 but now i get a lot of...

> unpack: Plugin will not work. rTorrent user must have read/execute access to the file (/var/www/html/rutorrent/plugins/unpack/unall_dir.sh).

rtorrent is running as root because thats the way i like/want it. So basically root should have access to any part of the server including the /var/www/html... but for some reason it doesnt?
Could be because i am using php 7 ?

**Comment by s-c-o-o-t** [comment]
unall_dir.sh is an executable   Try  chmod 755

**Comment by pwpx2** [comment]
But i am using the root. I should have all access

**Comment by Novik** [comment]
> But i am using the root. I should have all access.

This doesn't helps you to run script without setted execute flag.

**Comment by pwpx2** [comment]
I just reinstalled debian8 with php5.6 and everything works fine after installing rtorrent+libtorrent and rutorrent.
I honestly don't know what was happening on debian9

**Comment by s-c-o-o-t** [comment]
So honestly , it had nothing to do with rutorrent/rtorrent. It was to do with os itself ? ;=-)

**Comment by hapylestat** [comment]
check is selinux is not activated on your debian 9, afaik it is first debian with this nice feature =)

**Comment by henryford** [comment]
Debian 9 does not have selinux enabled by default. selinux was available on Debian since at least 5, probably earlier though.

However, the problem is definetly on phps side. Do you have any error logs from your webserver? Are you able to run the sh script from the command line? You probably simply forgot to make that script executable.
