### ISSUE TITLE
RSS syntax?

### ISSUE THREAD

**Issue by htilly** [Novik/ruTorrent#1714]
Hi!

I'm trying to understand the syntax of the "filter" file (or the one line in that file).
Think I have figured out the most, except ;s:2:"50" in the example below.
Obviously, s:2 declare that the field will contain 2 characters.. But where/what are the actual value based upon, in this example "50" ?

"linkCheck";s:1:"0";s:2:"no";s:2:"50";s:8:"interval";s:2:"-1";s:7:"matches";a:0:{}}}}

Thanks in advance...

Oho..  there isn´t any API to alter this file, is there?
Trying to build an external automation for updating the RSS filers..

**Comment by htilly** [comment]
Hi and thanks for a fast reply. 
I do get the structure, but I can't figure out the value and where it comes from..  I.e, when entering/looking thru the WebUI..
So in the two examples below, where does the values 25 and 16 come from?:
s:2:"no";s:2:"25";
and
s:2:"no";s:2:"16";

If I automatically would insert a new entry from an external script I have everything working except this field. Based on what do I set this value?
My goal is to automatically insert more RSS filters thru external source.

i:8;
O:10:"rRSSFilter":17:{
s:4:"name";s:7:"Divorce";
s:7:"pattern";s:23:"/.*Divorce.*S0.*720.*/i";
s:7:"exclude";s:0:"";
s:7:"enabled";s:1:"1";
s:7:"rssHash";s:32:”12345678900987654321123456789009”;
s:5:"start";s:1:"1";
s:7:"addPath";s:1:"1";
s:9:"directory";s:42:"/fast_down/content/Other/Torrents/TVShows/";
s:5:"label";s:0:"";
s:8:"throttle";s:0:"";
s:5:"ratio";s:0:"";
s:10:"titleCheck";s:1:"1";
s:9:"descCheck";s:1:"0";
s:9:"linkCheck";s:1:"0";
s:2:"no";s:2:"25";
s:8:"interval";s:2:"-1";
s:7:"matches";a:0:{}}

i:9;
O:10:"rRSSFilter":17:{
s:4:"name";s:13:"GameOfThrones";
s:7:"pattern";s:24:"/.*Game.*Of.*Thrones.*/i";
s:7:"exclude";s:0:"";
s:7:"enabled";s:1:"1";
s:7:"rssHash";s:32:”12345678900987654321123456789009”;
s:5:"start";s:1:"1";
s:7:"addPath";s:1:"1";
s:9:"directory";s:58:"/fast_down/content/Other/Torrents/TVShows/Game.of.Thrones/";
s:5:"label";s:0:"";
s:8:"throttle";s:0:"";
s:5:"ratio";s:0:"";
s:10:"titleCheck";s:1:"1";
s:9:"descCheck";s:1:"0";
s:9:"linkCheck";s:1:"0";
s:2:"no";s:2:"16";
s:8:"interval";s:2:"-1";
s:7:"matches";a:0:{}}

**Comment by Novik** [comment]
> So in the two examples below, where does the values 25 and 16 come from?:

This is a values of 'no' property of object with type 'rRSSFilter'.
It contains filter number.
Check plugin's source for details.
For example, you may see function 'theWebUI.loadFilters' in the rss/init.js file.
Pay attention to the 'f.no' and 'theWebUI.maxFilterNo' variables.
