### ISSUE TITLE
Possible to save the layout of ruTorrent interface?

### ISSUE THREAD

**Issue by SteveMalso** [Novik/ruTorrent#1719]
You are able to customize the layout of the ruTorrent interface but it doesn't appear to save. After a crash or restart, ruTorrent will revert back to its default layout arrangement. Is this an unavailable feature, a misconfiguration on my end or have I overlooked a setting?

**Comment by Micdu70** [comment]
ruTorrent WebUI can't "crash" or "restart". If you speak about rtorrent, I don't see how it can alter the layout of ruTorrent.

If it doesn't save, check the permissions of "share" directory (at the root of ruTorrent) and try to fix them (assuming 'www-data' is the webserver user and '/var/www/rutorrent' your rutorrent installation path):

```
cd /var/www/rutorrent
chown -R www-data:www-data share/
find share/ -type d -exec chmod 777 {} \;
find share/ -type f -exec chmod 666 {} \;
```

**Comment by SteveMalso** [comment]
Interesting, thank you. I was referring to a crash/restart of rtorrent. I believe those file permission changes solved my issue. I followed a rutorrent setup tutorial which instructed the following permission:

sudo chmod -R 755 /var/www/rutorrent

Guess that's incorrect. Thank you for your very much for your help.
