### ISSUE TITLE
Selected torrents go out of view, still selected

### ISSUE THREAD

**Issue by chesterjazzman** [Novik/ruTorrent#1722]
I just had a really unpleasant experience... here are the steps to reproduce:

I had 50 some torrents in the Error view, many were connection issues.
I did a Ctrl+A to select all of them, thinking I could stop and start them en masse.
Many of the errors were resolved, and the torrents disappeared from the Errors view.
The remaining one had an error that persisted (torrent was deleted from the tracker).
I right-clicked the remaining torrent and chose Remove.
All 50 of the original torrents in the error view were removed!  I expected only the one I could see, selected in front of me would be removed.

As far as I can tell there's no way to go back and undo this, so I'm stuck grabbing the .torrent files again manually for all the stuff I need to seed.

When a torrent is no longer included in a view due to a status change, could you please make sure it is deselected to avoid this issue in the future?

**Comment by Micdu70** [comment]
I did an another approach to solve your issue.

"Start / Pause / Stop / Check data / Update Tracker / Recreate torrent files" commands deselect the torrents.

And I made a patch to display number of selected torrents, It's helpful I think... ^^ : #1723

**Comment by Micdu70** [comment]
I have closed the previous patch, there is now a better one which do exactly what you want (or don't want ahah). ;-)

**Comment by chesterjazzman** [comment]
Interesting, so now I guess it is up to Novik to review your patch, and accept or reject that pull request?  Thank you for your help!
