### ISSUE TITLE
Torrents column added is blank sometimes

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1731]
Hello,
in ruTorrent is column Added. If torrents are automatically added via autodl-irssi, everything is ok. If I add torrent by drag and drop to ruTorrent GUI from my computer or just moved torrent to watch folder, column added is blank.

Using arakasi72/rtinst with rTorrent 0.9.7/0.13.7 in Debian Linux.

Any fix? Thank you

**Comment by Micdu70** [comment]
Don't have this issue with Drag&Drop (Chrome latest version) or this bug happen very few times... I only have 1 torrent with blank added column. (Don't remember how I added it)

I will investigate a bit... ^^

**Comment by USRGH** [comment]
just found every new torrents have blank column Added. Torrents from autodl-irssi have blank column too. It worked fine some days ago, didn't change anything in config.

Restarted server, same result.

**Comment by Micdu70** [comment]
Do you have blank "added" column in History tab too?

I installed rtorrent/libtorrent (0.9.7/0.13.7) some days ago and no issue actually.

My Config:
- Apache 2.4.33
- PHP 7.2.7
- Using "httprpc" plugin in ruTorrent for rtorrent remote ("rpc" plugin disabled with plugins.ini file conf)

**Comment by USRGH** [comment]
Didn't history plugin enabled. Enabled it now, added new torrent and removed it after some seconds. Have added column there too and it's blank too.

checked plugins.ini file and have httprpc enabled too. RPC plugin is disabled.

**Comment by sam20e** [comment]
3 years and still no update?
