### ISSUE TITLE
Add option to display sizes in KB/MB/GB

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1732]
As the title says, is there a way to display in KB, MB, GB and TB?

**Comment by Micdu70** [comment]
What is the problem of KiB, MiB, GiB and TiB? It's the universal computer capacity format.

Or you mean Kb, Mb, Gb and Tb maybe?

**Comment by SebbaGerra** [comment]
There's no problem. You are right, I mean Kb, Mb, Gb and Tb.
Is there any change that I can do to get the size in this way?

**Comment by Micdu70** [comment]
Not actually, but creating a setting option between "Bytes" and "bits" units is possible of course. :)

**Comment by SebbaGerra** [comment]
On rtorrent I have that information

```
Memory usage.........: 4.0 MB
Max memory usage.....: 3500.0 MB
Free diskspace.......: 620013.2 MB
Safe diskspace.......: 516.0 MB
Upload...............: 0.0 KB / 755.7 MB
Download.............: 0.0 KB /   0.0 KB
Skipped..............: 0.0 KB /   0.0 KB
Preload..............: 1 / 1 / 1
```
For some users this alphabet soup (Kb, KB ou KiB) is confusing.

**Comment by SebbaGerra** [comment]
I think df command is using only M, G or T, it's confusing too

```
user@server:~$ df -H
File System            Size  Used  Avail Use% Mount point
/dev/sda2              50G   27G   21G   57%  /
user@server:~$ df -h
File System            Size  Used  Avail Use% Mount point
/dev/sda2              46G   25G   19G   57%  /
```

**Comment by Micdu70** [comment]
"df --help" gives this info:

-h = powers of 1024 ( = B, KiB, MiB, GiB, etc. )
-H = powers of 1000 ( = B, KB, MB, GB, etc. )

Confusing is easy yes...

**Comment by SebbaGerra** [comment]
On Windows "500GB" is show as

`500.104.687.616 bytes          465 GB`

a bit confusing
