### ISSUE TITLE
Filter torrents view by a search string

### ISSUE THREAD

**Issue by bogenpirat** [Novik/ruTorrent#1742]
I have a lot of torrents in r(u)Torrent, and whenever I want to find one particular one, I have to scroll down and hope that I can spot it. This takes up a lot of time and makes it difficult to, e.g., select and delete many torrents that share a common file name fragment.

To alleviate this, I propose a new feature: Add a text input field that is placed similarly to the "search external torrent sites" field. Upon entering text into this field, the torrents view should be reduced to only consist of torrents whose name contains the entered text as a substring.

Thank you kindly.

**Comment by Micdu70** [comment]
Hello, this feature is already available with [rutorrent-instantsearch](https://github.com/Gyran/rutorrent-instantsearch) 3rd party plugin.

**Comment by Novik** [comment]
> To alleviate this, I propose a new feature: Add a text input field that

This input field is already exists.
![2018-08-15_10h26_32](https://user-images.githubusercontent.com/1230409/44136533-cad344ae-a075-11e8-9fa9-af2b4aa1b94e.png)
