### ISSUE TITLE
Hi Novik.. Question About ExSearch

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Novik/ruTorrent#1745]
Any chance you adding more public search engines? Pirate Bay is on their way out and we need more alternatives. Also, some urls have changed:

Demonoid.pw
https://katcr.co/
http://www.btscene.com/
https://1337x.to/home/
https://www.seedpeer.eu/

The above are updated urls and reliable. Please add them and whatever public engine you can think of.. these really help a lot. It's so much easier to search from within the application. Thank you for your hard work!!!

**Comment by Micdu70** [comment]
Hello, I will try to do them. ;)

**Comment by Micdu70** [comment]
As of the 18th october, 2018:

http://www.demonoid.pw/ = Site Down...
https://katcr.co/ = Was added in extsearch 1 week ago
http://www.btscene.com/ = Site Down...
https://1337x.to/home/ = To do
https://www.seedpeer.eu/ (new URL) = To do
