### ISSUE TITLE
[plugins/extsearch] RARbgTorrentAPI not giving results: ratelimit triggered by asking for token and then results

### ISSUE THREAD

**Issue by skgsergio** [Novik/ruTorrent#1759]
I wanted to try the RARbg search and I observed that it gives no results so I started debugging the plugin.

I checked that asking manually for the token and then asking for results worked so I started digging a bit and checked the result codes for the petitions done by ruTorrent.  I discovered that the actual search that is done after asking for the token is giving a `429` error code, so it is hitting the rate limit by doing the two requests in a row.

Checking [the API docs](https://torrentapi.org/apidocs_v2.txt) it only allows 1 request every 2 seconds so `get_token` + the actual `action` petition is happening with less than 2 seconds of wait.

I can think of a couple of solutions here:
- The lazy one that I'm using: add a `sleep(2.1);` just after the `get_token` call (well I did it after the `$token!==false` check).
- Allow `fetch` to perform retries when it receives a `429`, maybe an optional parameter to set it to the number of seconds between retries and set it as -1 by default to disable the retry logic.
- The token lasts for 15 minutes, so another option is to cache it for less than 15 minutes and perform the `sleep(2.1);` only when the token is not set or the cache is older than 15 minutes. Still need to perform some sort of throttling if a new token is required, tho.

**Comment by Novik** [comment]
Check result now, please.

**Comment by skgsergio** [comment]
Working perfectly, thanks! ✨
