### ISSUE TITLE
[Question] 3.8 no need to access rutorrent for RSS to work

### ISSUE THREAD

**Issue by Nihim** [Novik/ruTorrent#1772]
I remember reading that with 3.8 (but can't find anywhere that info) it would no longer be required to access the rutorrent webui after restarting the web-server for the RSS to start working.

Am I wrong / right?

**Comment by oboote** [comment]
I was wondering the same; will RSS matching filters download in the "background" or does the WebUI need to be loaded in a browser before the RSS download is triggered?

**Comment by Novik** [comment]
If you have correct call of initplugins.php in your rtorrent.rc then

> will RSS matching filters download in the "background" 

yes

> does the WebUI need to be loaded in a browser before the RSS download is triggered?

no
