### ISSUE TITLE
Fast resume option while adding torrents from RSS

### ISSUE THREAD

**Issue by v9999** [Novik/ruTorrent#1774]
Hey there,

adding torrents from the "add torrent" icon lets you select the "fast resume" option.
However, when you add a torrent from a RSS feed, there's no option to fast resume, and hash check becomes unavoidable.

How can I make a torrent from a rss feed fast resume instead of going through a check?

**Comment by Novik** [comment]
'Fast resume' option is intended for cases, when you *already* have data for this torrent.
How this may happens with a RSS feed?

**Comment by v9999** [comment]
> 'Fast resume' option is intended for cases, when you _already_ have data for this torrent.
> How this may happens with a RSS feed?

Mostly when it comes to cross-seeding in multiple trackers.
I guess the idea is similar to "match duplicates" in autodl-irssi (even though I'm not sure if rutorrent will hash check in this case).
