### ISSUE TITLE
ruTorrent 3.8 + Oblivion Theme + autodl-irssi Filters window

### ISSUE THREAD

**Issue by baz357** [Novik/ruTorrent#1792]
My account was updated from ruTorrent 3.7 to ruTorrent 3.8 today. Now the autodl-irssi Filters window doesn't show properly* unless I increase the window zoom in Chrome to 150%. Not sure if the cause is ruTorrent or autodl-irssi (which already was up to date).

*The "General | P2P | TV/Movies..." bar is shown at the bottom of the autodl-irssi Filters window:

![screenshot - 2018-11-07](https://user-images.githubusercontent.com/20575996/48142664-7d0ca380-e2ad-11e8-86ad-53a4f211b96c.png)

**Comment by TMTYD** [comment]
hi 

i have no problems with this theme and autodl-irssi filters option

**Comment by Novik** [comment]
Sorry, but I have not any relation to the plugin 'autodl-irssi' Try to ask from his author.
