### ISSUE TITLE
datadir: Plugin will not work. rTorrent user can't access external program (php).

### ISSUE THREAD

**Issue by kevin201** [Novik/ruTorrent#1793]
What is this actually looking for? Clearly not php as php -v at the command prompt as the rTorrent user produces the expected result.

This is running on a QNAP, there is only one user. Everything else seems to be running fine, I've only just added this datadir plugin today (there's only rpc and seedingtime plugins apart from this)

All the permissions look ok. Any clues on how to find the actual problem would be greatly appreciated.

**Comment by tuxayo** [comment]
Which permissions did you check? For the user running rtorrent? Or the server web user running ruTorrent?

I my case I have the group that gives access to one user, and the owner which gives access to the other. (I could have created a torrent group though)

**Comment by kevin201** [comment]
By the way, I may be mistaked, but I think the execute command might be deprecated at line 175 of getplugins.php

**Comment by Micdu70** [comment]
@kevin201 "execute" command is deprecated, "execute2" should be used yes.
So I just updated methods-0.9.4.php (#1797).

**Comment by kevin201** [comment]
Great! I don't pretend to understand this completely, but will this help with my addin problem? It seems to be connected:

```
function findRemoteEXE( $exe, $err, &$remoteRequests )
{
	$st = getSettingsPath().'/'.rand();
	if(!array_key_exists($exe,$remoteRequests))
	{
		$path=realpath(dirname('.'));
		global $pathToExternals;
		$cmd = array( "sh", addslash($path)."test.sh", $exe, $st );
		if(isset($pathToExternals[$exe]) && !empty($pathToExternals[$exe]))
			$cmd[] = $pathToExternals[$exe];
		$req = new rXMLRPCRequest(new rXMLRPCCommand("execute", $cmd));  <== this line caused an error
		$req->run();
		$remoteRequests[$exe] = array( "path"=>$st, "err"=>array() );
	}
	$remoteRequests[$exe]["err"][] = $err;
}
```

**Comment by kevin201** [comment]
Sorry, how is this closed? I can't see how it has addressed the initial problem.

**Comment by Novik** [comment]
Try to check result first.

**Comment by kevin201** [comment]
Yes, that seems to have done the trick! Thanks.
