### ISSUE TITLE
UI stopped respoding after attempt to create .torrent file.

### ISSUE THREAD

**Issue by bazarassa** [Novik/ruTorrent#1805]
Javascript at page can't work after attempt to create .torrent file with ruTorrent UI.
![default](https://user-images.githubusercontent.com/10389398/48989094-b9f3e980-f139-11e8-8008-a1a11d6baf5b.png)
Reinstalling can fix this issue, but again, if attempting to create torrent, JS stopped work.

> [26.11.2018 04:52:07] WebUI started.
> [26.11.2018 04:52:07] Bad response from server: (500 [error,getplugins]) Internal Server Error
> [26.11.2018 04:52:09] JS error: [http://tk1tez.tk/ruTorrent/js/stable.js : 1742] TypeError: this.dBody is undefined

**Comment by Micdu70** [comment]
Hello,

> [26.11.2018 04:52:07] Bad response from server: (500 [error,getplugins]) Internal Server Error

You have an error 500 so you need to check your Webserver and PHP logs about that.

**Comment by bazarassa** [comment]
/var/log/apache2/error.log

>  PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/ruTorrent/plugins/_task/task.php:150\nStack trace:\n#0 /var/www/html/ruTorrent/plugins/_task/task.php(163): rTask::tail('/var/www/html/r...')\n#1 /var/www/html/ruTorrent/plugins/_task/task.php(228): rTask::processLog('/var/www/html/r...', 'log', Array, 0, 0)\n#2 /var/www/html/ruTorrent/plugins/_task/task.php(102): rTask::check('15432601365bfc4...', 0)\n#3 /var/www/html/ruTorrent/plugins/create/action.php(145): rTask->start(Array, 0)\n#4 {main}\n  thrown in /var/www/html/ruTorrent/plugins/_task/task.php on line 150

Ok, i see, this requires `php-mbstring`. After installing it, all works propertly. Closed.

**Comment by Micdu70** [comment]
Some plugins uses some mbstring alternatives "tricks" functions if it is not installed. Except for "_task" plugin (task.php), "create" plugin (action.php) and "xmpp" (XMPPHP/XMLStream.php).

For these plugins, if no alternatives are possible, it should have "php.extensions.error: mbstring" line in their "plugin.info" file. @Novik
