### ISSUE TITLE
RSS status is lost

### ISSUE THREAD

**Issue by jcalado** [Novik/ruTorrent#1810]
AFAIK, the ruTorrent RSS plugin will check if link/enclosure tag changes as a part of determining if a torrent is in fact new.

Problem is, using ruTorrent with jackett will reset the "loaded" status of each item on a rss update, since the link/enclosure tags are different every time, despite the name and pubdate being the same.

Shouldn't the guid tag be used instead?
That's what the [RSS 2.0 spec](https://validator.w3.org/feed/docs/rss2.html) says:

> guid | A string that uniquely identifies the item. More. | <guid isPermaLink="true">http://inessential.com/2002/09/01.php#a2</guid>

**Comment by jcalado** [comment]
Reported this to jackett as well, but the ticket was closed, as per the rss spec a reader is supposed to use guid tags to figure out if an item is new.

https://github.com/Jackett/Jackett/issues/4292

**Comment by Novik** [comment]
> Shouldn't the guid tag be used instead?

In theory - yes. But in practice RSS plugin is one of oldest and complex plugins. And now I can't see an easy way for make these changes, sorry.
