### ISSUE TITLE
Release new Stable Version

### ISSUE THREAD

**Issue by Spedwards** [Novik/ruTorrent#1812]
The seedbox I use is currently using a version of ruTorrent that has a problem that I find very annoying that was fixed in e1b6dcb1bd350fe6f2067595a27547c067b09af1. This update was merged after v3.8. v3.8 is well over a year old now. My seedbox and other companies running this won't update to a development build, so please release v3.9.

**Comment by cantalupo555** [comment]
Is it possible to test version 3.9?

**Comment by KyleSanderson** [comment]
@Novik any update on this? I'm making docker files and am using stable versions :(

**Comment by Novik** [comment]
Done.
