### ISSUE TITLE
0.9.7 rtorrent support?

### ISSUE THREAD

**Issue by antiuser** [Novik/ruTorrent#1814]
Hi! I want to know, is 0.9.7 rtorrent version supported by rutorrent master?

**Comment by Novik** [comment]
Yes.

**Comment by antiuser** [comment]
I cannot get downloaded lists via RPC via rutorrent master, i get 500 error. rtorrent version 0.9.7

**Comment by Novik** [comment]
Check ruTorrent errors log. And web-server errors log.

**Comment by Novik** [comment]
Sorry, but I can't help. 
On my local configuration all works by normal way. 
Try to use rpc or httprpc plugins.

**Comment by antiuser** [comment]
Its strange, because after downgrade to 0.9.6, rutorrent works great.

**Comment by antiuser** [comment]
> Sorry, but I can't help.
> On my local configuration all works by normal way.
> Try to use rpc or httprpc plugins.

How to request rtorrent by xml-rpc to get downloaded list?

**Comment by Micdu70** [comment]
Hello, can you post a screenshot of ruTorrent?
How did you install rtorrent 0.9.7? And how did you start rtorrent?

**Comment by Micdu70** [comment]
I never used socket SCGI config. Try with IP:port (e.g.: 127.0.0.1:5000) instead?
And do not forget ruTorrent config ("conf/config.php" file) too.

**Comment by antiuser** [comment]
> I never used socket SCGI config. Try with IP:port (e.g.: 127.0.0.1:5000) instead?
> And do not forget ruTorrent config ("conf/config.php" file) too.

same result, even with tcp socket

**Comment by antiuser** [comment]
I can issume, that in new version rtorrent 0.9.7 xml requests changed

**Comment by Micdu70** [comment]
Hm... can you check "/tmp/errors.log" file? No issue here with rtorrent 0.9.7 and rutorrent 3.8 latest git update.

**Comment by antiuser** [comment]
Hm, i recompiled rtorrent and librtorrent, then restart, and rutorrent just worked again on version 0.9.7. Its strange, but fixed. So sorry for open issue. Thank you much!
