### ISSUE TITLE
Extratio rule doesn't apply on old torrent

### ISSUE THREAD

**Issue by adresch** [Novik/ruTorrent#1817]
Hello,
I'm facing an issue that i'm unable to solve.
Here is my problem:
I had multiple torrents with the tracker A
Now i created a rule with the filter "One of trackers url contains Tracker A".
My rule is applied to newly added torrent but not to the old one.
Is there a way to apply a rule on every torrent where uploaded before the creation of the rule ?

In advance, thanks and happy new year
Antoine

**Comment by Novik** [comment]
Try to change label on them.

**Comment by adresch** [comment]
Unfortunately I didn't solved my problème :/
Maybe you know if there exist a plug-in that can do something like that:

First, it would have to open a file containing a list of domain names and put it in an array.  Once that is done, he should get the list of all the torrents in seed or a break and do the following thing:

If one of the domain names present in the array generated just before is in one of the tracker url, let it put the torrent in finished.

Best regards, 
Antoine

**Comment by Novik** [comment]
Sorry, but I haven't information about such plugins.
