### ISSUE TITLE
error with initplugin

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1820]
I have this lines in my rtorrent config for initplugins "

method.insert = cfg.basename, private|const|string, (cat,"night-downloads/")
method.insert = cfg.basedir,  private|const|string, (cat,"/media/odroid/apps/app-data/rtorrent-rutorrent/",(cat,(cfg.basename)))
#execute2 = {sh,-c,/usr/bin/php (cat,(cat,(cfg.basedir)),"ruTorrent/php/initplugins.php &")}

but I get the error

rtorrent: Failed to parse command line option: Error in option file: /media/odroid/apps/app-data/rtorrent-rutorrent/night-downloads/rtorrent/rtorrent.rc:11: Could not find closing '}'.

what am I missing?

I use those parameters for other variables and they work.
for example this:
network.scgi.open_local = (cat,(cfg.basedir),"rtorrent/.socket")

**Comment by Novik** [comment]
Be simple. and don't use this damned syntax.
```
execute2 = {sh,-c,/usr/bin/php /media/odroid/apps/app-data/rtorrent-rutorrent/ruTorrent/php/initplugins.php &}
```
And should warn you - if you use authentication, then you must add user name before '&'.
