### ISSUE TITLE
geoip plugin issues

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#1821]
I noticed two minor issues:
- Flag are not diplayed for Curaçao 
- Country column not sorting properly

![clipboard001](https://user-images.githubusercontent.com/25719620/50724768-e31d7780-10f2-11e9-9452-7d85cb72ae24.png)

**Comment by Micdu70** [comment]
- geoip country codes are listed here -> https://dev.maxmind.com/geoip/legacy/codes/iso3166/
"CW" = Curacao and the flag (cw.gif) seems okay so I don't know how you can have this issue...

- Country column using the country code for sorting (followed by city name, if available), I tried to change that but I can't make it to work with country name yet...

**Comment by koblack** [comment]
> * geoip country codes are listed here -> https://dev.maxmind.com/geoip/legacy/codes/iso3166/
>   "CW" = Curacao and the flag (cw.gif) seems okay so I don't know how you can have this issue...

already fixed

> * Country column using the country code for sorting (followed by city name, if available), I tried to change that but I can't make it to work with country name yet...

thanks a lot for looking into that
