### ISSUE TITLE
Save as - no path or filename

### ISSUE THREAD

**Issue by bonk1990** [Novik/ruTorrent#1825]
Hi, I have a problem.

ruTorrent isn't displaying the full path of a torrent in the ‘Save As’ field of the ‘General’ tab for a selected torrent. Regardless of what the full path is it only displays the ‘Save to’ location (for me: ‘/media/downloads/torrent/completed’). This is making it impossible for me to copy a path or filename for a torrent within ruTorrent.

Every torrent: https://i.imgur.com/WxutTCm.png

How to fix this?

**Comment by Micdu70** [comment]
Hello,
This change was introduced in ruTorrent v3.8 but was reverted in latest development version (git).
Explained in #1505 and to fix this => https://github.com/Novik/ruTorrent/commit/8fc34959f91a6e6b99d0865fc36a50852e7cf3f9
=)

**Comment by bonk1990** [comment]
Thanks. Fixed it!
