### ISSUE TITLE
RSS URL Doesn't Support

### ISSUE THREAD

**Issue by Machou** [Novik/ruTorrent#1828]
Hi

I can't add this url to RSS Flux :

```https://www2.domain.gg/rss?action=generate&type=subcat&id=2181&passkey=key```

**Comment by Micdu70** [comment]
Hello,

No issue for me, using latest git version of ruTorrent.

**Comment by Machou** [comment]
> 
> 
> Hello,
> 
> No issue for me, using latest git version of ruTorrent. (Yggtorrent RSS URL)

I use the latest version :)

**Comment by Micdu70** [comment]
Maybe you can't access this torrent website from where ruTorrent is installed... try to use the "ExtSearch" feature of ruTorrent. (See => https://github.com/Novik/ruTorrent/wiki/PluginExtsearch , Yggtorrent is a "Private" Engine)

**Comment by Machou** [comment]
It's not a DDoS problem or anything, it's just that the regex that manages the urls is bad, you just have to modify it.

**Comment by Novik** [comment]
What is you mean?

1) Plugin RSS was modified half-year ago.
2) www2.domain.gg is not exists

**Comment by Novik** [comment]
Yes, works for me.

**Comment by Machou** [comment]
@Novik i have make a screenshot : https://i.ibb.co/p2P9cd6/Sans-titre-1.jpg

i use the latest version with git pull of ruTorrent and plugins.

**Comment by Novik** [comment]
Not informative, sorry.
Try to use link https://www2.yggtorrent.gg/rss?action=generate&type=subcat&id=2181&passkey=key as is without any replacements. 
I s it works for you?

**Comment by Machou** [comment]
Nop :(

**Comment by Machou** [comment]
I don't know if you've changed anything, but now it's working.
