### ISSUE TITLE
PtP external search doesn't work

### ISSUE THREAD

**Issue by AggelosM** [Novik/ruTorrent#1832]
ruTorrent/plugins/extsearch/engines/PtP.php needs update.

**Comment by Micdu70** [comment]
I don't have an account on this tracker. Can you send an invite?

If not, you may add, between line 32 and 33 of  "plugins/extsearch/engines/PtP.php", this following line `print_r($cli->results);`
Then do a search in ruTorrent (it will return a red error message).
In "Logs" tab, copy all lines and paste them on this website => https://privnote.com/

Send me the privnote sharing link: Micdu70@gmx.fr

I will create a PR after, only if login still works and search URL has not changed.
