### ISSUE TITLE
RSS Downloader isn't downloading things automatically

### ISSUE THREAD

**Issue by holygamer** [Novik/ruTorrent#1835]
I've had RSS downloader working fine for several months on my FeralHosting seedbox. I've setup RSS Manager to download things automatically. But today it's no longer downloading torrents automatically. To get it to download things in my feed I have to right-click on All Feeds and select "Update Feed".

I'm using rTorrent 0.9.6/0.13.6.

**Comment by m00nsl47r** [comment]
I am also having this issue. Are we missing something?

**Comment by inside83** [comment]
Same here, just different provider.
Using 0.9.8/0.13.8
