### ISSUE TITLE
Plugin failed to start

### ISSUE THREAD

**Issue by kevin201** [Novik/ruTorrent#1841]
I'm trying to use a couple of plugins (erasedata and rss) and I'm getting a "Plugin failed to start" for each of them. Looking in the errors.log I can see:

`<value><struct><member><name>methodName</name><value><string>schedule</string></value></member><member><name>params</name><value><array><data>
`

and

`<value><string>Method 'schedule' not defined</string></value></member></struct></value>`

As I recall, "schedule" is depracated. Could it be that this has been left out of the updates?

Thanks for your time.

**Comment by Novik** [comment]
Try to remove flags ```-I``` and ```-K``` from the rtorrent command line.

**Comment by kevin201** [comment]
Thanks Novik. Allowing intermediate commands by taking out the -I solves the immediate problem.

**Comment by Novik** [comment]
After commit above you may use these flags without troubles (I hope).

**Comment by kevin201** [comment]
I will try. Thanks again.
