### ISSUE TITLE
Please do request at random minute for each client

### ISSUE THREAD

**Issue by stopcenz** [Novik/ruTorrent#1844]
I am the owner of the service using your plugin rutracker_check. 

Now all clients automatically send requests synchronously at 0 minutes of each hour. I observe a nasty uneven load on the server:

[http://images.vfl.ru/ii/1536308765/c3e99035/23228450.png](url)

I would appreciate if you find a little time to fix it.

**Comment by Novik** [comment]
See config.pfp, variable $schedule_rand.
This variable contain random addition to the start of rtorrent schedule (in seconds).

**Comment by stopcenz** [comment]
Thank you for your prompt reply, but you misunderstood me. I do not use ruTorrent, I am the owner of the server to which your plugin sends requests.

I looked at your code. All clients **synchronously** start requests at 0 minutes, 10 seconds of every hour.

I have no connection with people installing rutracker_check on their computers. The more I can not change the settings on their machines. I spent more than a year trying to figure out the source of the problem. (By the way, it would be a great idea to leave a hint in the request headers).

Thus, I hope only on you. I ask you to change the program so that during each installation, not a fixed value "10" is automatically assigned, but a random value of 0..3600 for the $ schedule_rand variable. **Different value for each client** is important.

Of course, if the admin does not wish to change these settings manually.

**Comment by stopcenz** [comment]
Perhaps the correct solution will be to count from the start of the program. If the program started at 07:19, then requests will occur 07:19, 08:19, 09:19 ...

**Comment by Novik** [comment]
> I looked at your code. All clients synchronously start requests at 0 minutes, 10 seconds of every hour.

This is incorrect assumption. For the each initial request we have random delay from 0 to 10 seconds. And this request will be repeated with a 1 hour interval.

Anyway, what do you want from me, really?
I haven't control under user's installations (and I say more - this project has not 'installation' at all).
I can to change plugin's code, but this will not helps to you, because most of users will use old version of plugin.

**Comment by Novik** [comment]
I made corresponding changes.
