### ISSUE TITLE
Unable to add RSS Feed

### ISSUE THREAD

**Issue by PureSkillz** [Novik/ruTorrent#1848]
I installed ruTorrent 3.7-8 from SynoCommunity using Apache 2.2 and PHP 5.6 on DSM 6.2. The WebUI loads fine but when I try to add RSS Feeds Ii get an error as seen on my screenshot. In this example, the URL of the feed is fake but the same happens with valid RSS feeds such as YTS, EZTV or others.

I tried the Snoopy.class.inc fix, the TempDirectory trail slash fix but none solved the issue,

![uTorrent Add Feed Error](https://user-images.githubusercontent.com/8690142/54961981-60f65f80-4f39-11e9-84d8-8cd89585582e.png)

**Comment by Novik** [comment]
Stop using ancient versions, please.
Reports about them is not interesting for me.
