### ISSUE TITLE
scrolling torrents with mouse wheel

### ISSUE THREAD

**Issue by flier56** [Novik/ruTorrent#1851]
scrolling torrents with mouse wheel is broken in firefox 66 and above scrolls very fast no control

**Comment by Novik** [comment]
Turn on 'Full render of large tables' checkbox on the General tab od Settings dialog.

**Comment by Novik** [comment]
Or turn off 'Show table contents while scrolling' checkbox.

**Comment by flier56** [comment]
Turn on 'Full render of large tables fixed it Thanks

**Comment by Novik** [comment]
I hope now this will correctly work with any checkbox positions.

**Comment by Micdu70** [comment]
Still buggy for me... Thanks Mozilla Firefox for this crap update. xD

**Comment by Novik** [comment]
Try to press Ctrl-F5 and/or clear browser cache. 
All DOM elements 'div.table_tab' now must have css option ```overflow-anchor: none```.
You may control this via the browser inspector.

**Comment by Novik** [comment]
Try yet once.

**Comment by Nodens-** [comment]
I tested it and can verify the fix.

**Comment by Micdu70** [comment]
Yeah it's working perfectly now, thanks @Novik :)
