### ISSUE TITLE
@ . In Username Issue

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#1852]
Since updated rutorrent today I can no longer connect to rutorrent.

It appears to be an issue with the @ and . character in the username as in the /rutorrent/share/users folder the username is now being renamed to remove the @ and . characters.

So if your username is myname@email.com its renamed to myname_email_com

**Comment by Novik** [comment]
And this is correct behavior.
For preventing XSS attacks username can contain only alphanum characters + underscore.
Rename corresponding folders inside share/users and conf/users to the correct form.
Set correct username in the 'initplugins' string inside .rtorrent.rc.
