### ISSUE TITLE
"Added" and "Finished" fields not being populated

### ISSUE THREAD

**Issue by mtw3d** [Novik/ruTorrent#1859]
When I add a torrent, the "added" timestamp is not being set, and the finished stamp is not set when it finishes.  Googling found a suggestion to just change the date format in the settings, and that had previously seemed to fix it, but after upgrading to rtorrent 0.9.6 and ruTorrent 3.7 it no longer seems to work. 

Thanks!

**Comment by Novik** [comment]
1) Date format has not relation to this. Plugin 'seedingtime' must be installed and enabled.
2) Stop using ancient versions, please. Current version is 3.8 and during this week it will be 3.9.
