### ISSUE TITLE
Uncontrollable scrolling down with newer versions of Firefox due to Scroll Anchoring

### ISSUE THREAD

**Issue by Nodens-** [Novik/ruTorrent#1860]
Tested on Firefox 66.0.2

While Full Rendering of Large Tables is off scrolling down with the mouse wheel becomes uncontrollable.
The only workaround so far is setting layout.css.scroll-anchoring.enabled to false in about:config.

This needs fixing in ruTorrent.

See here: https://bugzilla.mozilla.org/show_bug.cgi?id=1305957

**Comment by Micdu70** [comment]
"Should" be fixed in latest git version, this issue was already reported => #1851

**Comment by Novik** [comment]
Dublicate.

**Comment by Nodens-** [comment]
Tested latest git and indeed it is fixed. I will go ahead and close this. Also sorry for the noise, I did search but somehow missed https://github.com/Novik/ruTorrent/issues/1851
