### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by nicktawan** [Novik/ruTorrent#1875]
rtorrent 0.9.6, rutorrent 0.13.6
Got this error
"_cloudflare plugin: CfScrape module can't be loaded in Python"
How can I resolve

**Comment by Novik** [comment]
Install corresponding module for python, if you need this plugin. Or disable this plugin otherwise. 
https://github.com/Novik/ruTorrent/issues/1870#issuecomment-480913560

**Comment by nicktawan** [comment]
Thank you

**Comment by dausruddin** [comment]
Just in-case anyone got here like I did, install `cloudscraper` instead of `cfscrape`
```
sudo pip install cloudscraper
```

Reference: https://github.com/Novik/ruTorrent/wiki/Plugin_cloudflare
