### ISSUE TITLE
[Plugin Request] ffprobe

### ISSUE THREAD

**Issue by dausruddin** [Novik/ruTorrent#1881]
Hi. It is nice to have mediainfo plugin. But can we have [ffprobe ](https://www.ffmpeg.org/ffprobe.html)too?
Thanks

**Comment by dausruddin** [comment]
@Novik how can I specify multiple flags to task?
I am trying to make FFprobe plugin by modifying mediainfo plugin.
I need 2 flags on https://github.com/Novik/ruTorrent/blob/c517387b69811f4f41a4ba9daead8a33a1be84a8/plugins/mediainfo/action.php#L61 
`rTask::FLG_WAIT` and `rTask::FLG_NO_ERR` because FFprobe write output to stdout.

Currently it is working but since the output is written to sdout, response is displayed in **Diagnostics** section instead.

**Comment by Novik** [comment]
By default plugin display information from stdout in the 'Log' section and information from stderr in the 'Diagnostic' section. Also plugin has such flags:
```
	const FLG_WAIT		= 0x0001;
```
Plugin will wait result of command immediately instead usage of polling (default). 
```
	const FLG_STRIP_LOGS	= 0x0002;
```
Plugin will keep only 80 newest lines in the 'Log' section.
```
	const FLG_ONE_LOG	= 0x0004;
```
Plugin will redirect stderr to the 'Log' section
```
	const FLG_ECHO_CMD	= 0x0008;
```
Plugin will display command with arguments in the 'Log' section
```
	const FLG_NO_ERR	= 0x0010;
```
Plugin will ignore stderr output
```
	const FLG_RUN_AS_WEB	= 0x0020;
```
Plugin will use web server user for execution of commands (by default - rtorrent user).
```
	const FLG_RUN_AS_CMD	= 0x0040;
```
Plugin will use combination 'sh -c "command"' instead "command" for launch. Used only with FLG_RUN_AS_WEB flag.
```
	const FLG_STRIP_ERRS	= 0x0080;
```
Plugin will keep only 80 newest lines in the 'Diagnostic' section.
```
	const FLG_NO_LOG	= 0x0100;
```
Plugin will redirect stdout and stderr to the 'Diagnostic' section
```
	const FLG_REMOVE_ASCII	= 0x0200;
```
Plugin will remove ASCII control characters from output of both sections.

By default plugin use combination FLG_STRIP_LOGS + FLG_ECHO_CMD.

> how can I specify multiple flags to task?

For example,

```
$task->start( $commands, rTask::FLG_RUN_AS_WEB | rTask::FLG_NO_ERR);
```
or
```
$task->start( $commands, rTask::FLG_RUN_AS_WEB + rTask::FLG_NO_ERR);
```
for this case '|' and '+' are identical.

**Comment by dausruddin** [comment]
I don't know why, but whenever I put 2 flags, the plugin returns empty log and empty error.

`{"no":"15716793875dadec9b8e42a1.69724454","pid":8154,"status":0,"log":[],"errors":[],"params":{"arg":"VIDEO.mkv","requester":"ffprobe","name":"ffprobe","hash":"7A694042BFA595FC650EE3BEB879D4B5D72876BC","no":"0"},"start":1571679387,"finish":1571679389}`

But it works fine with only 1 flag, except the output is stderr.

I have uploaded the code to github and this is that specific line
https://github.com/dausruddin/ffprobe-rutorrent/blob/b2cfa7cac9acf99e9e0def31fa11fe851caee013/action.php#L61

It took me a day to make these simple modifications because I has to study how plugins work. So I might do some mistake in the code. Hope you can help me.

**Comment by Novik** [comment]
Try to read documentation - https://ffmpeg.org/ffprobe.html
> By default the program logs to stderr

I.e. you should use plugins flag FLG_ONE_LOG. 
This flag will redirect stderr to the Log window.
Now you use flag FLG_NO_ERR. With this flag plugin will ignore all stderr output. I.e. you will see nothing.

Also should to say - i18n js technique is incorrect in your (and mediainfo) plugins.
You may have execution of this line 
https://github.com/dausruddin/ffprobe-rutorrent/blob/master/init.js#L34
before loading of theUILang for your plugin.

For avoid this you shoud 
1) Add line 
```
thePlugins.get("YOUR_PLUGIN_NAME").langLoaded();
```
to the end of the each lang file OR (and this is preferable way, because MS IE is died) change line
https://github.com/dausruddin/ffprobe-rutorrent/blob/master/init.js#L1
from
```
plugin.loadLang();
```
to 
```
plugin.loadLang(true);
```
2) Change line 
https://github.com/dausruddin/ffprobe-rutorrent/blob/master/init.js#L15
from
```
if(plugin.enabled) 
```
to
```
if(plugin.enabled && plugin.allStuffLoaded)
```

**Comment by dausruddin** [comment]
thanks a lot for your time looking into the code :)
it is working fine now.
