### ISSUE TITLE
create torrent not cancel

### ISSUE THREAD

**Issue by petersonti** [Novik/ruTorrent#1884]
267/5000
Hello, I'm using rtororrent version v3.9 rtorrent 0.9.7.
My problem when creating the torrent, if I click cancel, the process remains active:
/usr/bin/php ./createtorrent.php 1556 ***.80** myusername
(*** is the continuation of the numbers)
How to fix this?

**Comment by Micdu70** [comment]
Hi, the rutorrent "create" plugin needs to be updated to include a kill process function. ;-)
