### ISSUE TITLE
Torrent don't remove when i delete

### ISSUE THREAD

**Issue by Machou** [Novik/ruTorrent#1890]
Hi

When i delete a torrent from ruTorrent, he don't delete from the list of ruTorrent, but the data will remove.

I have try with : Opera, Firefox, Chrome, IE (:P)

I have clean my cache, restart computer, browser, cookie; all i can do....

What's the solution ?

Thanks you

**Comment by Feriman22** [comment]
Hello,

Did you check the permission of session folder? Try it with 777.
`sudo chmod -R 777 /your/session/folder`
