### ISSUE TITLE
Bad response from server: (404 [error,getplugins]) Not Found

### ISSUE THREAD

**Issue by XxAcielxX** [Novik/ruTorrent#1894]
Hello all,

First I have followed Arch Wiki to get working rtorrent, which is running all good. I can even control it with Transdroid.

Next I'm trying to get rutorrent to work with nginx, but is always having errors. I have even installed & enabled PHP-FPM. 

`[31.05.2019 12:59:21] WebUI started.
[31.05.2019 12:59:21] Bad response from server: (404 [error,getplugins]) Not Found`

This is the one I'm unable to solve. ~~I have no idea what chmod & chown to set for `/usr/share/nginx/html/rutorrent` and sub-directories~~.

Any help will be appropriated. Arch ARM on RPI3.

Regards.

**nginx.conf**
```
#user html;
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;                                                         
    server {
         listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /RPC2 {
            include scgi_params;
            scgi_pass localhost:5000;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

         location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;

            fastcgi_intercept_errors on;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
         }
    }
}
```
**Edits**
Applied https://github.com/Novik/ruTorrent/issues/1761 already. = Error still occurring

**Comment by Micdu70** [comment]
Hello,
See this => #1761
;-)

**Comment by XxAcielxX** [comment]
Already tried it, but no luck.

**Comment by chortya** [comment]
Same here with Apache2. This happened after one of the updates. The issue is somewhere in webserver redirects/access rights. I was updating letsencrypt certificates and standard apache2 without redirects and locations actually made Rutorrent work again, but I need all the other configs out of my standard portal apache configuration.

**Comment by XxAcielxX** [comment]
I was trying to diagnose the problem,

Connection between nginx & rtorrent SCGI is working as `xmlrpc localhost system.listMethods` test shows all commands.

If i stop the rtorrent, I'm still getting the error mentioned in the OP.

Connection between PHP & PHP-FPM is working as there is no Gateway error.

Permissions are all set by for `/usr/share/nginx/html/rutorrent` after installing rutorrent-git from AUR.

**Comment by GroupMaster** [comment]
I use Apache on Deb latest. I found that tasks get stuck and cause this error. When the task is deleted from the disk it comes back to life. If you are unable to figure out which task is the bad guy, delete them all. Then just reload the page.

These task files are found here:
<webserver root>/rutorrent/share/settings/tasks
And they look like:
15591919725cef61a4d505b5.37716099

It might not be the same issue, but if it is this will get you going. I hope it helps.

**Comment by XxAcielxX** [comment]
@GroupMaster  thanks for your input, but sadly no luck. It was a fresh install and no tasks were running.

So I have given up on this issue and moved to Docker based Container.

**Comment by torvald** [comment]
I had this problem to. I had to change the root to the full path to get rutorrent to be on the root URL.

I changed `root   /usr/share/nginx/html;` to the full path of the rutorrent, in my case; `root   /usr/share/nginx/html/rutorrent;`. I guess it has to do with SCRIPT_FILENAME.
