### ISSUE TITLE
extsearch plugin immortalseed engine not working

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#1902]
Hi, immortalseed has changed domain. Plugins loginmgr and extsearch not working currently.

If you are interested in fixing this, the registration is now open on this tracker. I appreciate any help with this.

**Comment by Flupster** [comment]
https://github.com/Novik/ruTorrent/blob/626ba3d33c8ab407f344033d4cd8a74f3ceaa24b/plugins/loginmgr/accounts/ImmortalSeed.php#L5

**Comment by Novik** [comment]
Fixed.
