### ISSUE TITLE
install filemanager

### ISSUE THREAD

**Issue by abeksis** [Novik/ruTorrent#1903]
Where can I install and install a file manager? Under Docker? Is there a link or something similar?

**Comment by Novik** [comment]
I don't know what is you mean.
ruTorrent do not contain something like 'file manager' in his official plugins.

**Comment by abeksis** [comment]
I installed the ruTorrent via Docker. And have the ruTorrent also through the seedbox, where they have filemanager but  dount have no. I believe there is a need to install a plugin. Is there a guide to this? Or link.

**Comment by Micdu70** [comment]
You can check my forked repo => https://github.com/Micdu70/rutorrent-thirdparty-plugins

Installation:
1) Use "cd" to go to the ruTorrent "plugins" directory
2)
`git clone https://github.com/Micdu70/rutorrent-thirdparty-plugins.git; cd rutorrent-thirdparty-plugins/; mv filemanager ../; cd ../; rm -rf rutorrent-thirdparty-plugins/`
3) Done!

**Comment by abeksis** [comment]
thank you for the answer.

I did exactly what you said - I see the filemanager but under the quick links do not see the filemanager
<img width="450" alt="Screen Shot 2019-07-05 at 21 29 17" src="https://user-images.githubusercontent.com/10877299/60739861-22c30000-9f6c-11e9-9a55-864d48c1dd57.png">

**Comment by Micdu70** [comment]
Clear your cache browser then retry

**Comment by abeksis** [comment]
Yes, I did it before I responded, and I also logged in from another browser. The same

This is the location of the plugins:

`root@99706fac49d0:/config/rutorrent/plugins/filemanager#`

**Comment by Micdu70** [comment]
I'm a noob with "Docker"... so maybe something need to be restarted on the server?

**Comment by abeksis** [comment]
Yes, I did that, too. Restart the Docker and there is no change.

**Comment by Micdu70** [comment]
Can you share where your get your Docker image please?

**Comment by abeksis** [comment]
https://hub.docker.com/r/linuxserver/rutorrent/

**Comment by Micdu70** [comment]
From => https://github.com/linuxserver/docker-rutorrent
ruTorrent is installed in `/app/rutorrent`
Try to install filemanager in `/app/rutorrent/plugins`

**Comment by abeksis** [comment]
I'm checking...

**Comment by abeksis** [comment]
`[05.07.2019 22:06:28] filemanager: Plugin will not work. Webserver user can't access external program (unzip).`

I received a message in the ui interface after installing according to your instructions.

**Comment by Micdu70** [comment]
You need to edit "conf.php" file to add path to "unzip" program.

**Comment by abeksis** [comment]
I try to find him.

Can you write me which line I should add?

**Comment by Micdu70** [comment]
Find and edit this line:
`pathToExternals['unzip'] = '/add/path/to/unzip';`

Use `whereis unzip` command to find him.

**Comment by abeksis** [comment]
Unzip software is under Docker problem to see where it comes from.
<img width="929" alt="Screen Shot 2019-07-05 at 22 12 33" src="https://user-images.githubusercontent.com/10877299/60741462-28bbdf80-9f72-11e9-82c4-ce6455e19d8c.png">

**Comment by abeksis** [comment]
I am using an unraid server

**Comment by abeksis** [comment]
Is there any additional plugin you recommend?

**Comment by Micdu70** [comment]
Ratiocolor => https://github.com/Micdu70/rutorrent-ratiocolor

**Comment by abeksis** [comment]
Thank you, are there any installation instructions?

I'm trying to find where sitting unzip have any idea how to search?

**Comment by Micdu70** [comment]
Read the "README.md" file
`whereis unzip` or `find . -name "unzip"` to find unzip

**Comment by abeksis** [comment]
Thank you very much for your support.

**Comment by abeksis** [comment]
I get the following error: [05.07.2019 23:05:09] FILE MANAGER: Failed to get directory contents: /

**Comment by Micdu70** [comment]
Please open an issue about adding the "filemanager" plugin on this repo => https://github.com/linuxserver/docker-rutorrent/issues

For your docker image, you need to edit in "conf.php" filemanager config file:
`$fm['tempdir'] = '/tmp';`
to
`$fm['tempdir'] = '/config/rutorrent/profiles/tmp';`

About the error, check "errors.log" file inside `/config/rutorrent/profiles/tmp`

**Comment by abeksis** [comment]
no "errors.log"  under /config/rutorrent/profiles/tmp
