### ISSUE TITLE
extsearch plugin torrentleech engine not working

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#1905]
Plugin extsearch not working currently with torrentleech. If someone want to fix that issue, the registration is now open on this tracker (just use invite code SUMMER2019). I appreciate any help with this.

**Comment by Micdu70** [comment]
I'm working on it. ;)

**Comment by Novik** [comment]
You was too later ;)

Done, check.

**Comment by koblack** [comment]
Games categories shouldn't be 17,42,18,19,40,20,21,39,22,**28**,30,**48** ?

**Comment by Novik** [comment]
Fixed, thanks.

**Comment by Micdu70** [comment]
I just added all missing categories

**Comment by koblack** [comment]
Thank you both for your quick response, works perfectly
