### ISSUE TITLE
lost SAVE PATH column in torrent list main window

### ISSUE THREAD

**Issue by douglassirk** [Novik/ruTorrent#1910]
i've tried multiple versions and cannot for the life of me figure out where the save path column has gone : ( or how to get it back... googling it people say it has to do with the datadir plugin? but thats installed and still no save path column...

makes mass moving/organizing things from the main window next to impossible : (

what am i missing?

thanks....

**Comment by Novik** [comment]
Press RMB on the columns of torrent list and select proper fields.

**Comment by douglassirk** [comment]
the field is not there.... it used to be there.... alas : (

**Comment by douglassirk** [comment]
though what does RMB stand for?

**Comment by douglassirk** [comment]
![columns](https://user-images.githubusercontent.com/30360470/61189692-9775f880-a656-11e9-8717-df02016d9c32.png)

this is what i get

**Comment by Micdu70** [comment]
You need to install latest ruTorrent version (3.9) or use a recent git version.
No plugin is needed to display this column...

**Comment by douglassirk** [comment]
thanks i'll try it : )

**Comment by douglassirk** [comment]
i must be completely blind... but i cannot for the life of me figure out where to get 3.9 from.... see 3.8... but....

**Comment by douglassirk** [comment]
yes 3.9 fixed it brought it back : )
thank you...
