### ISSUE TITLE
Wrong documentation for cpuload

### ISSUE THREAD

**Issue by Feriman22** [Novik/ruTorrent#1915]
Hello,

The [mentioned](https://github.com/Novik/ruTorrent/wiki/PluginCpuload) setting line is not found in any file of cpuload plugin.

`min(load_average[0]*100/processors_count,100)`

Where should I put this line? If anybody can tell me, we should to edit the page of this plugin with this information.

Thank you!

**Comment by Micdu70** [comment]
Hello,

It's not a "settings" line but the formula used by the plugin to calculate the % of load.

You can set the number of processors/cores in the `conf.php` file inside the plugin directory (default value is "null" and means autodetect if possible).

**Comment by Feriman22** [comment]
Hello,

Thank you for the reply! Can I set the graph to show the full height as 100%? The current state is confusing me.

Thanks!

**Comment by Micdu70** [comment]
I don't really understand your issue, maybe you are using an old ruTorrent version?

**Comment by Feriman22** [comment]
Okay, let me explain, I was not clear.

Normal graphs have a height with 100% value. This cpu loading graph height is flexible, usually 3-18%. This (let see the picture) 18% is the full height. It looks like the load is full of capacity.

![cpuload](https://user-images.githubusercontent.com/22872515/61647004-aee36000-acac-11e9-8239-7e6149f3fa4d.png)

I would like to set the height to fix 100% value, like this:

![Plugin-cpu-windows](https://user-images.githubusercontent.com/22872515/61647079-db977780-acac-11e9-81d5-868903a17412.png)

Is it possible?

Thank you!

**Comment by Micdu70** [comment]
No..., it will resize automatically if % go higher.
And color is changing too. (green = low % | red = high %)

**Comment by Feriman22** [comment]
I see. Can I fix it instead of automatically resize? Is it possible?

**Comment by Novik** [comment]
This has not any relation to ruTorrent. Closed.

**Comment by Micdu70** [comment]
@Feriman22 Yes it just one line to change => https://github.com/Novik/ruTorrent/blob/ec8d8f1887af57793a671258072b59193a5d8d6c/plugins/cpuload/init.js#L56

to

`max: 100,`

**Comment by Feriman22** [comment]
@Micdu70 Thanks, but unfortunately it doesn't works well.

![cpuload](https://user-images.githubusercontent.com/22872515/61650077-24eac580-acb3-11e9-90d8-41f6bde75bbd.png)

The graph is drawing partially and the "loading" is always full. I restarted the rtorrent and apache2 as well.

**Comment by Micdu70** [comment]
What's your browser? And which version of ruTorrent?

**Comment by Feriman22** [comment]
ruTorrent v3.9

Tried in Chrome and Firefox as well (both are latest).

**Comment by Micdu70** [comment]
Working without issue for me..., are you sure you change the good line? It's for "yaxis".

**Comment by Feriman22** [comment]
Okay, it was my bad. I just changed the value, not `min: 0` to `max: 100`

Niw, it works well! Thanks a lot! :)
