### ISSUE TITLE
rutorrent upgrade 3.8 > 3.9

### ISSUE THREAD

**Issue by kogoromori** [Novik/ruTorrent#1918]
Hey there,

actually i'm running rutorrent 3.8 on my debian server (buster).
now, that i've upgraded my rtorrent to 0.9.8, it seems that i need to upgrade rutorrent, too.
whats the easiest way to upgrade it, without messing up all my plugin-configs/user-configs etc?
i know this might not fit here, but the rutorrent forums are gone and i didn't find any good howto's.

kindly

**Comment by Micdu70** [comment]
Hello,
If you didn't use `git` command for your ruTorrent installation, I suggest you to convert your ruTorrent v3.8 installation to the latest git version. Here is the how-to:

=== Init git repository ===

- Go inside the ruTorrent directory (ex.: `cd /var/www/rutorrent`) and init a git repository => `git init`

=== "backup" branch ===

- Create a new git branch => `git checkout -b backup`
- Add all current files of your installation in git (yes, there is a dot at the end) => `git add .`
- Create a commit => `git commit -am backup`

=== "master" branch ===

- Add ruTorrent git repository => `git remote add origin https://github.com/Novik/ruTorrent.git`
- Fetch it => `git fetch`
- Checkout the git commit hash of ruTorrent v3.8 release => `git checkout -b master 9191af0`
- Merge your modified config files => `git merge --allow-unrelated-historie -X theirs backup`
- Link the local branch to remote branch => `git branch --set-upstream-to=origin/master master`
- Update your ruTorrent installation => `git pull`

Voilà! =)
You can now easily update your ruTorrent installation via a `git pull` command in it.

**Comment by LooseSeal2** [comment]
@Novik please make a new github release. Many dockerfile's use your releases instead of building master. All of them are currently broken right now b/c the last release was back in april.

**Comment by kogoromori** [comment]
> EDIT: In case if you already have a git installation, you need to:
> 
>     1. Go inside the ruTorrent directory (ex.: `cd /var/www/rutorrent`)
> 
>     2. Create a commit => `git commit -am "previous version"`
> 
>     3. Update your installation => `git pull`

Yes, i have it installed via git (like here: https://no.help/rTorrent-ruTorrent-Seedbox-Guide.php#ruTorrent )
, thank you for such a detailed help.
But still i need to ask, will this delete my configs/users etc?
Or do i need to perform a backup before?

**Comment by Micdu70** [comment]
You don't need to perform a backup if you create a commit, and it will keep your users config files and any modified config files. ;)

**Comment by kogoromori** [comment]
Thank you Micdu70.
