### ISSUE TITLE
PluginRatio - Update tracker before delete the torrent

### ISSUE THREAD

**Issue by Feriman22** [Novik/ruTorrent#1922]
Hello,

I would like to set this below:
One torrent reached the defined ratio target and the action is "Remove data (All)". The tracker is not received yet the latest uploaded data size (how much data I uploaded since last refresh), so I have to update tracker before the plugin delete the torrent.

Is it possible?

Thank you!

**Comment by Novik** [comment]
ruTorrent use rtorrent implementation of ratio system. 
I.e. this is a question to rtorrent author. 
Try to ask from him.

**Comment by Feriman22** [comment]
Thanks for the hint, I'll try it!

**Comment by Feriman22** [comment]
@Novik please check the answer in [opened thread](https://github.com/rakshasa/rtorrent/issues/899#issuecomment-515762412) of rtorrent.

**Comment by Novik** [comment]
As author of rtorrent said, this is a problem of client.
