### ISSUE TITLE
Method 'load_raw' not defined

### ISSUE THREAD

**Issue by erikhubers** [Novik/ruTorrent#1926]
After upgrading to Ubuntu 19.04 (From 18.04_2) I'm unable to send torrent download request from SickChill (using HTTP RPC). After looking at some logging it's seems rutorrent is to blame. 

Whenever trying to add a torrent, this error response is being logged
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
   <fault>
      <value>
         <struct>
            <member>
               <name>faultCode</name>
               <value>
                  <i4>-506</i4>
               </value>
            </member>
            <member>
               <name>faultString</name>
               <value>
                  <string>Method 'load_raw' not defined</string>
               </value>
            </member>
         </struct>
      </value>
   </fault>
</methodResponse>
```
Checking the [rTorrent command line list](https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)#load) it's noted "load_raw" is deprecated and replaced by "load.raw". Could this be the cause of my issues? Tried updating ruTorrent to latest, but didn't fix my issues unfortunately.

Versions:
rTorrent: Rakshasa's BitTorrent client version 0.9.7.

ruTorrent: 
git show
commit ec8d8f1887af57793a671258072b59193a5d8d6c (HEAD -> master, tag: v3.10-beta, origin/master, origin/HEAD)

**Comment by erikhubers** [comment]
Nvm, this a SickChill issue: https://github.com/SickChill/SickChill/issues/5118

**Comment by defhead** [comment]
@erikhubers Did you find another solution or did you abandon the idea to use sickchill with rtorrent 0.9.7, since this issue is open for almost a year now and doesn't seem to be taken care of?

**Comment by erikhubers** [comment]
@defhead, well I didn't find a (quick and dirty) solution to work around this issue. But I ended up just using a watch directory https://github.com/rakshasa/rtorrent/wiki/TORRENT-Watch-directories
