### ISSUE TITLE
“Create New Torrent” should copy source path from selected torrent

### ISSUE THREAD

**Issue by mietek** [Novik/ruTorrent#1929]
Right now, the “Create New Torrent” dialog reuses the last used source path.

I think it would be a nice improvement if the source path was automatically copied from the currently selected torrent.

**Comment by Novik** [comment]
Why you need such strange thing?

**Comment by mietek** [comment]
Every time I use “Create New Torrent”, it is to create a new torrent based on an existing torrent, for cross-seeding purposes.  This would make it easier.
