### ISSUE TITLE
Context menus should include “Copy Name” command

### ISSUE THREAD

**Issue by mietek** [Novik/ruTorrent#1930]
The context menus for torrents and for individual files should include a “Copy Name” command, as it is not possible to simply select the text in the web UI.

I think this would make cross-seeding easier, as creating symlinks or tweaking names is often necessary.

**Comment by Micdu70** [comment]
Hello,
You can select a torrent and go to "General" tab, then you can copy the directory path (or a part) from here. ;)

**Comment by mietek** [comment]
The “General” tab contains a “Save As:” item that shows the parent directory.  It does not show the name of the torrent itself.  (The same applies to the “Save to…” command in the context menu for the torrent.)

For example, consider the following directory structure:
```
/media/user/rtorrent/data/Epäjärjestelmällistyttämättömyydelläänsäkäänköhan/Älä.rääkkää.kääkkää.kääkänrääkkääjä.txt
/media/user/rtorrent/data/Epäjärjestelmällistyttämättömyydelläänsäkäänköhan/No.ehä.mää.rääkkääkkää.kääkkää.txt
```

In this case, the torrent list will show “Epäjärjestelmällistyttämättömyydelläänsäkäänköhan” as the torrent name.  The “Files” tab will show “Älä.rääkkää.kääkkää.kääkänrääkkääjä.txt” and “No.ehä.mää.rääkkääkkää.kääkkää.txt”.  The “General tab” will show `/media/user/rtorrent/data`, which is not the difficult to retype part.

**Comment by Micdu70** [comment]
Oh yeah I see... so maybe add the torrent's name in "General" tab? (more simple to do ^^)

**Comment by mietek** [comment]
Adding the torrent name to the “General” tab would help, but there are also the file names to consider.

**Comment by Micdu70** [comment]
"General" tab displays the torrent's name for the save path in ruTorrent v3.9, please update.

About a copy function for files/directories' names inside the torrent... I don't know if it is really useful.

**Comment by Novik** [comment]
IMHO this will be not useful. But you are free to write your own plugin for that.
