### ISSUE TITLE
extsearch plugin abtorrents engine not working

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#1934]
Plugin extsearch not working currently with abtorrents. If someone want to fix that issue, the registration is now open on this tracker. I appreciate any help with this.

**Comment by Micdu70** [comment]
Hello,
Using cookie informations don't work anymore... and we can't use login credentials method because of the "captcha" (click "X" button). :(

**Comment by Novik** [comment]
This is not a captcha.
Data to submit:
```
username=&password=&use_ssl=1&submitme=X&returnto=%2F
```
Where you see here something like captcha?

**Comment by Micdu70** [comment]
Thanks @Novik ^^ I thought it was a captcha thing, but I just find myself the "submitme=X" argument via browser console...

**Comment by koblack** [comment]
Thanks!
