### ISSUE TITLE
Add Ratiocolor plugin

### ISSUE THREAD

**Issue by defhead** [Novik/ruTorrent#1936]
Is it possible to add [ratiocolor](https://github.com/Gyran/rutorrent-ratiocolor) plugin to your repo?

([This](https://github.com/Micdu70/rutorrent-ratiocolor) is a little bit more recent version of the plugin, with some enhancements)

**Comment by Novik** [comment]
Why you can't simple clone this plugin from his repo?

**Comment by defhead** [comment]
Well, I use your repository within as a [docker](https://hub.docker.com/r/linuxserver/rutorrent) container, and I try to make each installation as automatic as possible.

Having this plugin within your repository would avoid me to fork your repository, modify the Dockerfile, include this plugin, set up a docker build process, etc.

**Comment by defhead** [comment]
I could do it as a PullRequest if you prefer?

**Comment by Novik** [comment]
Sorry, but this is your problem. And you try to convert it to the my problem.
Having this plugin within my repository force me to support it.

**Comment by defhead** [comment]
Wow, ok. Since it's a really small plugin I didn't think it would require any support. It's not a like a brand new plugin, it has been widely used by the community and was proven to be nice and reliable.

But I guess I'll have to manage this "problem" my self.

Thanks anyway.
