### ISSUE TITLE
[18.08.2019 23:41:21] WebUI started. [18.08.2019 23:41:22] The server does not have access to the 'stat' program. Some features will not be available.

### ISSUE THREAD

**Issue by vinedu18** [Novik/ruTorrent#1937]
[18.08.2019 23:41:21] WebUI started.
[18.08.2019 23:41:22] The server does not have access to the 'stat' program. Some features will not be available.

**Comment by zdzichu6969** [comment]
Check your config.php

`       $pathToExternals = array(
                "pgrep" => '/usr/bin/pgrep',
                "php"   => '/usr/bin/php7.2',                   // Something like /usr/bin/php. If empty, will be found in PATH.
                "curl"  => '/usr/bin/curl',                     // Something like /usr/bin/curl. If empty, will be found in PATH.
                "gzip"  => '/bin/gzip',                         // Something like /usr/bin/gzip. If empty, will be found in PATH.
                "id"    => '/usr/bin/id',                       // Something like /usr/bin/id. If empty, will be found in PATH.
                "stat"  => '/usr/bin/stat',                     // Something like /usr/bin/stat. If empty, will be found in PATH.
        );
`
