### ISSUE TITLE
[Enhancement] Reset torrent stats

### ISSUE THREAD

**Issue by Musaran2** [Novik/ruTorrent#1938]
To reset at will certain stats of a torrent : UL, DL, dates etc, possibly including stats sent back to the tracker.

This could be useful when changing connection or sharing habits, dealing with a broken torrent or tracker... and also cheating.

I presently do it by removing then adding back the torrent, with it's content files staying in place.

**Comment by GroupMaster** [comment]
You will not be able to change what information the tracker is given or has and DONT try. This may be seen as cheating and it will not end well. You can only reset the local stats of the torrents. The easiest way is to select the torrent and use the "Save to" feature. Save it in the same folder it already resides in and use the "move data files" option. This will reset most local records with the exception of the finished time.
