### ISSUE TITLE
Doesn’t load on mobile Safari

### ISSUE THREAD

**Issue by nyuszika7h** [Novik/ruTorrent#1947]
I’m using rtorrent 0.9.7 (Debian 10) and ruTorrent 3.9, and it doesn’t load at all in mobile Safari:

![Screenshot](https://user-images.githubusercontent.com/482367/64857669-7c5b4100-d625-11e9-9b1c-74b886d74734.png)

**Comment by xombiemp** [comment]
You could give this mobile plugin a try
https://github.com/xombiemp/rutorrentMobile

**Comment by L041S** [comment]
Hello, I have exactly the same issue, only with Safari (on iOS or macOS). But works perfectly in Firefox or Chrome (desktop or mobile). @nyuszika7h, were you able to find a fix ?
