### ISSUE TITLE
Couple of questions: Log tab, priority and fast resume...

### ISSUE THREAD

**Issue by cblknittights** [Novik/ruTorrent#1948]
A couple questions I am just not finding answers to from searches.... (log) file just points to BS about rtorrent.... 

#1 The log tab in the GUI is that an actual file that is read to display ie: its just a tail -f in GUI form via rutorrent???? V3.9.

If so where is that file located???? I checked in the usual suspects for /var/log/ and didn't seem to locate it?????

Is this file persistent over sessions??? Ie: I view the GUI etc... close it.. and reopen ...is that FILE persistent or truncated on a new session???

#2 Any way to SET the PRIORITY FLAG on a torrent on each load of a torrent from RSS, or the GUI add option v. having to add and then then turn on priority to it, and repeat after it downloads from magnet/DHT or .torrent file???

#3 Same as #2 but for Fast Resume...

I would like to have these as persistent settings and as the defaults... 

Don't see any way to set that in the settings via the GUI... config file options?????

Thanks!

**Comment by Novik** [comment]
> The log tab in the GUI is that an actual file that is read to display

No.

> Is this file persistent over sessions??? 

This is not file. 
And no, contents of log tab is not persistent. But for example, if 'RSS' plugin will have troubles between your UI sessions then on the next UI session you will see list of corresponding errors in the log tab.

> Any way to SET the PRIORITY

Try to write your own plugin, for example. Or correct existing.

> Don't see any way to set that in the settings via the GUI... config file options?????

You can change same settings (if this not directly disabled in the ruTorrent access.ini file). But this changes will be temporary. Up to the next rtorrent restart.
