### ISSUE TITLE
ExtSearch Plugin dropdown menu doesn't work

### ISSUE THREAD

**Issue by Seeder101** [Novik/ruTorrent#1950]
Hi does anyone actually use Extsearch plugin successfully ? 
I have 3 seedboxes running and all of them can't search inside any trackers public or private the dropdown menu for the trackers doesn't work here is a screenshot
![Screenshot from 2019-09-19 17-18-21](https://user-images.githubusercontent.com/7802688/65252499-b6cf4d00-db01-11e9-8344-2528fee7e078.png)
it doesn't matter when u click on it to display the list of trackers it won't show up all tho torrent searching is working ok 
I have 2 running with Nginx and 1 with Apache. 
Thank you in advance

**Comment by Novik** [comment]
Try to press on glass magnifier icon.

**Comment by Seeder101** [comment]
> Try to press on glass magnifier icon.

You're the MAN! 
it's a bit confusing tbh. I didn't think of clickng the glass magnifier icon lol 
Thank you
