### ISSUE TITLE
Multiple Labels in AutoMove

### ISSUE THREAD

**Issue by soulvoid86** [Novik/ruTorrent#1951]
Not an issue, I'm just confused on how this is supposed to be setup. AutoMove works great when I have a single label set, but how do you set multiple labels? You can see how I have it set in the attached screenshot, but I can't figure out how to add multiple labels to the field that has /.*/ as the default. 
![Capture](https://user-images.githubusercontent.com/11574738/65530450-fd3bf780-dec5-11e9-9de6-2e6f177f6a69.PNG)

**Comment by Novik** [comment]
> but I can't figure out how to add multiple labels to the field that has /.*/ as the default.

This is standard PCRE pattern. 
You may use this site - https://regex101.com/ for testing.

For example, 
for case "label may contain 'one' or 'two'" - /one|two/
for case "label starts with 'one' or 'two'" - /^one|two/
for case "label ends with 'one' or 'two'" - /one|two$/
for case "label equal 'one' or 'two'" - /^one|two$/
etc.

**Comment by soulvoid86** [comment]
Ok, so it seems I'd want the first example you listed. So when I put /Radarr|R-Seeds/, and then change the label from Radarr to R-Seeds, it doesn't adjust the file path. Is this only for newly added torrents?

**Comment by Novik** [comment]
> Is this only for newly added torrents?

This is only for torrents, that would be finished after your changes.

**Comment by soulvoid86** [comment]
Ok, is there any way to make this happen? Or am I going to have to adjust the torrents manually once they're finished?

**Comment by soulvoid86** [comment]
Sorry if that came across a little flat.. I was at work and in a hurry to respond. I'm pretty new to Linux, I have a basic knowledge, but definitely a noob. I currently use qBit to manage my torrents and with that, I can simply change the label and it will move the data to the folder specified to that label. I'm trying to accomplish the same thing with rTorrent, as that's all that my newly rented seedbox supports. That has this feature anyway.

**Comment by soulvoid86** [comment]
Something I just found that works as a work around. If I select the label in the tree on the left, I can right-click and choose Save To and simply hit OK. However, when Sonarr is finished working with a release, it will relabel the torrent, thus, moving the files to a different directory.
