### ISSUE TITLE
no settings menu with rtorrent ps ch 0.9.8

### ISSUE THREAD

**Issue by msagebiel** [Novik/ruTorrent#1952]
Log
ruTorrent cannot determine the UID of rTorrent user. Some functionality will be unavailable.

and pressing settings button
Bad response from server: (500 [error,getsettings]) Warning: XMLRPC call is failed.

Regards
https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/DebianInstallFromTarballsPackages.rst ubuntu bionic
version="1.8.3-0.9.8-ubuntu-bionic_amd64"

**Comment by Micdu70** [comment]
ruTorrent only support "stock" rTorrent version. ;)

**Comment by fsamareanu** [comment]
I do use it with rtorrent-ps-ch 0.9.8 and works just fine.
