### ISSUE TITLE
Oblivion theme: Add torrent window  broken

### ISSUE THREAD

**Issue by ChriZathens** [Novik/ruTorrent#1959]
I have two problems with Oblivion theme
1. Just noticed that in Chrome, Add torrent menu displays wrong
![Capture](https://user-images.githubusercontent.com/8545172/67574445-20ff9100-f743-11e9-996a-3569473b73b9.JPG)
In IE or Firefox it is almost OK (a bit trimmed at the bottom, please notice button "Add URL")
![Capture11](https://user-images.githubusercontent.com/8545172/67576413-2ced5200-f747-11e9-85e2-41cd80210729.JPG)

2. Even in IE or Firefox which have almost no problem, when I switch the language to Greek, a lot of the window is trimmed
![Capture2](https://user-images.githubusercontent.com/8545172/67574912-1396d680-f744-11e9-85c0-8252afbbe60e.JPG)
(Notice that no Add URL option is visible at all, it is all trimmed)
The Greek translation is longer than the English one, thus a line break is added and the window itself does not stretch, so a part of the bottom stuff is trimmed
This only happens to Oblivion theme, however.. a couple of other themes don't pose this issue
Do you believe it can be fixed?
Cheers!

**Comment by Micdu70** [comment]
My PR remove forced/fixed 'width' and 'height' values for this window by default ("Oblivion" theme doesn't force/fix these values, but some themes do). Browsers will size it by itself now. :)

**Comment by ChriZathens** [comment]
Hello! Thanks a lot for your efforts!!!
I can confirm that the trimming problem is now gone!!
What is still present, though, is the misalignment of the options in Chrome. I tried several hard refreshes of the browser in case it was a caching issue or something but no change. 

![Capture](https://user-images.githubusercontent.com/8545172/67616571-4cd25380-f7e3-11e9-8f5d-17dccbb903fe.JPG)
Not a big deal, since it is purely cosmetic, but can you please check yourself if it does the same?
This happens only to Chrome, I also tested IE and Firefox and it displays perfectly there
Cheers!!!

**Comment by Novik** [comment]
I can't reproduce this. May be you use some sort of browser extension?
Also try to clear browser cache (or press Ctrl-F5 when ruTorrent interface is active).

**Comment by Micdu70** [comment]
Can't reproduce too...
Here is mine:
![AddTorrent-ruTorrent-Window](https://user-images.githubusercontent.com/8136676/67620341-fe827c00-f805-11e9-8c7d-b3ff41360ad2.JPG)
