### ISSUE TITLE
Unknown download file size

### ISSUE THREAD

**Issue by Feriman22** [Novik/ruTorrent#1961]
Hi,

When I download bigger file than 2GB from ruTorrent web interface with "Get File" option, the download file size is not available for browser.

Reproduce the issue:

1., Open ruTorrent web interface
2., Select one torrent
3., Choose "Files" tab
4., Right click on any file
5., Select "Get File"
![image](https://user-images.githubusercontent.com/22872515/67669113-8f299b00-f971-11e9-9ae1-4fb49cece8c1.png)
6., Check the download in your browser. It will don't know the size of download file.
![image](https://user-images.githubusercontent.com/22872515/67669200-b41e0e00-f971-11e9-859e-e4ace5dbe386.png)

When the file size is smaller than 2GB, this feature works well. I'm using Chrome 78 and Windows 10.

Is it a bug or feature? I think it's a bug. If feature, why?

**Comment by Novik** [comment]
This mean - you use 32bit version of PHP. It can't operate with a files greater than 2G.
