### ISSUE TITLE
How to use labels, automove, and autowatch together?

### ISSUE THREAD

**Issue by ashenkin** [Novik/ruTorrent#1962]
Hi Folks,

I have rutorrent 3.9 set up such that I can manually add a torrent with a label, and upon completion, the download gets moved to /opt/rtorrent/download/complete/<label>/.  I have a number of other programs that add torrents with a label, and thus the downloads end up in the right place.

I would now like to set up a watch folder with subdirectories so that the proper labels are assigned to each torrent.  Eg torrents from /watchfolder/label1 would end up in /opt/rtorrent/download/complete/label1.  I have done this with autolabel = {DIR}.  But this ends up placing the downloads in /opt/rtorrent/download/complete/**label1/label1**.  I'm not totally sure why this is.  Any suggestions?

thanks in advance.

autotools config: https://i.imgur.com/LRR92rR.png

**Comment by Novik** [comment]
Turn on variable $autodebug_enabled in the plugin's conf.php, wait for processing, as minimum, one torrent and send debug information to me, please (by default debug information is placed in the /tmp/errors.log file, but this may be changed in your configuration, see conf/config.php for details).
novik65@gmail.com

Or you may attach this file here (but check it for private information first).

**Comment by xombiemp** [comment]
@ashenkin Try to uncheck the Add torrent's label to path check box.
