### ISSUE TITLE
The IP address has changed

### ISSUE THREAD

**Issue by abeksis** [Novik/ruTorrent#1963]
Is it possible to change the ip address in one of the files instead of starting the whole reinstall? Or there is another solution I would love to know

**Comment by Novik** [comment]
What do you mean?

**Comment by abeksis** [comment]
I'm trying to log in to https://192.168.1.153/rutorrent/ and am getting an error
`Your connection is not private
Attackers might be trying to steal your information from 192.168.1.153 (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_REVOKED`

Looks like a problem. Remember I did an installation, he asked me what ip address I told him locally and also was the outside. I thought it might have to do with changing the IP address - if I wasn't happy to try to help me understand why I can't log in.

**Comment by Novik** [comment]
Try to google by words "NET::ERR_CERT_REVOKED".
ruTorrent have'nt any relation to this.
