### ISSUE TITLE
Cannot set download/upload bandwidth beyond 320 Mbps

### ISSUE THREAD

**Issue by thirstyraven** [Novik/ruTorrent#1965]
I've set the global download/upload rate to unlimited in my rtorrent.rc file.

```
throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb = 0
```

However, when I open the ruTorrent UI after every restart, I can still see this.

<img width="458" alt="Screen Shot 2019-11-10 at 12 46 22 AM" src="https://user-images.githubusercontent.com/57574115/68541406-e6f1da00-0353-11ea-907a-49ccf57c134a.png">

I want to make full use of my 1 Gbps symmetric connection yet I'm seemingly limited to 320 Mbps. What is going on?

**Comment by thirstyraven** [comment]
When I searched the ruTorrent codebase for any such hardcoded limit, I did [come across this](https://github.com/Novik/ruTorrent/blob/44d43229f07212f20b53b6301fb25882125876c3/plugins/throttle/throttle.php#L6-L7).

```
@define('MAX_SPEED', 327625*1024);
// Can't be greater then 327625*1024 due to limitation in libtorrent ResourceManager::set_max_upload_unchoked function.
```

Which then [led me to this](https://github.com/rakshasa/libtorrent/blob/9bbbee6dbcec0aa4bdeed11b8053f2fc768a3090/src/torrent/download/resource_manager.cc#L266-L272).

```
void ResourceManager::set_max_upload_unchoked(unsigned int m) {
  if (m > (1 << 16))
    throw input_error("Max unchoked must be between 0 and 2^16.");
  m_maxUploadUnchoked = m;
}
```

Is this related? If so, can someone give me a more detailed reason on why this limit exists?

**Comment by Micdu70** [comment]
1) It's 327 MB/s, so 2,6 Gbps max. So you can reach 125 MB/s without problem (1 Gbps).
2) rTorrent via XMLRPC doesn't accept "0" for unlimited speed limit. Don't know if it's not better to not send a speed limit value if we don't want to limit speed...

**Comment by thirstyraven** [comment]
Ah, I see. Thanks for the quick clarification!!

**Comment by Novik** [comment]
> Is this related?

Yes, this related.

>  If so, can someone give me a more detailed reason on why this limit exists?

See here:
https://github.com/Novik/ruTorrent/wiki/PluginThrottle#some-non-obvious-points

Header "Some non-obvious points", point one.

**Comment by netty0** [comment]
>     1. It's ~320 MiB/s, so ~2,6 Gbps max. So you can reach 125 MiB/s without problem (1 Gbps).

The unit in ruTorrent WebUI states `KiB`. You're saying this is incorrect? As otherwise it's 327625 KiB or 0.34 gigabytes according to ruTorrent WebUI unit.

**Comment by Micdu70** [comment]
> > ```
> > 1. It's ~320 MiB/s, so ~2,6 Gbps max. So you can reach 125 MiB/s without problem (1 Gbps).
> > ```
> 
> The unit in ruTorrent WebUI states `KiB`. You're saying this is incorrect? As otherwise it's 327625 KiB or 0.34 gigabytes according to ruTorrent WebUI unit.

Learn the difference between Byte (B) and bit (b) maybe? ;)

**Comment by netty0** [comment]
> > > ```
> > > 1. It's ~320 MiB/s, so ~2,6 Gbps max. So you can reach 125 MiB/s without problem (1 Gbps).
> > > ```
> > 
> > 
> > The unit in ruTorrent WebUI states `KiB`. You're saying this is incorrect? As otherwise it's 327625 KiB or 0.34 gigabytes according to ruTorrent WebUI unit.
> 
> Learn the difference between Byte (B) and bit (b) maybe? ;)

[You're saying this incorrect? ](https://www.google.com/search?&q=327625KiB+to+gigabytes)

**Comment by AlleGodeNavneVarTaget** [comment]
I have the same issue, my download and upload is limited at KiB/s 327625, how can I changes it to KiB/s 948000?

If i changes via rutorrent web gui " like the screenshot " 
I can download / upload with full speed, but this settings is only temp... after I rebooting it's back on " 327625 KiB/S)
![Unavngivet](https://user-images.githubusercontent.com/114252362/194150682-325e5c00-757c-4da1-aa7e-e8210f3a4c9d.png)
