### ISSUE TITLE
Request: Bulk Add (import), Bulk Copy (export) magnet links

### ISSUE THREAD

**Issue by a-raccoon** [Novik/ruTorrent#1966]
The client qBittorrent allows you to paste hundreds of magnet links (or info-hashes or http links) in a single `Add Torrent(s)` operation.  It also allows you to select multiple loaded torrents to `Copy Magnet Link(s)` to clipboard for export to another client or friend.

I would really love to bulk export magnet links from qBittorrent then bulk import them into ruTorrent in one single click, instead of 4500 clicks.

**Comment by GroupMaster** [comment]
Use the watch folder feature. Get the .torrent files you want imported into rutorrent and just copy them into the watch folder and let it rip. Maybe use the /load watch folder so you can make sure the torrents are set properly before they start.

**Comment by a-raccoon** [comment]
@GroupMaster that would require SSH/FTP rights and privileges that joe user may not possess.  Please make this a working solution for joe users.

**Comment by a-raccoon** [comment]
:'(

**Comment by Novik** [comment]
> It also allows you to select multiple loaded torrents to Copy Magnet Link(s) to clipboard for export to another client or friend.

I added new plugin 'bulk_magnet'. 
In the current implementation it simply add for torrents context menu with a 3 commands
- Copy/Name
- Copy/Hash
- Copy/Magnet link.

But I have no idea - will this works for hundreds of torrents or not. 
You may check this, and if this will be useful then I will think about bulk addition.

**Comment by Novik** [comment]
I added torrents import too. You may find corresponded menu item in the 'Plugins' submenu.
