### ISSUE TITLE
autounpack behaving weird

### ISSUE THREAD

**Issue by iKatt** [Novik/ruTorrent#1968]
I have autounpack set up like this 
![image](https://user-images.githubusercontent.com/10321978/69421099-48627180-0d74-11ea-9501-3667e23ed771.png)
It unpacks the files properly in the newly created directory, however it also decides to unpack the same file in the root directory as well, despite there being no reason to resulting in me getting the playable file twice (one in the torrent directory and one in the root directory).

Why would it be doing this?

**Comment by GroupMaster** [comment]
Maybe there is another program doing the 2nd unpack?
