### ISSUE TITLE
Set ratio plugin based on ratio / day

### ISSUE THREAD

**Issue by Feriman22** [Novik/ruTorrent#1969]
I would like to set the ratio groups based on ratio / day, not the whole ratio value. The point is if the torrent's ratio/day less than expected (eg. less than 1.0), I would like to delete this torrent automatically.

![image](https://user-images.githubusercontent.com/22872515/69491200-0c253300-0e92-11ea-95a0-bf255609953a.png)

![image](https://user-images.githubusercontent.com/22872515/69491226-76d66e80-0e92-11ea-8d12-44a8c658de46.png)

Is it possible?

**Comment by Novik** [comment]
Of course. But you must write your own plugin for that.
