### ISSUE TITLE
Polish special signs

### ISSUE THREAD

**Issue by borygo77** [Novik/ruTorrent#1970]
Hi guys! Having problem with polish special characters in rss reader :( 
Can anyone help me find settings for it please ? 
System is set to Polish language charcters to default....
Here is screenshot how it looks like: 
![screenshot](https://user-images.githubusercontent.com/43052061/69570893-b4cdb280-0fb8-11ea-96d3-a62354f1071d.png)
First torrent should have Żmijowisko so there is Ї instead of Ż...

**Comment by Novik** [comment]
Try to set variable $locale in the your conf/config.php (or users/USERNAME/config.php) file to the proper locale - 'pl.UTF-8' in your case.
Warning: only one locale setting is exist. I.e. locale all your feeds will be interpreted as feeds with a polish lang.

**Comment by borygo77** [comment]
Unfortunately no luck :( This is my config file....
At the very end there was $locale = "UTF8";
so added pl. before UTF
Restarted rutorrent from systemctl and also rebooted server...
[config.php.zip](https://github.com/Novik/ruTorrent/files/3888588/config.php.zip)

**Comment by Novik** [comment]
1) Do you have this locale installed on your server?
2) Do you have php extension 'mbstring' installed on your server?
3) What about encoding of your rss feed?

**Comment by borygo77** [comment]
Looks like mbstring is not installed.
Checked with 
```
php -a
Interactive mode enabled

php > echo extension_loaded('mbstring');
```

And got no answer :( 
Not sure what you mean with rss feed
Same feed worked great with ubuntu 16.04 without those windows 1251 signs ;)

**Comment by Novik** [comment]
> Looks like mbstring is not installed.

Install 'mbstring' or 'iconv'.

**Comment by borygo77** [comment]
Well it's not so easy with libreelec I'm afraid. Will contact plugin author and try to get him to implement mbstring...
Thanks Novik!
