### ISSUE TITLE
Continuous downward scrolling in Firefox

### ISSUE THREAD

**Issue by catmalfunction** [Novik/ruTorrent#1972]
In Firefox, if you try to scroll down a list of torrents, either via buttons, scroll wheel, scroll tab, or clicking in the bar, it continues scrolling all the way to the bottom by itself unless you stop it by scrolling the opposite direction.

**Comment by Micdu70** [comment]
And which version of ruTorrent do you use? This bug has been fixed in ruTorrent v3.9

**Comment by catmalfunction** [comment]
Oh crap, my apol;ogies! I'm still on v3.8
