### ISSUE TITLE
Cannot read property 'flabel_cont' of undefined

### ISSUE THREAD

**Issue by notojak** [Novik/ruTorrent#1975]
After last update to rutorrent via git, I have a problem with error 
> _Uncaught` TypeError: Cannot read property 'flabel_cont' of undefined_

Browser: Opera 65.0.3467.48
Other browsers have no problem with this error (Edge, Firefox)

![screenshot-192 168 1 110-2019-11-30-07-18-51-138](https://user-images.githubusercontent.com/31856977/69896600-b93ff580-1341-11ea-9a53-2d40343de257.png)

**Comment by Micdu70** [comment]
It's a browser caching issue after the latest git update.
Clear your browser cache and it will be ok. ;)

**Comment by notojak** [comment]
@Micdu70 , thanks.
What a shame .... 👎
