### ISSUE TITLE
Upgrade PHP version

### ISSUE THREAD

**Issue by dausruddin** [Novik/ruTorrent#1976]
Hi. I have upgraded my PHP version to 7.4, but somehow rutorrent doesn't pick up the mcrypt I installed
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/lib/php/20180731/mcrypt.so (/usr/lib/php/20180731/mcrypt.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mcrypt.so.so (/usr/lib/php/20180731/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

But mcrypt is working fine when I tested it on PHP7.4.

Can I know how to fix this?

**Comment by Micdu70** [comment]
??? ... That's nothing related with ruTorrent... ruTorrent doesn't use/require "mcrypt" PHP module.

**Comment by dausruddin** [comment]
@Micdu70 @Novik At first I was thinking the same. But see this

![firefox_BhLolq2ypp](https://user-images.githubusercontent.com/5763466/70097263-ebb06200-1663-11ea-9b04-e43cbd9eaadd.png)

There is a "Diagnostics" section checking for mcrypt. It appears when creating torrent.

**Comment by Novik** [comment]
Yet once. ruTorrent has not any relation to this. Try to use google for fix your problem. 
For example, https://stackoverflow.com/questions/5282264/php-warning-php-startup-unable-to-load-dynamic-library

**Comment by dausruddin** [comment]
If it don't have relation, why it displaying the error?

I have tried using [this code](https://stackoverflow.com/a/25476928) and my mcrypt module is working fine. 
![image](https://user-images.githubusercontent.com/5763466/70289512-ea239d00-180f-11ea-8fb2-d9ab389d9bba.png)

Why ruTorrent  not checking mcrypt from PHP7.4 instalation? And why it checks for mcrypt in the first place?

Or can you at least tell me how to disable that diagnostics part?

**Comment by dausruddin** [comment]
Turned out I didn't update the PHP path in `conf/config.php`.
I don't understand why it checked for mcrypt, but I am glad now it is gone.

Sorry for the time wasted.
