### ISSUE TITLE
All (x) in all sections was only in State before.

### ISSUE THREAD

**Issue by GazCBG** [Novik/ruTorrent#1978]
Hi,

Just installed ruTorrent via Quickbox and noticed that there is an All (x) for each of the sections, before it was just State, but it is also in Labels, Search and Trackers.

Is this how it meant to be or is it a bug?
Also is there away to change it back to only show in state?

Thanks

**Comment by Micdu70** [comment]
Hello,

Yes it's the new qBitTorrent-style filtering and no option to revert it.
Added by PR #1854
