### ISSUE TITLE
Torrents added via rTorrent RPC directly do not show some metadata in ruTorrent

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Novik/ruTorrent#1981]
For example, comment data is not shown unless the torrent is added via the web UI.

**Comment by Novik** [comment]
This is a normal behavior.

**Comment by ThatNerdyPikachu** [comment]
@Novik Even something like "date added?"

**Comment by Novik** [comment]
Try to read header of your ticket. Key words - "via rTorrent RPC". rTorrent do not parse and/or store comment of torrent file. I.e. this is a question to the author of rTorrent, not to me.

> Even something like "date added?"

What do you mean?

**Comment by ThatNerdyPikachu** [comment]
@Novik Due to the reasons you specified above, would the "Date added" column also not be populated for torrents added not via ruTorrent?

**Comment by Novik** [comment]
For correct filling of this column you should have installed plugin 'seedingtime'.

**Comment by ThatNerdyPikachu** [comment]
@Novik That plugin has been installed, I never uninstalled it. So torrents that are added via rTorrent RPC don't populate that field either?

**Comment by Novik** [comment]
Torrents that are added via rTorrent RPC must populate this field if you have plugin 'seedingtime' installed and you have correct ruTorrent launcher in your .rtorrent.rc file.
https://github.com/Novik/ruTorrent/wiki/Plugins#starting-plugins-with-rtorrent

> Also, is there an easy way to clear the unused (by uninstalled plugins) custom fields in the ".rtorrent" files, or is there really no point to that?

Why you need such strange thing?
