### ISSUE TITLE
[Feature Request] Change displayed name

### ISSUE THREAD

**Issue by galgamesh-au** [Novik/ruTorrent#1985]
I'm not talking about renaming the directory or file names , the Relocate plugin would handle that.
I'm talking about the name that is displayed in the ruTorrent interface.

If two people create torrents with related content they can still use totally different names. Or it's even possible that the name they use is meaningless to the leacher.
Having the ability to simply change the displayed name in the client will allow people to organise torrents in a manner that suits them.

Unfortunately editing the .torrent file name field changes the hash code and means the tracker can't identify it.

**Comment by Fleshgrinder** [comment]
https://github.com/Fleshgrinder/rutorrent-rename it’s pretty raw and not very well tested but you can give it a try.
