### ISSUE TITLE
getplugins.php is slow on certain plugins

### ISSUE THREAD

**Issue by mayli** [Novik/ruTorrent#1986]
I notice the getplugins.php on a fresh installed diameter/rtorrent-rutorrent takes exact 0m6.988s to load. Some plugin reads/load instantly but some takes exact 0.56s to read, or 1.12s (which is 0.56x2).
It seems the `findRemoteEXE` takes 0.56s for each EXE it's looking for, and most plugins are just looking for common exes such as php/python. I notice there is a inline cache, but is it possible to cache the `findRemoteEXE` result at filesystem or skip the RPC when the PRC host is localhost for faster loading?

**Comment by Novik** [comment]
Try to set variable $do_diagnostic in the conf/config.php (or in the your user-specific config.php if you have one) to false.
With this you will avoid as minimum, part of checks.

But, of course, this process must be optimized. We must use cached copy of plugins js or something like that. I will think about that.
