### ISSUE TITLE
Search broken on latest build

### ISSUE THREAD

**Issue by Rid** [Novik/ruTorrent#1989]
Search appears to be broken in recent builds. As soon as you enter any text into the search field the following error appears in the console:

`JS error: [https://example.com/js/webui.js : 2146] Uncaught TypeError: Cannot read property 'id' of undefined`

**Comment by Rid** [comment]
Was caused by https://github.com/Gyran/rutorrent-instantsearch

**Comment by Micdu70** [comment]
Updated plugin is available here => https://github.com/Micdu70/rutorrent-instantsearch

:)
