### ISSUE TITLE
cloudflare for trackers "Tracker: [Could not parse bencoded data: Attention Required! | Cloudflare body{margin:0;padding:0} Please enable co]"

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1992]
I am trying to use the Plugin_cloudflare because a tracker is blocked and I have to use tor for it and cloudflare blocks the trackers with this massage:

"Tracker: [Could not parse bencoded data: Attention Required! | Cloudflare body{margin:0;padding:0} Please enable co]"

can this plugin fix this or is it only for the 5 second delay fix of cloudflare?

**Comment by Novik** [comment]
This plugin has not relation to the communication of **rtorrent** with trackers. 
This plugin is intended for normalize of communication of **ruTorrent** with a web-resources. For plugin 'extsearch', for example.
