### ISSUE TITLE
Ratio Groups not working

### ISSUE THREAD

**Issue by golya87** [Novik/ruTorrent#1996]
I've running rutorrent linuxserver docker image, after I've set up Ratio Groups and attached it to my torrents a lot of them has been deleted. The problem is that the time limit hasn't expired.
Here are my ratio rules:
![image](https://user-images.githubusercontent.com/19365979/73353186-1baa6900-4293-11ea-8be5-48e5f38a169f.png)

These are my plugins:
![image](https://user-images.githubusercontent.com/19365979/73353303-5a402380-4293-11ea-8f6b-329e9e0bfedb.png)

And my history:
![image](https://user-images.githubusercontent.com/19365979/73353452-a5f2cd00-4293-11ea-95dc-159e47126bd9.png)

Is it a plugin problem or a misconfiguration?

**Comment by koblack** [comment]
https://github.com/Novik/ruTorrent/issues/1949#issuecomment-533447509

**Comment by golya87** [comment]
Should I edit the Min,% and Max,% to 99999999999 and in this case the timelimit would be used?

**Comment by golya87** [comment]
This isn't clear to me, because my other two servers (installed last year and earlier) work with the mentioned ratio rules.

**Comment by golya87** [comment]
I've modified it like this and still not working.
![image](https://user-images.githubusercontent.com/19365979/73432320-c29a0e00-4342-11ea-9949-eb451b195d62.png)

After a reboot my plugins won't start automatically (my bad), but right after the webgui started it deleted a lot of files (but not all) before the rules even met.

![image](https://user-images.githubusercontent.com/19365979/73432452-10af1180-4343-11ea-8a2a-b58a21c8f9e3.png)
