### ISSUE TITLE
[Feature Request] Add a button to hide the General tab

### ISSUE THREAD

**Issue by Machou** [Novik/ruTorrent#1998]
Hello :)

It's possible to add a button (or other) to collapse the General tab.

Example : ![Example](https://i.imgur.com/CSsVCKh.jpg)

Or maybe an plugin exist but i not found it =)

**Comment by koblack** [comment]
![Schowek0123](https://user-images.githubusercontent.com/25719620/73884238-b7c10b00-4865-11ea-9122-86d922adb430.png)

**Comment by Micdu70** [comment]
F6 => "Toggle details" button is what you want. ^^
Or you broken this key and ask an another way? xD

**Comment by Machou** [comment]
Yes I know, but I just want to know if it was possible to add the button ^^

**Comment by Micdu70** [comment]
It's easy to add a button to hide this, but you don't want a button to display back so?

**Comment by Machou** [comment]
Of course i want like uTorrent :)

**Comment by Micdu70** [comment]
> Of course i want like uTorrent :)

Test this => https://github.com/Micdu70/plugin-toggle_details_button-ruTorrent

=)

**Comment by Machou** [comment]
> 
> 
> > Of course i want like uTorrent :)
> 
> Test this => https://github.com/Micdu70/plugin-toggle_details_button-ruTorrent
> 
> =)

very nice, thx you !

**Comment by Micdu70** [comment]
> > > Of course i want like uTorrent :)
> > 
> > 
> > Test this => https://github.com/Micdu70/plugin-toggle_details_button-ruTorrent
> > =)
> 
> very nice, thx you !

hey, no problem french mate. ^^
I have updated it (latest plugin version is 1.50) and I think it is 99.9% working perfectly now (so no more update). :D
