### ISSUE TITLE
rutracker adding url does not work anymore

### ISSUE THREAD

**Issue by Hacker-CB** [Novik/ruTorrent#1999]
Hello!

I have rutracker account configured in rutorrent.
Some weeks ago adding torrent from rutracker URL has stoped to work.

URL example: `https://rutracker.org/forum/dl.php?t=3946842`

I have tried to upgrade to the latest rutorrent but it still does not work.

So, seems that something was changed in rutracker side, but I don't know what.

**Comment by Hacker-CB** [comment]
I found the problem. Old user agent does not work anymore:
`User-Agent: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0`

Setting `$client->agent` to NULL fixes this:

```
diff --git a/plugins/loginmgr/accounts/RUTracker.php b/plugins/loginmgr/accounts/RUTracker.php
index fc40283a..e7ea22cc 100644
--- a/plugins/loginmgr/accounts/RUTracker.php
+++ b/plugins/loginmgr/accounts/RUTracker.php
@@ -42,6 +42,7 @@ class ruTrackerAccount extends commonAccount
                        $redirect = "https://rutracker.org/forum/viewtopic.php?t=".$id;
                        $referer = "https://rutracker.org/forum/viewtopic.php?t=".$id;
                }
+               $client->agent = NULL;
                if($client->fetch( $this->url."/forum/login.php","POST","application/x-www-form-urlencoded",
                        "redirect=".rawurlencode($redirect)."&login_username=".rawurlencode($login)."&login_password=".rawurlencode($password)."&login=%C2%F5%EE%E4" ))
                {
```

**Comment by Novik** [comment]
You can simple correct user agent in the conf/config.php file (or inside your user specific config.php if you have one).
