### ISSUE TITLE
unpack is returning wrong date created sometimes

### ISSUE THREAD

**Issue by SmokeyBR** [Novik/ruTorrent#2001]
ive been having problems with few movies been added to the end or middle of list (sort by date created)
just now ive found out why this is happening, auto unpack is saving the file with wrong "date created", it does not seem to happen all the time, for example:
![unpack5](https://user-images.githubusercontent.com/19333582/74507757-20e6f500-4edc-11ea-8446-a14183831d99.jpg)
![unpack2](https://user-images.githubusercontent.com/19333582/74506408-4d007700-4ed8-11ea-9aa6-45d786e4b9a2.jpg)
![unpack3](https://user-images.githubusercontent.com/19333582/74506409-4d990d80-4ed8-11ea-9116-f3e3585d6632.jpg)

did a quick test manual unpacking "Harold and Maude" and while it was unpacking the date was correct once it finished it changes to the older date.

im trying to show logs but having a difficult time right now.... any ideias? is this happening to anyone else ?

system:ubuntu server 18.04
nginx:1.14.0 (Ubuntu)
UnZip 6.00
UNRAR 5.50 freeware
rtorrent: 0.9.8/0.13.8

**Comment by Novik** [comment]
> auto unpack is saving the file with wrong "date created"

Plugin does not create files.
Your archiver (unrar?) create them.
Plugin may only move files from temp directory to current, if you have corresponding value of option $unpackToTemp in your unpack/conf.php.

**Comment by SmokeyBR** [comment]
i have `$unpackToTemp = false;`
so you saying if theres a problem its with unzip or unrar, which ever is unpacking? if i have both unzip and unrar installed which will it used ?

**Comment by Novik** [comment]
Unrar for .rar archives, unzip for .zip of course.

**Comment by SmokeyBR** [comment]
thanks just did a `unrar e filename.rar` on CLI and the problem is still there.

**Comment by defhead** [comment]
I also have some issues with dates of the unpacked files. But I think it doesn't come from the plugin nor unrar itself. Few hours ago rutorrent auto-unpacked some new download and I got my unpacked MKV with the date 12/31/2097 (yes, 2097) (both for access and modify times) . That was on my Ubuntu server. So I downloaded the RAR parts on my Windows, unpacked them there (with 7zip), and got the same thing.

So I think the date issues come from the **packing** done by the uploaders, not the unpacking.

@Novik I wonder if it would be possible to add an option to unpack plugin, to "touch" all unpacked files, so their mtime gets updated? (with something like `touch -m <path/to/unpacked/file>`

**Comment by SmokeyBR** [comment]
i think you got it defhead, i vote for an option like that in my case i use auto unpack mainly for video files while some media servers do support ordering when the file when it was actually added not all of them do, some will just use the date created regardless of when it was actually unpacked or added to the library.
