### ISSUE TITLE
HD-Torrent

### ISSUE THREAD

**Issue by sayroni** [Novik/ruTorrent#2008]
hi.

in the search section , and private tracker , HD-Torrent not work now..

nothing show in search result,

please check.. thanks.

**Comment by sayroni** [comment]
please fix this, tanks Novik

**Comment by Novik** [comment]
I need invite or existing account for this.

**Comment by koblack** [comment]
Plugin works fine, HDTS sometimes uses cloudflare protection.

**Comment by sayroni** [comment]
> Plugin works fine, HDTS sometimes uses cloudflare protection.

That's right, check now and correct...
