### ISSUE TITLE
Problem with Autotools

### ISSUE THREAD

**Issue by TMTYD** [Novik/ruTorrent#2009]
Hi in the log file I get this message: 

> PHP Warning: readdir () expects parameter 1 to be resource, bool given in /var/www/ru/plugins/autotools/util_rt.php on line 274 

What does this message mean?  Rtorrent runs at 100% CPU utilization.

Output from util_rt.php

> 274:            while( false !== ( $item = readdir( $handle ) ) )

**Comment by Novik** [comment]
This mean: you turned on 'AutoWatch' feature but rtorrent do not have access to the directory, that you specified.

**Comment by TMTYD** [comment]
Ok thanks, I'll take a look at it, then give feedback thx

**Comment by TMTYD** [comment]
Hi

I found the error, the rights were set incorrectly in the rutorrent / share folder.

Thanks for your hint
