### ISSUE TITLE
[Diskspace plugin] Change hard drive

### ISSUE THREAD

**Issue by Hightmar** [Novik/ruTorrent#2011]
Hello, 

I can't change my hard drive on the diskspace plugin

conf.php in `/var/www/rutorrent/conf`
`$topDirectory = '/media/pi/Raspnas/'; // Upper available directory. Absolute path with trail slash.`

conf.php in` /var/www/rutorrent/plugins/diskspace/`

`$diskUpdateInterval = 10;       // in seconds
$notifySpaceLimit = 512;        // in Mb
$partitionDirectory =  $topDirectory;   // if null, then we will check rtorrent download directory (or $topDirectory if$                                // otherwise, set this to the absolute path for checked partition.`

I also tried to modify the user's `conf.php` file. If I put the disk location `/media/pi/Raspnas` the plugin is no longer displayed. If I put the disk name `/dev/sda2` the plugin shows me 1.7GB while the disk is 980 GB.

Help please

**Comment by minidarknova** [comment]
I think ruTorrent uses rtorrent settings and structure to figure out for that plugin, I do also use a similar situation and had to put .session folder in my external hard drive and then it will be recognised by rutorrent.

**Comment by Baton34** [comment]
In my case different drives linked in topDirectory (/home/data/). So I changed in conf.php in /var/www/rutorrent/plugins/diskspace/
$partitionDirectory ='/home/data/video/';
and diskspace shows me info about drive with video.
