### ISSUE TITLE
RSS-Error loading feed

### ISSUE THREAD

**Issue by Kopeeec** [Novik/ruTorrent#2014]
After rutorrent update to 0.9.8/0.13.8 i cant add any RSS Feed. RSS links are good and works in uT.2.2.1 . Any advise to fix this ? :) 
Thanks.

**Comment by Novik** [comment]
> to 0.9.8/0.13.8

This is a *rtorrent* version. And it's upgrade can't affect *ruTorrent* plugin 'rss'.

**Comment by Kopeeec** [comment]
Oh sorry. ruTorrent went from v3.x ( not sure if it was 7 or 8)  to v3.9. 

>  And it's upgrade can't affect ruTorrent plugin 'rss'.

So if it wasnt fault of the upgrade, then why i am keep getting this error?

**Comment by Balykoo** [comment]
I have the same problem

**Comment by Balykoo** [comment]
What is the difference between DOWNLOAD feed and a WEB feed ? Maybe it's the point

**Comment by Novik** [comment]
For first you have torrent download links in the feed items.
For second - *description* of torrents data. 
Only first may be used for automatic download.

**Comment by Balykoo** [comment]
so that's good ? 
```rss
<item>
<title>Integrale Johan van der Keuken Coffret 3 DVD3 2007 VOSTFR FullDVD Mpeg2 AC-3-Skwar (S:0/L:0)</title>
<link> https://www.site.com/torrent/filmvidéo/documentaire/623339-integrale+johan+van+der+keuken+coffret+3+dvd3+2007+vostfr+fulldvd+mpeg2+ac-3-skwar</link>
<category domain="https://www.site.com/search_builder?id=2145">Film/Vidéo</category>
<description>
<![CDATA[ Catégorie: <strong><a href="https://www.site.com/search_builder?id=2145">Film/Vidéo</a></strong> <br/> Taille de l'upload: 6.95Go <br/> Status: 0 seeders et 0 leechers <br/> Ajouté le: 29/05/2020 13:55:49 ]]>
</description>
<guid isPermaLink="true">https://www.site.com/torrent/filmvidéo/documentaire/623339-integrale+johan+van+der+keuken+coffret+3+dvd3+2007+vostfr+fulldvd+mpeg2+ac-3-skwar</guid>
<pubDate>Fri, 29 May 2020 13:55:49 +0200</pubDate>
<enclosure url="https://www.site.com/rss/download?id=6666666&passkey=michel" length="7461251072" type="application/x-bittorrent"/>
</item>
```

**Comment by Novik** [comment]
This is a question to you. If manual downloads in plugin works - then yes.

**Comment by gpmnsp** [comment]
Same problem here. I've recently updated to 3.10 but the issue perseeds.
