### ISSUE TITLE
Keeping completed torrents

### ISSUE THREAD

**Issue by inside83** [Novik/ruTorrent#2017]
Hello,

I was wondering if there is some other way of not downloading the same torrents again.
Now I move files but keep them in the interface so they get recognized if I put the same .torrent file into a watch folder.
But seams rather silly because now I have over 10k torrents under 'Completed' files and the number just keeps on rising.

**Comment by xombiemp** [comment]
Why do you keep putting the same .torrent files in the watch folder?

**Comment by inside83** [comment]
Thank you for your reply :-)
Well I don't do it on purpose. I browse through tracker sites and download what looks interesting then put it into a watch folder.
Sometimes same stuff seams interesting and I forget I already downloaded it.
