### ISSUE TITLE
Setting ratio group of torrent added by sonarr/radarr

### ISSUE THREAD

**Issue by jperk66** [Novik/ruTorrent#2019]
Hello, I am having an issue with rtorrent. My setup is I have rtorrent in the binhex-rtorrentvpn docker with rutorrent as the front end, sonarr/radarr in their docker containers both version 3, all on my unraid server. On rtorrent I have the extratio plug in and ratio groups setup. The ratio groups just remove the torrent after it has seeded 1:1. The issue that I am having is I need rutorrent to set the ratio group automatically when the torrent gets added to rtorrent from sonarr/radarr. Currently this only works when I manually add the torrent. I have a lot of default trackers that I add as to each torrent, around 160 of them. I have noticed this helps a lot with speed and the number of seeders. When I have the ratio rule "all trackers are public" it adds the correct ratio group only when I have the default trackers but none of the other rules work. This only occurs when I add the torrent through sonarr/radarr, but again manually adding the torrent it works as expected. This issue is relatively small as everything else works wonderfully and rtorrent is the best client that I have tried out of the 4-5 major ones. I appreciate the help!

**Comment by xombiemp** [comment]
You set the tag using the Category field in the rTorrent setup in Sonarr.

**Comment by jperk66** [comment]
> You set the tag using the Category field in the rTorrent setup in Sonarr.

Sorry I am new to all of this. What would I set the tag to in the category field? I already have it set to 'tv-sonarr' the default that sonarr puts in there.

**Comment by esran** [comment]
Not sure which plugin provides it, but I have a menu bar option: Plugins->Ratio Rules. This lets me set ratio groups based on tracker url, or label. So that should do what you want.
