### ISSUE TITLE
Ratio not working correctly?

### ISSUE THREAD

**Issue by disgrace2029** [Novik/ruTorrent#2020]
Below is my settings. Every once in awhile a torrent will not follow the group ratio so I get a HnR. Other settings I have is the torrent will automove and unzip. Is there a problem with the Ratio not working correctly?

![ratio](https://user-images.githubusercontent.com/20175679/78676628-b25b5d80-78b4-11ea-89e4-20dbf0e8e23c.JPG)

**Comment by xombiemp** [comment]
Ratio Groups work fine, but I have noticed that sometimes what a tracker records is different than what you have actually seeded. This could be because of network issues or other transient tracker issues.  I gave an extra day buffer to the Time in my Ratio Group rules to account for this.

**Comment by Feriman22** [comment]
Sometimes you have to wait a few minutes (up to 20 mins) to execute the action. This plugin works well.
