### ISSUE TITLE
Autotools Settings 'undefined'

### ISSUE THREAD

**Issue by pistolwhip-dev** [Novik/ruTorrent#2021]
Just pulled the latest rutorrent (well, git clone to webroot) and I'm seeing some strange behavior with the Autotools settings dialogue:

![vivaldi_xPNTHctsRm](https://user-images.githubusercontent.com/55765377/78737434-77d9db00-791d-11ea-85ea-1bdb5117f899.png)

Haven't seen anything in the logs.

**Comment by Novik** [comment]
Try to clear browser cache.

**Comment by pistolwhip-dev** [comment]
Ah, yep, that got it.  Apologies for posting with such a basic troubleshooting step skipped!
