### ISSUE TITLE
Fetch Error with YggTorrent

### ISSUE THREAD

**Issue by L041S** [Novik/ruTorrent#2022]
Worked perfectly until today. It looks like it’s related to the new cloudflare DDoS protection of the website. But it’s strange cause I have the cloudscraper plugin loaded and running 🤔
Is there something to do to enable the plugin with this specific search engine ?

**Comment by L041S** [comment]
More info here, you can see that the plugin is loaded but nothing in the results ![EE12D45C-EE9A-407C-A2B5-A77DB6285D30](https://user-images.githubusercontent.com/60223861/79230352-bfec8680-7e64-11ea-8bc5-7ad8e0bd3616.jpeg)

**Comment by manganate06** [comment]
Same problem for me.
I had the issue (no results in Yggtorrent) with rutorrent 3.8 and when I tried to get the search URL in browser I had the cloudflare message.

I thought it was a rutorrent version problem so I update to 3.9 but still the same message.
Problem starts last week.

I don't have any issue with Couchpotato or Medusa using Jackett

**Comment by L041S** [comment]
By looking at the [wiki](https://github.com/Novik/ruTorrent/wiki/Plugin_cloudflare) it looks like there’s an extra step, I have set $pathToExternals['python'] to the conf.php inside the cloudflare’s plugin directory to usr/bin/pyhton3 already but it seems that we have to set PYTHONPATH for the web server ?
I’m using nginx and have absolutely no idea how to do it x)

**Comment by Novik** [comment]
https://serverfault.com/questions/351696/how-do-you-set-server-specific-env-values-in-nginx

**Comment by L041S** [comment]
Thank you for the link !
If I understand correctly I have to add
`fastcgi_param PYTHONPATH "usr/bin/python3";`
in my case ?

**Comment by Novik** [comment]
You may do this by any described method. With 'env' command globally or with 'fastcgi_param' per location (if you use php-fastcgi, of course).

**Comment by L041S** [comment]
Ok, so I edited my nginx.conf and added 
`env PYTHONPATH=/usr/bin/python3;` (globally) but still the same issue

**Comment by mickkael** [comment]
you can try manually by launching the following command in your linux box:
python3 -c "import cloudscraper;import json; cloudscraper.get_tokens('https://www2.yggtorrent.se/engine/search?name=1080p&do=search');

The reason of the error could be:
- Cloudflare has changed the challenge and the cloudscraper module is not fixed yet (https://github.com/VeNoMouS/cloudscraper/issues/195)
- For some reason (too many tries or just bad luck..), cloudflare is asking you to solve the captcha challenge. The code here is not compatible with captchas. It anyways requires a paid subscription to external provider like anti-captcha.com

I've tried to get a demo account in anti-captcha, but it still fails to get the cookie. Cloudscraper has to be fixed I guess.

**Comment by mickkael** [comment]
Interesting.
the following python commands gives different results from my server running rutorrent and from my laptop. Same public IP though.
`python3 -c "import cloudscraper; scraper = cloudscraper.create_scraper();print(scraper.get('https://www2.yggtorrent.se/engine/search?name=1080p&do=search').text)" | grep HDForever`

Result from the laptop:
`<td style="text-align: left;"><a id="t(###Masked###)HDForever`

Result from the rutorrent server:
`cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

same public IP
same cloudscraper module version 1.2.33
python3 version is different, not sure if it makes any difference.
3.7.3 on the laptop, 3.7.5 on the server

Python version is not the issue : I have tried from a fresh docker with python 3.7.3, same error than on the server:
```
$ docker run -it --rm python:3.7.3 sh
# pip install cloudscraper
Collecting cloudscraper
  Downloading (.....)
# python -c "import cloudscraper; scraper = cloudscraper.create_scraper();print(scraper.get('https://www2.yggtorrent.se/engine/search?name=1080p&do=search').text)" | grep HDF
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
```
it seems to be random, let's wait for the next cloudscraper version and see

**Comment by mickkael** [comment]
Update cloudscaper and the issue is resolved.

pip3 install cloudscraper -U

**Comment by L041S** [comment]
I updated cloudscraper and it seems to work now, here is the result with the command `python3 -c "import cloudscraper; scraper = cloudscraper.create_scraper();print(scraper.get('https://www2.yggtorrent.se/engine/search?name=1080p&do=search').text)" | grep HDForever `
![F55160E4-19BE-45DF-98B1-358782712DCA](https://user-images.githubusercontent.com/60223861/79979322-a0c3a980-84a1-11ea-8042-a7c159023670.jpeg)

However, I still get the fetch error in rutorrent even if the plugin is loaded. 🤔

**Comment by mickkael** [comment]
do you have any error in the logs of your webserver ?

It works for me, so it is on your configuration now.

**Comment by L041S** [comment]
Nothing related to my rutorrent server in my /var/log/nginx/error.log.
The only thing I'm not sure about according to the wiki of the plugin is the part about setting environment variable PYTHONPATH for your web-server. I added 

`env PYTHONPATH="/usr/bin/python3";`

to my /etc/nginx/nginx.conf but I'm not sure if it's enough

**Comment by Novik** [comment]
After dance with tambourine it's works for me.
What I made:

1) Upgrade ssl up to 1.1.1g. See details, for example, here -
https://askubuntu.com/questions/1102803/how-to-upgrade-openssl-1-1-0-to-1-1-1-in-ubuntu-18-04
(but type 1.1.1g instead 1.1.1f)
2) Upgrade clouscraper module up to 1.2.34
I.e.
pip install cloudscraper --upgrade

> Something related to php-fpm maybe ?

Are you restart web server and php-fpm after changes in config?

**Comment by L041S** [comment]
I updated to openssl 1.1.1.g as well this morning and rebooted my machine after changes.
Same issue, I don’t know what could be wrong 🤔
I edited my /etc/php/7.3/fpm/pool.d/www.conf and uncommented 
`clear_env = no`
and added
`env[PYTHONPATH] = /usr/bin/python3.7` but the "Fetch Error" is still here.

**Comment by mickkael** [comment]
The cloudflare challenge has changed again.
https://github.com/VeNoMouS/cloudscraper/issues/209

**Comment by mickkael** [comment]
How to get the dev version without waiting for the release:
pip3 install \
-U --no-deps --force-reinstall \
https://github.com/VeNoMouS/cloudscraper/archive/dev.zip
