### ISSUE TITLE
[Feature Request] Add/copy multiple magnet links and multiple peers.

### ISSUE THREAD

**Issue by PaulinoRBJ** [Novik/ruTorrent#2025]
I just switched to ruTorrent after being a [Transmission Web Control](https://github.com/ronggang/transmission-web-control) user for years and this is the feature that I miss most.
The current dialogues to add the links and peers only accept single line values while multi line inputs are reduced to single liners and in case of magnets only the first link is honored. Also there is no context menu option to copy magnet links like transmission-web-control and most major clients. It would be really helpful if these could be changed to multi-line dialogues, with use cases like mine where I sometimes need to manually add peers from trackers like RARBG that blacklist for example my seedbox's IP address preventing me from getting peers, and for users (including me) that mass import magnet links.

I'm aware that this issue is a (partial) duplicate of #1966 but I felt I needed to open another because this also includes the peer import dialogue.

**Comment by Novik** [comment]
Partially was added in this - https://github.com/Novik/ruTorrent/tree/master/plugins/bulk_magnet plugin.

**Comment by a-raccoon** [comment]
Some day this will be marked as `willfix` given how many people ask for it.  #1966
