### ISSUE TITLE
Unpack Automatically Issue

### ISSUE THREAD

**Issue by Pingblue** [Novik/ruTorrent#2026]
I have an issue with the unpack plugin, the plugin can unpack manually but when you check the box to unpack automatically it doesn't.

I enabled the plugin log and this states that the archives where found and successfully unpacked but this didn't happen.

Tried multiple versions of unrar with the same result.

Managed to fix the issue by using a previous version of the unpack.php file.

PHP 7.3
Apache/2.4.38

**Comment by kultigspritzig** [comment]
Same exact issue, except it used to work so far and I didn't update anything in rutorrent itself.
