### ISSUE TITLE
check_port 

### ISSUE THREAD

**Issue by MrOnyx** [Novik/ruTorrent#2030]
check_port plugin not loadet no icon 
![Anmerkung 2020-04-29 122459](https://user-images.githubusercontent.com/2565966/80586285-04575500-8a15-11ea-83f5-c26adc33f48e.jpg)

**Comment by tryoutuser** [comment]
check_port also reports unknown for me
![image](https://user-images.githubusercontent.com/35561383/83447091-0e3c0000-a47a-11ea-83a5-0126ba2c34f8.png)

**Comment by Micdu70** [comment]
> check_port plugin not loadet no icon
> ![Anmerkung 2020-04-29 122459](https://user-images.githubusercontent.com/2565966/80586285-04575500-8a15-11ea-83f5-c26adc33f48e.jpg)

Check if it is realy loaded in "Plugins" tab, check PHP/WebServer logs too. ;)

> check_port also reports unknown for me
> ![image](https://user-images.githubusercontent.com/35561383/83447091-0e3c0000-a47a-11ea-83a5-0126ba2c34f8.png)

Fixed in git (18 days ago) => https://github.com/Novik/ruTorrent/commit/414fe89dd828febfdc981dc2b855061d8cc11904

**Comment by tryoutuser** [comment]
@Micdu70 uh how do i fix it? by downloading 3.10 beta zip file?

**Comment by Micdu70** [comment]
@tryoutuser no... you need to download "master" zip (https://github.com/Novik/ruTorrent/archive/master.zip) or, better, use git command to easily install (git clone) & update (git pull) ruTorrent.

**Comment by tryoutuser** [comment]
@Micdu70 ok so i just have to extract and overwrite the rutorrent content right?
don't worry i know i have to backup first before doing that.

**Comment by Micdu70** [comment]
@tryoutuser yeap. =)
