### ISSUE TITLE
Question: How to get rid of "All" filters for every single section?

### ISSUE THREAD

**Issue by BRTPOB** [Novik/ruTorrent#2032]
I just installed ruTorrent, and it seems that my instance now has "All" filters for each and every section, and I'm curious what plugin is causing it so I can remove it. I've got a different instance that performs how I'd expect, which I've included screenshots of both.

How can I get the second one to look like the first?

Thanks.
![2c881r76](https://user-images.githubusercontent.com/7201028/80867079-1ee63400-8c8a-11ea-8c43-54e6c2c5af2c.png)
![2o1hncbl](https://user-images.githubusercontent.com/7201028/80867083-21488e00-8c8a-11ea-8812-bdfe5dca1f06.png)

**Comment by Micdu70** [comment]
You can't, it's a new filtering system ("qBitTorrent" like).

**Comment by BRTPOB** [comment]
Ugh there's gotta be an option or something to let people disable this functionality.
