### ISSUE TITLE
non-RIPE Peer IP Details lead to nowhere on ripe.net

### ISSUE THREAD

**Issue by m-ahsen** [Novik/ruTorrent#2033]
On 'Peers' tab, for a given IP, clicking on 'Details' navigates user to RIPE, even though most likely a random IP doesn't belong to RIPE. 

##### Examples, last octets anonymized:
[49.14.121.1](https://apps.db.ripe.net/db-web-ui/query?searchtext=49.14.121.1)
[103.126.60.1](https://apps.db.ripe.net/db-web-ui/query?searchtext=103.126.60.1)

##### Expected result:
Details for an IP address, Country, Region, AS number.

##### Suggestion: 
We could replace `RIPEURL` variable to something more generic, `IPQUERYURL` and use a provider, [https://ipinfo.io/](https://ipinfo.io/) for example, but could be any provider really. This would require 2 line changes on [https://github.com/Novik/ruTorrent/search?q=RIPEURL](https://github.com/Novik/ruTorrent/search?q=RIPEURL)

##### Why?
As RIPE manages European IP assets, for a given IP Details check, it's most likely not an European IP address.

##### Expected result, using ipinfo.io:
[https://ipinfo.io/49.14.121.1](https://ipinfo.io/49.14.121.1)
[https://ipinfo.io/103.126.60.1](https://ipinfo.io/103.126.60.1)

**Comment by Micdu70** [comment]
Did you test before creating this pull request?

URL address should be "https://ipinfo.io**/**" (missing last slash) if you want it to work.
