### ISSUE TITLE
There is no 'libapache2-mod-scgi' in Ubuntu 20.04

### ISSUE THREAD

**Issue by bernid** [Novik/ruTorrent#2037]
There is no 'libapache2-mod-scgi' packet in the Ubuntu 20.04 focal. 
In the wiki:
https://github.com/Novik/ruTorrent/wiki/WebSERVER#apache-specific-scgi-config
you recommend install:
`apt-get install libapache2-mod-scgi`

How to deal with SCGI instalation in the newest Ubuntu?

**Comment by ofry** [comment]
Same problem.

**Comment by Novik** [comment]
Forget about this and use plugin HTTPRPC.

**Comment by bernid** [comment]
I installed manually as deb package earler version: 
https://packages.ubuntu.com/eoan/libapache2-mod-scgi
and works ok.
