### ISSUE TITLE
HTTPRPC usage

### ISSUE THREAD

**Issue by ofry** [Novik/ruTorrent#2040]
Related to https://github.com/Novik/ruTorrent/issues/2037

How to use it? No related info in wiki.

**Comment by bernid** [comment]
I don't think you checked it carefully
https://github.com/Novik/ruTorrent/wiki/PluginHTTPRPC

**Comment by ofry** [comment]
And where are any settings? How I can use it (switch from libapache2-mod-scgi way)?

**Comment by bernid** [comment]
There are no special settings. The plugin (as others plugins) is loaded automatically . You can only switch it off and switch off on launch. See the plugins list and menu (after click (right)) the individual plugin. See also rpc plugin add decide which one to choose.

**Comment by ofry** [comment]
Thank you. Problem is solved.
