### ISSUE TITLE
latest version does not work

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#2041]
this is the error message:

[06.05.2020 12:23:05] JS error: [undefined : 5132] TypeError: undefined is not an object (evaluating 'this.actLbls["flabel_cont"]')

**Comment by Micdu70** [comment]
latest version = latest git version I think?

If yes, you only need to clean your browser's cache. ;)

**Comment by hagabla** [comment]
Yes latest git version, i had no idea there were releases as well.
Clearing browser cache was the first thing i did, did not work though. Switched to the release version now.

**Comment by Micdu70** [comment]
That's only a caching issue, if it's not the browser it can be your webserver (caching .js files). ;)

**Comment by hagabla** [comment]
If nginx does cache js files per default maybe, i didn't tell it to though.
