### ISSUE TITLE
IPad 2020 can’t load .torrent to rutorrent

### ISSUE THREAD

**Issue by DeNeDeM** [Novik/ruTorrent#2043]
I just got a new iPad Pro 2020 and when I tried to load a .torrent file to my rtorrent server via rutorrent I couldn’t select it. The file is blurred out.
Any ideas why?
Thank you.

**Comment by koblack** [comment]
For IOS compatibility #1994

**Comment by DeNeDeM** [comment]
I’ve tried that fix and the result is the same. Torrent files are still blurred. I’m using iPadOS 13.4.1
