### ISSUE TITLE
Edit torrent greyed out

### ISSUE THREAD

**Issue by DeNeDeM** [Novik/ruTorrent#2051]
Is there any reason why edit torrent would be greyed out when I’m trying to edit and announce url in bulk for 1k torrents?

**Comment by Micdu70** [comment]
and for 2 torrents it works?
If the answer is no, you use a very old ruTorrent version.

**Comment by DeNeDeM** [comment]
Hmm..a friend gave me his link to seedbox and I’m seeing it is using version 3.6

**Comment by Micdu70** [comment]
So, yes, it's very old. ^^

**Comment by DeNeDeM** [comment]
Ohh..so i need to get him to the latest build. I understand.

**Comment by Micdu70** [comment]
Yeap! =)

**Comment by DeNeDeM** [comment]
Thank you 👌
