### ISSUE TITLE
Question: Asking for Help on AutoTools?

### ISSUE THREAD

**Issue by Cyb3rGh05t** [Novik/ruTorrent#2058]
Hi,

Using AutoTools, just want to copy the downloaded torrent to a given folder, but only those torrents which come without .rar files. I use Unpack plugin to move finished .rar packed torrents.

How can i set AutoTools to only exclude torrents folders with .rar files in it? so that it just copies the finished unpacked torrent folders.

Thanks for helping :)

![image](https://user-images.githubusercontent.com/5200101/82754960-d7f2e680-9dd0-11ea-87dc-154ebe2b81de.png)

**Comment by Micdu70** [comment]
In "Skip torrents that contain files matching pattern", write this:
- For ".rar" only => `.*\.rar$`
- For all "rar" type => `.*\.(?:rar|r\d\d|\d\d\d)$`

N.B.: I have not tested but should do what you want. :)

**Comment by Cyb3rGh05t** [comment]
thanks works like a charm :)
