### ISSUE TITLE
Remove and delete data sometimes fails

### ISSUE THREAD

**Issue by albertofustinoni** [Novik/ruTorrent#2066]
Selecting multiple torrents and doing `remove and -> delete data` does not always work.

All torrents will be removed from the UI but the data for some will be left behind.
Permissions are the same between removed and not removed torrent data and whether the torrent is a single file or a folder also makes no difference.

**Comment by Feriman22** [comment]
I have very similar issue. The permissions are same on all files/folders, but the "Remove data (all)" function not always works.

I'm using this function mostly with Ratio plugin.

**Comment by retrorat1** [comment]
Have you checked if the undeleted file/folder was auto unzipped and the original torrent was a zip bundle? This can be one reason for files/folders being left behind as it was not part of the original zipped torrent.

**Comment by Feriman22** [comment]
@retrorat1 No, I never download zipped files via torrent, so this way is impossible in my case.

**Comment by Feriman22** [comment]
@retrorat1 No, I never download zipped files via torrent, so this way is impossible in my case.

**Comment by albertofustinoni** [comment]
Likewise I never used the auto unzip functionality.

**Comment by Selas81** [comment]
Hey I have the same issue since my seedbox was upgraded by the provider about a year ago, it's getting more and more annoying having to delete multiple times..

**Comment by EsEnZeT** [comment]
@Selas81  

try adding this to rtorrent.rc
`schedule2 = untied_directory,5,5,"remove_untied="`

**Comment by Selas81** [comment]
> @Selas81
> 
> try adding this to rtorrent.rc
> `schedule2 = untied_directory,5,5,"remove_untied="`

Thanks a lot @EsEnZeT , it does seem to help somewhat, however the issue still happens to a slightly less degree, is it possible to adjust the command, to make it more likely to catch every file?

**Comment by EsEnZeT** [comment]
Not sure, sorry, above works for me with everything.
