### ISSUE TITLE
about port checker

### ISSUE THREAD

**Issue by bleeee** [Novik/ruTorrent#2068]
for users in china, https://portchecker.co/ returns port status close whether the port is open or not. Guessing GFW is blocking it.
I find out following websites working fine and their response is very short

https://codebeautify.org/open-port-checker
https://websistent.com/tools/open-port-check-tool/
https://www.yougetsignal.com/tools/open-ports/

**Comment by Micdu70** [comment]
@Novik Worth changing website for check_port plugin? "yougetsignal.com" is OK for you?

**Comment by Novik** [comment]
In theory you may implement checker, that will work with *all* of these services. 
With configuration of currently used service in the plugins conf.php.
