### ISSUE TITLE
_task plugin

### ISSUE THREAD

**Issue by TMTYD** [Novik/ruTorrent#2070]
Hi

I noticed the following, the task plugin runs continuously, if I deactivate it and reactivate it, it will continue to run

Output form task.php

```
(root)-(~)->sed -n 325,326p /var/www/ru/plugins/_task/task.php
$tasks[$file]["name"] = $tasks[$file]["params"]["name"];
$tasks[$file]["requester"] = $tasks[$file]["params"]["requester"];
```

i found this in the Apache log file:
```
PHP Notice:  Undefined index: requester in /var/www/ru/plugins/_task/task.php on line 326,

PHP Notice:  Undefined index: name in /var/www/ru/plugins/_task/task.php on line 325, 
```

![grafik](https://user-images.githubusercontent.com/29516076/84200706-7c4e7b80-aaa7-11ea-9d11-0cc079545735.png)

I cannot remove the tasks without a name

I found out where the tasks are saved in share / settings / tasks

where is the mistake that he doesn't indicate? Or is another plugin responsible for this?

```
#!/bin/sh
dir="$(dirname $0)"
echo $$ > "${dir}"/pid
chmod a+rw "${dir}"/pid
touch "${dir}"/status
chmod a+rw "${dir}"/status
touch "${dir}"/errors
chmod a+rw "${dir}"/errors
touch "${dir}"/log
chmod a+rw "${dir}"/log
last=0
mediainfo  '/xxxx' 2>> "${dir}"/errors >> "${dir}"/log
if [ $? -ne 0 ] ; then
        last=1
fi
echo $last > "${dir}"/status
/usr/bin/php7.3 '/var/www/ru/plugins/_task/notify.php' $last "${dir}" '' > /dev/null 2>> /dev/null &
```

**Comment by TMTYD** [comment]
?

**Comment by Novik** [comment]
I have no idea - what do you have here.
If you want to remove all tasks, you may simple remove all inside share/settings/tasks (or shar/users/USERNAME/settings/tasks) manually.

**Comment by TMTYD** [comment]
this happens when I try to create a torrent, the console is also empty see screenshot

![grafik](https://user-images.githubusercontent.com/29516076/85950410-cc10bc00-b95c-11ea-93d5-9da9d2a54d2a.png)

**Comment by TMTYD** [comment]
> 
> 
> I have no idea - what do you have here.
> If you want to remove all tasks, you may simply remove all inside share/settings/tasks (or shar/users/USERNAME/settings/tasks) manually.
I have removed all of them, but if I create a new torrent again, it will come back

**Comment by TMTYD** [comment]
it was the scgi host wrong,

I installed in vm debian, rutorrent, rtorrent etc., there was the standard scgi host: port 127.0.0.1:5000, so it was also set in .rtorrent.rc. So now I went through everything and compared it with my rtorrent + rutorrent on my server until I came across the scgi host: port, I had it with nas: 5000, nas (127.0.1.1), then got it changed to 127.0.0.1 and restarted everything and tried creating again and it worked, that was the error.
