### ISSUE TITLE
Check_port

### ISSUE THREAD

**Issue by rtorrentuser** [Novik/ruTorrent#2071]
Check_port plugin stopped working after the latest commit:

[13.06.2020 13:54:57] Bad response from server: (500 [error,initportcheck])

**Comment by nerthazrim** [comment]
Same issue here.

Looks like something is wrong with **plugins/check_port/action.php**

On line 43, the following function is defined:
`function check_port($ip,$port,$checker,$closed,$open)`

On line 72, the following call is made:
`check_port($ip_glob,$port)`

My assumption is that either the call needs to give the 3 next parameters ($checker,$closed,$open) or the parameters need to have default values in the function definition.

**Comment by Micdu70** [comment]
@nerthazrim Yeap, my bad. ^^

**Comment by moerfutin** [comment]
updated to the latest release 3.10. But the same issue here.
On YouGetSignal site, it says port is open, but in ruTorrent it's 'unknow'.

![image](https://user-images.githubusercontent.com/9960618/92727201-4fa94900-f3a1-11ea-94c2-00b0764038cd.png)
