### ISSUE TITLE
Question: Mediainfo plugin output customization

### ISSUE THREAD

**Issue by Smoukus** [Novik/ruTorrent#2077]
Hi, by default the plugin generates complete mediainfo of the video.
On Windows you are able to output custom format mediainfo.

Is thst also possible with this plugin?

**Comment by Novik** [comment]
No. But you may create your own version of plugin, that will support that feature.

**Comment by Smoukus** [comment]
> No. But you may create your own version of plugin, that will support that feature.

Alright, thanks for the swift reply.
