### ISSUE TITLE
Why is there a "Select Source" and then also "Source" in "Create New Torrent"?

### ISSUE THREAD

**Issue by justauserid** [Novik/ruTorrent#2079]
**Version**: 3.9

<img width="408" alt="Screenshot 2020-07-02 at 1 32 33 PM" src="https://user-images.githubusercontent.com/67732475/86332762-9293c580-bc68-11ea-84cf-2a79709ed121.png">

[Documentation](https://github.com/Novik/ruTorrent/wiki/PluginCreate) doesn't show it. 

Is it to be left blank? 
Or to be filled with the same path from "Select Source"? 
Or is it supposed to be some other kind of source?

**Comment by Novik** [comment]
This is a tag for cross-seeding.
https://www.reddit.com/r/trackers/comments/5gvz19/how_does_adding_a_source_tag_help_with/

> Is it to be left blank?

Yes.

> Documentation doesn't show it.

Everyone may change documentation.
