### ISSUE TITLE
When using Search box in a top-right corner i got: JS error: [../js/webui.js : 2150] Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by silasmariusz** [Novik/ruTorrent#2081]
Hi,

When trying to search for local torrents in a right-top corner search box i got:
JS error: [http://xxx/ui/rtorrent/js/webui.js : 2150] Uncaught TypeError: Cannot read property 'id' of undefined

However search works well.

Best Regards

**Comment by silasmariusz** [comment]
I found its instantsearch issue.

**Comment by Micdu70** [comment]
@silasmariusz You can update instantsearch plugin, download from my fork => https://github.com/Micdu70/rutorrent-instantsearch ;)
