### ISSUE TITLE
Issue with uploading multiple torrents at once and sorting by added

### ISSUE THREAD

**Issue by NoahBK** [Novik/ruTorrent#2082]
The issue arises if you upload multiple torrents at once into ruTorrent. I originally thought it was an issue with my seedbox provider, but it doesn't seem to be. What's weird is that I have been doing this for what seems like forever and it recently just became an issue. Perhaps it's the amount of torrents I am seeding that is breaking ruTorrent? (I am seeding 918 torrents currently if that is actually the issue and someone needs to know how many I have)

Example of what is happening:
https://i.imgur.com/EQuLMIo.gif

**Comment by allixx** [comment]
shift+click on torrent name column. this assigns second-pass sort data source, which is very useful when 'main' sort column data is not unique (in your example there are multiple torrents with the same 'Added' timestamp).
