### ISSUE TITLE
Strtolower remove from REMOTE_USER

### ISSUE THREAD

**Issue by silasmariusz** [Novik/ruTorrent#2085]
Please apply this patch:
`--- util.php`
`+++ util.php.fixed`
`@@ -390,7 +390,7 @@`
` function getLogin()`
` {`
` 	return( (isset($_SERVER['REMOTE_USER']) && !empty($_SERVER['REMOTE_USER'])) ?`
`-		preg_replace( "/[^a-z0-9\-_]/", "_", strtolower($_SERVER['REMOTE_USER']) ) : '' );`
`+		preg_replace( "/[^a-zA-Z0-9\-_]/", "_", $_SERVER['REMOTE_USER'] ) : '' );`
` }`
``
` function getUser()`
``

Since several config files are saved in:
`Username\*.dat`
and other are in lowercase directory:
`username\*.dat`

**Comment by Novik** [comment]
I can't understand - why we need this. If you still need these changes, please add yet one ticket with explain.
