### ISSUE TITLE
The "added" column not being populated (still an issue with version 3.10)

### ISSUE THREAD

**Issue by electrotype** [Novik/ruTorrent#2088]
I'm aware of https://github.com/Novik/ruTorrent/issues/1859 . But the issue still occures with ruTorrent v3.10

The issue is that after a while, the "added" column is not populated anymore. Therefore you can't sort your torrents by the latest ones added, which is an issue for me.

The ruTorrent I use runs on a seedbox provider, pulsedmedia.com , which is very responsive and always keeps the softwares up-to-date. Version 3.10 of ruTorrent is currently installed. The support from Pulsedmedia says that this bug now exists for many years and that the only thing that seems to "fix" it is to restart rTorrent...

I sadly don't have control on the installation of rTorrent or ruTorrent, but I do have access to the files on the server and I see the `seedingtime` plugin is installed.

Do you have any idea of what can be the cause for this issue?

Let me know if you need information about any of the files on the server or need an HTTP response from the server for a specific request (I could use my browser's devTools to get it).

Thank you!

**Comment by esran** [comment]
I'm seeing this also. It also seems that when this happens ratio stuff can also fail on that torrent. So ratio rules for assigning a ratio group based on tracker url doesn't seem to happen. If manually applied then the ratio rules do work okay.

When this happens on torrents it is also quite common for the finished column to be empty, though not consistently it seems.

I'm wondering whether its an issue with how torrents are added and interaction with the UI. One thing I've noticed is that when I'm checking the web UI to see what's going on with these torrents that the timestamps shown are all over the place. The time in the bottom of the window is wrong and existing timestamps on torrents are often several hours or more in the future. Refreshing the browser window seems to bring this back in line.

If a browser session thinks its in the future then maybe this could affect things when a torrent gets added? (maybe it is attempting to work around back-dated timestamps?)

**Comment by esran** [comment]
Another data point: when this happens to torrents I note that there is also no pushbullet notification. So it looks like the events aren't being fired for these torrents for some reason. I have a mix of torrents added by sonarr/radarr and also autodl using the direct rtorrent method.

**Comment by electrotype** [comment]
The comments from @esran make me realise that maybe the way I add new torrents has something to do with the issue? I have a script on my local machine which automatically uploads the `.torrent` files to the "`/watch`" folder on the server where rTorrent runs...

But then again, this works fine and the empty "added" column issue only happens sometimes/after a while.

**Comment by Novik** [comment]
Possible reasons of this:
1) Failed 'on_insert' handler in the other plugin(s). For detection: add diagnostic to the .rtorrent.rc, catch issue and check log file. For example, by such way:
```
log.execute = /tmp/rtorrent_exec.log
```
2) This issue - https://github.com/rakshasa/rtorrent/issues/161 Solution: use patched version of rtorrent - https://github.com/Novik/rtorrent

**Comment by esran** [comment]
I enabled the log and had that running when a new torrent failed to get updated. No added date and no pushbullet notification. No errors show in the log. I went back to the previous log entry referring to a torrent, which was a different torrent finishing. Following that we got the following:

[rtorrent_exec_log.txt](https://github.com/Novik/ruTorrent/files/5081221/rtorrent_exec_log.txt)

I've trimmed out a lot of duplicate messages. Some of these occur very frequently. For reference, here are some counts from the current log file:

- erasedata = 496
- autotools = 24
- trafix = 8
- rutracker_check = 1
- scheduler = 1

**Comment by esran** [comment]
Interestingly, I've just been pinged with a finished notifcation for the torrent that failed on adding. So it does have a finish time, but no added time and auto ratio group hasn't been set.

**Comment by YaPaY** [comment]
could you fix the problem @esran 

I cannot fix this problem, changing date format, restart server or restart plugin didn't help on me

**Comment by esran** [comment]
Haha, no. I've switched to qbittorrent.

**Comment by YaPaY** [comment]
> Haha, no. I've switched to qbittorrent.

are there supports for qbittorrent like execute scripts after finished downloads etc?

**Comment by sam20e** [comment]
not sure why this is marked as "wontfix" this is an ongoing issue........

**Comment by electrotype** [comment]
For those following this issue, I found a workaround that is acceptable for me. It's not a fix.

First, I realized that this empty "Added" field occures only when the web interface is not open when a torrent file is added (I add new torrent files using a script and sftp).

Since I sort by the "Added" column, all new torrents with an empty added date are listed first so they are easy to find. 

The trick is to right-click on them, choose `Edit torrent...` and then click `OK` without changing anything. This will actually populate the added date and the torrent will be moved to the end of the list!

**Comment by mpuckett159** [comment]
Just to be more specific for those in the future, the added date that is populated using the above method will be the date and time you clicked edit torrent and ok, not the actual date and time the torrent was added. This is a good enough fix for me when my container runs out of memory and crashes all the plugins since I'm just trying to keep track of roughly how long the torrent has been active for, and a few days here and there aren't that big an issue, but may not be for others.

**Comment by Maksim-us** [comment]
This also resets the ratio column to 0.

**Comment by stickz** [comment]
You can also write a method for rTorrent to populate the added time using something like:
`method.set_key = event.download.inserted`
You need to populate the value of `d.set_custom` for `addtime` on the current torrent. Should be able to retrieve this from shell.

The real problem though is a race condition with `rTorrent` like Novik mentioned. It's not an `ruTorrent` issue. I will submit a patch to the swizzin install script when time permits. This is only supported on Ubuntu and Debian though.

**Comment by petarmm** [comment]
I had this problem for a long time. It's intermittent nature suggested some type of race condition like people here suggested. After a recent upgrade of ruTorrent I did, the problem worsened to the point almost no torrent, especially added through a watch directory, had populated "Added" column. 

_In my case_, using a diagnostic method Novik mentioned, I managed to narrow it down to the "**quotaspace**" plugin. This plugin is labeled as authored by Novik, but there is no such thing in the repository. So it's probably a custom edit of the "diskspace" plugin to include quotas, made by the seedbox provider. Keeping the Novik's name as an author led me to skip it in my previous searches for a culprit. Upgrading ruTorrent changed some of the UI where free space is shown, so it's possible that the plugin itself was rewritten, causing even bigger issues.

Disabling the "**quotaspace**" plugin solved this problem for me, for the most part. I've been running like this for around a month and have no fails in "Added" column, but I can't claim 100% as I did not do any extensive testing, or dive into a code to check what the actual problem is (it does seem that the plugin doesn't respect the time limit for updates or something).

I hope this helps someone in a similar situation.

**Comment by daymanbpi** [comment]
> quotaspace

rtorrent 0.9.8 | rutorrent 5.1.4
Testing now. Thankyou for working this out. This problem has been plaguing me forever and might be the most annoying bug I have ever experienced.....

**Comment by w4hnsinn** [comment]
Well that's great for those of you using seedboxes where that's not lisated as "MANDATORY"....

> You can also write a method for rTorrent in `rtorrent.rc` to populate the added time using something like: `method.set_key = event.download.inserted` You need to populate the value of `d.set_custom` for `addtime` on the current torrent. Should be able to retrieve this from shell.

This sounds promising? Can anyone maybe come up with the complete method? I'm clueless about this scripting, but I'd really like if that column got reliably populated.

**Comment by keldian** [comment]
Following https://github.com/Novik/ruTorrent/issues/2088#issuecomment-2605685121 I disabled the `diskspace` plugin and added dates started appearing again on new torrents. That suggests the race condition is within rutorrent itself and not with rtorrent as stated.

**Comment by hwcltjn** [comment]
I don't have either of the `quotaspace` or `diskspace` plugins enabled - or any other plugin that might offer the same functionality - and still face this issue.

**Comment by adm-eni** [comment]
Presumably for those affected, `diskspace` or `quotaspace` gets delayed with filesystem operations on remote mounts, which blocks rutorrent from setting `addtime` on a new torrent. In your case it could be another plugin getting too busy for a different reason.

**Comment by keldian** [comment]
Presumably for those affected, diskspace or quotaspace gets delayed with filesystem operations on remote mounts, which blocks rutorrent from setting addtime on a new torrent. In your case it could be another plugin getting too busy for a different reason.

**Comment by Novik** [comment]
AFAIR, reason of this is an error inside rtorrent - it use one static buffer for execute_capture statement. As result, launching of execute_capture in one thread may overwrite result of execute_capture in another.
Possible fix: https://github.com/novik/rtorrent/commit/8022acf3342b3c899d0cdc0627921b7b946e6846
Or you should not use plugins with usage of execute_capture statement.

**Comment by keldian** [comment]
I suggested a workaround at https://github.com/Novik/ruTorrent/discussions/2856#discussioncomment-12264968 based on stickz's idea. Can't confirm it works 100% but after re-enabling `diskspace` and using that, I'm still not hitting blank "added" cells.
