### ISSUE TITLE
Automove moving torrents too early

### ISSUE THREAD

**Issue by gstacks13** [Novik/ruTorrent#2089]
I'm running into a persistent issue where Automove is moving torrents before they're completed downloading, leading to partial downloads when my client attempts to grab the files from the completed folder.  I've traced that the issue is with Automove by logging the file size upon discovery, and oftentimes they're not even 1/2 the size of the completed file.

Running ruTorrent 3.9.

**Comment by Ferarchi** [comment]
I'm running into the same issue where ruTorrent tells sonarr and Radarr the directory where the file was downloaded but not where it has moved it to for seeding. The only way i've found to fix this is to restart sonarr or radarr and it gets the updated/moved file location.
