### ISSUE TITLE
Autounpack not working

### ISSUE THREAD

**Issue by EchoDev** [Novik/ruTorrent#2090]
I recently upgraded my system and now I'm having issues with autounpack

rTorrent upgraded to 0.9.8
ruTorrent upgraded to v3.10 (manually)
php upgraded to v7.4

With my old setup autounpack was working but now it does not. I can't seem to produce a proper log so I cant find out whats wrong. Manual unpack works without issues. 

Anyone else running into issues?

**Comment by Pingblue** [comment]
I did have this issue, resolved it by reverting to a previous version of the unpack.php file.

**Comment by EchoDev** [comment]
@Pingblue which version did you revert to? v3.9 or previous commit?

**Comment by EchoDev** [comment]
Ok I see 1 issue already with the unpack.php

rtorrent 0.9.8 has changed a bunch of commands. The commands in the unpack.php didn't trigger anything because they werent correct for 0.9.8 

See here: https://raw.githubusercontent.com/rakshasa/rtorrent/master/doc/scripts/update_commands_0.9.sed

I finally got unpack to trigger the autounpack but it doesnt seem to extract anything. Still looking into that.

**Comment by EchoDev** [comment]
Throwing a chmod 777 to the tasks folder fixed the issue for me
