### ISSUE TITLE
Plugin loginmgr: MyAnonamouse login not working

### ISSUE THREAD

**Issue by incryptosoft** [Novik/ruTorrent#2094]
It seems that the login mechanism for MyAnonamouse isn't working.

I tried messing with the  code some  but the page response always returns the login page when trying to get a list of torrents.

I will continue to try to fix this but if anyone else has any ideas or knows how to fix this input is welcome.

**Comment by jrdnlc** [comment]
Did you end figuring this out? I'm having same issues.

**Comment by Novik** [comment]
I made corresponding changes, but can't clearly test them, because my account on the MyAnonamouse is disabled.

**Comment by Novik** [comment]
I got invite and solved problem with authentication for this tracker, but I have no idea what we have with a search on it.
This tracker has a strange karma system and I can't download something from it without manipulations with this fucking karma.
As result, I haven't download links on the search result and I can't check search RegEx.

**Comment by Novik** [comment]
Now all must works.

**Comment by koblack** [comment]
Thanks, everything is working properly.
