### ISSUE TITLE
download speed is changing after a few minutes

### ISSUE THREAD

**Issue by YaPaY** [Novik/ruTorrent#2095]
Hello, please see

https://monosnap.com/file/DyepL8y3lQVFym777cfuG059BeiC2D

I am setting this value to 0 (unlimited) but a few minutes later it is becoming 327625. in .rtorrent.conf file also the download speed=0

is it a bug?

**Comment by Micdu70** [comment]
That's "normal" behavior, check the first non-obvious point here => https://github.com/Novik/ruTorrent/wiki/PluginThrottle#some-non-obvious-points

Check also #1965
