### ISSUE TITLE
how to debug RSS manager not fetching items

### ISSUE THREAD

**Issue by piramiday** [Novik/ruTorrent#2098]
I am relying on the **Rules manager** to transform an ill-prepared feed into a healthy RSS stream.
for the sake of clarity, let's imagine that the ill-prepared feed does not have a download link, and that the Rules manager uses some regex to assign its value correctly.

from what I can see the **RSS manager**, which uses filters to decide which items to download automatically, is acting on the _unmodified_ feeds.

is there a way to make sure that the **Rules** manager executes _before_ the **RSS** manager, so that the RSS manager sees feeds that have already been sanitized?

thanks.

**Comment by Novik** [comment]
Hook from the Rules manager called from the RSS plugin after the fetching data.
Yet once - it called *from*, not *before* or *after*.

How I may reproduce your situation?

**Comment by piramiday** [comment]
allow me to explain a bit further.
I have a feed from a private site that is not properly set up for direct download: the RSS feed items have links such as `details.php?item=1234` which bring me to the release page on the website, not the torrent file.
as a consequence, I cannot right-click an item from the feed view to fetch its torrent and download it straight away.
in order to accomplish direct download, I have used the Rules manager to replace the URL with `download.php?item=1234`, which works like a charm from the WebUI.

likewise, the filters I have set up in the RSS manager work fine.
e.g.: I can press the question mark button and ruTorrent will pop up a dialog telling me that those regex rules have found, say 10 matches, highlighting the items in the feed view, exactly as expected.

yet... nothing happens automatically.
I do not have any means to properly debug this, but I have verified that both the Rules and the Filters work properly.
I fear that the RSS manager is actually trying to match/download the unmodified feed which does not have proper download links.
if there are other important details that might prevent the RSS manager from fetching automatically new items, please let me know.

>  Yet once - it called _from_, not _before_ or _after_.

I'm not sure I understand what you wrote.
allow me to ask the question in a different way: are the rules for modifying feeds applied before the filters for autodownload get matched?

I am not sure what is causing this behaviour, but if this was indeed the issue you might just experiment with a feed with improperly formatted download links (not magnets) which necessarily need to be rules-regex-replaced to work.

thank you for your help!

**Comment by Novik** [comment]
> allow me to ask the question in a different way: are the rules for modifying feeds applied before the filters for autodownload get matched?

They should be applied as soon as the feed data is received. If this is not happens - then this is an error and I need a way to reproduce it.

> I am not sure what is causing this behaviour, but if this was indeed the issue you might just experiment with a feed with improperly formatted

I think we have something specific for your feed here. May you download it in browser, replace private data and attach result here? With configuration of your rules manager filter, of course.

**Comment by Novik** [comment]
@piramiday Now I have time for dig, but I can't see your gist more. What happened?

**Comment by piramiday** [comment]
sorry, the gist is gone, I can pop it up again as needed but...
just take any valid feed and _break it by replacing details URL and download URL_ -- you will end up with a feed that cannot be used to download items **unless** you use the "Rules manager" to switch back those two fields (`link` and `guid` if I'm not mistaken).

if you have time, could you please let me know how and where to debug this?
I don't understand whether ruTorrent is writing logs somewhere, e.g.:
```
- item with title "whatever.2020.720p.mkv" matches filter "720p"
- item with title "whatever.2020.720p.mkv" has download url "website.com/download.php?item=1234"
- item successfully added
```
since, if that was the case, I could easily see whether the "download url" is the correct one, post link-guid switch, or the original one from the feed.
thanks!

**Comment by Novik** [comment]
> just take any valid feed and break it by replacing details URL and download URL

For example, such feed: 
[142.xml.gz](https://github.com/Novik/ruTorrent/files/5239482/142.xml.gz)

In this feed all download links are incorrect, they contain incorrect sequence ```http://ru.rss-torrent.ru/upload/torrent/``` instead correct ```http://ru.rss-torrent.ru/upload/torrents/```.

And you may see this on the screenshot:

![2020-09-17_16h49_42](https://user-images.githubusercontent.com/1230409/93480167-d1e7bf00-f905-11ea-96b4-8fcf841ee64e.png)

I try to correct this:

![2020-09-17_16h51_13](https://user-images.githubusercontent.com/1230409/93480370-08bdd500-f906-11ea-8f1d-f58a40932a85.png)

I reload feed and now all correct:

![2020-09-17_16h53_03](https://user-images.githubusercontent.com/1230409/93480571-43c00880-f906-11ea-8066-9fa3422eaf3c.png)

As you may see now all loadded correctly. And you may see this without any logs.

**Comment by piramiday** [comment]
thanks for investigating!

of course, I have used right click > URL info to see what ruTorrent sees.
like you, I have an incorrect feed before the Rules manager is setup, and a correct feed after I have set it up.
I can right click and load an item through my webUI, thanks to the Rules manager correcting the download link.

if I then setup a filter for autodownload in the RSS manager, I can easily try it out through the `?` button and see that the right items are identified in the feed (first, I get a dialog saying "10 matches", then the 10 matches are highlighted in the feed) so that I'm positive my filter and regex work fine.
still, nothing happens automatically -- it might be that stuff works fine "on-the-fly" when I press the buttons, but not automatically when ruTorrent fetches new elements.

*this* is the part that I'd like some help in debugging. thanks!

**Comment by Novik** [comment]
> it might be that stuff works fine "on-the-fly" when I press the buttons, but not automatically when ruTorrent fetches new elements.

We have the same code in the both cases. No differences are exists.
And I may say more - I used this method (with a correction from filter) for auto-download torrents from the real trackers. And all worked correctly.

> if you have time, could you please let me know how and where to debug this?

You may set variable $rss_debug_enabled in the plugin's conf.php file to ```true```.
Location of the log file you may see at the main config.php. file in the $log_file variable.

**Comment by piramiday** [comment]
thank you for your help in debugging this.

I have set:
```bash
[user@host:~]$ grep debug /var/www/ruTorrent/plugins/rss/conf.php 

$rss_debug_enabled = true;		// true, false or 'dry-run'

[user@host:~]$ grep log /var/www/ruTorrent/conf/config.php 

	$log_file = '/tmp/rutorrent.log';		// path to log file (comment or leave blank to disable logging)

```
and restarted everything, yet I do not see log lines -- the log file does not even appear.
is this expected? am I missing something else?

**Comment by piramiday** [comment]
I also tried matching pretty much anything on a well-formed feed (thus no "rules manager" involved) -- nothing gets pulled anyways!
maybe this issue is not due to the interplay of RSS and Rules manager, but to the RSS engine itself failing.

any help is appreciated. thanks!
