### ISSUE TITLE
[ADD] oMg[WtF]trackr - Gazelle

### ISSUE THREAD

**Issue by xalphabetax** [Novik/ruTorrent#2099]
Torrents: 301,513
Files size: 580.39 TB
Completed: 1,041,586,908
Transferred: 2.219 EB
Peers: 9,560,207
Seeders: 5,042,435
Leechers: 4,517,772
Seeder/leecher ratio: 1.11

https://omg.wtftrackr.xyz/

For Invite: zer0bytes@tuta.io

**Comment by Novik** [comment]
Error 521 
Ray ID: 5f49bdf9d939c3f2 • 2020-11-19 11:55:25 UTC
Web server is down
