### ISSUE TITLE
[Ask for Help] Add custom tab to rutorrent

### ISSUE THREAD

**Issue by Gosokan** [Novik/ruTorrent#2101]
Hello,

Can someone here help me? I want to add a custom tab in rutorrent, where this custom tab can display pages from a php file (for example phpinfo).  Long time ago when rutorrent.org forum still around, some one did one. Thanks before.

**Comment by Novik** [comment]
[discord.tar.gz](https://github.com/Novik/ruTorrent/files/5239459/discord.tar.gz)

Edit init.js file and replace iframe ```src``` attribute to the url of your contents.
