### ISSUE TITLE
php API

### ISSUE THREAD

**Issue by vipera7** [Novik/ruTorrent#2102]
Hello,

I'm looking for a sdk or a php classto interact with ruTorrent. Do you have any reccomendation ? 
I want to connect to ruTorrent using ip address, port and credentials

Cheers

**Comment by Gosokan** [comment]
Although I am not very familiar with php, interacting with rutorrent can be done through httprpc plugins (../rutorrent/plugins/httprpc/action.php). For example to list all torrent, you can send post "mode=list" to action.php. The result will be displayed in json form.

**Comment by vipera7** [comment]
Well, I'm doing the request by myself. I didn't found any recent lib up to date. To list torrent name : 

```
function do_call($request) {

    $url = "https://mypassword:mypassword@example.com:32491/RPC2";
    $header[] = "Content-type: text/xml";
    $header[] = "Content-length: ".strlen($request);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $request);

    $data = curl_exec($ch);
    if (curl_errno($ch)) {
        print curl_error($ch);
    } else {
        curl_close($ch);
        return $data;
    }
}

$request = xmlrpc_encode_request("d.multicall2", array("", "main", "d.name="));
$response = do_call($request);
var_dump($response);
```
