### ISSUE TITLE
Trafic plugin not working

### ISSUE THREAD

**Issue by MrOnyx** [Novik/ruTorrent#2109]
Trafic-Plugin does not work last time has worked 09.2020 

.rtorrent.rc
execute = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php mronyx &}

I have this file on tmp dir **rutorrent-trafic-mronyx-31995f83330e064973.55720588**
but before was not in tmp folder

![Screenshot 2020-10-11 105729](https://user-images.githubusercontent.com/2565966/95674573-636ae980-0bb1-11eb-8603-5b6048acce6a.jpg)

**Comment by rozhuk-im** [comment]
In some cases this is issue with tmp dir.
In my case I set in config: ```$tempDirectory = '/tmp';``` and it broke trafic plugin.
```$tempDirectory = '/tmp/';``` proper value to work.

I made https://github.com/Novik/ruTorrent/pull/2880 to make sure trailing slash will exist and WebUI report error if something wrong with tmp dir.
