### ISSUE TITLE
Hash ID:

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Novik/ruTorrent#2119]
This maybe perhaps thought of as a feature request rather than an issue. But, most desktop torrent apps allow you to add a torrent via Hash ID. Why after all these years RuTorrent still requires a magnet? Sometimes there's no magnet, and it's easier to add the hash.. Please consider adding this feature. Or maybe some talented programmer can add a plugin?

Thanks..

**Comment by Novik** [comment]
![2020-11-13_12h27_54](https://user-images.githubusercontent.com/1230409/99056776-da7a1000-25ab-11eb-9b26-32b85134a46a.png)

Any questions?

**Comment by AnythingOldSkewl** [comment]
I do not have this plugin, that's why I posted this. I have version 0.9.6/0.13.6 I am under a Linux based seedbox. Is there a special repository I can get this from?

**Comment by Novik** [comment]
Yes, this is a special repository. And I may say more - you already created a ticket in this "special repository"...
https://github.com/Novik/ruTorrent/tree/master/plugins/bulk_magnet

**Comment by AnythingOldSkewl** [comment]
It accepts the hash, but it appears the plugin only works with DHT. is there a way I can automatically add default public announcements to them?

**Comment by Novik** [comment]
Please, try to read wiki.
https://github.com/Novik/ruTorrent/wiki/PluginRetrackers
