### ISSUE TITLE
[Feature Request] DiskSpace plugin for 2 or more mount points/hdds

### ISSUE THREAD

**Issue by espiman** [Novik/ruTorrent#2121]
Hi.

How could you do what appears here?

https://github.com/Novik/ruTorrent/issues/1146#issuecomment-161624498

Thank you

**Comment by Micdu70** [comment]
[diskspace2.zip](https://github.com/Novik/ruTorrent/files/5588754/diskspace2.zip)

Extract this zip and move "diskspace2" folder in the "plugins" directory of your ruTorrent installation.

Do not forget to edit **conf.php** file if needed (by default, it will display info of the " / " partition).

=)

**Comment by espiman** [comment]
> [diskspace2.zip](https://github.com/Novik/ruTorrent/files/5588754/diskspace2.zip)
> 
> Extract this zip and move "diskspace2" folder in the "plugins" directory of your ruTorrent installation.
> 
> Do not forget to edit **conf.php** file if needed (by default, it will display info of the " / " partition).
> 
> =)

Thank you very much!!!
