### ISSUE TITLE
[feature request] Sort by online seeders

### ISSUE THREAD

**Issue by weyrlingrider** [Novik/ruTorrent#2122]
Current: Sorting by Seeds only sorts by connected seeders. 

Proposed: Sorting by Seeds sorts by connected seeders, and all torrents with 0 seeders are secondarily sorted by non-connected online seeders.

Functionality added: Some private trackers provide bonus points (or other benefits) if you actively seeding a torrent that has only a  few seeders.  Being able to easily sort through a list of torrents that meet a threshold of online seeders would allow one to easily keep seeding low seed torrents for bonus points and offline others.

**Comment by Micdu70** [comment]
We don't know what version of ruTorrent you have but this sorting system has been added in ruTorrent v3.9. ;)
