### ISSUE TITLE
When sorting by date added, UI refresh changes order

### ISSUE THREAD

**Issue by stormj-UH** [Novik/ruTorrent#2128]
If you upload multiple torrents at once and then sort by "date added" every UI refresh may (or may not) resort the list, making it difficult to stick with the desired file.
I believe this is because the sorting algorithm doesn't really know what to do when there's a tie. 
I would suggest that every sort that could possible end in a tie should be sorted secondarily by hash, making it very close to impossible that there is ever a tie.
If you can point me to the place in the code, I'm happy to try my hand at it.

**Comment by Novik** [comment]
> I believe this is because the sorting algorithm doesn't really know what to do when there's a tie.

This is a normal behavior.
Use secondary sort - Shift+Click on the another column header.

**Comment by stormj-UH** [comment]
Yes, but this normal behavior makes it very difficult to use, especially on touch devices. It would be nice if the ties were automatically broken by some neutral element, again, like hash.

**Comment by Novik** [comment]
Object, that implement table view, hasn't any knowledge about hash or something like that. He know about first and secondary sort columns.
Og course you are free to write your own plugin for changing this behavior.
