### ISSUE TITLE
[Request] Webform login for rutorrent

### ISSUE THREAD

**Issue by Phukit** [Novik/ruTorrent#2132]
Any way we can get an integrated webform login for rutorrent?

This would make it alot better than the simple htaccess login

Thanks

**Comment by Gosokan** [comment]
I once tried to integrate rutorrent with a php login script, 
replace /rutorrent/index.html with /rutorrent/index.php and put session_start(); at the very top after the php opening tag
and also in /plugins/httprpc/action.php.

then add the some code to check whether the user is logged in or not after session_start(). It's working, but with a lot of warnings in the log file, is written every time httprpc is called (almost every second).

Without put session_start() in /plugins/httprpc/action.php, no warning message are written in log file, but this make rutorrent insecure due to anyone can send POST/GET data to /plugins/httprpc/action.php directly with or without login.

> This would make it alot better than the simple htaccess login

it's not htaccess login but basic http authentication, because not all web servers can recognize .htaccess configuration file.

**Comment by Solwayuk** [comment]
Please someone come up with a form based login solution! ak like sonarr/radarr has

**Comment by ninijule** [comment]
It's easy to add a login form,
I will show you my code, it's so disgusting but it works.
So you have to create a file with for exemple name " login.php" : 
then add this code in : 
"login.php"
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<form class="" action="index.php" method="post">
			<input type="text" name="login" value="">
			<input type="password" name="password" value="">
			<input type="submit" name="form_send" value="Se connecter !">
		</form>
	</body>
</html>

Put this file in the same directory of your rutorrent directory.
After, copy all data from the index.html and create another file named : "index.php" 

And the beginning of the file just add this : 

<?php

if(isset($_POST['form_send'])){

	if(isset($_POST['login']) && isset($_POST['password'])){

		$login = htmlspecialchars($_POST['login']);
		$password = htmlspecialchars($_POST['password']);

		if($login == "Admin" && $password == "YourPassword"){
			?>



			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			<html xmlns="http://www.w3.org/1999/xhtml">
				<head>
					<title></title>
					<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
					<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
					<meta http-equiv="cache-control" content="no-cache" />
					<link href="./images/favicon.ico" rel="SHORTCUT ICON" />
					<link rel="apple-touch-icon-precomposed" sizes="57x57" href="./images/apple-touch-icon-57x57.png" />
					<link rel="apple-touch-icon-precomposed" sizes="114x114" href="./images/apple-touch-icon-114x114.png" />
					<link rel="apple-touch-icon-precomposed" sizes="72x72" href="./images/apple-touch-icon-72x72.png" />
					<link rel="apple-touch-icon-precomposed" sizes="144x144" href="./images/apple-touch-icon-144x144.png" />
					<link rel="apple-touch-icon-precomposed" sizes="60x60" href="./images/apple-touch-icon-60x60.png" />
					<link rel="apple-touch-icon-precomposed" sizes="120x120" href="./images/apple-touch-icon-120x120.png" />
					<link rel="apple-touch-icon-precomposed" sizes="76x76" href="./images/apple-touch-icon-76x76.png" />
					<link rel="apple-touch-icon-precomposed" sizes="152x152" href="./images/apple-touch-icon-152x152.png" />
					<link rel="icon" type="image/png" href="./images/favicon-196x196.png" sizes="196x196" />
					<link rel="icon" type="image/png" href="./images/favicon-96x96.png" sizes="96x96" />
					<link rel="icon" type="image/png" href="./images/favicon-32x32.png" sizes="32x32" />
					<link rel="icon" type="image/png" href="./images/favicon-16x16.png" sizes="16x16" />
					<meta name="msapplication-TileColor" content="#FFFFFF" />
					<meta name="msapplication-TileImage" content="./images/mstile-144x144.png" />

					<link href="./css/stable.css" rel="stylesheet" type="text/css" />
...
<?php

		}

	}


}else{

echo "not connected";

}


?>



That's it if you have any question ask me !
