### ISSUE TITLE
Bad response from server: (500 [error,getplugins]) Internal Server Error

### ISSUE THREAD

**Issue by mgtra** [Novik/ruTorrent#2135]
Hi I recently updated to rutorrent 3.10-10 on my synology.

No when i go to rutorrent i get this in the log:

[08.01.2021 06:36:04] WebUI started.
[08.01.2021 06:36:04] Bad response from server: (500 [error,getplugins]) Internal Server Error

Any ideas ?

Was working fine until i updated

Thankyou

**Comment by Ghostfly** [comment]
Step 1 : Make sure that your rTorrent config for user is correct into : `.rtorrent.rc`

```
network.scgi.open_port = 127.0.0.1:500x
```
Replace 500x by 5001 for example, this should be unique.

Step 2 : Check your nginx (or apache config) 
```
    location = /<USERNAME> {
        include scgi_params;
        scgi_pass 127.0.0.1:500x;
        auth_basic "seedbox";
        auth_basic_user_file "/etc/nginx/passwd/rutorrent_passwd_<username>";
    }
```

Note the 500x (who should be replaced by 5001 too.)

If that could help, here is a really great tutorial that explain every steps (in French but google translate exists) : 
https://mondedie.fr/d/10831-tuto-installer-rutorrent-sur-debian-10-nginx-php-fpm

**Comment by rarealphacat** [comment]
I have the exact same problem here after update.

> Step 1 : Make sure that your rTorrent config for user is correct into : `.rtorrent.rc`
> 
> ```shell
> $ nano /home/<username>/.rtorrent.rc
> ```
> 
> Into find :
> 
> ```
> network.scgi.open_port = 127.0.0.1:500x
> ```
> 
> Replace 500x by 5001 for example, this should be unique.
> 
> Step 2 : Check your nginx (or apache config)
> 
> ```
>     location = /<USERNAME> {
>         include scgi_params;
>         scgi_pass 127.0.0.1:500x;
>         auth_basic "seedbox";
>         auth_basic_user_file "/etc/nginx/passwd/rutorrent_passwd_<username>";
>     }
> ```
> 
> Note the 500x (who should be replaced by 5001 too.)
> 
> If that could help, here is a really great tutorial that explain every steps (in French but google translate exists) :
> https://mondedie.fr/d/10831-tuto-installer-rutorrent-sur-debian-10-nginx-php-fpm

I have the exact same problem here after update and it double checked these steps but didn't help.

**Comment by aecro** [comment]
I found the issue. Check <rutorrent_root_dir>/plugins/extsearch/engines/ and check for JPopsuki.php and jpopsuki.php. Looks like with the latest update the file was changed to upper case, so when you upgrade from an older version and merge the directories, both exist which causes PHP to stop working. Delete the lower case file jpopsuki.php and it starts working again.
