### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by mibj** [Novik/ruTorrent#2137]
Suddenly it returns this error
I'm not able to create any torrent 
any help ?Thank

PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /var/www/rutorrent/php/util.php:58
Stack trace:
#0 /var/www/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
#1 /var/www/rutorrent/php/xmlrpc.php(3): require_once('...')
#2 /var/www/rutorrent/plugins/create/createtorrent.php(7): require_once('...')
#3 {main}
  thrown in /var/www/rutorrent/php/util.php on line 58`
`
![Screenshot from 2021-01-15 14-18-20](https://user-images.githubusercontent.com/31144126/104731838-95ee2a80-573c-11eb-8922-af81fdfeb680.png)

Webserver Nginx

**Comment by Novik** [comment]
Try to update ruTorrent.

**Comment by mibj** [comment]
I didn't get the cause but upgrading has solved Thanks
