### ISSUE TITLE
Autoload crashed and wont restart

### ISSUE THREAD

**Issue by a7mag3ddon** [Novik/ruTorrent#2147]
Hello,

I have a problem where the autowatch/ load folder was working fine, not sure why or what caused it but it stopped being checked, I removed the files from the folder, restarted ruTorrent but files in the watch folder are no longer being picked up.

I have also tried ticking / unticking enable watch folder as well.

Please can someone help me diagnose the problem? I could reinstall ruTorrent to fix it but would rather not.

Many thanks.

**Comment by n1ce-0ne** [comment]
can someone help

just out of interest you tested the files in question by adding them manually?

**Comment by a7mag3ddon** [comment]
yes i have added about 23 torrents in totally manually without problems.

**Comment by a7mag3ddon** [comment]
Looks like someone else had simmilar but never resovled too : https://github.com/Novik/ruTorrent/issues/2139

**Comment by a7mag3ddon** [comment]
So i guess theres no easy way to restart this feature without deleting everything and starting it again from scratch?
