### ISSUE TITLE
Plugin "EraseData" not delete downloaded data

### ISSUE THREAD

**Issue by gennady-ovcharov** [Novik/ruTorrent#2148]
rutorrent v3.10
plugin erasedata v3.10
rtorrent 0.9.8

When the menu item "Remove and ..." is selected, the plugin deletes the torrent file and session data, but does not delete the downloaded (partially downloaded) data.
Previously, on my server configuration, the plugin worked correctly (I can't say exactly on which version of the plugin)

**Comment by t0mab** [comment]
Maybe your are on php 7
I am facing the same issue in logs I found thaht 

`

PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/share/webapps/rutorrent/php/util.php:58
Stack trace:
#0 /usr/share/webapps/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
#1 /usr/share/webapps/rutorrent/plugins/erasedata/update.php(6): require_once('/usr/share/weba...')
#2 {main}
  thrown in /usr/share/webapps/rutorrent/php/util.php on line 58


`

**Comment by Novik** [comment]
Or maybe you use ascient version of ruTorrent, like @t0mab 
Because current version does not have something like this.

**Comment by t0mab** [comment]
@Novik thanks for the comment, it's allright now I had a tool old version on my archlinux box. Indeed juste need to update a little bit my dusty installation.

**Comment by gennady-ovcharov** [comment]
Sorry guys
I downloaded the latest version from this particular repository and it worked
