### ISSUE TITLE
Lable List too long

### ISSUE THREAD

**Issue by HeywoodFloyde** [Novik/ruTorrent#2149]
I use a lot of lables. When the list gets too long I cannot reach the create new lable at the bottom of the drop down.

Using rutorrent on latest Chrome browser

Is there a way to either:
1. Have a hotkey for "new lable"
2. Make the list scroll from the bottom up ( occasionally it will do this automatically but I am never able top make it do so on command)
3. Have the list auto scroll somehow.

any one of these will solve my issue

thanks

**Comment by Micdu70** [comment]
Screenshot of your issue because I don't understand how you can't create a new label...

**Comment by HeywoodFloyde** [comment]
When I select the torrents, right click on lables, the list is so long that the "create new" at the bottom would be about 2 inches below the bottom of my monitor.

I will try to make screenshot now

**Comment by HeywoodFloyde** [comment]
![lable](https://user-images.githubusercontent.com/80245693/110291527-03d70580-7fba-11eb-8330-e5e89cc81f93.jpg)

**Comment by HeywoodFloyde** [comment]
Does that explain it?

I had to blur out the personal info but I think the issue can be seen

**Comment by Micdu70** [comment]
"New Label..." and "Remove Label" are always on top.
This change has been made since ruTorrent v3.9...

**Comment by HeywoodFloyde** [comment]
My version is too old. 
Ive been afraid to update because its finally working smoothly ( all other things)

**Comment by Micdu70** [comment]
You installed ruTorrent from a zip or with a git command?
I can update ruTorrent for you if you want.
There is no shortcut for that.

**Comment by HeywoodFloyde** [comment]
I didn't install client. I just connect to server running rtorrent.

I will have to have the admin update rtorrent on server? Or can I update client in my browser?

**Comment by Micdu70** [comment]
ruTorrent is just a WebUI, not a torrent client. (rtorrent is the client torrent but it doesn't need to be updated)
If you don't have SSH access of this server then you should ask your seedbox provider to update the ruTorrent version. ;)

**Comment by HeywoodFloyde** [comment]
will it just be:
apt-get update

and then

update rutorrent

?

thanks for all the help

**Comment by Micdu70** [comment]
No...
"apt-get" is for updating the whole server and programs (packages).
To update the server, it's:

apt-get update && apt-get dist-upgrade

But ruTorrent is not a package. ^^

**Comment by HeywoodFloyde** [comment]
I tried this command:

sudo rutupgrade

but it said command not found

**Comment by Micdu70** [comment]
Do you installed rtorrent/ruTorrent from a script? If yes, please give script name or a link. ;)

**Comment by HeywoodFloyde** [comment]
I think it was done with something called Quickbox. I sort of 
 inherited it.

**Comment by Micdu70** [comment]
Hm... it would be easier if I have SSH access.... I will only update ruTorrent.
You can send all your SSH infos to my email (remove spaces) : Micdu70 @ gmx.fr
:)
