### ISSUE TITLE
Extsearch plugin for Immortalseed returns nothing

### ISSUE THREAD

**Issue by odd12348** [Novik/ruTorrent#2150]
Hello,

A couple weeks ago, Immortalseed engine stopped returning results, whatever search term I could enter.
I've compared ImmortalSeed.php with the search string from the official website. Immortalseed admins have changed the search URL. It's gone from "/browse.php?&keywords=" to "/browse.php?**do=search**&keywords="
I've tried to change the URL in Immortalseed.php but it keeps on returning empty results even after my changes.

I've changed this in line 76 : 
`$cli = $this->fetch( $url.'/browse.php?do=search&keywords='.$what.'&search_type=t_name'.$cat.'&sort=seeders&order=desc&page='.$pg`);

Before, it was like this : 
$cli = $this->fetch( $url.'/browse.php?include_dead_torrents=no&keywords='.$what.'&search_type=t_name'.$cat.'&sort=seeders&order=desc&page='.$pg );

Could someone help me fixing it ? It's very convenient for me, I use it a lot.

Thanks

**Comment by koblack** [comment]
Thanks for reporting, try this
```
			$res = preg_match_all('`<td align="center" style="width: 40px; height: 36px;" class="unsortable2">.*'.
				'<img src=".*" border="0" alt="(?P<cat>.*)" title=".*" width="40" height="36" loading="lazy" />.*'.
				'<div style="text-align:left; margin-top: 5px">(?P<name>.*)</div>.*'.
				'<div>.*</span>(?P<date>.*)</div>.*'.
				'<td .*>.*</td>.*'.
				'<td .*>.*</td>.*'.
				'<td .*>(?P<size>.*)</td>.*'.
				'<td .*>.*<a href=".*id=(?P<id>\d+)" title=".*">.*</td>.*'.
				'<td .*>(?P<seeds>.*)</td>.*'.
				'<td .*>(?P<leech>.*)</td>'.
				'`siU', $cli->results, $matches);
			if($res)
			{
				for($i=0; $i<$res; $i++)
				{
					$link = $url."/download.php?id=".$matches["id"][$i];
					if(!array_key_exists($link,$ret))
					{
						$item = $this->getNewEntry();
						$item["cat"] = self::removeTags($matches["cat"][$i]);
						$item["desc"] = $url."/details.php?id=".$matches["id"][$i];
						$item["name"] = self::removeTags($matches["name"][$i]);
						$item["size"] = self::formatSize(trim($matches["size"][$i]));
						$item["time"] = strtotime(self::removeTags(str_replace("-", "/",$matches["date"][$i])));
						$item["seeds"] = intval(self::removeTags($matches["seeds"][$i]));
						$item["peers"] = intval(self::removeTags($matches["leech"][$i]));
						$ret[$link] = $item;
						$added++;
						if($added>=$limit)
							return;
					}
				}
			}
			else
				break;
		}
	}
}
```

**Comment by odd12348** [comment]
Thanks a lot it works perfectly ! 
You're amazing !
