### ISSUE TITLE
Unpack Queue

### ISSUE THREAD

**Issue by richward1** [Novik/ruTorrent#2161]
Does the unpack plugin just start unrar jobs as soon as a torrent completes, possibly ending up with multiple unrar jobs running simultaneously?
I'm trying to find out if just queueing them to be processed one at a time, will help reduce the cpu load on my old server hardware.

**Comment by NullReferenceError** [comment]
I think it starts the jobs concurrently, and can cause some problems with unrar. I think some kind of queuing mechanism would solve an issue I'm currently investigating that relates to this. When multiple unpacks are triggered when several downloads finish around the same time, the second unpack (with unrar) never completely finishes until I manually unpack at a later time.
