### ISSUE TITLE
Bad response from server: (200 [parsererror,removewithdata]) ""

### ISSUE THREAD

**Issue by stickz** [Novik/ruTorrent#2163]
How do I fix or debug this issue? I added error logging to rTorrent, but nothing has appeared in my log file.

It happens when I try to delete 4000 torrents at once using "Remove And Delete Data". 

I'm running ruTorrent 3.10 with rTorrent 0.9.8 with libtorrent 0.13.8.

**Comment by mariotacke** [comment]
I have the same/similar problem. When I select "Remove And -> Delete Data", it issues the delete request and properly deletes the torrent and data, but the UI does not update automatically. Only after I refresh the UI, the torrent is gone. This started happening once I updated to the latest `rtorrent` 0.9.8 as well (running `rutorrent` off of master). Any ideas?

**Comment by Commissar0617** [comment]
i too have this issue. seems it cannot remove with data at all
