### ISSUE TITLE
Is it possible to set throttle on torrents after the ratio condition is met automatically?

### ISSUE THREAD

**Issue by lilws** [Novik/ruTorrent#2167]
I want the torrent will seed up to ratio 1.00 then it will automatically limit the upload speed to 256Kbps for example. Is it possible now? Because I seem can't find the options in rutorrent. 

For now ratio group plugins allow it to stop and clear ratio group, and the extratio is only set new torrent to ratio group and throttle based on label.

This is necessary to preserve bandwidth for new adding torrent.

**Comment by stickz** [comment]
Yes, you can create a 256kbps Channel. Then set channel to 256kbps after a max % of 100.
