### ISSUE TITLE
[Feature Request] Total size next to "All" filters

### ISSUE THREAD

**Issue by the-lazy-fox** [Novik/ruTorrent#2168]
Hi there,

I'm wondering how complicated it would be to add the total size next to the "torrents count" for the filter "All"  like it is to others?

![image](https://user-images.githubusercontent.com/35723598/115585062-99f58f80-a2cb-11eb-97f6-89c288e7c0ef.png)

Thanks a lot

**Comment by castillo92** [comment]
I would request it, please :D

**Comment by the-lazy-fox** [comment]
Yes, I just miss the "; xx Gb" for the "All" one like it is for others :)

**Comment by TrimmingFool** [comment]
<p float="left"><img src="https://user-images.githubusercontent.com/83290594/153514056-aeea0f11-615d-4fe1-ad4c-569c501cb161.png" alt="rutorrent_label_display" width=200/>
<img src="https://user-images.githubusercontent.com/83290594/153514080-e8bcf336-c151-4da1-b27e-d74c3e9fe76a.png" alt="rutorrent_label_display_dark" width=200/></p>

**Comment by the-lazy-fox** [comment]
This looks good

**Comment by castillo92** [comment]
> <img alt="rutorrent_label_display" width="200/" src="https://user-images.githubusercontent.com/83290594/153514056-aeea0f11-615d-4fe1-ad4c-569c501cb161.png"> <img alt="rutorrent_label_display_dark" width="200/" src="https://user-images.githubusercontent.com/83290594/153514080-e8bcf336-c151-4da1-b27e-d74c3e9fe76a.png">

Woow, it is great! How did you get it?

**Comment by TrimmingFool** [comment]
@castillo92 checkout the `master` branch

**Comment by castillo92** [comment]
> @castillo92 checkout the `master` branch or https://github.com/TrimmingFool/ruTorrent-MaterialDesign for the theme

Thanks you very much! Installed and working
