### ISSUE TITLE
The list of all trackers is not loaded correctly

### ISSUE THREAD

**Issue by the-lazy-fox** [Novik/ruTorrent#2171]
#### Steps to reproduce this issue

1. Open rutorrent with several torrents from several trackers
2. Check the filter section "trackers"

#### Expected behaviour

> All unique tracker should be in the list with a counter next to it + total volume summ

#### Actual behaviour

> The list is empty and trackers will show up ONLY when I manually click on one torrent --> tracker added in the list but counter = 1
> Then if I select another torrent it completed the filter section
> Etc.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.29.1, build c34c88b2 
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux docker-host 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

No issues in my client with 1000 and 2000 torrents.
I have this issue only for client with 4000+ torrents.

**Comment by Novik** [comment]
ruTorrent (and xml-rpc api in common) is not intended for support such large number of torrent. 
For 4000+ torrents you should use console or something like that.
Also you may check this - https://github.com/Novik/ruTorrent/pull/2170 PR.

**Comment by the-lazy-fox** [comment]
Thanks for your feedback.
Any plan to integrate this PR ?
Best

**Comment by Novik** [comment]
Sorry, but no (as minimum in the nearest future). Reasons:
1) Problem already solved on the client level
2) Too complex changes

**Comment by TrimmingFool** [comment]
> ruTorrent (and xml-rpc api in common) is not intended for support such large number of torrents.
> For 4000+ torrents you should use console or something like that.

ruTorrent is running fine now for me even with ~3700 torrents. Especially with 'httprpc' enabled I don't see a problem to continue using ruTorrent :+1:

**Comment by the-lazy-fox** [comment]
Hello @TrimmingFool 
Then it would be super great to integrate it somehow.
Otherwise, is there any other way?
Could we integrate the change in an "nightly" build to be able to test it at bigger stake?
Thanks

**Comment by TrimmingFool** [comment]
@the-lazy-fox Novik is the maintainer/owner. For now you could use my fork: [https://github.com/TrimmingFool/ruTorrent/commit/a42c506b221a1d458425960fe9b194864cf76462](https://github.com/TrimmingFool/ruTorrent/commit/a42c506b221a1d458425960fe9b194864cf76462)

**Comment by the-lazy-fox** [comment]
I'm running docker on crazy-max images so I will not be able to do so.

**Comment by the-lazy-fox** [comment]
up

**Comment by Novik** [comment]
> What do you mean by "Problem already solved on the client level" ?

Try to read PR description. "Size limitation is 16MiB on rtorrent master: rakshasa/rtorrent#905"

> Regarding the "Too complex changes", as the changes are already done and in PR. 

And, I think, a lot errors also was added by this PR. Who will support it? 

> We just need a part of the community to test them right?

You just need to update rtorrent from the master branch.
Or use corresponding fork of ruTorrent.

**Comment by TrimmingFool** [comment]
> Try to read PR description. "Size limitation is 16MiB on rtorrent master: rakshasa/rtorrent#905"

That's true if you assume that no one wants to use more than 8*3700=29600 torrents :smile: 
> And, I think, a lot errors also was added by this PR. Who will support it?

I totally get that merging seems risky. All I know is that it fixed the issue on my rutorrent setup.
However, I have no real interest in "long term support" if you meant that.

**Comment by 1265578519** [comment]
我有相同的问题，使用两种方法添加trackers都发生了错误，ruTorrent该如何正确使用trackers？在transmissiond上使用-t参数没有遇到问题
```
cmd=create&piece_size=16384&trackers=http://tracker1.itzmx.com:8080/announce&trackers=http://tracker2.itzmx.com:6961/announce&trackers=http://tracker3.itzmx.com:6961/announce&trackers=http://tracker4.itzmx.com:2710/announce&trackers=udp://tracker1.itzmx.com:8080/announce&trackers=udp://tracker2.itzmx.com:6961/announce&trackers=udp://tracker3.itzmx.com:6961/announce&trackers=udp://tracker4.itzmx.com:2710/announce
```
```
cmd=create&piece_size=16384&trackers=http://tracker1.itzmx.com:8080/announce
http://tracker2.itzmx.com:6961/announce
http://tracker3.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker2.itzmx.com:6961/announce
udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce
```
