### ISSUE TITLE
Unable to copy torrent files list ( need a file list in txt format with % downloaded )

### ISSUE THREAD

**Issue by laurus-lx** [Novik/ruTorrent#2173]
Greetings,
Wondering, if there is a way to get a file list from torrent along with % downloaded. E.g. - copy/paste from RuTorrent to a plain txt file. I can see a list of files in RuTorrent GUI, but I can't find a way to copy or save them. 

Help is much appreciated!

**Comment by jheyneman** [comment]
Hit F12 in Chrome and go to the Elements tab. 

![image](https://user-images.githubusercontent.com/21336105/118347014-e79d9a80-b50d-11eb-9e0d-e3dfd731c1fd.png)

Next, look for this table element, it'll have a bunch of table rows <tr> with all of the torrent information.

![image](https://user-images.githubusercontent.com/21336105/118347034-0f8cfe00-b50e-11eb-9b3f-5335452d15fb.png)

Right click on the <table> and hit Copy -> Copy Element. 

Paste it into something like https://www.convertcsv.com/html-table-to-csv.htm and convert it to Excel.  You can manipulate the data to fit your needs from there.

**Comment by Novik** [comment]
> Next, look for this table element, it'll have a bunch of table rows

1) By default ruTorrent do not store all torrents list into the table rows.
2) For retrieving torrent list direct call to the xmlrpc mount point should be used.
