### ISSUE TITLE
Check_port

### ISSUE THREAD

**Issue by Hipoglos** [Novik/ruTorrent#2174]
rutorrent 3.10 is showing "Port status is unknown" but the port is open. Anything I can try to fix it?

**Comment by Micdu70** [comment]
Edit `plugins/check_port/conf.php` file with your preferred text editor.

Do you see `$useWebsite = "yougetsignal";` or `$useWebsite = "portchecker";`?

If you see `$useWebsite = "portchecker";` => Try with `$useWebsite = "yougetsignal";`

;)

**Comment by perfect7gentleman** [comment]
My ruttorent is showing that "Port X is closed".
But checking port status on these both sites is showing that port is open.
