### ISSUE TITLE
 Is it possible to update mediainfo plugin v3.80 to display correct 4k file information? 

### ISSUE THREAD

**Issue by kdantas** [Novik/ruTorrent#2180]
Hi, I have the MediaInfo plugin v3.80 installed in my Seedbox. Would it be possible to update the plugin version or install new libs to display correct 4k file information? My OS is Ubuntu 16.04 LTS (GNU / Linux 4.9.160-armada375 armv7l)

MediaInfo 21.03 - Notebook with Windows 10

General
Unique ID : 254603260475835282936779418005277935827 (0xBF8ACDE87FBF7D5D6735B9CCB50288D3)
Complete name : Overlord.2018.2160p.UHD.BluRay.TrueHD7.1.Atmos.x265-HQMUX.mkv
Format : Matroska
Format version : Version 4
File size : 21.1 GiB
Duration : 1 h 49 min
Overall bit rate mode : Variable
Overall bit rate : 27.5 Mb/s
Movie name : Overlord.2018.UHD
Encoded date : UTC 2019-02-09 22:18:31
Writing application : mkvmerge v30.0.0 ('Interstellar') 64-bit
Writing library : libebml v1.3.6 + libmatroska v1.4.9

Video
ID : 1
Format : HEVC
Format/Info : High Efficiency Video Coding
Format profile : Main 10@L5.1@High
HDR format : SMPTE ST 2086, HDR10 compatible
Codec ID : V_MPEGH/ISO/HEVC
Duration : 1 h 49 min
Bit rate : 21.8 Mb/s
Width : 3 840 pixels
Height : 1 600 pixels
Display aspect ratio : 2.40:1
Frame rate mode : Constant
Frame rate : 23.976 (24000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 10 bits
Bits/(Pixel*Frame) : 0.148
Stream size : 16.7 GiB (79%)
Writing library : x265 2.9+2-7e978ed93d60:[Windows][GCC 8.2.0][64 bit] 10bit
Encoding settings : ...
Language : English
Default : Yes
Forced : No
Color range : Limited
Color primaries : BT.2020
Transfer characteristics : PQ
Matrix coefficients : BT.2020 non-constant
Mastering display color primaries : Display P3
Mastering display luminance : min: 0.0001 cd/m2, max: 1000 cd/m2

MediaInfo Plugin 3.80 [0.7.82-1] - Seedbox with Ubuntu 16.04 Server in Armhf-32 Architecture

    This version does not show all 4K file information

    HDR format : ?
    Transfer characteristics : ?
    Mastering display color primaries : ?
    Mastering display luminance : ?

General
Unique ID : 254603260475835282936779418005277935827 (0xBF8ACDE87FBF7D5D6735B9CCB50288D3)
Complete name : Overlord.2018.2160p.UHD.BluRay.TrueHD7.1.Atmos.x265-HQMUX.mkv
Format : Matroska
Format version : Version 4 / Version 2
File size : 21.1 GiB
Duration : 1h 49mn
Overall bit rate mode : Variable
Overall bit rate : 27.5 Mbps
Movie name : Overlord.2018.UHD
Encoded date : UTC 2019-02-09 22:18:31
Writing application : mkvmerge v30.0.0 ('Interstellar') 64-bit
Writing library : libebml v1.3.6 + libmatroska v1.4.9

Video
ID : 1
Format : HEVC
Format/Info : High Efficiency Video Coding
Format profile : Main 10@L5.1@High
Codec ID : V_MPEGH/ISO/HEVC
Duration : 1h 49mn
Bit rate : 21.8 Mbps
Width : 3 840 pixels
Height : 1 600 pixels
Display aspect ratio : 2.40:1
Frame rate mode : Constant
Frame rate : 23.976 (24000/1001) fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 10 bits
Bits/(Pixel*Frame) : 0.148
Stream size : 16.7 GiB (79%)
Writing library : x265 2.9+2-7e978ed93d60:[Windows][GCC 8.2.0][64 bit] 10bit
Encoding settings : ...
Language : English
Default : Yes
Forced : No
Color range : Limited
Color primaries : BT.2020
Matrix coefficients : BT.2020 non-constant

**Comment by Novik** [comment]
Plugin code has'nt any relation to this. It simply pass output of mediainfo binary to the WebUI.
You should update mediainfo binary on your seedbox and/or set correct path to it in the plugin's conf.php file.

**Comment by kdantas** [comment]
Thanks Novik for the quick response. Due to my little knowledge of Linux, would you know if Ubuntu 16.04 LTS supports the update of mediainfo binary? Currently my version is 0.7.82-1.  Anyway, thanks for your attention.

**Comment by Novik** [comment]
You must have root access (or sudo) to the your seedbox.
First of all, try to update package from the existing repo - 
```
sudo apt-get update && sudo apt-get --only-upgrade install mediainfo
```
If you already have last possible version, then try to install package from here - 
https://mediaarea.net/en/MediaInfo/Download/Ubuntu
Or you may compile it from source - 
https://github.com/MediaArea/MediaInfo

> Due to my little knowledge of Linux

Sorry, but with such restiction you have only one way.
Try to find someone locally, who have this knowledge. You should trust to this person.

**Comment by kdantas** [comment]
Thanks again for you help. I will follow your advice. Best Regards.
