### ISSUE TITLE
Torrents won't delete on ruTorrent 3.9

### ISSUE THREAD

**Issue by holygamer** [Novik/ruTorrent#2183]
I have ruTorrent 3.9 installed on my Feral Hosting seedbox which comes as an installation option. I've been using ruTorrent for years and I noticed that when trying to delete a torrent that has hundreds of files in it that ruTorrent won't delete it which is fair enough I suppose.

However today I tried to delete a single torrent that only has one file inside it and the torrent would delete but the file on my FTP did NOT delete. I tried deleting several torrents like that and they all wouldn't delete.

Seems to be a bug. Deluge doesn't have that problem. Can you fix it please? Thanks

**Comment by Micdu70** [comment]
You should contact your seedbox provider (Feral Hosting) about your issue. We can do nothing for you here. ;)

**Comment by holygamer** [comment]
I already did and they told me it was a bug in ruTorrent and nothing to do with them.
