### ISSUE TITLE
weird only text output on site.

### ISSUE THREAD

**Issue by anon-127** [Novik/ruTorrent#2188]
Preview: Browser Firefox but also test with brave,

![2021-06-28-180912_1885x870_scrot](https://user-images.githubusercontent.com/83167209/123637947-385a2000-d83c-11eb-8634-cc9ca64053be.png)

**Comment by anon-127** [comment]
Found this.
dra
![2021-06-28-181758_885x894_scrot](https://user-images.githubusercontent.com/83167209/123638914-52e0c900-d83d-11eb-9503-bcf9cfe32732.png)

**Comment by Gosokan** [comment]
check your webserver mime types
