### ISSUE TITLE
Limited to adding only 20 torrents at time 

### ISSUE THREAD

**Issue by Feejus** [Novik/ruTorrent#2189]
I have noticed the ruTorrent can't add more then 20 torrent at a time. It seems to me there is upper limit. So if i add 50 torrents at a time it only add the first 20.

**Comment by n1ce-0ne** [comment]
me too, if i add 50 about 30 to 35 are added, following.

**Comment by Novik** [comment]
https://www.php.net/manual/ru/ini.core.php#ini.max-file-uploads

**Comment by Feejus** [comment]
Hi Novik, I understand you kindly provided a link and closed the case! Can you please explain why? I can't see a solution on the website, in fact most of the website is in what i suspect is russian?

**Comment by Novik** [comment]
20 files per upload is a default PHP limitation. For change this behavior you should configure PHP on your server by proper way (see link above).

**Comment by Feejus** [comment]
Novik, thank you. Appriciate the explanation. This sits in seedbox so i can only assume i won't be able to access it to change this.

Thank you
