### ISSUE TITLE
`XML Parsing Error: unclosed token` when opening ruTorrent; ruTorrent completely broken.

### ISSUE THREAD

**Issue by solonovamax** [Novik/ruTorrent#2191]
So first, imma start this off saying I have literally zero clue how any of  this shit works and it's WAY out of my domain, so feel free to yell at me if I'm just doing smth stupid.
Sick, with that out of the way, here's the bug:

ruTorrent just doesn't work what-so-ever.

When opening it up, it throws
```
XML Parsing Error: unclosed token
Location: http://localhost/rutorrent/php/getplugins.php
Line Number 1, Column 1:
```
in the browser console, and
```
[16.07.2021 17:54:02] Bad response from server: (200 [parsererror,getplugins]) SyntaxError: expected expression, got '<'
```
in the log.

It just looks like this:
![image](|width=100)

<a href="url"><img src="https://user-images.githubusercontent.com/46940694/126012732-af6645f1-cf2e-4540-8d72-8dd3b02fbf11.png" width="800" ></a>

Not sure if you'd want it or not, so I've attached the file it's trying to get, [getplugins.txt](https://github.com/Novik/ruTorrent/files/6833554/getplugins.txt), here. (It has `.txt` because github moment.)
I haven't ever personally modified it, so I'm not sure why it'd be broken though.

I have the following versions of things installed:

|Program|Version|
|-|-|
|[libtorrent-ps-ch](https://aur.archlinux.org/packages/libtorrent-ps-ch/)|1.8.3-1
|[rtorrent-ps-ch](https://aur.archlinux.org/packages/rtorrent-ps-ch/)|1.8.3-2
|[rutorrent](https://aur.archlinux.org/packages/rutorrent-git/)|r2795.9eff223c-1

I cannot find any logs anywhere that, other than the 2 above.
I'm running it through an apache http webserver, and it has no error logs:
```bash
$ systemctl status httpd
● httpd.service - Apache Web Server
     Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-07-16 17:46:18 EDT; 19min ago
   Main PID: 814992 (httpd)
      Tasks: 109 (limit: 19077)
     Memory: 12.7M
        CPU: 94ms
     CGroup: /system.slice/httpd.service
             ├─814992 /usr/bin/httpd -k start -DFOREGROUND
             ├─815004 /usr/bin/httpd -k start -DFOREGROUND
             ├─815005 /usr/bin/httpd -k start -DFOREGROUND
             ├─815007 /usr/bin/httpd -k start -DFOREGROUND
             └─820644 /usr/bin/httpd -k start -DFOREGROUND

Jul 16 17:46:18 solo-main systemd[1]: Started Apache Web Server.
```
nor does `php-fpm`:
```bash
$ systemctl status php-fpm
● php-fpm.service - The PHP FastCGI Process Manager
     Loaded: loaded (/usr/lib/systemd/system/php-fpm.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-07-16 17:46:14 EDT; 20min ago
   Main PID: 814901 (php-fpm)
     Status: "Processes active: 0, idle: 2, Requests: 0, slow: 0, Traffic: 0req/sec"
      Tasks: 3 (limit: 19077)
     Memory: 7.4M
        CPU: 77ms
     CGroup: /system.slice/php-fpm.service
             ├─814901 "php-fpm: master process (/etc/php/php-fpm.conf)" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─814904 "php-fpm: pool www" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             └─814905 "php-fpm: pool www" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">

Jul 16 17:46:14 solo-main systemd[1]: Starting The PHP FastCGI Process Manager...
Jul 16 17:46:14 solo-main php-fpm[814901]: [NOTICE] fpm is running, pid 814901
Jul 16 17:46:14 solo-main php-fpm[814901]: [NOTICE] ready to handle connections
Jul 16 17:46:14 solo-main php-fpm[814901]: [NOTICE] systemd monitor interval set to 10000ms
Jul 16 17:46:14 solo-main systemd[1]: Started The PHP FastCGI Process Manager.
```

I'm probably providing _way_ too much information for things that don't matter, but not enough for the things that do lmfao. But, as I said, this is way out of my domain. So I have no clue what to look for.

**Comment by n1ce-0ne** [comment]
yea the older versions seem bulletproof, might be better trying one :)

**Comment by solonovamax** [comment]
Though, I'm installing it from the AUR package which uses the latest version.

**Comment by solonovamax** [comment]
To be honest, I have no clue what it was.
Remember when I said I was running it via an appache http webserver, well I was wrong. For some reason I have
- nginx
- httpd
- lighttpd
all installed on my computer. I was using `lighttpd`.

I also downgraded to php 7, so it might've been a combination of the two?? who knows.
