### ISSUE TITLE
AutoMove corrupted save path

### ISSUE THREAD

**Issue by GiovanniK** [Novik/ruTorrent#2201]
Hello,

I have been running AutoMove for a long time now and I've noticed that it sometimes corrupts the save path.
Today I moved to a new server and the exact same issue appeared again, which made me think it's caused by AutoMove .

I have AutoMove set to move to a different folder and append the torrent label, this works well for 95% of the time. 
However some torrents get a corrupted path, it appends the device path to the save path. This obviously does not work, and the torrent stops.

This is what's expected:
/home3/{user}/downloads/completed/{LABEL}/{TORRENT}

This is what sometimes happens:
/dev/sdb5       3809453244 40751404 3768685456       2% /home3
/home3/{user}/downloads/completed/radarr/{TORRENT}

Here's a screenshot of ruTorrent and the settings:
Save path: https://gyazo.com/d89d1f24ba436b402d61c8f94aae92a8
Settings: https://gyazo.com/5bbd26ca7358e0cde28333bf141bf3f9

As you can see it somehow appends that in front of it. But this is not always the case...
If I manually fix the path again that same torrent will work properly.

Does anyone have any idea what may cause this?

**Comment by olliejm** [comment]
Guessing this isn't gonna get more attention 2y later, but i have the exact same issue and have for a while. It seems if the file is particularly large or if there's multiple torrents currently downloading, then it is more likely to occur

**Comment by GiovanniK** [comment]
> Guessing this isn't gonna get more attention 2y later, but i have the exact same issue and have for a while. It seems if the file is particularly large or if there's multiple torrents currently downloading, then it is more likely to occur

Probably not indeed. It surprised me that the issue is 2 years old, I'm still having problems.

I think it's exactly what you say, when the files are large or there are multiple torrents downloading/moving. It seems the harddrive, software or cpu can't keep up and it bugs out.
