### ISSUE TITLE
RSS not downloading

### ISSUE THREAD

**Issue by aldojack** [Novik/ruTorrent#2202]
Hi, 

Issue I'm having is downloading torrents from private tracker using RSS, when I add the RSS feed it will show the torrents but if I try double click a link it will take me to a error 404 page

Is there a fault or something I need to fix on my side? 

Thanks

**Comment by varoOP** [comment]
In my case, the description URL and the download URL are switched. ruTorrent tries to download images instead of the actual torrent. Any idea how I could rectify this?

**Comment by Novik** [comment]
Please, provide contents of your RSS feed. Or you may try to experiment [with this plugin](https://github.com/Novik/ruTorrent/wiki/PluginRSSURLRewrite) by self.
