### ISSUE TITLE
ruTorrent is stingy until a torrent reaches 100% completion.

### ISSUE THREAD

**Issue by a-raccoon** [Novik/ruTorrent#2211]
I'm not sure if this can be addressed, but it's a pretty annoying behavior that I've observed.

If you add a rather large torrent to your remote ruTorrent server, one that you expect to take several days to complete, it will chug away downloading it as fast as it can.  However, if you try to download the same torrent at the same time on your home computer, ruTorrent will only let you download at 2x the speed that you upload to it.  Very slow if your home has low upload speed.  It's not until ruTorrent reaches 100% completion that it opens up and lets you leech from it at full speed.

Is there any way to disable **tit for tat** transfer throttling to peers while the torrent is <100%?

**Comment by lps-rocks** [comment]
This sounds like you're being choked by peers in the swarm, throttled, or some other issue that's on your side. rTorrent/ruTorrent do not have any hard-coded throughput restrictions.

Again, ruTorrent just fetches data from rTorrent.

You should validate your issue with a bare rTorrent installation before attributing this to ruTorrent.
