### ISSUE TITLE
Some Private Trackers incorrectly flagged as Public

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2216]
Hi,

I'm having an issue with some private trackers getting incorrectly flagged a public within ruTorrent so are unfortunately getting limited by my ratio/throttle settings.  Is there a way to whitelist the trackers or is there a fix to apply?

For example..
https://i.imgur.com/Inr6K7Z.png

A solution/workaround would be much appreciated,

**Comment by Micdu70** [comment]
Hello,

What version of ruTorrent are you using? Private tracker detection has been improved since ruTorrent v3.8.

Please paste full tracker URLs (do not forget to replace the passkey value with "xxxxxxxxxx").

**Comment by ADz-83** [comment]
> 
> 
> Hello,
> 
> What version of ruTorrent are you using? Private tracker detection has been improved since ruTorrent v3.8 (4 years ago already!).
> 
> Please paste full trackers URLs (do not forget to replace the passkey value with "xxxxxxxxxx").

My apologies.  I'm using ruTorrent v3.10
http://www.theempire.click:3110/xxxxxxx/xxxxxxxx

**Comment by Micdu70** [comment]
Is there another private tracker with this issue or is this the only weird one? ^^

How many torrents did you download from TheEmpire? Can you confirm that the first letter after the last slash "/" is always the "a" letter?

**Comment by ADz-83** [comment]
Yes there have been others but can't recall which off top of head. 

I'm not sure if its same for everybody after the "/" if that is what you mean?  Mine does start with an "a" though.

**Comment by Micdu70** [comment]
I don't know how you installed ruTorrent (by using git or by downloading and extracting a zip file) but you can apply these modifications (= replace "/an" with "/a" in **js/webui.js** and **plugins/extratio/rules.php** files): https://github.com/Micdu70/ruTorrent/commit/59c978185442b4067da55bf1a7667544ea79f75d

**Comment by ADz-83** [comment]
> 
> 
> I don't know how you installed ruTorrent (by using git or by downloading and extracting a zip file) but you can apply these modifications (= replace "/an" with "/a" in **js/webui.js** and **plugins/extratio/rules.php** files): [Micdu70@59c9781](https://github.com/Micdu70/ruTorrent/commit/59c978185442b4067da55bf1a7667544ea79f75d)

I used the Quickbox Pro script.
https://quickbox.io

**Comment by ADz-83** [comment]
I ran update and they are now showing a Private in trackers tab but for some reason they are still being stopped by the plugin as if thy are still being detected as public in back?

**Comment by Micdu70** [comment]
Try to delete and re-add these torrents in ruTorrent.

**Comment by ADz-83** [comment]
> 
> 
> Try to delete and re-add these torrents in ruTorrent.

Thanks I think that's done it  :)

Thanks for the help.  Much appreciated.
