### ISSUE TITLE
Problem with js in ruTorrent

### ISSUE THREAD

**Issue by soondermix** [Novik/ruTorrent#2221]
when I upload a .torrent file, ruTorrent print this message : [13.11.2021 07:17:32] JS error: [https://rutorrent.domainname.extension/js/stable.js : 1743] TypeError: this.rowdata[row] is undefined

**Comment by stickz** [comment]
hi @soondermix I would like to look into this problem for you, but I need your help to make it happen again.

Could you upgrade your version of ruTorrent to this? Then create a new issue with the "Javascript errors" template?
https://github.com/Novik/ruTorrent/archive/846a46e1a297557ac401f1b519cae828fd9b825d.zip

When upgrading it's required to copy and replace everything expect for the share folder. I need the stack trace from your web browser to be able to pinpoint where this error is coming from. There are instructions on the issue template for this.
