### ISSUE TITLE
status on compatibility with php8.0/php8.1

### ISSUE THREAD

**Issue by jamiew0w** [Novik/ruTorrent#2226]
hi all,

i've had a quick peek through issues trying to see if PHP8.0 is currently compatible or if there are plans to support it?

could anyone shed some light on this please?

Thanks!

**Comment by stickz** [comment]
hi @jamiew0w would you be willing to help test php8 on ruTorrent? 

I'm almost finished JQuery 3.6 support. I could give this a shot afterwards.

**Comment by jamiew0w** [comment]
@stickz I'd be happy to, can spin up a VM and test whenever. I (unknowingly) updated a seperate machine to PHP8 almost a week ago and it's running perfectly fine - I didn't even notice.

php version `PHP 8.0.14 (cli) (built: Dec 20 2021 21:22:57) ( NTS )`

**Comment by stickz** [comment]
Awesome, thanks for the heads up. I'll spin up a cloud server tomorrow. If this works, I'll put it on one of my seed boxes.

If you have already upgraded to ruTorrent master, it's probably a good idea. The dxSTables were just optimized two days ago and JQuery 3.6 support is probably coming soon. These changes are far more significant than PHP 8.

**Comment by jamiew0w** [comment]
Sounds great, I'll look into it in a few days!

I'll leave this issue open for now I guess, just in case you (or I or anyone else) spots anything awry on PHP8, can close it in a few days/week or whatever.

**Comment by skibbipl** [comment]
Count me in for testing php8.1. So far except autodl plugin everything works fine.

**Comment by HuwSy** [comment]
Given 7.x reaches EOL in Nov I think I’ll be putting this up to test shortly too.
