### ISSUE TITLE
Any plans on releasing a 3.11 version?

### ISSUE THREAD

**Issue by th0ma7** [Novik/ruTorrent#2232]
As I was planning to update our SynoCommunity package I was wondering, any plans on tagging a 3.11 version? 
Happy Holiday, cheers!

**Comment by stickz** [comment]
jQuery 3.6 support is probably coming soon. Then I plan on testing PHP 8.0 on ruTorrent and maybe fixing a few plugin bugs. This will be a very significant release when tagged. It's important not to rush it though, to ensure there's no regressions.

Have you thought about adding php-fpm and varnish-cache to SynoCommunity @th0ma7 ? If I'm reading correctly, this is a framework for a NAS environment. It would benefit from having this acceleration and reduced resource consumption.

**Comment by th0ma7** [comment]
@stickz thnx for the suggestions. Something to look for indeed.
As for a newer release I'll be following-up for the next version and migrate existing to newer Synology DSM version as-is.
(as I naively thought getting current snapshot marked as 3.11 was trivial :smile:)
cheers!

**Comment by castillo92** [comment]
@stickz To get the latest ruTorrent available, is it only neccessary download this Git as it is in our webserver folder?

**Comment by stickz** [comment]
> @stickz To get the latest ruTorrent available, is it only neccessary download this Git as it is in our webserver folder?
Yes that is correct.

**Comment by stickz** [comment]
@Novik Could you tag a 3.11-beta (pre-release)? There's been a lot of significant changes. I'm done with the major changes now.

The master branch currently has a lot of breakage, which third party developers need to resolve. We need to indicate an API bump through a patch release, so they can address these issues. It's too difficult to work off the master branch.

This will also encourage users and seed box providers to start testing these changes and reporting bugs.

**Comment by Novik** [comment]
> Could you tag a 3.11-beta (pre-release)? There's been a lot of significant changes.

Maybe 4.0-beta in this case?

**Comment by stickz** [comment]
@th0ma7 A new beta version is most likely coming soon. I would recommend creating a new package for it. It will not be compatible with some third party plugins yet and there could be a few bugs. Select users may still want to use 3.10.

We did thoroughly test and eliminate most of the regressions though. This is a relatively polished release which is ready for use.

> > Could you tag a 3.11-beta (pre-release)? There's been a lot of significant changes.
> 
> Maybe 4.0-beta in this case?

Yeah, I agree. There has been some major code restructuring, optimizations and bug fixes.

**Comment by Novik** [comment]
Added.

**Comment by th0ma7** [comment]
Awesome!  Just saw the 4.0-beta tag :rocket: 
I'm glad that thread triggered this, and now one more reason to rework SynoCommunity package :)

**Comment by th0ma7** [comment]
@Novik is 4.0-beta still using v0.9.8 of https://github.com/rakshasa/rtorrent ?

**Comment by stickz** [comment]
@th0ma7 We recommend using v0.9.8 to access all the features of 4.0-beta. It's not required though. There is a history of backwards capability with the ruTorrent web client. Look out for a stable release of version 4.0 is the new year!
