### ISSUE TITLE
[myanonamouse.net] Incorrectly being detected a Public Tracker

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2234]
Hi,  

Could you please add an exception or fix for this tracker as it's incorrectly being flagged as public and getting restricted by public ratio rules etc.

rutorrent v3.10

https://t.myanonamouse.net/tracker.php/XXXXXXXXXXXXX/announce

**Comment by Micdu70** [comment]
Hello,

Your given URL is already matching one of the regex for private trackers, in ruTorrent. ;)

Please send an uncensored URL of this tracker via e-mail => `Micdu70 [at] gmx [dot] fr`
