### ISSUE TITLE
Diskspace plugin two separate independent hard drives

### ISSUE THREAD

**Issue by rcasunshare** [Novik/ruTorrent#2235]
If I have two separate independent hard drives, how do I make the Diskspace plugin show the total sum of both?

**Comment by stickz** [comment]
You have to edit `plugins/diskspace/action.php`. There is an if statement that calculates the total and free disk space:
```
if( is_dir($partitionDirectory) )
{
	$ret["total"] = disk_total_space($partitionDirectory);
	$ret["free"] = disk_free_space($partitionDirectory);
}
```
It's possible to add the total disk space of your two hard drives together, as long as you know the mount points. Example:
```
$ret["total"] = disk_total_space("/home/disk1/downloads") + disk_total_space("/home/disk2/downloads");
$ret["free"] = disk_free_space("/home/disk1/downloads") + disk_total_space("/home/disk2/downloads") ;
```
However, I would highly recommend using a software raid for distributing torrents. Unless of course you have a SSD and HDD. It's much faster than separate hard drives. A raid 1 offers redundancy and 2x the read speed but it wastes half the disk space. A raid 0 offers 2x read & write speed and wastes no disk space but if one of the hard drives fails, you'll lose all your data.
