### ISSUE TITLE
Can't save to..

### ISSUE THREAD

**Issue by bernid** [Novik/ruTorrent#2248]
Hi, 
I've just installed the ruTorrent version 3.10 from 30 Dec 2021. 
Unfortunately have errors when I want to 'save to..' files to the  different place.
`[03.01.2022 06:11:36] JS error: [http://10.10.10.1/rutorrent/ : 1936] Uncaught TypeError: this.torrents[id].done.trim is not a function`

I use Ubuntu 10.21
kernel: 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64
PHP: 8.0.8
Apache:  2.4.48

BTW. Thanks for the cool software! I have been a user for several years

**Comment by Micdu70** [comment]
It's now fixed. ;)
Update your rutorrent installation (via the `git pull` command) and clear the cache of your web browser. :)

**Comment by bernid** [comment]
Thanks guys!!!

**Comment by stickz** [comment]
Thanks for helping test the master branch. If you find anymore bugs please let us know. There are more really big updates coming in the near future hopefully. The next 3.11 release is going to have some significant improvements.
