### ISSUE TITLE
Error 500 with master branch

### ISSUE THREAD

**Issue by Whisper40** [Novik/ruTorrent#2255]
![image](https://user-images.githubusercontent.com/30440458/148829727-b1d95b71-6157-485e-9fd4-28b947e91070.png)
Hello, our docker was working properly 9 days ago, today, the image is built, no errors in logs but rutorrent won't start

**Comment by barnumbirr** [comment]
Check your Nginx logs. Had the same thing happen to me yesterday, was due to the `geoip2` plugin.
This has now been fixed upstream.

**Comment by Whisper40** [comment]
This bug is fixed (but no errors in my traefik logs about that)
