### ISSUE TITLE
TypeError: jQuery.event.props is undefined

### ISSUE THREAD

**Issue by barnumbirr** [Novik/ruTorrent#2257]
Hello,

master@e8f0fefc0005ef86687c6fd5bcb3b6b62e5dff56 throws the following error:

```
[11.01.2022 13:00:19] JS error: [https://example.com/plugins/filedrop//jquery.filedrop.js : 28] TypeError: jQuery.event.props is undefined
[11.01.2022 13:00:19] JS error: [https://example.com/ line 2 > injectedScript : 2467] TypeError: $(...).filedrop is not a function
```

ruTorrent still functions as expected, at least from what I've experienced.

Cheers.

**Comment by stickz** [comment]
You can't pick and choose which files you upgrade when using the master branch. Please make sure your whole js folder copies and replaces successfully. This newer version of the filedrop plugin also requires the newer version of jQuery.

**Comment by barnumbirr** [comment]
`js/jquery.js` was upgraded to the latest changes (from commit 603f0b3f6ea28d40c36e517eed74e2740d21e531) when pulling from master. Issue appears despite having the latest changes.

**Comment by Arakmar** [comment]
I had a very similar problem with filedrop in recent master due to caching problems. Try to use private browsing mode first to check if the problem is gone. If so, clear your cache.

**Comment by stickz** [comment]
Yes please try to clear your cache. If the problem persists afterwards let us know. This error is likely from the wrong jQuery version.

**Comment by barnumbirr** [comment]
Clearing cache does indeed fix the issue. Probably the only fix I didn't think of 🤦.
