### ISSUE TITLE
FileManager is broken with master branch

### ISSUE THREAD

**Issue by Whisper40** [Novik/ruTorrent#2258]
Error : Could not retrieve directory -> Échec de la récupération du contenu du dossier. - /

**Comment by stickz** [comment]
I'm going to close this issue. It's not related to the ruTorrent project and the problem with the third party plugin has been resolved. Thanks @Micdu70 for helping third party authors update their plugins. 

Please feel free to bring other third-party plugins that need updated to our attention by creating a discussion. 
https://github.com/Novik/ruTorrent/discussions
