### ISSUE TITLE
Throttle plugin failure

### ISSUE THREAD

**Issue by tomerblecher** [Novik/ruTorrent#2259]
Hey there,

I'm trying to install the ExtRatio plugin which requires the 'Throttle' plugin. When installing 'Throttle', I'm getting errors on my nginx server and the GUI fails.

PHP message: PHP Fatal error:  Uncaught Error: Class 'FileUtil' not found in /srv/rutorrent/plugins/throttle/throttle.php:4
Stack trace:
#0 /srv/rutorrent/plugins/throttle/init.php(2): require_once()
#1 /srv/rutorrent/php/getplugins.php(495): require_once('/srv/rutorrent/...')
#2 {main}

Are there any more pre-requires that I'm missing or is it a bug?

Env:
php7.2-fpm
rTorrent 0.9.6/0.13.6
ruTorrent 3.10

**Comment by Micdu70** [comment]
Hello,

If you don't want to update your whole ruTorrent installation to the latest Development version (=git "master" version) then you have to download the 'Throttle' plugin included in ruTorrent Stable v3.10 (zip file) => https://github.com/Novik/ruTorrent/releases

👋
