### ISSUE TITLE
Throttle Plugin causes ...(500 [error,getplugins]) Internal Server Error

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2267]
ruTorrent v3.10

When I enable the Throttle plugin it causes rutorrent to crash with following error..
Bad response from server: (500 [error,getplugins]) Internal Server Error

**Comment by stickz** [comment]
The master branch is not compatible with ruTorrent v3.10. A new release is in the process of being tagged currently. If you want to use anything from the master branch, it's required to upgrade your entire ruTorrent installation. There is API breakage.

**Comment by stickz** [comment]
hi @ADz-83 ruTorrent version 4.00 beta is now available for download, if you would like to give that a try!

**Comment by ADz-83** [comment]
> The master branch is not compatible with ruTorrent v3.10. A new release is in the process of being tagged currently. If you want to use anything from the master branch, it's required to upgrade your entire ruTorrent installation. There is API breakage.

When did this change.  I've installed various times over last few month and had no issues with v3.10 and the throttle plugin.   It's only started very recently for me?

**Comment by stickz** [comment]
#2236 and #2247 broke combability with v3.10. 

You need to use the [v4.0-beta.1](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1) if you like to pull things from the master branch. Otherwise, please use the plugins from [v3.10](https://github.com/Novik/ruTorrent/releases/tag/v3.10).

When upgrading your version, make sure to copy and replace everything except for the share folder.

**Comment by ADz-83** [comment]
> #2236 and #2247 broke compatibility with v3.10.
> 
> You need to use the [v4.0-beta.1](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1) if you would like to pull things from the master branch. Otherwise, please use everything from [v3.10](https://github.com/Novik/ruTorrent/releases/tag/v3.10). When changing/upgrading your version, make sure to copy and replace everything except for the share folder.



> #2236 and #2247 broke compatibility with v3.10.
> 
> You need to use the [v4.0-beta.1](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1) if you would like to pull things from the master branch. Otherwise, please use everything from [v3.10](https://github.com/Novik/ruTorrent/releases/tag/v3.10). When changing/upgrading your version, make sure to copy and replace everything except for the share folder.

Ah this may be the issue then.  I pre-configure some ratio/throttle settings and have copied the settings files over to new installs.

How do I migrate the settings over,  do I need to re-create settings files again using a new install of v3.10?

**Comment by stickz** [comment]
Yeah, you might want to re-create the setting files with a new install of v3.10 just to be safe.

It may also be a good idea to prepare a version v4.0 build of ruTorrent. Developers are working on migrating to this build currently. There are some very critical fixes. Memory leaks in the web browser have slowed down drastically for instance.
