### ISSUE TITLE
Selected theme is reset after recreation of the container Bug or not ?

### ISSUE THREAD

**Issue by Whisper40** [Novik/ruTorrent#2280]
The selected theme is reset when the container is recreated, i don't know if this is a bug or not, but i don't remember to saw this before..
(master branch)

Reproduce : 
Select materialdesign theme
recreate your container
it goes back to default

**Comment by stickz** [comment]
The WebUI settings reset once when upgrading to master or 4.0 beta from version 3.x. The storage location was changed. We had to do this because there was a race condition with the old storage method. It's expected behavior, not a bug.

**Comment by stickz** [comment]
You should report this bug to the container you're using. It's not related to ruTorrent.

**Comment by Whisper40** [comment]
Yes we will fix it, what's the new storage location ?
What's the change ?

**Comment by stickz** [comment]
The profile path must be this for master or beta 4.0. $profilePath = '../../share';

If you didn't change it, this is why your settings reset.
