### ISSUE TITLE
JavaScript errors with Chrome 97.0.4692.99

### ISSUE THREAD

**Issue by imperia777** [Novik/ruTorrent#2281]
Hello,

I got those errors when I load the page with Chrome 97.0.4692.99:

```
JS error: [http://rtorrent.imperia.lan/rutorrent/plugins/filedrop//jquery.filedrop.js : 28] Uncaught TypeError: Cannot read properties of undefined (reading 'push')
JS error: [http://rtorrent.imperia.lan/rutorrent/ : 2580] Uncaught TypeError: $(...).filedrop is not a function
```

I tried latest master-b46deed and 4.0-beta.1

Meanwhile it works with Firefox 96 without those errors.

I am on Debian testing with PHP Version: 8.1.1-4

P.S. Also the title is still 3.10

**Comment by stickz** [comment]
Clear your web browser cache.

**Comment by imperia777** [comment]
That worked. Thanks. 
latest master.
