### ISSUE TITLE
bug in trafic plugin

### ISSUE THREAD

**Issue by ratM1n** [Novik/ruTorrent#2284]
Hi!

Im using latest master branch (commit 4a6cc11d5864387c264d9b0425e5f3fe76541774) of rutorrent and plugins/trafic/update.php script gives error:

`
$ php /var/www/rutorrent/plugins/trafic/update.php
PHP Fatal error:  Uncaught Error: Call to undefined function getTempFilename() in /var/www/rutorrent/plugins/trafic/stat.php:49
Stack trace:
#0 /var/www/rutorrent/plugins/trafic/update.php(84): rStat->flush()
#1 {main}
  thrown in /var/www/rutorrent/plugins/trafic/stat.php on line 49
`

resulting that traffic statistics are not updated.

Got it fixed by changing this line in https://github.com/Novik/ruTorrent/blob/master/plugins/trafic/stat.php#L49

```
--- a/plugins/trafic/stat.php
+++ b/plugins/trafic/stat.php
@@ -46,7 +46,7 @@ class rStat
        public function flush()
        {
                global $profileMask;
-               $randName = getTempFilename('trafic');
+               $randName = FileUtil::getTempFilename('trafic');
                if($file=@fopen($randName,"w"))
                {
                        if( (fputcsv($file,$this->hourUp)!==false) &&

```

System is ubuntu linux 20.04 with php 7.4.27

**Comment by Novik** [comment]
Fixed, thanks.
https://github.com/Novik/ruTorrent/commit/59434bde76b5c1ba5ecc8e74eb8735aeb268615a
