### ISSUE TITLE
Add the ability to start a ffmpeg video conversion from within rutorrent

### ISSUE THREAD

**Issue by Rc2-ops** [Novik/ruTorrent#2292]
Would be cool to be able to start a conversion/encoding process in ffmpeg from within rutorrent.

**Comment by Gosokan** [comment]
Why not just use the ssh shell?
Or maybe modify old FileManager plugins. Create new bash script or just modify screen file in the `/ruTorrent/plugins/filemanager/scripts` directory , so ffmpeg can do transcode video instead of making screenshot.
