### ISSUE TITLE
got error 504 when loading more than 11000 torrents

### ISSUE THREAD

**Issue by SMooxx** [Novik/ruTorrent#2306]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Chrome 98.0.4758.102 Stable (x64)
ruTorrnet: v3.10
PHP: PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22)
OS: Ubuntu 20.04.3 LTS

### Tell us how you installed ruTorrent

https://github.com/arakasi72/rtinst

### Describe the bug

I have tons of torrents. My NAS has a J1900 CPU and 8G Ram. 
Every time I use the command **'rt restart'** to restart rTorrent, rt works fine as expected. But RuTorent webui gets this error even after I refresh the page several times.
![image](https://user-images.githubusercontent.com/9960618/154204747-816b2ce0-0036-4b93-b5e0-081b4fd6c226.png)

**Comment by stickz** [comment]
Thank you for this detailed issue report. While this is not a problem with ruTorrent, I can help you fix this issue.

Please run `sudo rutupgrade`. When asked which build to install select: `1. Use the latest stable release`.

You can't use the master branch on this script because it's not compatible with the autodl-irssi plugin.

**Comment by SMooxx** [comment]
`Joinerd@WiiCat: ~/rtorrent/download $ sudo rutupgrade
Installed version: 3.10
   Latest version: 3.10
A previous backup is available to restore

Detected /root/rutorrent_old
1. Restore rutorrent_old
2. Upgrade to latest version
Select 1 or 2: 2
Rutorrent will be upgraded
WARNING: rutorrent_old will be deleted
If you wish to retain this older version you should exit this script, and rename or move it
Do you wish to continue? **y**
Choose which build to install, (if you are not sure select 1)
1. Use the latest stable release
2. Use the most recent master build
Select 1 or 2: 1
rutorrent_old has been deleted

Installing version 3.10 of rutorrent
Your existing rutorrent folder will be moved to /root/rutorrent_old

If you are not happy with the upgrade you can restore the old version, by rerunning this script

Installing Rutorrent (v3.10)
Setting permissions, Starting services

Installation of RuTorrent complete`

**Huge thanks, mate.  It works like a charm.**
