### ISSUE TITLE
Additional label icons

### ISSUE THREAD

**Issue by newadventure079** [Novik/ruTorrent#2350]
### Is your feature request related to a problem?

There's a label for `movie` but not `movies`.  There's also a label for `sickbeard` but not `Sonarr` or `Radarr`.  

I also believe every category should have a plural option, ie. movie/movies, book/books, etc

### Describe the solution you'd like

Label icons for plurals of every icon (where it makes sense).  And icons more software like Sonarr, Radarr, etc

**Comment by stickz** [comment]
I added icons for "images", "movies", "pornos" and "videos". I also added icons for "sonarr" and "radarr". 

Please let me know if there's anything more I can do for you. If you're satisfied feel free to close the issue.

**Comment by newadventure079** [comment]
Thanks @stickz!
