### ISSUE TITLE
cannot adjust the tab size by dragging border in phone browser

### ISSUE THREAD

**Issue by highblade46** [Novik/ruTorrent#2358]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web browser : Google Chrome  on Android phone
![Screenshot_20220507-175803_Chrome](https://user-images.githubusercontent.com/77506070/167247219-4c511204-5a81-4ef2-bfd9-799c3f4c803b.jpg)
ruTorrent is connect with seedboxes server
![Screenshot_20220507-175600_Chrome](https://user-images.githubusercontent.com/77506070/167247183-97b31b50-0a2f-4ef3-801a-65d2e52822d2.jpg)

### Give us detailed steps to reproduce the error

I try to adjust the size of side and bottom tab, but it cannot drag to increase the tab area. It would only get smaller and almost cannot see anything like the screenshot.
![20220507_180645](https://user-images.githubusercontent.com/77506070/167247499-b25fe136-47b0-4acf-9cc9-a96924f92b1f.jpg)

### Tell us the error message

There is no error message, but I couldn't find a way to recover this through phone browser.

**Comment by Novik** [comment]
Standard interface of ruTorrent is not intended for mobile devices. Try to use plugin 'iPad' (if you already not use it).
