### ISSUE TITLE
Plugin History incorrect work

### ISSUE THREAD

**Issue by CityAceE** [Novik/ruTorrent#2359]
### Is your feature request related to a problem?

Плагин History при переполнении количества записей ведёт себя не так, как ожидается. Предположим, что у нас в настройках задано количество хранимых записей 300 (по умолчанию), а количество текущих записей в логе достигло 300. Мы пытаемся добавить ещё одну запись (301-ю). В результате такого добавления история полностью очищается, в ней остаётся только одна самая первая (старая) запись. Новая запись не добавляется.

### Describe the solution you'd like

Я ожидаю, что при добавлении 301-й записи, будет удалена самая старая запись, а новая добавится в самое начало. Таким образом весь список просто сдвинется на одну запись. Общее количество записей останется равным 300.

### Additional context

Обнаружил такое поведение, когда пытался перенести историю ruTorrent с другого сервера, где количество записей в истории превышало заданное по умолчанию на новом сервере. Никак не мог понять почему история всё время очищается при добавлении любого нового действия. В итоге разобрался почему.

Пока в качестве workaround выставил заведомо большее число хранимых записей в настройках плагина. В дальнейшем хотелось бы получить корректную работу плагина. Сам, к сожалению, PHP не владею.

**Comment by Novik** [comment]
Пожалуйста
1) Используйте по-возможности английский язык. В противном случае реакции Вы можете ждать долго.
2) Используйте корректный шаблон issue. То, о чем Вы пишите, никак не согласуется с шаблоном "Feature Request". В результате сведения о используемой Вами версии мне взять неоткуда. И сразу хотелось бы предупредить - древние версии не интересуют.
