### ISSUE TITLE
History plugin problem

### ISSUE THREAD

**Issue by CityAceE** [Novik/ruTorrent#2360]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Firefox 100.0 (64bit)
ruTorrent: v3.10
PHP: PHP 7.4.28

### Give us detailed steps to reproduce the error

The problem in History plugin. The history list clears if quatity of items in history list becomes more then numer defined in settings of this plugin. For example, max number of items in settings is 300, we already have 300 items in history list, then we add one more action (add new torrent for downloading). In this case the only item leaves in histry list. It's the oldes item, not our new torrent. All other items just disappeare.

### Tell us the error message

There is no any messages.

### Provide the php error log contents (if applicable)

There is on any helpful logs.

**Comment by Novik** [comment]
Thanks, fixed here - https://github.com/Novik/ruTorrent/commit/97ec928100ba9b108d8e71b0850db363d89a4688
But for 3.10 you should apply this manually.
