### ISSUE TITLE
Ratio rules don't work at restart until they are manually updated

### ISSUE THREAD

**Issue by rmichelena** [Novik/ruTorrent#2361]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

docker horjulf/rutorrent-autodl (latest) = rTorrent 0.9.8, ruTorrent 3.10
running under Ubuntu 20.05
Web Browser: Firefox (latest)

### Tell us how you installed ruTorrent

docker image horjulf/rutorrent-autodl (latest)

### Describe the bug

I have set ratio rules, such as "if one of torrent's tracker URL contains xxx, then set ratio to yyyy, don't set throttle"
They work beautifully. That is, until the container is restarted. Then they won't work at all, until I go again to the "ratio rules" settings, fiddle with it (make any unimportant change and revert it) and press "ok".
At that point they start working again, until next restart.
Ratio Rules should be loaded and initiated from startup!

unless all this is a rTorrent problem and not ruTorrent ?

**Comment by stickz** [comment]
This version of ruTorrent is accent. We no longer support it. I would recommend using an alternative install script.

- https://github.com/mondediefr/docker-rutorrent
- https://github.com/swizzin/swizzin

**Comment by rmichelena** [comment]
mmm... 3.10 is the "stable" version... so you say I'd be better off with the latest beta?
can you confirm whether this was a known bug in 3.10 and solved in 4.x.b ?

**Comment by stickz** [comment]
The latest beta is faster and more stable than 3.10. I would recommend swizzin. 
If this bug is still present on version 4, please let us know so we can fix it.
