### ISSUE TITLE
DataDir plugin: Error 500 when trying to change directory of a torrent file

### ISSUE THREAD

**Issue by colinborins** [Novik/ruTorrent#2362]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 97.0.4692.71
ruTorrent: 4.0
PHP: PHP81
OS: Truenas 13.0 running Freebsd 13.0-RELEASE-p11

### Tell us how you installed ruTorrent

Followed the following guide: https://forums.freebsd.org/threads/freebsd-install-rtorrent-and-rutorrent-on-lighttpd-full-guide.85230/#post-567706

### Describe the bug

Package data Dir is not working. When trying to move a saved torrent the following error occurred:

VM25815:1          POST http://192.168.2.133:8080/plugins/datadir/action.php 500 (Internal Server Error)

Upon clicking the link the following message appears:

{"errors":[{"desc":"theUILang.datadirSetDirFail","prm":"\/usr\/local\/rtorrent\/downloads"}]} 

I have made sure the permissions are correct,  $topDirectory in config.php is set to "/".

**Comment by colinborins** [comment]
appolgies its rutorrent 4.0

**Comment by stickz** [comment]
Could you go to `settings -> more tools -> developer tools -> console` on google chrome? Then click the button I circled and press `info` while on your ruTorrent webpage. Look for a stack trace.

![chrome_dev_tools](https://user-images.githubusercontent.com/9171157/171292286-b39cba87-c171-45b4-905c-c44d42b9a607.png)

**Comment by colinborins** [comment]
![image](https://user-images.githubusercontent.com/10972668/171473844-8c046edd-5b13-4efd-a3c9-bbdf34d76f39.png)

**Comment by colinborins** [comment]
If you want to set up a time to do a teamviewer session let me know

**Comment by stickz** [comment]
> No info available :/

Yeah I figured that might happen. The next step is to edit your php.ini configuration file to log errors.

Stop services:
```
service php-fpm stop
service lighttpd stop
```
Edit your phi.ini file: `ee /usr/local/etc/php.ini`
uncomment this line: `error_log = php_errors.log`
Start services:
```
service php-fpm start
service lighttpd start
```

Provide the output of the php errors log file: 
`cat /usr/local/www/lighttpd/ruTorrent/php/php_errors.log`

**Comment by stickz** [comment]
Also the guide you followed is wrong. This step should not be needed:
> Create missing the directory for cache/history added .torrent file.
> `mkdir -p /usr/local/www/lighttpd/ruTorrent/php/share/torrents`

Instead edit your ruTorrent configuration file to save cache/history content in the correct location:
`ee /usr/local/www/lighttpd/ruTorrent/conf/config.php`
Change `$profilePath` to `$profilePath = '../../share';`

This will save in `/usr/local/www/lighttpd/ruTorrent/share/`. Saving cache/history content in the php folder will break things.

If it is required to create a directory, it should be done like this instead:
`mkdir -p /usr/local/www/lighttpd/ruTorrent/share/torrents`

Reset permissions again afterwards:
```
chown -R www:www /usr/local/www/lighttpd/ruTorrent
chmod -R 0775 /usr/local/www/lighttpd/ruTorrent
```

**Comment by colinborins** [comment]
@stickz  here is a screenshot:
on. php: 36
Stack trace:
#0 {main}
thrown in /usr/local/www/lighttpd/ruTorrent/plugins/datadir/action.php
on line
36

Also, inscase someone needs to do this in the future. You need to add a path to error_log = php_errors.log aka error_log = /usr/local/www/lighttpd/ruTorrent/php/php_errors.log

In regards to your message after that, 
It was already changed from $profilePath to $profilePath = '../../share';

**Comment by colinborins** [comment]
Also for vmtouch -i '*.torrent' -m 125K /usr/local/www/lighttpd/ruTorrent/ Can i do that at any time after restarting rtorrent or does it need be at first startup?

**Comment by stickz** [comment]
You can try this in your demon. Ideally, this should be run every time you start rTorrent.
`rtorrent_args="-O execute2='vmtouch, -i, *.torrent, -m, 125K, /usr/local/www/lighttpd/ruTorrent/' ${rtorrent_args}"`

I tracked down the cause of your error. I believe you need to install the ctype extension for php8.1 on FreeBSD.
`pkg install php81-extensions`

**Comment by stickz** [comment]
You can't change the port from ruTorrent. It's required to configure the settings file from the guide.

```
#General Settings
: ${rtorrent_port_range="64999-64999"}
: ${rtorrent_port_random="no"}
```

**Comment by colinborins** [comment]
@stickz i should have lead with that. I also have tried that without luck:

![image](https://user-images.githubusercontent.com/10972668/172933412-81ad8017-dabb-4fef-b265-7e13d9f97d34.jpeg)

**Comment by colinborins** [comment]
[rtorrent.txt](https://github.com/Novik/ruTorrent/files/8873582/rtorrent.txt)
Here is  my file

**Comment by colinborins** [comment]
@stickz ive corrected the vmtouch line. However, im still getting the same result for ports. If you have any ideas that would Be amazing

**Comment by colinborins** [comment]
The author of the article also said “ PS.
By the way, not all manual commands work. I do not know why maybe manual it is old.”

**Comment by colinborins** [comment]
@stickz any updates?

**Comment by eazrael** [comment]
FWIW. Accidently updated my containerized rutorrent, got a mix up of Alpine's PHP 8.1 & PHP 8.2 (installed 8.1 and rutorrent depends on 8.2 now) and in the end I needed to install php8*-ctype. Seems they modularized it out in newer Alpine versions.

2023-10-21 11:42:43: (../src/mod_fastcgi.c.449) FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ctype_xdigit() in /usr/share/webapps/rutorrent/plugins/datadir/action.php:36
2023-10-21 11:42:43: (../src/mod_fastcgi.c.449) FastCGI-stderr:Stack trace:
2023-10-21 11:42:43: (../src/mod_fastcgi.c.449) FastCGI-stderr:#0 {main}
2023-10-21 11:42:43: (../src/mod_fastcgi.c.449) FastCGI-stderr:  thrown in /usr/share/webapps/rutorrent/plugins/datadir/action.php on line 36
