### ISSUE TITLE
Rutorrent on OpenWrt

### ISSUE THREAD

**Issue by rogales** [Novik/ruTorrent#2363]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [ ] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Latest Chrome, latest Edge
ruTorrent: 3.10
Php 8

### Give us detailed steps to reproduce the error

Hello there.
I know that I'm now like an archaeologist but I need help from this community.

Well I have problem with ruTorrent - I'm still getting an error like this:
https://i.imgur.com/fh6Iw9C.png and after trying to add torrent I get also : " JS error: [ : 0] Script error."

I did everything in a turn like here: [https://eko.one.pl/forum/viewtopic.php?pid=188347#p188347 1](https://eko.one.pl/forum/viewtopic.php?pid=188347#p188347)
but my php packets are php8 not 7, and my rutorrent version is 3.10
I have also problem with chown -R http.www-data /www/rutorrent - I'm getting error like this: "chown: unknown user/group http:www-data"
My server is uHTTPpd.
rTorrent is in 0.9.8-2 version.

Can someone help me track and resolve my problem?
Would be very appreciated

### Tell us the error message

[05.06.2022 16:24:41] WebUI started.
[05.06.2022 16:24:42] Bad response from server: (200 [parsererror,getplugins]) SyntaxError: Unexpected token '<'
[05.06.2022 16:24:48] JS error: [http://192.168.0.50/rutorrent/js/webui.js : 765] Uncaught TypeError: Cannot read properties of undefined (reading 'rTorrent')

### Provide the php error log contents (if applicable)

empty

**Comment by Novik** [comment]
> SyntaxError: Unexpected token '<'

This means - your server return something strange, html page instead result of the execution php script. Check your web-server configuration and error log.

**Comment by rogales** [comment]
I'm completely a newbie when it comes to openwrt, so I'd like to ask You for precise commands how to paste here errors, or log info You need to give any hints and help. 
Thank You.

**Comment by rogales** [comment]
I did factory reset.
Now I have:

Kernel：5.10.116
OpenWrt 22.03-SNAPSHOT r19385-f765f2f114
rtorrent rpc 0.9.8-2 
rutorrent v4.0-beta.2.1

and i still get this error https://i.imgur.com/4Fl1Guo.png

I'm completely helpless, really don't know what I'm doing wrong.
Any help would be appreciated, thank You.

**Comment by rogales** [comment]
Ok, I've managed with running rutorrent but i still have some problems.

"[08.06.2022 22:00:12] Webserver user can't access 'stat' program. Some functionality will be unavailable.
[08.06.2022 22:00:12] rTorrent user can't access 'stat' program. Some functionality will be unavailable."

https://i.imgur.com/QyEqjTP.png

The plugins problem I will manage by myself, but with the problem above I would use some help of You.

Thanks.

**Comment by rogales** [comment]
Thank You **stickz**.

There was a lot of work in terminal with configs etc. but I finally have managed to make everything work.
Thank You for Your help **Novik** & **stickz**.
