### ISSUE TITLE
V4.0 UL,GB ratio is broken. 

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2371]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Firefox/Edge
4.0
8.1 (Nginx)
Linux Ubuntu 22.04

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent.git

### Describe the bug

Changing the UL,GB ratio to anything rolls back to "0.01". Only absurd values like 99999 change the value to something else.

### Steps to reproduce

Go to the ratio setting tab in Rutorrent settings, change the UL,GB value to something else than 0.01
Click OK to close the setting window
Reload or restart the browser
It will be back to 0.01

### Expected behavior

Same behavior as the old plugin. 

### Additional context

Absurd values like 99999 are changed to 97.66.
Other boxes like Max%, Min%, time and name can be changed and keep their updated value/string. 

If this plugin is supposed work differently than the old that had 20 as default in the UL,GB ratio, it would be nice to write something about how it is supposed work now.

**Comment by stickz** [comment]
Hi @Antorell, I have committed a fix for this issue. Could you try reinstalling ruTorrent to verify this problem is resolved?

**Comment by Antorell** [comment]
Seems to be fixed, yes. 

Thanks :)
