### ISSUE TITLE
Rutorrent Truenas settings in rtorrent.rc does not work 100 percent of the time

### ISSUE THREAD

**Issue by ac1dburnz** [Novik/ruTorrent#2373]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 97.0.4692.71
ruTorrent: 4.0
PHP: PHP81
OS: Truenas 13.0 running Freebsd 13.0-RELEASE-p11

### Tell us how you installed ruTorrent

Followed the following guide: https://forums.freebsd.org/threads/freebsd-install-rtorrent-and-rutorrent-on-lighttpd-full-guide.85230/#post-567706

### Describe the bug

Some settings in my rtorrent file are not working. For example, i cannot change ports and it is stuck on the defaulted amount. 

### Additional context

This is a continuation to issue 2362 since the original issue has been solved.

**Comment by colinborins** [comment]
@stickz is there anything i can manually change in the source code that would change the port’s defaulted numbers ?

**Comment by colinborins** [comment]
Would manually changing the source code correct this?

[rtorrent](https://github.com/rakshasa/rtorrent)/[src](https://github.com/rakshasa/rtorrent/tree/master/src)/command_network.cc 

And Changing line line 243??

**Comment by nexor666** [comment]
@colinborins  i followed the same guide and changed the default port by editing /usr/local/etc/rc.d/rtorrent and changed the line in there to : ${rtorrent_port_range="50000-50000"} and that worked for me. Its not a perfect fix but it seemed to work for me. Hope this helps!
