### ISSUE TITLE
action.php failing to acquire basicauth data

### ISSUE THREAD

**Issue by Mycah** [Novik/ruTorrent#2383]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Browser: Firefox 104.0.2 (tested with cache cleared and in private browser)  Tried in edge too.
ruTorrent Master: 55e533a
PHP: PHP 8.1
Tried the following httpd:
Caddy v1.0.4
Caddy v2.5.2

### Give us detailed steps to reproduce the error

I can login to the rutorrent console, see all the data all the existing torrents.  Torrents added by sonaar are added with no problem.  When I click "Add Torrent.." browse and select a torrent to upload, I reports it cannot add the torrent.  It seems like action.php isn't able to get the basicauth token from httpd.

### Tell us the error message

Error in rutorrent console:
`[12.09.2022 15:16:51] [any filename].torrent - Failed to add torrent.`

Errors in caddy logfile:
```
2022/09/12 15:12:59 [ERROR 401 /] BasicAuth: user "" was not found or password was incorrect. [my ip address] [my domain] / HTTP/2.0
2022/09/12 15:13:02 [ERROR 401 /] BasicAuth: user "" was not found or password was incorrect. [my ip address] [my domain] / HTTP/2.0
2022/09/12 15:13:13 [ERROR 401 //plugins/httprpc/action.php] BasicAuth: user "" was not found or password was incorrect.  [my ip address] [my domain] //plugins/httprpc/action.php HTTP/1.1
2022/09/12 15:14:43 [ERROR 401 //plugins/httprpc/action.php] BasicAuth: user "" was not found or password was incorrect.  [my ip address] [my domain] //plugins/httprpc/action.php HTTP/1.1
```

### Provide the php error log contents (if applicable)

No errors listed in /var/log/php8.1-fpm.log

**Comment by stickz** [comment]
Your caddy web server configuration is responsible for this issue. ruTorrent does not technically have authentication.

**Comment by Mycah** [comment]
weird. i thought that might be the cause, but it's worked in the past.  i think it stopped working after updating to ubuntu 22.04.1 which doesn't make sense because its the same caddy version and same rutorrent version.  php shouldn't matter for authentication right?  it went from 7.4 to 8.1
my caddy configs:
1.0.4:
```
domain.com {
    root /home/user/rutorrent
    fastcgi / /run/php/php-fpm.sock php {
        env PATH /bin
    }
    log /var/log/caddy/rutorrent_access.log  {
      rotate_size 5
      rotate_age 7
      rotate_keep 5
      rotate_compress
    }
    errors /var/log/caddy/rutorrent_errors.log
    markdown
    tls {
        dns cloudflare
    }
    gzip
    basicauth / user password
}
```

v2.5.2
```
domain.com {
    root * /home/user/rutorrent
    php_fastcgi unix//run/php/php-fpm.sock
  	file_server
  	header Cache-Control "no-cache"
    encode gzip
    tls {
	    dns cloudflare {env.CF_API_TOKEN}
    }
    basicauth / {
      user hashedpassword
    }
    log {
    format console
    level DEBUG
        output file /var/log/caddy/rutorrent_acess.log {
  	      roll_size     50mb
  	      roll_uncompressed
  	      roll_local_time
  	      roll_keep     5
  	      roll_keep_for 5d
        }
    }
}
```

**Comment by stickz** [comment]
basicauth is a caddy directive. This is not related to php or rutorrent. You should look strictly at caddy for this.

**Comment by Mycah** [comment]
I turned off basicauth and I still can't upload a torrent with the UI.  So the issue isn't what the log reported.
