### ISSUE TITLE
Add exception/Recognise pwtorrents.net/seedbox.php as Private tracker

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2384]
### Is your feature request related to a problem?

pwtorrents.net seedbox option/tracker announce isn't showing as private so gets limited by ratio rules etc.

Full tracker announce is
http://pwtorrents.net/seedbox.php

There is no passkey as it uses pre-defined IP address in profile.

### Describe the solution you'd like

Please add an exception to recognise it as private announce.

**Comment by stickz** [comment]
This should be a **Bug report** not **Feature Request**. You saved 2 minutes using the wrong template and didn't give us enough information to fix the problem. We created those templates to help fix reported problems, not to waste your time.

The plimits plugin is no longer supported by us. If you're using ruTorrent 4.0, the third-party plugin author might be able to fix this. We don't even know which version of ruTorrent version you're using. This is why it's good to use the proper template.
https://github.com/Micdu70/rutorrent-plimits

**Comment by ADz-83** [comment]
My apologies for using wrong template.

However this has nothing to do with plimits.   It has to do with the ratio/throttle plugins not plimits.
