### ISSUE TITLE
Plugin: check_port fails when $useWebsite is portchecker

### ISSUE THREAD

**Issue by dylansama** [Novik/ruTorrent#2403]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: N/A
ruTorrent: Master: 1c80a6d4a67ea73295f17866241d261c1e34116a
PHP: PHP 7.4.3
OS: Ubuntu 20.04.5 LTS

### Tell us how you installed ruTorrent

Manually

### Describe the bug

Not correctly checking port, will simply error.

### Steps to reproduce

1. Change $useWebsite to 'portchecker' in `plugins/check_port/conf.php`
2. Enable check_port plugin.
3. Load ruTorrent
4. Receive port is closed error (even though its not)

### Expected behavior

Check if port is open or not

### Additional context

The POST sent to https://portchecker.co when checking port will always fail. The site url apparently changed to: https://portchecker.co/checking. Easily noticed when examining portchecker.co site in browser with dev tools enabled.

Already filed PR with fix. Likely un-noticed as the default port checking site was changed to www.yougetsignal.com long ago.
https://github.com/Novik/ruTorrent/pull/2395

**Comment by stickz** [comment]
Resolved in https://github.com/Novik/ruTorrent/pull/2395.
