### ISSUE TITLE
Issues with files tab after changing view setting to list

### ISSUE THREAD

**Issue by wb6vpm** [Novik/ruTorrent#2405]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 106.0.5249.119
ruTorrent: v4.0 (unsure of specific version, as it was installed by swizzin script)
PHP: PHP 8.1.2
OS: Ubuntu 22.04.1 LTS

Happens on all client browsers, not just the above declared Chrome (Firefox/Chrome/Safari) 

This was installed via Swizzin (https://swizzin.ltd/).

### Tell us how you installed ruTorrent

https://swizzin.ltd/

### Describe the bug

After changing the view setting to list on the Files tab, I get the following error when I right click a file in the window under the file tab (all 3 below are from my Mac OSX computer):

Chrome:
JS error: [https://DOMAINNAME/rutorrent/ : 2695] Uncaught TypeError: Cannot read properties of undefined (reading 'IsDirectory')

Firefox:
JS error: [https://DOMAINNAME/rutorrent/ line 2 > InjectedScript : 2695] TypeError: theWebUI.dirs[theWebUI.dID] is undefined

Safari:
JS error: [https://DOMAINNAME/rutorrent : 2695] TypeError: undefined is not an object (evaluating 'theWebUI.dirs[theWebUI.dID].isDirectory')
![Screen Shot Safari](https://user-images.githubusercontent.com/24217989/200542816-f1ffe15a-e80c-488d-bf39-6507fe0f14e0.png)
![Screen Shot Firefox](https://user-images.githubusercontent.com/24217989/200542824-3d5f69f6-a4af-4fb2-85f5-5627b765d654.png)
![Screen Shot Chrome](https://user-images.githubusercontent.com/24217989/200542826-e79b6931-a6e3-491d-abc9-e44466e38048.png)

### Steps to reproduce

1. Open rutorrent in browser
2. select a torrent
3. select the 'Files' tab
4. right click and select view, then list
5. right click again and it will error

### Expected behavior

should see standard context menu (Priority/File Manager/Download Strategy/View/...)

**Comment by rex** [comment]
I am seeing this issue as well, and it was never a problem until recently despite my having never changed the ruTorrent version.

**Comment by stickz** [comment]
I'm investigating this problem currently. Bug is confirmed and assigned high priority.

**Comment by stickz** [comment]
@rex @wb6vpm This issue is caused by the file manager plugin. Please disable it and report the issue to the developer.
https://github.com/nelu/rutorrent-filemanager/blob/master/init.js#L121

**Comment by stickz** [comment]
@Enissay Please upgrade to the latest hot fix release. It resolves a jQuery issue with error notifications.
https://github.com/Novik/ruTorrent/releases/tag/v4.0.1-hotfix
