### ISSUE TITLE
Material Design theme uppercase text problem in Greek translation

### ISSUE THREAD

**Issue by ChriZathens** [Novik/ruTorrent#2407]
### Is your feature request related to a problem?

In Greek, intonation is used, unless you write a word all uppercase. Due to this, all elements that have "text-transform: uppercase" in Material Design Theme's css , show as all uppercase but there is also intonation which is wrong. 

Example: 
In settings the first option is General. 
In Greek, General is Γενικά. If you transform this to uppercase, it appears as ΓΕΝΙΚΆ. Notice the extra **'** ? It should appear as ΓΕΝΙΚΑ.

I cannot consider this as a bug, since I believe it  is something specific to Greek, so I created the issue as a feature request. 

### Describe the solution you'd like

I don't know how easy this is, but my suggestion would be an option for the Material theme to use or not uppercase.
The other option I can think of, is a simple clone of the Material theme with an altered css, ommiting only the text-transform: uppercase part.

### Additional context

This is a nice to have option, nothing important. Thought I should mention it because the Material Design theme is one of the best looking ones and in Greek this "bug" affects its looks  :)

**Comment by stickz** [comment]
Closing as #2408 was merged as a resolution. Please comment if the problem still isn't fixed.
