### ISSUE TITLE
Progress reporting for partially completed torrents

### ISSUE THREAD

**Issue by halilnevzat** [Novik/ruTorrent#2410]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Chrome 10.0.53
ruTorrent: 3.10
PHP :  php8
OS: windows 10

merlinwrt RT-AC86U

### Tell us how you installed ruTorrent

after installing entware i used opkg install rtorrent-easy-install  thats it.

### Describe the bug

lets assume the total file size of torrent is 10GB, but i only picked 5 files in it to download and rest will not download. so it shows %50 percent download even if it downloaded everything that i want. i think it should show %100 percent after downloaded everything that i picked.

### Steps to reproduce

1. get a torrent to download with multiple files
2. select only 1 file to download in it.
3. after selected file finished it will still show download percentage less than %100

### Expected behavior

should show %100 percent after desired files downloaded

### Additional context

there was already issue about it but it was in 2015. please let me know if i should update my rutorrent to 4.0 versions
![ss](https://user-images.githubusercontent.com/15174006/202901661-32273d75-1013-4dec-88d9-9ed6aeb46629.JPG)

**Comment by usr20210909** [comment]
I do not agree. The shown percentage should relate to the overall content of the torrent, including the files the user has excluded from downloading.

If anything, there should be a separate column with a different name ("Done selected" or something like that) for the percentage of the files that have been selected to be downloaded.

Or can both values be incorporated into a single column? For a torrent, where half the files have been excluded from downloading, it could be shown like this: "50% (100% selected)". The progress bar should still relate to the overall content - unless two progress bars can be shown at the same time similar to the traffic window. This might be confusing for some users, though.

How is it being handled in other BitTorrent clients?

**Comment by stickz** [comment]
I pinned this issue for discussion. I agree this is not a good way to report download progress. It says "Downloading" as well, when you've downloaded all the intended files. We should have a new status for partially completed torrents.

The problem is how we should resolve this problem. It's very abstract and could impact other features. I'm open to hearing suggestions or pull requests. Any changes will NOT be back-ported to version 3. You will have to upgrade to version 4.
