### ISSUE TITLE
JS error: Uncaught SecurityError: Blocked a frame with origin

### ISSUE THREAD

**Issue by spotpl** [Novik/ruTorrent#2433]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Google Chrome, latest version
ruTorrent 4.0 latest version (tested on version 3 also)

### What were you trying to do?

It's fresh installation

### What us the error message?

JS error: [https://XXX/XXX/ruTorrent/js/content.js : 72] Uncaught SecurityError: Blocked a frame with origin "https://XXX" from accessing a cross-origin frame.

**Comment by n1ce-0ne** [comment]
any good to you? https://github.com/Novik/ruTorrent/issues/2104#issuecomment-697196210

**Comment by spotpl** [comment]
> any good to you? [#2104 (comment)](https://github.com/Novik/ruTorrent/issues/2104#issuecomment-697196210)

Unfortunately no, I tried run it with 
add_header X-Frame-Options DENY
and
add_header X-Frame-Options SAMEORIGIN.

The same error occurred everytime. It's appear only once new torrent is added to the rTorrent WebUI.
regards

**Comment by stickz** [comment]
What install script are you using? How do you install ruTorrent? What type of web server are you using?

Cross origin checks are disabled by default on ruTorrent. This issue is mostly likely related to your configuration.

**Comment by spotpl** [comment]
I'm using Ubuntu 18.04 64bit with nginx and apache2 server. rTorrent are started as user in screen and ruTorrent files are storred under user www directory.
I have checked most of the configuration files and can't find anything related such problem for fix it. That's why I have reported it here.
