### ISSUE TITLE
Labels with slashes do not render properly as folder structure when neighbors have dashes

### ISSUE THREAD

**Issue by phene** [Novik/ruTorrent#2435]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox
ruTorrent: v4.0-stable
PHP: PHP 8.1.7
OS: Ubuntu 22.10

### Tell us how you installed ruTorrent

No issues related to installation

### Describe the bug

Using the webui.show_label_path_tree option, if a list of labels represents a directory structure, similar labels with dashes will interrupt the flow of the directory structure.

### Steps to reproduce

Add torrents with the following labels:

* tv
* tv-foo
* tv/bar
* tv/bar/baz
* tv/quux

Labels 3-5 will properly render as a directory tree, but appear directly under tv-foo rather than tv. This is most likely due to the sort orders/ascii values of `-` and `/`.

![2023-01-20_00-11](https://user-images.githubusercontent.com/166528/213647704-08324900-1ee5-499e-993d-350395ce4576.png)

### Expected behavior

The directory structure would properly render under the tv label, and tv-foo would appear after the directory structure.

**Comment by stickz** [comment]
@phene Please update to cf9807839d96a2bb4e3eb2d9fa54cb2cc0973e09 and let us know if this problem is resolved. A hot fix will be coming eventually for version 4 stable. I'm just waiting for major platforms like swizzin to upgrade and test it further.

**Comment by phene** [comment]
@stickz Confirmed that fixed it. Thanks!
