### ISSUE TITLE
Rutorrent caching is causing issues with the RSS manager

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2438]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Firefox 109
ruTorrent: v4.0-stable
PHP 8.1
Ubuntu 22.10

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent.git

Latest commit at time of writing. 

### Describe the bug

With the latest version of Rutorrent new filters and/or filter changes in the RSS manager do not get saved until I restart my browser. 

### Steps to reproduce

Open the RSS manager,
Create a new filter or edit an already configured filter, 
Click OK on the RSS manager box to confirm the new filter or setting,
Open the RSS manager again,
Everything is back as if nothing had been changed

### Expected behavior

Save settings on the fly without the need to restart the browser for Rutorrent to display the changes. 

### Additional context

It's an issue with the new cache thingy(?). Rutorrent 4.0-beta1 doesn't have any issue. Also, if I open the developer toolbox in Firefox and set the toolbox to disable the the HTTP cache when it's open, the RSS manager saves the settings right away when I click OK to confirm changes. 

edit: clarification.

**Comment by stickz** [comment]
@Antorell Could you post some screenshots to document this issue? Also, try the latest master commit?

**Comment by Antorell** [comment]
I fixed the issue by disabling the caching in cachedecho.php 
https://github.com/Novik/ruTorrent/blob/1bcdd30f1bb5ffc247833daf7c4b328d20789f7d/php/utility/cachedecho.php#L14-L16

replaced by:
```
			header('Expires: 0');
			header('Pragma: no-cache');
			header('Cache-Control: no-store, must-revalidate ');
```

I'll try to make a screenshot or gif later, but there isn't much to see. When I edit or create a new filter in the RSS manager and click OK to validate the configuration changes and close the RSS manager. If I re-open the RSS Manager, the changes don't show up. It shows exactly the same filter as  when I first opened the RSS manager before I change/add/edit anything, and I need to restart the whole browser or clear the cache to see the changes.

**Comment by Antorell** [comment]
![Rss_manager_1](https://user-images.githubusercontent.com/25066224/215347935-bb9036bb-abdf-4a2a-8f46-bd7858978cb5.gif)

**Comment by Antorell** [comment]
And here is the RSS manager working as expected when caching is disabled
![Rss_manager_2](https://user-images.githubusercontent.com/25066224/215348164-1c2a1446-9cb8-4071-99fa-d37c46538548.gif)

**Comment by Antorell** [comment]
It still happen with the latest commit. All the tries were done on the latest commit from today

This is when I edit a filter, to show it's not an issue with creating new filters. 
![Rss_manager_3](https://user-images.githubusercontent.com/25066224/215348608-9d6b81f6-2b80-4b90-80cd-6ffd6f020a40.gif)

**Comment by stickz** [comment]
Thanks for the demo GIF. Please try https://github.com/Novik/ruTorrent/commit/3722b0a1f8a46f321a1c7aaa30d186f3bd1e3780. This should be a proper fix.

**Comment by Antorell** [comment]
I just tried and the RSS manager works as expected now. Thanks.

If you could add a switch to enable/disable caching it would be awesome. On my seedbox it makes literally no difference when caching is disabled compared to enabled, and I'd rather run rutorrent with the cache disabled without having to edit non-config .php files.

**Comment by stickz** [comment]
I don't think there is anything left with web browser caching enabled. As long as `$do_diagnostic` is set to true. Just remember to clear your web browser cache when upgrading to the latest commit and you should be fine. I eliminated almost all caching issues.

There is different types of caching. For instance on the web server, it's required to save your RSS filters and WebUI settings. 

Please continue to do an awesome job reporting bugs! It's having a big impact on the torrent community. We need people like you testing beta changes, to keep improving the web client. Significant RSS improvements are coming to version 4.1 next month.
