### ISSUE TITLE
Can we remove git metadata from release tarballs?

### ISSUE THREAD

**Issue by henning-schild** [Novik/ruTorrent#2440]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser ...

### Tell us how you installed ruTorrent

NA

### Describe the bug

The release tarballs contain version control metadata and github stuff, when creating packages for a distro one has to remove those because they are not needed for the application to function.

Instead of everybody having to decide to ship that anyhow, or remove it ... it would be nice if such stuff would simply not be in a release.

Note that when removing it some directories will become empty, which means distro packaging might skip them. Which in turn means that the application might not work as expected. It can not deal with the the share/ tree missing because it does not `mkdir` on missing dirs.

### Steps to reproduce

fetch i.e. https://github.com/Novik/ruTorrent/archive/refs/tags/v4.0-stable.tar.gz

```
$ find -iname ".git*"
./.github
./.gitmodules
./conf/users/.gitignore
./share/settings/.gitignore
./share/torrents/.gitignore
./share/users/.gitignore
./tests/.gitignore
```

put that all in a package ... you ship too much stuff that is not needed

remove it ... the application does not work as expected because missing dirs will not be created on demand

One has to remove and make sure to include empty dirs into the package. see https://github.com/gentoo/gentoo/pull/29010 the commit removes .gitignore s and later has to `keepdir` because missing folders cause problems

### Expected behavior

Would be nice if the tarballs would be free of such not needed metadata, and the application able to handle missing empty directories and just create them.

### Additional context

NOTE: No issue template really matched my case, seems a little restrictive

**Comment by stickz** [comment]
I'll take a look when I get a chance, to see if we can make ruTorrent easier to ship with Linux Distributions. If someone wants to create a pull request to add missing directories, they are more than welcome to. See [FileUtil](https://github.com/Novik/ruTorrent/blob/master/php/utility/fileutil.php) class for existing functionality.

I can't get around to doing this right away because I'm working on releasing version 4.0.1 stable for some upstream fixes.

**Comment by sertonix** [comment]
This issue still exists (at least with the `.gitignore` files). Stale bot shouldn't have closed this.
