### ISSUE TITLE
Clearly see the version of ruTorrent

### ISSUE THREAD

**Issue by castillo92** [Novik/ruTorrent#2447]
### Is your feature request related to a problem?

In the last update, hotfix 4.0.1, the version label has not been updated.

### Describe the solution you'd like

We could found in Tab title and with Crtl+F1. 

Could be also in the Log tab, for example: WebUI started. Version x.x.x
Or near to rTorrent version in the bottom of the webpage

**Comment by stickz** [comment]
We will update this when version 4.0.2 is released. This is planned due to additional bug fixes.

**Comment by castillo92** [comment]
Great Stickz, happy to know you keep in mind it.

Do you want to close this issue now or wait till the next release?

**Comment by stickz** [comment]
Resolved with latest v4.0.2 release. https://github.com/Novik/ruTorrent/releases/tag/v4.0.2
