### ISSUE TITLE
Most Plugins not loading

### ISSUE THREAD

**Issue by MarkusLange** [Novik/ruTorrent#2452]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Browser/ruTorrent Version
Firefox 110.0 64bit / Edge 110.0.1587.50
ruTorrent: v4.0.1-hotfix

works not:
PHP 8.1.7-1ubuntu3.2
on Ubuntu Kinetic Kudu 22.10

PHP 8.1.2-1ubuntu2.10
on Ubuntu  Jammy Jellyfisch 22.04

works on:
Firefox 110.0 64bit / Edge 110.0.1587.50
ruTorrent: v4.0.1-hotfix

PHP 7.4.33
on Debian bullyeye 11.6

PHP 8.2.3
on Debian bullyeye 11.6

PHP PHP 7.4.3-4ubuntu2.17
on Ubuntu Focal Fossa 20.04

### Give us detailed steps to reproduce the error

complete identical installation on both ubuntu and debian, on ubuntu nearly 70% of the plugins not loading

### Tell us the error message

Only a few plugins did load
![grafik](https://user-images.githubusercontent.com/1971238/220046418-3ae72446-3a40-487d-b303-ae3c6a3b1735.png)
all other did not load

**Comment by stickz** [comment]
@MarkusLange How did you install ruTorrent? Are there any errors in the "Log" tab?

**Comment by MarkusLange** [comment]
I install it with the help of a script.
only this error:
[21.02.2023 00:19:45] WebUI started.
[21.02.2023 00:19:46] Keine Verbindung zu rTorrent. Überprüfe ob es wirklicht läuft. Überprüfe $scgi_port und $scgi_host Einstellungen in config.php und scgi_port in der rTorrent Konfigurationsdatei.
but rpc nor httprpc are loaded.

working:
![grafik](https://user-images.githubusercontent.com/1971238/220213206-290159e8-fb92-4278-ba76-b3627f689132.png)
not working:
![grafik](https://user-images.githubusercontent.com/1971238/220213246-c9d47bdf-8d99-42b8-89a7-3e9da94141b2.png)
both with the PHP reposity from [Ondřej Surý](https://launchpad.net/~ondrej)

**Comment by stickz** [comment]
That error is the reason why it's not working. Ensure the PATH variable for PHP is properly set.

**Comment by MarkusLange** [comment]
little update:
on ubuntu:
if I set the rpc on open.port and the rutorrent config also it works
rtorrent.rc
`network.scgi.open_port = 127.0.0.1:5000`
/conf/config.php
`$scgi_port = 5000;`
`$scgi_host = "127.0.0.1";`
but if I use open.local it's not working
rtorrent.rc
`network.scgi.open_local = (cat,(session.path),rpc.socket)`
/conf/config.php
`$scgi_port = 0;`
`$scgi_host = "unix:///home/ubuntu/rtorrent/.session/rpc.socket";`

the apache vhost conf also may I miss something
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/ruTorrent-4.0.2
        <Directory "/var/www/ruTorrent-4.0.2">
                AllowOverride None
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/rutorrent_error.log
        CustomLog ${APACHE_LOG_DIR}/rutorrent.log vhost_combined
</VirtualHost>
```

**Comment by liaralabs** [comment]
Is your www-data user able to read the socket? There may be permission issues on the way to the rpc.socket you've created. But you're correct, this is likely not an issue with ruTorrent in particular.

Generally speaking, home directories aren't a great place for unix socket that need to be read by other users. `/var/run`  is sort of the de-facto place for these ephemeral objects that only live as long as the application does.

```
network.scgi.open_local = /var/run/liara/.rtorrent.sock
schedule2 = chmod_scgi_socket, 0, 0, "execute2=chmod,\"g+w,o=\",/var/run/liara/.rtorrent.sock"
```

This creates the socket, then sets the group to have write permissions and "other" no permissions -- www-data is in the group for liara so the www-data user can access this socket without issue.

**Comment by MarkusLange** [comment]
Some exhausting days, at first you are right @liaralabs the socket has to be in `/run` (for my explain the rtorrent put all in a compact stucture usually inside the users homedir, including the socket) also as far as I can evaluate the best place for samba/ftp/torrents is the `/srv` folder not the users home, but now to the intersting part Ubuntu had until 22.04 755 for home and now 750 debian has still 755. So everything was fine until Ubuntu makes a move. So thanks @liaralabs for the hint.

**Comment by stickz** [comment]
Did you find a solution to your problem @MarkusLange?

**Comment by MarkusLange** [comment]
Yes @stickz I describe it, mostly explained by @liaralabs allready
My Solution (I use the [rtorrent Template](https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template), and Apache Server)
A.
is to set everything including home to 755 and give the user www-data group permissions to the rtorrent user, but this will break the privacy so it's the wrong way, we will not talk about it again.
B.
is a bit more complex
1. add the group www-data to the user who runs rtorrent
2. create a `/usr/lib/tmpfiles.d/rtorrent.conf` because `/run` will be cleaned on startup
```
#Type Path            Mode UID      GID        Age Argument
d     /run/rtorrent   0775 www-data www-data   -   -
```
3. change this lines inside .rtorrent.rc
```
#network.scgi.open_local = (cat,(session.path),rpc.socket)
#execute.nothrow = chmod,770,(cat,(session.path),rpc.socket)
```
to
```
network.scgi.open_local = /run/rtorrent/rpc.socket
execute.nothrow = chmod,776,/run/rtorrent/rpc.socket
```
4. change this lines inside the config.php from ruTorrent
```
        $scgi_port = 5000;
        $scgi_host = "127.0.0.1";
```
to
```
        $scgi_port = 0;
        $scgi_host = "unix:///run/rtorrent/rpc.socket";
```
5. move the basedir to `/srv` like `/srv/rtorrent/` and set the group to www-data, if not the rutracker_check will not work it needs access to the sessiondata.

I hope I didn't forget nothing but I will all integrate in this [script](https://github.com/MarkusLange/r_ru-torrent-install-script) for the better use.

**Comment by stickz** [comment]
Excellent. Thanks for posting your solution. I'm going to close this issue report off now, since it's been resolved.

**Comment by MarkusLange** [comment]
@PhantomEight max I habe a solution for you https://github.com/MarkusLange/r_ru-torrent-install-script

**Comment by MarkusLange** [comment]
> I get these issues with plugins after installing rtorrent+rutorrent using this script:
> [04.06.2023 11:54:01] _cloudflare: Plugin will not work. Webserver user can't access external program (python). [04.06.2023 11:54:01] rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory (/home/jesper/.rtorrent-session/). [04.06.2023 11:54:01] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg). [04.06.2023 11:54:01] spectrogram: Plugin will not work. rTorrent user can't access external program (sox).

I'm guessing this is a permissions issue but I have no idea how to fix this.

@Jespertnh if you are to be patient enough to install it on an fresh system try this https://github.com/MarkusLange/r_ru-torrent-install-script

**Comment by MarkusLange** [comment]
https://github.com/Bercik1337/rt-auto-install/issues/47#issue-1773315612

@thatandrewguy you can try [this](https://github.com/MarkusLange/r_ru-torrent-install-script) it supports Bookworm

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee

May you can take a look at this https://github.com/MarkusLange/r_ru-torrent-install-script supports rutorrent updates

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

What version is your RuTorrent?

**Comment by MarkusLange** [comment]
It will allways be the latest, and as I mentioned upgrading is allways possible
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/5c31b386-5d63-4ddc-9e0b-939257227187)

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

How will it work if version v4.2.9 comes out? I will have installed v4.2.6!!!

**Comment by MarkusLange** [comment]
> @MarkusLange
> 
> How will it work if version v4.2.9 comes out? I will have installed v4.2.6!!!

Easy, you use this point (marked blue):
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/dcb836dc-6d48-4b08-a4de-f24f73cc7f8e)
follow the directions and the script will do the rest, it will install your selected ruTorrent version and will create and edit all needed files to use the newly installed version

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 


Thank you for your patience with me. I am from Brazil. I will test your script.

**Comment by MarkusLange** [comment]
> @MarkusLange
> 
> Thank you for your patience with me. I am from Brazil. I will test your script.

@GitHub-BumBleBee

You are wolcome, i hope it helps

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

The installation went well!! But I can't change the folder where the torrents are saved

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 

Ah yeah, the use is a bit ruff, there is link how to use it:
https://unix.stackexchange.com/questions/249965/how-to-navigate-in-dialogs-file-and-directory-selectors

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange I want to change this directory

https://i.postimg.cc/gkTnTd1D/Captura-de-tela-2023-09-19-040929.png

I want it to stay like this: /arq.upload/BUMBLEBEE

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange I don't want anything else added to the directory.

I don't want to save any more configuration in the directory.

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange If you don't understand something, please let me know.

**Comment by MarkusLange** [comment]
> /arq.upload/BUMBLEBEE

I did'nt understand this " /arq.upload/BUMBLEBEE" is that a folder?

You have an link to /srv/rtorrent/... inside the home of your user!
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/dc5f9a9e-08c0-4ba0-89c4-ce3c0e294d68)
the cyan one this will lead you directly to the folder

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

Friend, that path would be a folder where my files are located.

I need to configure rutorrent to save it inside the folder.

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

Remembering my friend that I only want to leave my files in the folder and nothing else.

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 
Go this way:
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/35893e13-e089-4ee4-9f76-a735486fc001)
then this
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/b2c69d97-a592-4e63-97d7-e269c92030da)
and set the folder direct (green cursor)
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/9f457283-6c83-4ce6-9f5a-7850567acd6b)
and remove this files direcly inside the folder  /arq.upload/BUMBLEBEE:
*.libtorrent_resume
*.rtorrent
so that rtorrent/rutorrent grep the files again

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I do what he asked but he doesn't do it...

https://i.postimg.cc/fLGKtkxH/Captura-de-tela-2023-09-19-070037.png

https://i.postimg.cc/FHHjK0Mr/Captura-de-tela-2023-09-19-070235.png

The location looks like this: /arq.upload/BUMBLEBEE/rtorrent/download

I don't want.
I want it like this: /arq.upload/BUMBLEBEE

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 
Ah I understand you, but you won't get it this way rtorrent used to have several folder
![grafik](https://github.com/Novik/ruTorrent/assets/1971238/6a3aec3f-5dcf-4c73-bc0f-35817ee03404)
.session contains the sessiondata, rtorrent needs to track the data by itself
download the downloads itself when finalized
log the logfiles usefull if something went wrong
watch where you can drop torrent-files you want to download
and the .rtorrent.rc file contains the configuration

a . in front means the file oder folder are hidden

with the Script von Bercik you had a hidden folder .rtorrent-session for the session data und Downloads for the download, Bercik script doesn't support the log folder nor the option to drop torrent files in a folder to autoload them I do, you will find out this advantage isn't as bad as it seems to be with the added folders and structure in exchange

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

You can't change.
Leave the files in a separate folder.
And I leave my files in another.
Please change!

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange Your work was impeccable, show, congratulations!


I need this change. Can you do it for me?

**Comment by MarkusLange** [comment]
I thinking about a solution can you post this file for me: /etc/samba/smb.conf
as your screenshot shows you use an samba folder from you Windows PC

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange Yes, I use

https://drive.google.com/drive/folders/1NlkkwjDzlv7taUYey_Vqx9oBGRamP9Pf?usp=sharing

Help me like power. Please

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 
Strange thing there are no directories inside the smb.conf how do you get your folder to your Windows PC isn't that samba?

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange I'm from Brazil and I use the translator to translate from my language to yours.

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I click on the folder options and then go to share. Then in Windows I locate the folder using the IP of the other Notebook. I fixed the folder in Windows. And using that shortcut I send my files.

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 
Okay, move the torrent basedir back to /srv and then enter this to the command line:
`ln -s /srv/rtorrent/download/ /arq.upload/BUMBLEBEE/`

so you get only the folder download inside BUMBLEBEE

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange Just a question, what time is it now?


https://i.postimg.cc/Nfm5LGYF/Captura-de-tela-de-2023-09-19-10-32-29.png


https://i.postimg.cc/RCn0bCWd/Captura-de-tela-de-2023-09-19-10-34-01.png

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange If this situation cannot change, I will go back to using do Bercik1337


Would you accept 1 payment for the change?

**Comment by MarkusLange** [comment]
> @MarkusLange
> 
> Would you accept 1 payment for the change?

I won't accept payment in any way, but I can help you to get this working, so show me the folder from the terminal so I can see what happend there and if there allready any softlinks

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

https://i.postimg.cc/QMfdTHHg/Captura-de-tela-de-2023-09-19-10-52-27.png

https://i.postimg.cc/gkbLdLRr/Captura-de-tela-de-2023-09-19-10-53-22.png

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I can generate or do whatever my system needs. Anything!

**Comment by MarkusLange** [comment]
> @MarkusLange
> 
> https://i.postimg.cc/QMfdTHHg/Captura-de-tela-de-2023-09-19-10-52-27.png
> 
> https://i.postimg.cc/gkbLdLRr/Captura-de-tela-de-2023-09-19-10-53-22.png

I don't see why this shoudn't work

**Comment by jakobbg** [comment]
> @MarkusLange
> 
> https://i.postimg.cc/QMfdTHHg/Captura-de-tela-de-2023-09-19-10-52-27.png
> 
> https://i.postimg.cc/gkbLdLRr/Captura-de-tela-de-2023-09-19-10-53-22.png

Seriously? This smells a bit like a troll to me… :-)

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

One question. I use 2 disks. Being 1 for the Linux Mint 21.02 system. And 1 for the files.
The /arq.upload/BUMBLEBEE folder is on disk 2, 4TB

**Comment by MarkusLange** [comment]
> > @MarkusLange
> > https://i.postimg.cc/QMfdTHHg/Captura-de-tela-de-2023-09-19-10-52-27.png
> > https://i.postimg.cc/gkbLdLRr/Captura-de-tela-de-2023-09-19-10-53-22.png
> 
> Seriously? This smells a bit like a troll to me… :-)

@jakobbg
I know what you mean, try to ignore

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 


What to do? On 4TB disk 2, I have 2TB of personal files.

**Comment by MarkusLange** [comment]
try to create the softlink with sudo rights

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I already tried, and it didn't work. If it doesn't work for you to change this suggestion. I'll leave it alone. And stop using ruTorrent!

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I don't want to be disrupting anyone's life. Thank you for your help.

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange I will remove everything

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 

Don't you have anyone around who can set a softlink to the folder by hand? Or the other way around share the folder download like you did it with the folder BUMBLEBEE so you will see both on Windows

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

I know how to do what I said. But what I need now would be to configure rutorrent for the location I choose. /arq.upload/BUMBLEBEE

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange 

It worked out!!!
I am really happy.
Thank you for everything.
May God bless you always.

**Comment by MarkusLange** [comment]
@GitHub-BumBleBee 

Finally. What a hard birth.

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange Beauty
