### ISSUE TITLE
Throttle: Plugin failed to start

### ISSUE THREAD

**Issue by GH0STDATA** [Novik/ruTorrent#2455]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 110.0
ruTorrent: v4.0.2
PHP: PHP 8.0.12
OS: Ubuntu 20.04 LTS

### Tell us how you installed ruTorrent

https://hub.docker.com/r/binhex/arch-rtorrentvpn/
https://github.com/binhex/arch-rtorrentvpn

### Describe the bug

I'm getting a generic error that the throttle plugin is failing to start.

### Steps to reproduce

1. Install rtorrentvpn Docker image.
2. log into web UI.

### Expected behavior

Throttle plugin should enable itself and work.

### Additional context

It worked on ruTorrent v3.10 perfectly fine before I upgraded to the v4.02 version, so there must have been some changes that caused it to break along the way. Can't seem to figure out what that change could be. All other plugins work with no issues except throttle.

**Comment by stickz** [comment]
@GH0STDATA Yes, there is breakage in v4. You must upgrade your entire ruTorrent installation.

**Comment by GH0STDATA** [comment]
I'm confused, can you elaborate? I've already upgraded ruTorrent from v3.10 to v4.02. Are you referring to upgrading rtorrent as well? I'm on 0.9.6/0.13.6.

**Comment by stickz** [comment]
No, I'm referring to ruTorrent. Clear your web browser cache. Ensure that you've carefully upgraded everything. Version 3 and 4 are not backwards compatible. A full installation upgrade is required. Backup all your files and copy everything over.

**Comment by stickz** [comment]
It also looks like your docker image is not longer maintained. I would recommend selecting an alternative installation.

Crazy max has a very good one.
https://github.com/crazy-max/docker-rtorrent-rutorrent

There's also swizzin, if you want to move outside a docker container and have other utilities like a VPN.
https://github.com/swizzin/swizzin

**Comment by nakooe** [comment]
i have a same problem   i have try with ct and vm on Proxmox with the fresh setup 

![grafik](https://user-images.githubusercontent.com/100241989/221384867-3a81ad98-1f18-4487-aa61-a374a824cdd2.png)

**Comment by GH0STDATA** [comment]
> No, I'm referring to ruTorrent. Clear your web browser cache. Ensure that you've carefully upgraded everything. Version 3 and 4 are not backwards compatible. A full installation upgrade is required. Backup all your files and copy everything over.

> It also looks like your docker image is not longer maintained. I would recommend selecting an alternative installation.
> Crazy max has a very good one. https://github.com/crazy-max/docker-rtorrent-rutorrent
> 
> There's also swizzin, if you want to move outside a docker container and have other utilities like a VPN. https://github.com/swizzin/swizzin

@stickz I'm aware that the docker image is no longer maintained, but it is stable and works fine currently. The only plugin that is throwing an error is throttle. Everything else works perfectly, so this leads me to believe that it has nothing to do with the installation process or the docker image I'm using. I do plan on switching over to either my own custom docker image, or the one you just linked with a gluetun VPN setup. 

It looks like @nakooe also mentioned that the plugin still isn't working even with a fresh installation.

**Comment by nakooe** [comment]
i have resolve this problem    https://github.com/arakasi72/rtinst/issues/614    i have copy the php config 
in to the /var/www/rutorrent/conf/config.php  and restart.     https://raw.githubusercontent.com/stickz/rtinst/b3adc6a3c9df181934cd477eb2882e3d22c04cb4/conf/ru.config

**Comment by stickz** [comment]
@GH0STDATA It's not the plugin. The docker image is not setup properly for version 4.

> i have resolve this problem [arakasi72/rtinst#614](https://github.com/arakasi72/rtinst/issues/614) i have copy the php config in to the /var/www/rutorrent/conf/config.php and restart. https://raw.githubusercontent.com/stickz/rtinst/b3adc6a3c9df181934cd477eb2882e3d22c04cb4/conf/ru.config

I haven't had a chance to update that yet. You should get the latest config from here instead. 
https://github.com/Novik/ruTorrent/blob/master/conf/config.php

**Comment by GH0STDATA** [comment]
> i have resolve this problem [arakasi72/rtinst#614](https://github.com/arakasi72/rtinst/issues/614) i have copy the php config in to the /var/www/rutorrent/conf/config.php and restart. https://raw.githubusercontent.com/stickz/rtinst/b3adc6a3c9df181934cd477eb2882e3d22c04cb4/conf/ru.config

This fixed it for me as well. There were some missing variables that were newly added to `config.php`, including a variable that was specifically created for the throttle plugin. Thank you!
