### ISSUE TITLE
Regex parsing of RSS description issue, <br> are replaced by "" breaking the use of \b for some words 

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2456]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Firefox 110/Edge110
rutorrent 4.02
PHP 8.1

### Give us detailed steps to reproduce the error

When parsing the description of a RSS feed, using  the regex's \b word boundary's anchor to flag the end of a word that is also the last word of a line in the description breaks the matching. The same regex rules works perfectly fine in any other regex editor parsing the whole description. Rutorrent doesn't seem to replace the `<br>` tag correctly and to get the \b word boundary's anchor to flag the end of a word that's also the last word of a line, you need to stick the first word of the next line to the end of the word you want to match.

### Tell us the error message

To match the group with a given number of completed dl, says below 10, of a description that would look like this:
```
File: Boob Zombies 2033 1080p Blu-ray AVC DTS-NOGROUP
Size: 3 TB
Completed: 2
Seed: 1
```
Normally something like; `/-(:?Bob|nogroup)\b.+?\bcompleted:\s\d\b/i ` would match the NOGROUP with a completion under 10. 
https://regex101.com/r/LJWmvB/1 (rutorrent doesn't need the /s regex option as the unparsed description is just one line with `<br>` tags) 

But that doesn't work in rutorrent as it seems to replace the `<br>` and other tags with nothing "". 

Something like:
`<strong>File</strong>: Boob Zombies 2033 1080p Blu-ray AVC DTS-NOGROUP<br><strong>Size</strong>: 3 TB<br><strong>Completed</strong>: 2<br><strong>Seed</strong>: 1<br>`

becomes:
`File: Boob Zombies 2033 1080p Blu-ray AVC DTS-NOGROUPSize: 3 TBCompleted: 2Seed:  1`

And needs something like  `/-(:?Bob|nogroup)Size\b.+?completed:\s\dSeed\b/i ` to match end of word correctly. 
https://regex101.com/r/LJWmvB/3

I didn't check if it's an issue with the recent changes or a much older issue as I don't have access to the machine I use to test rtorrent scripts and stuff to try with an old version of rutorrent. I tried to set the `Sanitize.Config.` to RELAXED, but it didn't change anything.

**Comment by stickz** [comment]
@Antorell Could you give ruTorrent `v4.1.5` a try and see if this resolves your problem? We rewrote the RSS parsing in `v4.1`.
https://github.com/Novik/ruTorrent/releases/tag/v4.1.5

**Comment by Antorell** [comment]
Awesome. I'll give it a try later this evening.

**Comment by Antorell** [comment]
@stickz I didn't really have the time to test but a quick try showed that something like `/S0\dE\d{2}\b.+?Completed:\s(\d|1[0-5])/i` that works with rutorrent 4.04, doesn't work with 4.15. It seems to be related to the colon `:`, if I try `/S0\dE\d{2}\b.+?Completed:/i` in 4.15 it doesn't pick anything when it should pick all the TV episodes. If I remove the colon`:` at the end of Completed, rutorrent 4.15 picks up the TV episodes.

**Comment by TrimmingFool** [comment]
@Antorell Before, tags in the description were removed. Now, the regex is applied directly on the title + raw content of the description + link.

https://github.com/Novik/ruTorrent/blob/145529129c2a82939042eadd2c443daa9fdcbd71/plugins/rss/rss.php#L480-L498

@stickz In my view, matching the raw description content is the most flexible and practical solution. Especially, since, now, there is a `>Raw` button in the top-right corner of the RSS content view. 

Btw, why do we trim spaces when matching the description `$temp = preg_replace("/\s+/u"," ", $rssItem['description']);`? I think, if it is not necessary or expected by the user, it should be removed.

**Comment by Antorell** [comment]
@TrimmingFool if now I need to do `/Completed\<\/strong\>:\s(?:\d|1[3-9])\b/i` to match something, pardon me to say it but it's a pointless fix. I'd rather have to deal with tags being replaced with nothing that tags in the raw XML of the RSS. 

The RSS I parse look like this
```
The XML of the description of the RSS
`<description><![CDATA[<p><strong>File Name</strong>: Bondage Linux S01E11 1080p WEB-DL AAC H.264-UNIX<br><strong>Type</strong>: TV-Show<br><strong>Size</strong>: 1.8 GB<br><strong>Uploaded</strong>: May 3, 2023<br><strong>Seed</strong>: 14 | <strong>Leech</strong>: 1 | <strong>Completed</strong>: 12<br><strong>Uploader</strong>: UNIX</p><p><strong>Rip Type</strong>: WEB-DL<br><strong>Video Quality</strong>: 1080p<br><strong>Video Resolution</strong>: 1920x1080</p><p><strong>TV Show</strong>:  Season: 6 Episode: 6  <p><a href="https://kernel.org/bondate-linux" title="Bondage Linux (2023)">Bondage Linux (2023)</a><br>It is possible to use Linux without any non-free firmware binaries, but usually at the cost of rendering a lot of hardware inoperable.Furthermore, many devices that do not require a firmware blob during driver initialization simply already come with non-free firmware preinstalled on them.If your goal is to run a 100% free-as-in-freedom setup, you will often need to go a lot further than just avoiding loadable binary-only firmware blobs.<br><br>TheMovieDB: <a href="https://anon.to?https://www.themoviedb.org/xxxxx" target="_blank">999</a><br>TheTVDB: <a href="https://anon.to?https://www.thetvdb.com/xxxxx" target="_blank">999</a><br>Runtime: 1h 29m 59s<br>Subtitles: English<br></p>]]></description>
`

**Comment by TrimmingFool** [comment]
@Antorell Note that the string content of the rss `<description>` is up to the feed author.
Your proposal seems to be "match the text as it is displayed":
- `<br>`, `<h1>`, `[center]`, ... -> `"\n"`
- `<strong>`, `<i>`, `[i]`, `<b>`, `[b]`, `<a href="...">`, ... -> `""`
as this simplifies writing regular expressions.

This transformation could be added at this line:
https://github.com/Novik/ruTorrent/blob/145529129c2a82939042eadd2c443daa9fdcbd71/plugins/rss/rss.php#L487

I am not interested in adding this, myself, but would you merge something like this? @stickz

**Comment by stickz** [comment]
> @stickz I didn't really have the time to test but a quick try showed that something like `/S0\dE\d{2}\b.+?Completed:\s(?:\d|1[0-5])/i` that works with rutorrent 4.04, doesn't work with 4.15. It seems to be related to the colon `:`, if I try `/S0\dE\d{2}\b.+?Completed:/i` in 4.15, it doesn't pick anything when it should pick all the TV episodes. If I remove the colon`:` at the end of Completed, rutorrent 4.15 picks up the TV episodes.

The colon should be escaped for the regex expression, if it's inside the description of the RSS feed. I would consider this a bug.

**Comment by Antorell** [comment]
> @Antorell Note that the string content of the rss `<description>` is up to the feed author. Your proposal seems to be "match the text as it is displayed":
> 
> * `<br>`, `<h1>`, `[center]`, ... -> `"\n"`
> * `<strong>`, `<i>`, `[i]`, `<b>`, `[b]`, `<a href="...">`, ... -> `""`
>   as this simplifies writing regular expressions.
> 
> This transformation could be added at this line:
> 
> https://github.com/Novik/ruTorrent/blob/145529129c2a82939042eadd2c443daa9fdcbd71/plugins/rss/rss.php#L487
> 
> I am not interested in adding this, myself, but would you merge something like this? @stickz

@TrimmingFool  The "match the text as displayed" is the old behavior, I don't understand why it's so important to change it. I'm gonna stick with 4.04 I guess. I really don't have the time to redo all my regexes or deal with rutorrent ant-sized regex edit boxes. 

@stickz  I've never had to escape the colon on rutorrent, and unless I missed something or rutorrent does something I'm unaware of, it's not a character that does anything outside non-capturing groups (?:) or character classes [[:bob:]].
![Screenshot (70)](https://user-images.githubusercontent.com/25066224/236082481-08716056-9800-46c3-a865-bbe2cf06d174.png)
https://regex101.com/r/NyC8q7/1

**Comment by TrimmingFool** [comment]
> I don't understand why it's so important to change it.

@Antorell You could also bring back the `removeTegs` function and call it here:

https://github.com/Novik/ruTorrent/blob/cba1bfc11cc8ebc8a3c65d1d37cfbd4d6261a39e/plugins/rss/rss.php#L602

And it would be the same behavior as before: `<br>` -> `""`


> I really don't have the time to redo all my regexes...

Couldn't you just use `.*?` (or  `[^:LTCUS]*?`) instead of `\b`?

**Comment by Antorell** [comment]
Using a general wildcard .* or .+ to skip the XML tags and if the regex doesn't match the number of completed  torrent, it picks the next number that will match -> https://regex101.com/r/NyC8q7/4. If ` [^:LTCUS]*?` is added at the end to replace the boundary \b, it'll match any number instead of matching a single digit number or the range I want -> https://regex101.com/r/NyC8q7/6

` [^:LTCUS]*?`, even shortening it to `[^:U]*?` is almost the size as matching the tag with escapes` \<\/strong\>`, so there's little to no point in using it here.  https://regex101.com/r/NyC8q7/5

I don't see any point in updating to 4.15 if it's to spend time to turn it back to the old behavior or get a headache updating my regexes to match the new behavior. The edit box is tiny and it's easy to mess up when I quick edit regex, like yesterday I didn't see the regex to match HDR\HDR10 `\b(?:v2|HDR\d+?|DV)\b` files was missing a `+` until I post a screenshot. 

 Version 4.04 works fine, I'm just gonna stay on that for now.

**Comment by TrimmingFool** [comment]
I see no problem with: `/Completed.*?:\s(\d|1[3-9])([^\d]|$)/` (no DOTALL and no IGNORECASE)

And I also see no problem with your proposal.

**Comment by Antorell** [comment]
> I see no problem with: `/Completed.*?:\s(\d|1[3-9])([^\d]|$)/` (no DOTALL and no IGNORECASE)
> 
> And I also see no problem with your proposal.

Let's say, here `(\d|1[3-9])` I want it to match a single digit or anything between 13 and 19 max completed, your regex will match any single digit or anything between 13 and 19. However without the boundary, at 12 or 20, it'll hop to the next possible match. 
Here is a : 6 in the episode number a couple of lines below that has nothing to do with the number of time the dl has been completed. 

/Completed.*?:\s(\d|1[3-9])([^\d]|$)/ -> https://regex101.com/r/NyC8q7/11
vs
` /Completed\b:\s(\d|1[3-9])\b/ `https://regex101.com/r/NyC8q7/12

https://www.regular-expressions.info/wordboundaries.html

**Comment by Antorell** [comment]
@TrimmingFool my complain isn't really about the regex boundaries, they work with punctuation (like /\ba\b/ will match a<br> but not aa -> https://regex101.com/r/NyC8q7/15), it's more that it fixed an issue https://regex101.com/r/NyC8q7/14 but changed the old behavior to something else -> https://regex101.com/r/NyC8q7/13
