### ISSUE TITLE
The 'Time,h' option from the 'Ratio group' plugin is missing?

### ISSUE THREAD

**Issue by steve51184** [Novik/ruTorrent#2457]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Chrome 111
ruTorrent: v4.0.0
PHP: PHP 7.3
OS: Debian 10

### Tell us how you installed ruTorrent

Swizzin

### Describe the bug

Since upgrading from 3.1 to 4.x the 'Time,h' option from the 'Ratio group' plugin is missing?

Is it dependent on other plugins?

**Comment by stickz** [comment]
Please try installing the latest changes from the development branch of swizzin. Your ruTorrent version is outdated.

`git clone -b develop https://github.com/swizzin/swizzin`
`sudo bash swizzin/setup.sh --local`

**Comment by steve51184** [comment]
I'm not 100% sure about moving my whole production server over to a development branch just for a small bug.. I'm also not sure if 4.0.1 or 4.0.2 would fix it..

One thing I did do was remove unneeded plugins.. could that be an issue? Does the ratio plugin depend on another for that seeding time 'Time,h' option?

**Comment by steve51184** [comment]
Sorry didn't mean to mark as closed

**Comment by steve51184** [comment]
I'm not 100% sure about moving my whole production server over to a development branch just for a small bug.. I'm also not sure if 4.0.1 or 4.0.2 would fix it..

One thing I did do was remove unneeded plugins.. could that be an issue? Does the ratio plugin depend on another for that seeding time 'Time,h' option?

**Comment by steve51184** [comment]
I'd also like to point out I had this problem on v3.1 manual install so it's not related to swizzin and probably a plugin I deleted which the Ratio Group plugin needs..

![Screenshot_20230303-134644](https://user-images.githubusercontent.com/12534098/223149659-5e11b0ae-087d-478d-a488-d4ad381946cd.jpg)

**Comment by stickz** [comment]
@steve51184 You are running an old beta version of ruTorrent on swizzin. This ratio group plugin was fixed in stable. It's highly recommended to upgrade to `v4.0.2` once the swizzin development branch becomes stable.

There's nothing we can do investigate this problem, until your version matches our latest stable production release.

**Comment by steve51184** [comment]
I found the problem I had deleted the seedingtime plugin so I just grabbed it and it's all working fine now

I understand I'm on a depreciated version but I have to want on the swizzin team to move to the stable branch.. they ironically have the beta version in stable and the stable in the beta/develop branch 🤷🏻‍♂️
