### ISSUE TITLE
rutorrent VPN

### ISSUE THREAD

**Issue by d4nm0** [Novik/ruTorrent#2460]
### Is your feature request related to a problem?

I would like to know if it is possible, or if in the near future it is planned to be able to configure a vpn from ruttorent

### Describe the solution you'd like

in the settings have a vpn location

**Comment by stickz** [comment]
No, ruTorrent is a remote control web client for rTorrent. It's not feasible to do this.

Your next best option is to use iptable rules on wireguard. I posted an example how to do this here: 
https://github.com/pia-foss/manual-connections/issues/62#issuecomment-748414682

**Comment by dalilgriffith** [comment]
You could hypothetically connect to rutorrent on VPN interface like OpenVPN. The seeded traffic would not be handled by the VPN, but the command & control traffic between your PC and the site would be.

**Comment by stickz** [comment]
> You could hypothetically connect to rutorrent on VPN interface like OpenVPN. The seeded traffic would not be handled by the VPN, but the command & control traffic between your PC and the site would be.

This is better done through the cloudflare plugin.
