### ISSUE TITLE
Rutracker check plugin not work

### ISSUE THREAD

**Issue by bend-er** [Novik/ruTorrent#2470]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 111.0.1
PHP: PHP 7.4.24
OS: Ubuntu 20.04.3 LTS

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent

### Describe the bug

Rutracker_check not work

### Additional context

I think because api.rutracker.org no longer resolving and unavailable

**Comment by bend-er** [comment]
New address http://api.rutracker.cc/.

**Comment by stickz** [comment]
Please give https://github.com/Novik/ruTorrent/commit/0f1c1e25ced4ddb04892e7d5b8c05537a17ae866 a try. It should be fixed.
