### ISSUE TITLE
[Feature] BitTorrent v2 Support

### ISSUE THREAD

**Issue by hbednar** [Novik/ruTorrent#2473]
### Is your feature request related to a problem?

Can you please add support for BitTorrent v2:
https://blog.libtorrent.org/2020/09/bittorrent-v2/

### Describe the solution you'd like

https://blog.libtorrent.org/2020/09/bittorrent-v2/

**Comment by halilnevzat** [comment]
afaik , rutorrent is just a nice web gui for the Rtorrent client, so you should demand it from rtorrent :D

**Comment by stickz** [comment]
> afaik , rutorrent is just a nice web gui for the Rtorrent client, so you should demand it from rtorrent :D

Agreed. Please report the issue to libtorrent / rtorrent. We are just a graphical user interface.
