### ISSUE TITLE
Cannot declare a const variable twice: 'actDeleted'

### ISSUE THREAD

**Issue by Frizlab** [Novik/ruTorrent#2484]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Safari Version 16.4 (18615.1.26.11.23) and Firefox 112.0.1
ruTorrent: v4.1.1 (083aca359fc15598c623438dbff8df121c07cea1)
PHP: PHP 7.4.33
OS: Debian GNU/Linux 11

### Tell us how you installed ruTorrent

Clone of the repo + some conf installed manually

### Describe the bug

Since I updated to v4.1.1 rutorrent does not load at all.
I get the following error in the console:
```
Cannot declare a const variable twice: 'actDeleted'.
```

Everything worked well with the previous stable version.

### Steps to reproduce

1. Install rutorrent v4.1.1;
2. Use it in Safari or Firefox.

### Expected behavior

The page should load and I should not get an error in the console.

**Comment by stickz** [comment]
Did you clear your web browser cache? I can see here that `actDeleted` is only declared once and the variable is not `const`.

```
                var actDeleted = false;
		var pLabels = ['nlb'].concat(Object.keys(this.cLabels));
		p.children().each(function(ndx,val)
		{
			var id = val.id;
			var lbl = (id&&theWebUI.idToLbl(id))||'nlb';
			if (!pLabels.includes(lbl)) {
				$(val).remove();
				if(theWebUI.actLbls["plabel_cont"] == id)
					actDeleted = true;
			}
		});
		if(actDeleted)
		{
			this.switchLabel($("#plabel_cont .-_-_-all-_-_-").get(0))
		}
```

**Comment by allixx** [comment]
https://github.com/Novik/ruTorrent/blob/v4.1.1/js/webui.js#L2213
https://github.com/Novik/ruTorrent/blob/v4.1.1/js/webui.js#L2227

**Comment by Frizlab** [comment]
I reloaded the page with the `Disable Caches` option active, yes.

**Comment by stickz** [comment]
Hold on please, I'm fixing an issue with GitHub. I need to re-merge a few commits and re-release.

**Comment by buggsi** [comment]
Same problem here:
```
SyntaxError: bad method definition  graph.js:6:9
SyntaxError: redeclaration of var actDeleted  webui.js:2227:8
```

**Comment by stickz** [comment]
@buggsi @Frizlab @allixx Could you please `git clone https://github.com/Novik/ruTorrent/` now to verify the problem is resolved? The commit history is broken on GitHub. Conflicts between the `master` and `develop` branches were not resolved correctly.

**Comment by allixx** [comment]
master branch works fine for me now.

**Comment by buggsi** [comment]
master works.

**Comment by Frizlab** [comment]
`master` looks good! 🙂

**Comment by stickz** [comment]
Okay, version 4.1 stable is re-tagged and re-released now. The pre-releases were removed for 4.1. The conflicts in the master branch are fixed. https://github.com/Novik/ruTorrent/releases/tag/v4.1
