### ISSUE TITLE
Js error for new changes to graph.js

### ISSUE THREAD

**Issue by colinborins** [Novik/ruTorrent#2490]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Web Browser: Google Chrome 97.0.4692.71
ruTorrent: 4.1
PHP: PHP81
OS: Truenas 13 running Freebsd 13.1-

### What were you trying to do?

I upgraded to 4.1 and ever since the throttle plugin will not load

**Comment by stickz** [comment]
Please provide more details such as the error you're experiencing.
