### ISSUE TITLE
Throttle  plugin not working

### ISSUE THREAD

**Issue by ac1dburnz** [Novik/ruTorrent#2491]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Google Chrome 97.0.4692.71
ruTorrent: 4.1
PHP: PHP81
OS: Truenas 13 running Freebsd 13.1-

### Give us detailed steps to reproduce the error

Followed the following guide for installation : https://forums.freebsd.org/threads/freebsd-install-rtorrent-and-rutorrent-on-lighttpd-full-guide.85230/#post-567706 and upgraded to 4.1

### Tell us the error message

Upon loading the UI  throttle: Plugin failed to start and I cannot find any logs to backup why it failed. I have tried installing it on a sperate instance with the same result.

**Comment by stickz** [comment]
Please try the install process again using the latest master commit. Clear your web browser cache when completed. https://github.com/Novik/ruTorrent/commit/cac820560df0c84f49a6d106b4d51c2ee3db49eb

I mitigated a potential issue with users hosting content in hierarchy directories where the web server doesn't have executable access. I don't know if this was your problem, but it was easily avoidable during the initialization process for ruTorrent.

**Comment by colinborins** [comment]
hey ! so i updated but I'm still not able to load it. Any ideas for next steps?

**Comment by stickz** [comment]
The guide is bad. The owner still hasn't updated it yet.

This command should be: `mkdir -p /usr/local/www/lighttpd/ruTorrent/share/torrents`
NOT: `mkdir -p /usr/local/www/lighttpd/ruTorrent/php/share/torrents`

Also you need: `pkg install php81-extensions`. Read the comments bellow the guide.

Please check `/usr/local/www/lighttpd/ruTorrent/php` folder. There should not folders creating in this directory. The only folder in there should be the `utility` folder. `/usr/local/www/lighttpd/ruTorrent/share` should contain settings, users, torrents etc.

**Comment by colinborins** [comment]
i know this isnt really something you do but you did a great job making the vmtouch work. How can i get method.set_key=event.download.finished,cross_seed,"execute={'`pwd`/rtorrent-cross-seed.sh',$d.name=}"' >> .rtorrent.rc to work in my rtorrent file?

**Comment by stickz** [comment]
I'm glad you got version 4.1 working. I don't have time to investigate the custom cross seeding script.
