### ISSUE TITLE
RSS Update Fails

### ISSUE THREAD

**Issue by Frizlab** [Novik/ruTorrent#2496]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Safari Version 16.4 (18615.1.26.11.23)
ruTorrent: v4.1.3
PHP: 7.4.33
OS: Debian GNU/Linux 11

### Tell us how you installed ruTorrent

It’s a clone of the repository, checked-out at version 4.1.3.

### Describe the bug

When I click “Update Feed” on the contextual menu on an RSS feed, nothing happens visually on the UI, and there’s an HTTP request that fails.
On the server logs, I get this:
```
2023/04/28 06:50:25 [error] 587#587: *604424 FastCGI sent in stderr: "PHP message: PHP Warning:  include_once(utility/domdocument.php): failed to open stream: No such file or directory in /usr/share/nginx/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/domdocument.php' for inclusion (include_path='.:/usr/share/php') in /usr/share/nginx/rutorrent/php/util.php on line 21PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /usr/share/nginx/rutorrent/plugins/rss/rss_reader.php:124
Stack trace:
#0 /usr/share/nginx/rutorrent/plugins/rss/rss.php(169): rssXpath()
#1 /usr/share/nginx/rutorrent/plugins/rss/rss.php(940): rRSS->fetch()
#2 /usr/share/nginx/rutorrent/plugins/rss/rss.php(961): rRSSManager->tryFetch()
#3 /usr/share/nginx/rutorrent/plugins/rss/action.php(74): rRSSManager->updateRSS()
#4 {main}
  thrown in /usr/share/nginx/rutorrent/plugins/rss/rss_reader.php on line 124" while reading response header from upstream, client: 2a04:4e41:13:c::b64c:8d08, server: rutorrent.frostland.fr, request: "GET /plugins/rss/action.php?mode=refresh&rss=fe1fe12fe48adf09abd3b7a3b5c5c8d7 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "rutorrent.frostland.fr", referrer: "https://rutorrent.frostland.fr/"
```

### Steps to reproduce

1. Install ruTorrent
2. Add an RSS feed
3. Right-click the feed and select “Update Feed”

### Expected behavior

The feed should update.

**Comment by stickz** [comment]
Thanks for the bug report. We updated to `libxml` in `v4.1` for RSS. Tagging @TrimmingFool who made the change.

**Comment by Frizlab** [comment]
As additional info in the mean time, I’m pretty sure all the RSS feeds are not updated automatically.
I do not know why but it’s probably related so I’m mentioning it here.
