### ISSUE TITLE
The 'Ratio Groups' plugin doesn't delete files?

### ISSUE THREAD

**Issue by steve51184** [Novik/ruTorrent#2497]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Chrome latest
Rutorrent latest 
PHP 7.3.31
Android

### Tell us how you installed ruTorrent

Swizzin 

### Describe the bug

The ratio group plugin used to delete files when the 'action' was set to "remove data (all)" but after upgrading to rutorrent 4.x it no longer deletes the files when the ratio and/or seed time (etc) are hit.. it just removes the torrent not the files..

**Comment by stickz** [comment]
Thanks for the bug report. Did you modify the plugin configuration for the `erasedata` plugin? There was a new feature added here, but It should be disabled by default.

**Comment by steve51184** [comment]
It was erasedata I believe ✌️

**Comment by stickz** [comment]
> It was erasedata I believe ✌️

Thank you for the follow up. I will resolve this problem next week. It is easily fixable.

Let's keep this issue report open, to avoid duplicates.

**Comment by stickz** [comment]
@steve51184 Please confirm fix in `v4.1.4` by upgrading rutorrent. I believe this to be a caching bug with the web interface. I didn't find anything with the `erasedata` plugin. https://github.com/Novik/ruTorrent/releases/tag/v4.1.4

**Comment by stickz** [comment]
Fixed in https://github.com/Novik/ruTorrent/commit/bfb1808174c5bcc603d6eaeba8a80b8013a1575e. Version 4.1.5 releasing shortly.
