### ISSUE TITLE
throttle: Plugin failed to start

### ISSUE THREAD

**Issue by koxx79** [Novik/ruTorrent#2508]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Chrome Version 113.0.5672.93 (Official Build) (64-bit)
rutorrent:  4.1.5
PHP: php 7.4
OS: Ubuntu 18.04.6 LTS

### Tell us how you installed ruTorrent

https://github.com/arakasi72/rtinst/wiki/Installing-rtinst

### Describe the bug

after update to 4.1.5 cant load throttle plugin, got this message: throttle: 
Plugin failed to start. All other plugins works fine.

My .rtorrent.rc config:

method.insert = cfg.basedir,     private|const|string, (cat,"/home/koxy/rtorrent/")
method.insert = cfg.watch,       private|const|string, (cat,(cfg.basedir),"/mnt/green/watch/")
session.path.set = (cat,(cfg.basedir),"/mnt/green/~session")
directory.default.set = (cat,(cfg.basedir),"/mnt/green/torrent/")
schedule = watch_directory,5,5,((load.start,(cat,(cfg.watch),"*.torrent")))
#system.umask.set = 0000
throttle.global_down.max_rate.set = 10000
throttle.global_up.max_rate.set = 5000
throttle.max_downloads.global.set = 150
throttle.max_uploads.global.set = 150
throttle.min_peers.normal.set = 30
throttle.max_peers.normal.set = 150
throttle.min_peers.seed.set = -1
throttle.max_peers.seed.set = -1
network.port_range.set = 33101-33199
network.port_random.set = yes
dht.mode.set = disable
protocol.pex.set = no
trackers.use_udp.set = yes
network.scgi.open_port = 127.0.0.1:5000
network.http.ssl_verify_peer.set = 0
protocol.encryption.set = allow_incoming,enable_retry,prefer_plaintext
network.max_open_files.set = 4096
network.max_open_sockets.set = 1536
network.http.max_open.set = 48
network.send_buffer.size.set = 4M
network.receive_buffer.size.set = 4M
pieces.hash.on_completion.set = no
pieces.preload.type.set = 1
pieces.memory.max.set = 3500M
execute2 = {sh,-c,/usr/bin/php /var/www/rutorrent/php/initplugins.php koxy &}

throttle plugin is in version 4.1

rtorrent&rutorrent was updated via arakasi72 script

**Comment by stickz** [comment]
https://github.com/Novik/ruTorrent/discussions/2482
