### ISSUE TITLE
_cloudflare plugin will not work

### ISSUE THREAD

**Issue by mak163** [Novik/ruTorrent#2510]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Yandex Browser 23.3.4.594 (64-bit)
ruTorrent: v4.1.5
PHP: PHP 7.4.33

### Give us detailed steps to reproduce the error

I have installed and configured rtorrent, Lighttpd and ruTorrent according to the Wiki.
Every time you open the ruTorrent page in the browser, the "Log" tab displays the message "_cloudflare: Plugin will not work. Webserver user can't access external program (python)."

### Tell us the error message

_cloudflare: Plugin will not work. Webserver user can't access external program (python).

**Comment by stickz** [comment]
You can disable that plugin because it's not required.

**Comment by MarkusLange** [comment]
You can add (somewhere after line 50):

	$pathToExternals = array(
		"python"=> '/usr/bin/python3',

to /conf/config.php so ruTorrent knows the path
