### ISSUE TITLE
Directroy list is showing empty or blank

### ISSUE THREAD

**Issue by Nirzak** [Novik/ruTorrent#2513]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

OS Version: Ubuntu 22 LTS
Web Browser: Google Chrome
PHP Version: PHP 7.4.33
ruTorrent: v4.1.5

### Tell us how you installed ruTorrent

I have installed rtorrent with arakasi's script, as I am using that since a long time. https://github.com/arakasi72/rtinst

### Describe the bug

When creating torrent, the directory list is just showing empty or blank.
I have already checked permissions and other things already. here's the screenshot of the issue.

![image](https://github.com/Novik/ruTorrent/assets/11460645/c579d181-c8a7-4232-9910-75d0d427c9f6)

also got that error on chrome web console during that issue.

![image](https://github.com/Novik/ruTorrent/assets/11460645/11b68331-3edf-48e7-b2b8-4b741a06b774)

Looks like an issue from _getdir php plugin.

### Steps to reproduce

1. Go to create new torrent option.
2. Click on ...

### Expected behavior

Should list all the files and directories.

**Comment by stickz** [comment]
rtinst is not maintained. The install script is broken and doesn't install ruTorrent properly. You can see alternatives here: https://github.com/Novik/ruTorrent/discussions/2482

**Comment by Nirzak** [comment]
> rtinst is not maintained. The install script is broken and doesn't install ruTorrent properly. You can see alternatives here: #2482

Oh thanks a lot. let me use that then..
