### ISSUE TITLE
Need to press ENTER twice for search to work

### ISSUE THREAD

**Issue by gashtal** [Novik/ruTorrent#2516]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 113.0.2
ruTorrent: v4.1.5 (145529129)
PHP: PHP 8.2.6
OS: Ubuntu 22.04.2 LTS

### Tell us how you installed ruTorrent

Cloned from Github and created configured manually. Issue is _**not**_ related to a new installation.

### Describe the bug

When I type a new search term in the search box on the top right within a given session and press ENTER, the search operation is not actually executed. If a torrent has been highlighted before doing so, the highlight will be removed, as though the torrent list has been refreshed. When I press ENTER a second time, then the search is executed. If I then change the search term and press ENTER again, all torrents will be listed as though the search has been cancelled/torrent list has been refreshed, and then I need to press ENTER for a second time again for the new search term to take effect. However, if a previous search term is used again, ENTER will work the first time.

### Steps to reproduce

1. Open ruTorrent.
2. Type search_term_1 in the search box on top right and pres ENTER. The torrent list will **_not_** be filtered based on the search term.
3. Press ENTER again, now the torrent list will be filtered based on the search_term_1.
4. Replace search_term_1 with search_term_2 in the search box and pres ENTER. The torrent list will be refreshed, as though the search box has been emptied.
5. Press ENTER again, now the torrent list will be filtered based on the search_term_2.
6. Replace search_term_2 with search_term_1 in the search box and pres ENTER. The torrent list is immediately filtered as expected.

### Expected behavior

Entering a search term in the search box and pressing ENTER **_once_** should filter the torrent list based on the search term.

### Additional context

This started happening a few weeks ago. I recently updated from v4.1.1 to v4.1.5 (git pull). Not sure if the issue started after the upgrade, or some PHP or browser update is causing this.

**Comment by stickz** [comment]
Thank you for the bug report @gashtal. I have resolved this issue in https://github.com/Novik/ruTorrent/commit/26e05370f79ae673b6f23cac3432e539c8c3b9b7. I will release a hot fix later today.

It's required to run the search engine twice because the results are queried in an asynchronous fashion. Users only need to press enter or click the green go button **once** now. ruTorrent will automatically handle the logistics in the back end.

**Comment by gashtal** [comment]
@stickz I just updated to 4.1.6 and the issue is certainly fixed. Thank you very much for addressing the problem so quickly.
