### ISSUE TITLE
Errors with torrent creation tasks

### ISSUE THREAD

**Issue by ysarkain** [Novik/ruTorrent#2517]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Chrome 113.0.5672.127
ruTorrent: 3.10
PHP: 8.1.12-1ubuntu4
OS: Ubuntu 23.04

### Tell us how you installed ruTorrent

I installed rtorrent and rutorrent using Bercik's rt-auto-install (https://github.com/Bercik1337/rt-auto-install.git)

### Describe the bug

When I try to create torrents, I get errors "Bad response from server: (500 [error,taskcheck])" and "Bad response from server: (500 [error,tasklist])".  They appear to occur intermittently - sometimes a torrent will create and the save button appears so I can grab the torrent, other times it appears to be stuck making the torrent, though it will start the torrent up and I have to cancel the task and get the torrent via the right-click menu.  Tasks don't appear in the tasklist at all when it does this.

### Steps to reproduce

1. Create a torrent using the flask icon, start torrent and private tracker are checked
2. The torrent creation script runs, logged on screen
3. The error appears, script continues to run
4. Hit cancel after the torrent is added in the background

### Expected behavior

When torrent creation script finishes, a save button appears which allows you to download the torrent and provides confirmation the torrent is ready.  I should also be able to hide the torrent script window and recall it when it is complete.

### Additional context

Recently changed from a bare metal Ubuntu 20.04 install to a Ubuntu 23.04 VM running under proxmox, same install script was used.

**Comment by ysarkain** [comment]
Just a note the script continues to run, but logging stops after the error.  After the expected time for the script to complete the torrent is added to the list and started.  I'm pretty sure it's got to be a timeout error somewhere, just not sure where to look, since small torrents seem to get through before the error, but large torrents do not.

**Comment by stickz** [comment]
ruTorrent version 3.10 is not supported. Consider upgrading to version 4.
