### ISSUE TITLE
Add dark mode to loading screen when using a dark theme.

### ISSUE THREAD

**Issue by sekuza009** [Novik/ruTorrent#2519]
### Is your feature request related to a problem?

Currently, the way the app works is that it always has a white loading screen, and it's blinding.

### Describe the solution you'd like

Ideally, I'd like the loading screen to match whatever custom theme background you have set because it's very unpleasant.

I would use a dark mode app but it doesn't seem to make a difference for ruTorrent.

**Comment by stickz** [comment]
@sekuza009 Please give https://github.com/Novik/ruTorrent/commit/09cbecc57c22f0cd6a754fec6a6f8a4f8dbbab6f a try. Browse Files -> Code -> Download Zip -> Extract CSS folder.

Is this new colour scheme easier on your eyes? It should reduce the strength of high screen brightness.

**Comment by sekuza009** [comment]
That's 100% better, though I'd still prefer a 100% dark loading screen. Or at the very least to have it match whatever background and colors are in the selected theme you use for it.

**Comment by MarkusLange** [comment]
Hi, I use the DarkBetter Theme, what I wonder of is, the loading screen is at first white, switches then to black while still loading

**Comment by stickz** [comment]
> That's 100% better, though I'd still prefer a 100% dark loading screen. Or at the very least to have it match whatever background and colors are in the selected theme you use for it.

We are not able to apply the theme settings to the loading screen at this moment in time. Plugin loading doesn't support it.

> Hi, I use the DarkBetter Theme, what I wonder of is, the loading screen is at first white, switches then to black while still loading. why this 2 steps?

Themes are part of the plugin modules. They load during the initial loading screen process. ruTorrent `v4.2` is going to be so fast, we might be able to remove the loading screen entirely. We are waiting for 10 000 lines of code to be read from the web server, that is why the loading screen was implemented. This exercise is pointless, when we can send and cache the files in 100ms.

**Comment by stickz** [comment]
Closing this issue. Feature for dark loading screen was created and released in `v4.2` as requested.
