### ISSUE TITLE
Header location set to wrong path when adding a new torrent

### ISSUE THREAD

**Issue by Bacto** [Novik/ruTorrent#2526]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Not revelant

### Tell us how you installed ruTorrent

Not revelant

### Describe the bug

Hi,

`addtorrent.php` uses `$_SERVER['PHP_SELF']` which isn't set when using a reverse proxy and a subdirectory in front of rutorrent.
See https://github.com/Novik/ruTorrent/blob/09cbecc57c22f0cd6a754fec6a6f8a4f8dbbab6f/php/addtorrent.php#L102

This results to an error when adding a new torrent file.

Here is a solution (tested and works):
```diff
--- /var/www/rutorrent/php/addtorrent.php.orig
+++ /var/www/rutorrent/php/addtorrent.php
@@ -99,7 +99,7 @@
 			}
 		}
 	}
-	$location = "Location: //".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/addtorrent.php?";
+	$location = "Location: ./addtorrent.php?";
 	if(empty($uploaded_files))
 		$uploaded_files = array( array( 'status' => "Failed" ) );
 	foreach($uploaded_files as &$file)
```

**Comment by Novik** [comment]
[Check second comment](https://github.com/Novik/ruTorrent/commit/345dbe58a892f1d05b7e6235d630b0bb6741229e)

**Comment by stickz** [comment]
@Novik What about this fix? I don't think we should reference a variable which is not set. It will just create anther error.
```
if ((isset($_SERVER['PHP_SELF']) && isset($_SERVER['HTTP_HOST']))
        $location = "Location: //".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/addtorrent.php?";
else
	$location = "Location: ./addtorrent.php?";
```

**Comment by Novik** [comment]
@stickz 
I think this variable - $_SERVER['PHP_SELF'] - is set for this case. Its is empty.
https://stackoverflow.com/questions/54605902/php-serverphp-self-is-empty

**Comment by stickz** [comment]
Okay, let's use `empty` instead of `isset`. Target is `v4.1.7` for hotfix. 
```
if (!empty($_SERVER['PHP_SELF']) && !empty($_SERVER['HTTP_HOST']))
        $location = "Location: //".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/addtorrent.php?";
else
	$location = "Location: ./addtorrent.php?";
```
