### ISSUE TITLE
FileZilla Pro EPSV 500 unknown command

### ISSUE THREAD

**Issue by ataoist1** [Novik/ruTorrent#2528]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Brave Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (arm64)
Hosted at appbox.co ruTorrent installed version 3.10-9
(PHP Unknown)  MacPro 2023 Ventura Version 13.4.1 (22F82) 

### Give us detailed steps to reproduce the error

While recently, this week, downloading a file through appbox.co I received an 500 unknown command.
The access and downland have worked flawlessly for the past year

### Tell us the error message

500 Unknown Command

### Provide the php error log contents (if applicable)

Status:      	Directory listing of "/apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed" successful
Status:      	Retrieving directory listing of "/apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10"...
Status:      	Directory listing of "/apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10" successful
Status:      	Resolving address of rutorrent.tiki-sprinter.appboxes.co
Status:      	Connecting to [2607:7700:0:1b:0:1:51ab:987]:10321...
Status:      	Connection established, waiting for welcome message...
Status:      	Initializing TLS...
Status:      	TLS connection established.
Status:      	Logged in
Status:      	Starting download of /apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10/Ghosted.2023.WEBRip.x264-ION10.mp4
Command: 	CWD /apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10
Response: 	250 OK. Current directory is /apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10
Command: 	PWD
Response: 	257 "/apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10" is your current location
Command: 	TYPE I
Response: 	200 TYPE is now 8-bit binary
Command: 	EPSV
Response: 	500 Unknown command
Command: 	EPRT |2|2607:fb90:8f88:8770:3c5e:328a:c428:7a75|62387|
Response: 	522 Only IPv4 is supported (1)
Error:         	File transfer failed
Status:      	Starting download of /apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10/Ghosted.2023.WEBRip.x264-ION10.mp4
Command: 	EPSV
Response: 	500 Unknown command
Command: 	EPRT |2|2607:fb90:8f88:8770:3c5e:328a:c428:7a75|62388|
Response: 	522 Only IPv4 is supported (1)
Error:         	File transfer failed
Status:      	Starting download of /apps/rutorrent.tiki-sprinter.appboxes.co/torrents/completed/Ghosted.2023.WEBRip.x264-ION10/Ghosted.2023.WEBRip.x264-ION10.mp4
Command: 	EPSV
Response: 	500 Unknown command
Command: 	EPRT |2|2607:fb90:8f88:8770:3c5e:328a:c428:7a75|62389|
Response: 	522 Only IPv4 is supported (1)
Error:         	File transfer failed
Status:      	Disconnected from server

**Comment by stickz** [comment]
We do not support `ruTorrent v3.10` anymore. I would suggest upgrading to `ruTorrent v4.1.6` it is more stable.

You have a receiving a Response 522, which states only IPv4 is supported. It's recommended to connect FTP with IPV4. The best channel of communication for this issue is through your hosting provider. Inform them the DNS is resolving to IPV6 and ask how you can instead connect to the FTP server with IPV4. This problem is not related to ruTorrent.

**Comment by ataoist1** [comment]
Thanks I didn't think it was. Some things g changed a week or two ago. I'll
see about updating to 4.x.

Thanks
