### ISSUE TITLE
check_port plugin: IP address and port status are incorrect

### ISSUE THREAD

**Issue by xyzzy4** [Novik/ruTorrent#2539]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 115.0.2 (64-bit)
ruTorrent: v4.1 and v4.1.6
PHP: PHP 7.4.3-4ubuntu2.19 and PHP 8.1.2-1ubuntu2.13
OS: Ubuntu 20.04 and Ubuntu 22.04

### Tell us how you installed ruTorrent

Installed through Swizzin install script https://swizzin.ltd/

### Describe the bug

IP address and port at the bottom of ruTorrent as part of the check_port plugin are not displaying correctly. I am seeing a yellow exclamation point triangle with my external IP shown as ?.?.?.?. The port displayed is correct.

### Steps to reproduce

1. Ensure that the rtorrent port in use is opened and incoming connections can be made.
2. Open ruTorrent.
3. Look at the IP address and port status on the bottom of the ruTorrent interface, where it will show as described in the bug.

### Expected behavior

I expect to see a green circle with a checkmark indicating that the port is open, my external IP address, and the configured port in rtorrent.

### Additional context

In the Swizzin Discord server, it was clarified that this bug is due to yougetsignal.com being down. Navigating to it shows a Cloudflare error page indicating a 502 bad gateway error.

I would greatly appreciate if multiple port/IP address checking APIs could be added to fall back if necessary as mentioned in the Swizzin Discord server, rather than simply replacing the existing one, as this issue could then reoccur.

**Comment by stickz** [comment]
Problem resolved. Will release hot fix in near future.
