### ISSUE TITLE
Issues with French translation

### ISSUE THREAD

**Issue by DameGAD** [Novik/ruTorrent#2542]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web browser: 1.56.20

### Give us detailed steps to reproduce the error

When using the French translation, two check boxes ("move data" & "sequential download") are either unreadable or hidden because the French translation is too long. "Move data" being an essential feature and inaccessible, it makes the use of this translation difficult.

How to reproduce it: Set Language to French. Right click on any torrent, then choose: "Définir l'emplacement du torrent". Go back, and try to add a torrent.

### Tell us the error message

How to fix it:
On the first screenshot, "Téléchargement séquentiel" could be shorten by using "Tél. séquentiel".
On the second screenshot, I would suggest to shorten "Définir l'emplacement" and just use "Définir" (the title "Définir l'emplacement du torrent" at the top is clear enough) and if not enough to shorten "Déplacer les données" by "Dépl. les données" (context make it clear Dépl. is short for "Déplacer").

![Screenshot 2023-08-06 à 13 13 54](https://github.com/Novik/ruTorrent/assets/65853049/7ecbd8f9-aa7e-4d9a-b5af-6b668b64a411)
![Screenshot 2023-08-06 à 13 14 10](https://github.com/Novik/ruTorrent/assets/65853049/d1eb6788-4c37-42ae-98d8-f711f9a160a9)

**Comment by DameGAD** [comment]
I apologize if it is not the right place to report such issue, but I had know idea where else to share it.

**Comment by stickz** [comment]
Hello, what version of ruTorrent are you using? Are you running the latest supported `v4.1.x` release?

**Comment by DameGAD** [comment]
> Hello, what version of ruTorrent are you using? Are you running the latest supported `v4.1.x` release?

I posted in the wrong project page...... I'm sorry.

**Comment by stickz** [comment]
No problem.
