### ISSUE TITLE
Version 4.2.0 not working in Safari: “Can't find variable: theUILang”

### ISSUE THREAD

**Issue by Frizlab** [Novik/ruTorrent#2543]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Safari 16.6 (18615.3.12.11.2)
ruTorrent: v4.2.0
PHP: PHP 7.4.33
OS: Debian 11

### Tell us how you installed ruTorrent

It is a clone of the project that is used directly.
I upgraded the clone to v4.2.0 from v4.1.8.
I did not upgrade de user config files (but I don’t think there are modifications?)

### Describe the bug

Loader never goes away.
I have the following errors in the JS console.
![image](https://github.com/Novik/ruTorrent/assets/523041/db387ffb-b21b-48c5-af03-4c24558b7a73)

### Steps to reproduce

1. Launch rutorrent v4.2.0 on Safari.

**Comment by stickz** [comment]
Thanks for testing in Firefox. I would recommend using v4.1.8 or Firefox, until a hotfix is released to resolve this problem. Support will be continued for `v4.1` (as mentioned in the release notes) for a while longer.

**Comment by stickz** [comment]
@TrimmingFool Is there any possibly this commit could have broken support for Safari? https://github.com/Novik/ruTorrent/commit/58722631f5a84bb0665d2e94042e53133f48b619

**Comment by stickz** [comment]
@Frizlab ruTorrent v4.2.1 has been released, if you would like to give it a try on Sarafi. https://github.com/Novik/ruTorrent/releases/tag/v4.2.1

**Comment by Frizlab** [comment]
Fixed in 4.2.1. Thanks!
