### ISSUE TITLE
upgrade ubuntu 20.04 LTS to ubuntu 22.04, rutorrent can't work.

### ISSUE THREAD

**Issue by SMooxx** [Novik/ruTorrent#2544]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Chrome
ruTorrent: 4.2.0
Php: 7.4
OS: ubuntu 22.04

### Tell us how you installed ruTorrent

rtinst install rutorrent long ago. and I update rutorrent 3.10 to 4.1.8, then 4.2.0.

### Describe the bug

upgrade ubuntu 20.04 LTS to ubuntu 22.04, rutorrent can't work. 
1. because ubuntu 22.04 update php7.4 to php8.1, then I found rutorrent can't load page with error 500[lists]
2. then I downgrade php8.1 to php7.4, then finally rutorrent can load my 12000+ torrents on the indexpage. but with this error on the log section.
``[08.08.2023 12:07:30] WebUI started.
[08.08.2023 12:07:34] autodl-irssi: __init2: ex: Exception info: No content elem with id autodl-prefs-contents-upload``

don't know what cause this.

**Comment by stickz** [comment]
Hi @SMooxx the rtinst install script is not maintained and broken. If you want support for PHP8.1 on Ubuntu 22.04LTS, I would recommend using swizzin instead. The author has chosen not to maintain rtinst. It's a miracle you even got this far.
https://github.com/Novik/ruTorrent/discussions/2482

**Comment by MarkusLange** [comment]
I can offer also a working [script](https://github.com/MarkusLange/r_ru-torrent-install-script) whats capable of updating rutrorrent to newer versions

**Comment by SMooxx** [comment]
Thanks, guys. I stick to this rtinst script because I used to the rtorrent location (home/user/rtorrent/download) and don't know if I change it to other scripts, how can I modify the new script to adapt to my existing 12000+ torrents

**Comment by MarkusLange** [comment]
Hi @SMooxx,
you will run in serveral problems since Ubuntu 21.04 the homefolder rights are changed to 750 so some plugins are not running, and as far I can evaluate autodl-irssi does not work with the latest ruTorrent nor php8.x [link](https://github.com/autodl-community/autodl-rutorrent/pull/58) and I had to learn it the hard way the users homefolder isn't the right [place ](https://github.com/Novik/ruTorrent/issues/2452)

**Comment by MarkusLange** [comment]
So some tests (testet on debian 12) later, (I can't test auto autodl-irssi, but it's loaded) I run the script rtinst with some modifications what works is.

Debian 12
PHP8.2
ruTorrent v3.10
rtorrent 0.9.8

What I don't know if it can readopt existing torrents
