### ISSUE TITLE
Views label size issues

### ISSUE THREAD

**Issue by allixx** [Novik/ruTorrent#2556]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: 115.1.0esr
ruTorrent: v4.2.4
PHP: PHP 8.0.29

### Tell us how you installed ruTorrent

-

### Describe the bug

Disabling "Views label size" (Settings / Format / Show label size in Views panel) still displays size of default "All" views entry, which is not expected, considering how other "Show label size" settings work.
![1](https://github.com/Novik/ruTorrent/assets/1695323/b499874b-14ba-431d-8c1a-90db985a6f50)

Enabling "Views label size" doesn't start displaying label sizes even after reloading the page. I'd have to remove an existing view, or add a new view, for label sizes to appear.

**Comment by stickz** [comment]
@TrimmingFool 
- "Show label size in Views panel" doesn't work at all.
- "Show label size in Labels panel" also adjusts Views panel.
- All category in Views panel shows label size regardless of these settings.

**Comment by stickz** [comment]
Resolved in [v4.2.5](https://github.com/Novik/ruTorrent/releases/tag/v4.2.5). Thanks for the bug report.
