### ISSUE TITLE
Error when searching and clicking torrent

### ISSUE THREAD

**Issue by ac1dburnz** [Novik/ruTorrent#2557]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
ruTorrent: 4.2.4-0.9.8-0.13.8-r0
PHP: PHP 8.1.22 
OS: Docker os

### Tell us how you installed ruTorrent

Installed docker through  rutorrent app at:

https://github.com/ac1dburnz/catalog

which pulls from:

https://github.com/ac1dburnz/rtorrent-rutorrent-cross-seed

### Describe the bug

Error when searching for a torrent and clicking on said torrent

### Steps to reproduce

Step One: type in the search bar
<img width="154" alt="Screenshot 2023-08-25 at 1 51 30 PM" src="https://github.com/Novik/ruTorrent/assets/10972668/be84af22-bb8d-4f28-abe9-f06b4845ece1">

Step Two: click on any torrent in your browser
![image](https://github.com/Novik/ruTorrent/assets/10972668/d24d568c-71b6-486e-84f2-81783167b414)

### Expected behavior

Error does not pop up 

### Additional context

VM1363:7068 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at theWebUI.updateLabel (<anonymous>:7068:19)
    at Object.updateLabels (webui.js?v=424:2353:10)
    at theWebUI.updateLabels (<anonymous>:7085:22)
    at domUpdates (webui.js?v=424:1814:11)

**Comment by stickz** [comment]
Resolved in [v4.2.5](https://github.com/Novik/ruTorrent/releases/tag/v4.2.5). Thanks for the bug report.
