### ISSUE TITLE
Search -> All navigation doesn't work after making a search without clearing the text from the search box

### ISSUE THREAD

**Issue by albino1** [Novik/ruTorrent#2561]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 116.0.5845.111 + Firefox 116.0.3
ruTorrent: v4.2.5

### Tell us how you installed ruTorrent

From source

### Describe the bug

When searching via the search box and hitting enter you get a search result under the Search tab on the left pane.  If you then switch from the search result back to All the results remain filtered.  The only way to get back to All is to manually clear the text from the search box.

### Steps to reproduce

1. Search for "text" in the search box in the top right.
2. Observe that `text` is now selected under `Search` in the left panel.
3. Click `All` to navigate away from `text`.
4. Observe that the filtered results are still only for `text` even though `All` is selected.
5. Clear "text" from the search box in the top right.
6. Observe that now you can successfully navigate to `All` and show unfiltered results.

### Expected behavior

I expect that when I click `All` it will show all results regardless of any text that might happen to be in the search box, or that it will just clear the text from the box on click so that `All` works correctly.

**Comment by stickz** [comment]
Resolved in ruTorrent [v4.2.6](https://github.com/Novik/ruTorrent/releases/tag/v4.2.6). Thanks for reporting this bug.
