### ISSUE TITLE
RSS counter on the interface isn't on sync with the actual RSS update

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2568]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Edge 116
Rutorrent 4.04 and latest master tree
PHP8.1
Ubuntu 2304

### Tell us how you installed ruTorrent

4.04 release and git clone from the master/main tree

### Describe the bug

The timer displayed on the interface differ from the actual RSS update. It's most of the time 45sec off, and occasionally up to 1 minute. 

### Steps to reproduce

Add a RSS feed,
set the timer to any time,
the update will always fires when the timer still has 45sec remaining, with the occasional 1 minute off. 

### Expected behavior

Be roughly in sync, not with a huge time difference between the actual firing of `plugins/rss/update.php` and the time displayed on the Interface, and the display of new RSS entries. 

### Additional context

Also, Rutorrent occasionally adds time to the timer displayed on the interface (edit: when the coundown resets to the time set in the RSS settings), from 45sec up to 1 minute. Why not just reset the timer on the webui to match the new countdown to the next RSS update? 

Also, is there an option to manually reset the timers to try to sync the RSS feed to time the RSS refresh to around when the cache of the feed reset on the website? I'd use something else but Autodl-irssi isn't an option and jackett is just garbage for my usage since it doesn't put basic info like the size of the release in its RSS feed. 

Edit: clarifications

**Comment by stickz** [comment]
Have you tried upgrading to ruTorrent `v4.2.6`? We don't support `v4.0.x` anymore. RSS was rewritten in these newer releases.

**Comment by Antorell** [comment]
I tried with 4.1.8, the lastest commit from the master/main tree like I already mentioned, and update.php triggers 45 sec before the counter on the WebUI.

I'll try 4.2.6 later tonight, but pretty sure it will have the same issue. Nothing has been touched in the rss plugin code since May the 1st https://github.com/Novik/ruTorrent/commits/master/plugins/rss

**Comment by Antorell** [comment]
I tried  4.2.6 (git clone -b 4.2 https://github.com/Novik/ruTorrent.git), and it happens with this version as well. 

![Screenshot (7)](https://github.com/Novik/ruTorrent/assets/25066224/58f61ed1-8543-46aa-b9d1-76aaa66de053)

**Comment by Antorell** [comment]
Closing this as the 45 seconds difference is hardcoded. Thanks for making it a bit more obvious in the PR
