### ISSUE TITLE
404 Not Found error in DarkBetter theme for pnl_open.gif upon inspect

### ISSUE THREAD

**Issue by Nejeth** [Novik/ruTorrent#2573]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Mozilla FireFox
ruTorrent: V3.2.6
Theme: DarkBetter
PHP: Not relevant

rutorrent/plugins/theme/themes/DarkBetter/images/pnl_open.gif

I think its either a simple conversion from the existing pnl_open.SVG to pnl_open.GIF or changing the code to point to pnl_open.SVG which already exists in the folder.

### Give us detailed steps to reproduce the error

Once DarkBetter theme is chosen you will get 404 not found error in the inspect

### Tell us the error message

404 NOT FOUND rutorrent/plugins/theme/themes/DarkBetter/images/pnl_open.gif

**Comment by stickz** [comment]
Thanks for the bug report. I resolved this problem by copying `pnl_open.gif` and `pnl_close.gif` from the `rutorrent/images` folder to the `rutorrent/plugins/theme/themes/DarkBetter/images/` folder. You can do the same. 

We will resolve this trivial bug next release. There will not be a release made this for bug alone. The impact is very minor.

**Comment by Nejeth** [comment]
Yeah its a really insignificant change but its a quick and easy fix. thanks
