### ISSUE TITLE
JS error: [https://www.example.com/rutorrent/ line 2 > injectedScript : 7423] TypeError: this.plot is undefined

### ISSUE THREAD

**Issue by Nejeth** [Novik/ruTorrent#2574]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Mozilla FireFox
ruTorrent: V4.2.6
Theme: DarkBetter
PHP: v7.4

When pressing F4 the top menu hides/collapse, when pressed again it reappears/expands without any problems.
However when pressing F5 the bottom bar where it shows the torrent information and details hides/collapse, upon repressing F5 for it to reappears it gives the error "[https://www.example.com/rutorrent/ line 2 > injectedScript : 7423] TypeError: this.plot is undefined"

### Tell us how you installed ruTorrent

Manually as i have always been doing

### Describe the bug

JS error: [https://www.example.com/rutorrent/ line 2 > injectedScript : 7423] TypeError: this.plot is undefined

### Steps to reproduce

Click on F5 then F5 again.

### Expected behavior

Collapse and Expand the bottom bar without JS Error.

**Comment by stickz** [comment]
Hi @Nejeth I'm not able to resimulate this bug. I launched the DarkBetter theme on Firefox. Then pressed F4, F6, F7 to toggle/show various bars with no JavaScript errors.

Have you tried a different web browser to see if the problem persists? Anything chromium based would be important to try.

Also, could you please post the stack trace in your web developer console for this JavaScript error? Please advise if not availible.

**Comment by Nejeth** [comment]
Problem solved, it was related to my Mozilla Firefox
