### ISSUE TITLE
No time in ratio groups

### ISSUE THREAD

**Issue by anthology** [Novik/ruTorrent#2575]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Version 116.0.5845.188 (Build officiel) (64 bits)
rutorrent V4.2.6
os debian 11

### Tell us how you installed ruTorrent

Swizzin

### Describe the bug

hi,

few days ago, i have option on ratio groups for delete torrent when he reached a time.
now, this option is not possible.
why ? 

on the wiki, he have this option but not on my rutorrent

thanks a lot
first picture from the wiki
![image](https://github.com/Novik/ruTorrent/assets/1763750/9bbd08e9-edf7-4987-9704-2d04a2c19ef7)

second picture from my rutorrent (i have tested with other skin)

![image](https://github.com/Novik/ruTorrent/assets/1763750/1031dfe5-16be-45ee-9888-60ed3e2e5794)

### Steps to reproduce

update your rutorrent and plugins
go to settings, ratio groups

**Comment by stickz** [comment]
The `seedingtime` plugin is required to use the time feature on ratio groups. Ensure it is enabled and working properly.

**Comment by anthology** [comment]
oh, good

it's that, thanks a lot
it's possible to write on the plugin page, the other plugin needed ?

**Comment by stickz** [comment]
> it's possible to write on the plugin page, the other plugin needed ?

Yes, you can do that if you want. There is public edit access for the wiki.
