### ISSUE TITLE
Torrent Properties trackers text not visible in the Create New Torrent box

### ISSUE THREAD

**Issue by waz1500** [Novik/ruTorrent#2581]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 118.0.5993.71
ruTorrent: 4.2.6-0.9.8-0.13.8-r0 [Crazymax]
PHP: Unsure of version
OS: Ubuntu 20.04.3 LTS

### Tell us how you installed ruTorrent

Installed via CrazyMax docker container

### Describe the bug

When trying to create a new torrent, and using the Oblivion theme, any text input under the `Trackers:` section stays and is white whilst typing.
Tested on Chrome, Edge browser, no extensions enabled or browser plugins. 

It works as expected under different themes but Oblivion. This theme is the one bundled within rutorrent by default. 
The text does show up when highlighting the contents of the box but not whilst typing. 
![chrome_eNcRtwqaDk](https://github.com/Novik/ruTorrent/assets/17833884/69b1c6f2-07c6-4ddd-848a-56edf52a1e6c)
![chrome_SCrTYHNvTG](https://github.com/Novik/ruTorrent/assets/17833884/4266c162-e3b7-4ad5-bbdb-da4ffee6cae6)

### Steps to reproduce

1. Enable Oblivion Theme in rutorrent
2. Click Create Torrent
3. Start typing in an annnounce URL 
4. Notice the text not showing up visibly untill it's highlighted. 

### Expected behavior

Be able to read the output whilst typing into the box.

**Comment by TrimmingFool** [comment]
I guess this is because of the new `.dark-theme { color-scheme: dark; }`.

Possibly, it is as simple as adding `color: black` here:

https://github.com/Novik/ruTorrent/blob/8af54c71525899f9bf8387286464f9a431d4ca06/plugins/theme/themes/Oblivion/style.css#L69

I would appreciate if someone could test this and make a PR.

**Comment by stickz** [comment]
Problem resolved in [v4.2.7](https://github.com/Novik/ruTorrent/releases/tag/v4.2.7). I applied it to the `div` instead of generic `textarea` object, so we don't impact anything else.
