### ISSUE TITLE
Bad response from server: (500 [error,list]) Warning: XMLRPC call is failed.

### ISSUE THREAD

**Issue by Oreloth** [Novik/ruTorrent#2585]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Opera GX LVL5 (core: 102.0.4880.114) (Chromium: 116.0.5845.188)
ruTorrent: v4.2.6-hotfix
PHP: PHP 8.2.11

### Give us detailed steps to reproduce the error

Fresh install of AlmaLinux 8 (CentOS-like)
Install [Virtualmin](https://www.virtualmin.com/download/) using official installation script
Making a domain for the seedbox
Install and configure rtorrent for SCGI (RPC socket doesn't work) according to [ruTorrent wiki](https://github.com/Novik/ruTorrent/wiki/MainInstall)
Download, unzip and configure ruTorrent config file (links are set, including Python)
Start rtorrent with the user that owns web server
Install missing packages (pip3 install cloudscraper, dnf install mediainfo, etc.)
Start rtorrent again

### Tell us the error message

```
[30.10.2023 11:34:21] WebUI started.
[30.10.2023 11:34:22] Bad response from server: (500 [error,list]) Warning: XMLRPC call is failed.
```

### Provide the php error log contents (if applicable)

```
[29-Oct-2023 03:39:14] NOTICE: error log file re-opened
[29-Oct-2023 03:39:18] NOTICE: Terminating ...
[29-Oct-2023 03:39:18] NOTICE: exiting, bye-bye!
[29-Oct-2023 03:39:18] NOTICE: fpm is running, pid 425337
[29-Oct-2023 03:39:18] NOTICE: ready to handle connections
[29-Oct-2023 03:39:18] NOTICE: systemd monitor interval set to 10000ms
```

**Comment by stickz** [comment]
It sounds like you were unable to setup rtorrent and/or the ruTorrent stack properly. This is a generic error that means ruTorrent is unable to contact rTorrent. These are notices in your php error log file - they are not errors.

**Comment by Oreloth** [comment]
I found an alternative that works without hours of workaround. Anyway thank you.
