### ISSUE TITLE
Stable.js error

### ISSUE THREAD

**Issue by Csaba27** [Novik/ruTorrent#2590]
### Please complete the following tasks.

- [x] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Firefox
Rutorrent v4.2.7

### What were you trying to do?

Always

### What us the error message?

[06.11.2023 10:38:06] JS error: /js/stable.js?v=427 : 1786] TypeError: can't convert undefined to object

**Comment by Csaba27** [comment]
> ### Please complete the following tasks.
> * [x]  Web browser cache cleared
> * [x]  Copied everything if upgrading to v4.0 or master
> * [x]  Web browser and ruTorrent version provided
> 
> ### Tell us about your environment
> Firefox Rutorrent v4.2.7
> 
> ### What were you trying to do?
> Always
> 
>

**Comment by stickz** [comment]
Could you please provide a full stack trace from developer console? Along with an explanation of what you were trying to do? This is not enough information to investigate the problem.

**Comment by Csaba27** [comment]
This error then occurs when i try to open torrenr files section
Developer console content:
TypeError: can't convert undefined to object from dxSTable.prototype.setAttr@https://host/js/stable.js?v=427:1786:29
dxSTable.prototype.setRowById@https://host/js/stable.js?v=427:1136:76
redrawFiles@https://host/js/webui.js?v=427:1233:12
addFiles@https://host/js/webui.js?v=427:1280:15
Ajax/<@https://host/js/rtorrent.js?v=427:1301:22
c@https://host/js/jquery.js?v=427:2:25266
fireWith@https://host/js/jquery.js?v=427:2:26015
l@https://host/js/jquery.js?v=427:2:77721
send/o/<@https://host/js/jquery.js?v=427:2:80204

**Comment by stickz** [comment]
Resolved in [v4.2.8](https://github.com/Novik/ruTorrent/releases/tag/v4.2.8).
