### ISSUE TITLE
File list disappears after failure to download file

### ISSUE THREAD

**Issue by Csaba27** [Novik/ruTorrent#2600]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 119.0.6045.160 
ruTorrent: v4.2.8
PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
OS: Ubuntu 22.04.3 LTS

### Tell us how you installed ruTorrent

Rtorrent installed via repo with default .rtorrent.rc config file, Rutorrent from git

### Describe the bug

So I want to download an NFO file for example from torrent files.
After double-click a file in the "Files" section, all files are disappearing. When I open the browser console and then I try it again, then it works.

### Steps to reproduce

1. Click a torrent
2. Click "Files" section
3. Double click to download a file
4. After this see the error (everything disappears)

**Comment by Csaba27** [comment]
There is no JavaScript error or PHP. The file download sometimes working with double click sometimes not.

**Comment by stickz** [comment]
Fixed in [v4.2.9](https://github.com/Novik/ruTorrent/releases/tag/v4.2.9).

**Comment by Csaba27** [comment]
Nice work, thank you!
