### ISSUE TITLE
Torrent File Completion Percentage Incorrect

### ISSUE THREAD

**Issue by THELASTOFUS** [Novik/ruTorrent#2608]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

RuTorrent 4.2.7
Web Browser: Chrome
OS: Linux Debian Bookworm 12

### Tell us how you installed ruTorrent

[Swizzin](https://swizzin.ltd/applications)

### Describe the bug

Downloaded files for partial torrents are showing incorrect %'s even though they have 100% been downloaded. Download from seperate client (qbittorrent) to same directory and "checking files" shows files at 100% but RuTorrent showing them at 90%, 85.2%, etc. 

### Steps to reproduce

Attempt partial file download via magnet link

### Expected behavior

Files to properly report percentages

**Comment by stickz** [comment]
This is related to an rTorrent patch on swizzin. It's best to file a bug report with the swizzin project.
https://github.com/swizzin/swizzin/issues
