### ISSUE TITLE
Automove works only when i first login into the webpage

### ISSUE THREAD

**Issue by j4ckp0t85** [Novik/ruTorrent#2609]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Hi, i'm using latest version of rutorrent (4.2.9) with rtorrent 0.98, php 8.2.10 running on a raspberry 4 Ubuntu 23.10 OS.

I have noticed that automove function on torrent completion triggers only when i first open the rutorrent page and login.
Every time i power off and on the system, i should repeat the login process to enable the feature.

Any suggestions or similar experience? I have no clue 

### Give us detailed steps to reproduce the error

Enable automove. Do a shutdown of the host system and power on. Verify if automove works even without logging in webinterface

### Tell us the error message

Server error

**Comment by j4ckp0t85** [comment]
Fixed my problem following those suggestions, found on a forum

```
a couple things to check:

php extensions.

you may be missing one that is important. I'm PRETTY sure you need the xmlrpc php extension

Also, which distro are you using? i know on FreeBSD this didn't work properly for me at first because my php binary was using php-cgi and not php-cli

and one other thing, if you are using php-cli, you need to find the config file and make sure register_argc_argv is on.

Those are the first things i'd check.
```

**Comment by j4ckp0t85** [comment]
Provided resolution found online

**Comment by j4ckp0t85** [comment]
Ok, think i found at least a workaround.
I've created a script to do a login on the web interface using lynx.

If you have any better solution let me know

**Comment by TrimmingFool** [comment]
@j4ckp0t85 I guess, you are not using this config:

https://github.com/Novik/ruTorrent/blob/53abb07798f209496284a7641178e2e1e8c28502/php/initplugins.php#L5-L10

Maybe you could try [the docker-rtorrent-rutorrent image by crazymax](https://github.com/crazy-max/docker-rtorrent-rutorrent) since it includes this config:

https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/56abffe6f59c52880359afe3589c101833fb2abb/rootfs/tpls/etc/rtorrent/.rtlocal.rc#L55-L56

**Comment by j4ckp0t85** [comment]
> @j4ckp0t85 I guess, you are not using this config:
> 
> https://github.com/Novik/ruTorrent/blob/53abb07798f209496284a7641178e2e1e8c28502/php/initplugins.php#L5-L10
> 
> Maybe you could try [the docker-rtorrent-rutorrent image by crazymax](https://github.com/crazy-max/docker-rtorrent-rutorrent) since it includes this config:
> 
> https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/56abffe6f59c52880359afe3589c101833fb2abb/rootfs/tpls/etc/rtorrent/.rtlocal.rc#L55-L56

Good hint thank you, that did the trick. Had to adjust paths (and username of course) on mentioned conf entry on my rtorrent.rc file and it works.
