### ISSUE TITLE
TypeError: the UILang.MoveView is undefined - pnlViews

### ISSUE THREAD

**Issue by codog180** [Novik/ruTorrent#2614]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Firefox: 120.0.1
ruTorrent: v4.2.9

### What were you trying to do?

Right click on a new pnlView to try to rename. 

### What us the error message?

JS error: [http://rutorrent.mynetwork.com/js/webui.js?v=429: 2083] TypeError: the UILang.MoveView is undefined

### Give us the stack trace.

Cookie “browser_timezone” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite common.js:1644:62
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. rutorrent.mynetwork.com
TypeError: theUILang.MoveView is undefined from contextMenuEntries@http://rutorrent.mynetwork.com/js/webui.js?v=429:2083:20
theWebUI.contextMenuEntries@http://rutorrent.mynetwork.com/ line 2 > injectedScript:3326:31
theWebUI.contextMenuEntries@http://rutorrent.mynetwork.com/ line 2 > injectedScript:5851:35
theWebUI.contextMenuEntries@http://rutorrent.mynetwork.com/ line 2 > injectedScript:7071:44
labelContextMenu@http://rutorrent.mynetwork.com/js/webui.js?v=429:2044:29
mouseclick/</<@http://rutorrent.mynetwork.com/js/common.js?v=429:166:64
dispatch@http://rutorrent.mynetwork.com/js/jquery.js?v=429:2:39997
add/v.handle@http://rutorrent.mynetwork.com/js/jquery.js?v=429:2:37968
3 webui.js:3188:14

**Comment by stickz** [comment]
Does this happen in other web browsers such as Google Chrome? 
Do you have any further detailed to help reproduce this issue? I'm not able to reproduce this problem simply by renaming a view.

**Comment by codog180** [comment]
Hello,

Interestingly enough the problem only seemed to exist on Firefox. However,
when I loaded it into chrome I was able to rename the view. Once I renamed
the view and cleared the cache in firefox, I was able to create and rename
views without issue. I had tried clearing the cache and reloading firefox
several times before attempting anything in chrome so there must have been
something stuck that loading and making a change in the other browser
cleared out. Please feel free to close out this ticket. Thank you
