### ISSUE TITLE
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

### ISSUE THREAD

**Issue by bartsimp** [Novik/ruTorrent#2618]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Web Browser: Google Chrome 120.0.6099.111

server side:
rutorrent 4.2.8
rtorrent 0.9.8
PHP 8.2.13
lighttpd 1.4.73
Alpine Linux running via LinuxDeploy on Samsung S2 i9100, Android 4.1.2

### Give us detailed steps to reproduce the error

Hello, I’m struggling with this a bit. (I apologize if this is not the correct section to post problems)

I start services with
```
sudo rc-service -v php-fpm82 start; sudo rc-service -v lighttpd start; sudo rc-service -v rtorrentd start
```

then check the open ports:
```
netstat -nat
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 ::ffff:127.0.0.1:5000   :::*                    LISTEN
tcp        0      0 :::50000                :::*                    LISTEN
```

and test the xml-rpc connection:
```
python test_rutorrent.py
Connecting to 'http://localhost/RPC2'...
<ServerProxy for localhost/RPC2>
Session:         localhost:6062
XMLRPC methods:  738
Time (usec):     1703434128089087 (2023-12-24T17:08:48.089087)
OK
```

but I still have the error
"No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file."

here below my config files:
**/etc/lighttpd/lighttpd.conf**
```
[...]
import "mod_scgi_host.conf"
[...]
```

**/etc/lighttpd/mod_scgi_host.conf**
```
server.modules += ("mod_scgi")

scgi.server =(
"/RPC2" =>
	( "localhost" =>
			(
			"host" => "127.0.0.1",
			"port" => "5000",
			"check-local" => "disable"
			)
		)
	)
```
**/var/www/localhost/htdocs/rutorrent/conf/config.php**
```
[...]
$scgi_port = 5000;
$scgi_host = "127.0.0.1";
[...]
```

**/home/android/.rtorrent.rc**
```
[...]
network.scgi.open_port = "127.0.0.1:5000"
[...]
```

### Tell us the error message

 "No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file."

**Comment by bartsimp** [comment]
php-mbstring and php-dom already installed

**Comment by stickz** [comment]
Try to use a unix socket instead. This is more secure and easier than ports.

**/etc/lighttpd/mod_scgi_host.conf**
```
scgi.server =( ".php" => ((
                    "bin-path" => "/usr/local/bin/php-cgi",
                    "socket" => "/var/run/android/.rtorrent.sock",
                    "max-procs" => 1,
                    "bin-environment" => (
                      "PHP_FCGI_CHILDREN" => "3",
                      "PHP_FCGI_MAX_REQUESTS" => "1000"
                    ),
                    "bin-copy-environment" => (
                      "PATH", "SHELL", "USER"
                    ),
                    "broken-scriptfilename" => "enable"
                )))
```

**/home/android/.rtorrent.rc**
```
schedule2 = chmod_scgi_socket, 0, 0, "execute2=chmod,\"g+w,o=\",/var/run/android/.rtorrent.sock"
network.scgi.open_local = /var/run/android/.rtorrent.sock
```

**/var/www/localhost/htdocs/rutorrent/conf/config.php**
```
$topDirectory = '/home/android';
$scgi_port = 0;
$scgi_host = "unix:///var/run/android'/.rtorrent.sock";
$XMLRPCMountPoint = "/android'";
```

**Comment by stickz** [comment]
Please feel free to comment here if have a follow. I'm going to close this question. It's been two weeks.

**Comment by bartsimp** [comment]
I tried your socket solution but it still doesn't work :(

**Comment by gstrauss** [comment]
> here below my config files:
> /etc/lighttpd/lighttpd.conf
```
[...]
import "mod_scgi_host.conf"
[...]
```

The most basic troubleshooting steps involve checking that your syntax is correct and that the service is running.  If you do not know how to do that, it is in your best interest to find out how to do exactly that.

`import` is not valid in lighttpd.conf syntax.  Testing your lighttpd config work report that error.  Testing your lighttpd config is a step included in every reasonable tutorial, e.g. the lighttpd 5 minute tutorial: https://wiki.lighttpd.net/TutorialConfiguration
It seems like you have not done that?

**Comment by bartsimp** [comment]
@gstrauss thanks for your clarification (you're right) **but** actually "import" it was just a typo while writing here.
My real configuration has always been with the "include" keyword

[...]
include "mod_scgi_host.conf"
[...]

Anyway, I guess that lighttpd service is running as reported by the "netstat -nat" output

**Comment by bartsimp** [comment]
switched to unix socket and solved by setting 
chmod **777** /home/android/rtorrent/.session/rpc.socket

I suppose I need to investigate about how to set the right permissions

**Comment by gstrauss** [comment]
Only one process should create the listening socket.  If you're using PHP-FPM, then that PHP-FPM process should create the listening socket and should set ownership (e.g. group) and permissions appropriately so that the web server can access the socket.  If PHP-FPM is creating the socket, then lighttpd should not be configured to create the socket and you should omit `"bin-path"` from `scgi.server` for that socket.
