### ISSUE TITLE
Files right click theWebUI.dirs[theWebUI.dID] is undefined 

### ISSUE THREAD

**Issue by Csaba27** [Novik/ruTorrent#2631]
### Please complete the following tasks.

- [x] Web browser cache cleared
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Web browser: latest firefox and chrome

### What were you trying to do?

Click files section and rigth click and throws error

### What us the error message?

**Firefox:**
S error: [https://***/rutorrent/ line 2 &gt; injectedScript : 2818] TypeError: theWebUI.dirs[theWebUI.dID] is undefined

**Chrome:**
JS error: [ : 2818] Uncaught TypeError: Cannot read properties of undefined (reading 'isDirectory')

### Give us the stack trace.

**Firefox:**
TypeError: theWebUI.dirs[theWebUI.dID] is undefined from plugin.ui.handleTorrentFilesMenu@https://***/rutorrent/ line 2 > injectedScript:2818:23
[plugin.ui.init/theWebUI.createFileMenu@https://***/rutorrent/](chrome://devtools/content/webconsole/plugin.ui.init/theWebUI.createFileMenu@https://***/rutorrent/) line 2 > injectedScript:2987:31
flsSelect@https://***/rutorrent/js/webui.js?v=429:1295:19
onselect@https://***/rutorrent/js/webui.js?v=429:53:40
dxSTable.prototype.selectRow@https://***/rutorrent/js/stable.js?v=429:1129:8

**Chrome:**
Uncaught TypeError: Cannot read properties of undefined (reading 'isDirectory') from TypeError: Cannot read properties of undefined (reading 'isDirectory')
    at plugin.ui.handleTorrentFilesMenu (<anonymous>:2818:51)
    at theWebUI.createFileMenu (<anonymous>:2987:31)
    at Object.flsSelect (https://***/rutorrent/js/webui.js?v=429:1295:19)
    at dxSTable.onselect (https://***/rutorrent/js/webui.js?v=429:53:40)
    at dxSTable.selectRow (https://***/rutorrent/js/stable.js?v=429:1129:8)
    at dxSTable.handleClick (https://***/rutorrent/js/stable.js?v=429:265:8)
    at HTMLTableSectionElement.<anonymous> (https://***/rutorrent/js/common.js?v=429:166:64)
    at HTMLTableSectionElement.dispatch (https://***/rutorrent/js/jquery.js?v=429:2:39997)
    at v.handle (https://***/rutorrent/js/jquery.js?v=429:2:37968)

**Comment by stickz** [comment]
1) Can you be more specific about what caused this to happen? Simply right clicking on a file does not cause this problem to happen for me. I tried a torrent with folders as well.

2) Did you clear your web browser cache when upgrading versions?

**Comment by Csaba27** [comment]
1. There are only problems with 2 webuis, even though there are 6 on the server, there are only problems with these two. I am thinking about what data can be sed to yout for detect the problem. If you want I can send you access, to login a check it.
2. Yes the web browser cache already cleared

**Comment by Csaba27** [comment]
Interesting, the problem solved, I deleted the /share/users/[exampleuser]/ settings  and tmp directories, now i can click files section

**Comment by Csaba27** [comment]
share/users/exampleuser/settings .dat files occured the problem, I already deleted them.

**Comment by stickz** [comment]
Do you know which version of ruTorrent those old settings files are from? This is likely a version upgrade issue.

**Comment by Csaba27** [comment]
There were 4.2 versions, but as soon as a new version came out, I immediately upgraded it, but there were no errors immediately after the version update.

**Comment by w4hnsinn** [comment]
This was caused (for me) by clicking "View > As List" in the Files tab of a torrent with several files selected. I have no clue what that option does, so I wanted to check it out. 

Teach me to assume there are non-app-breaking options in the right-click menu.. 

Will try to delete the .dat files that @Csaba27 indicated and report back after.

**Comment by Csaba27** [comment]
I've deleted the .dat files, that helped with the problem, thanks

**Comment by jevenski** [comment]
This is a third-party plugin issue: [filemanager](https://github.com/nelu/rutorrent-filemanager). It only occurs when the file list tab is set to "List View" and right-clicking on any of the files in the file list. Disabling that plugin will take this error away, the conclusion can be confirmed.

Removing "WebUISettings.dat" file might not be the best solution, because this will wipe all the user defined UI settings and restore everything to default. As a workaround, disabling the filemanager plugin and set file list back to "Tree View" is a better solution.

**Comment by stickz** [comment]
Please open an issue reports with the third party plugin. This issued is not related to the base ruTorrent.
