### ISSUE TITLE
"Remove" torrent now deletes data 

### ISSUE THREAD

**Issue by dstyp** [Novik/ruTorrent#2632]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Tested on macOS 14.2.1 - Firefox 121.0.1 & Chrome 120.0.6099.234
ruTorrent: 4.2.9
PHP: PHP 8.2.7
OS: Debian 12

### Tell us how you installed ruTorrent

Docker - https://github.com/crazy-max/docker-rtorrent-rutorrent/

### Describe the bug

Right-click a torrent in list and choosing "Remove" will now delete all data. No prompt or warning. This all while rendering the remaining file still present but with 0b. This is what I assume is the same behavior that "Remove And... - Delete Data" should do.

Change in behavior that seems like a bug but am not sure if I missed some update where this behavior changed? If so - what is the option "Remove And... - Delete Data" supposed to do?

### Steps to reproduce

1. Open rutorrent and have a completed torrent in the list
2. Choose "Remove"
3. Torrent data will be deleted

### Expected behavior

Remove torrent from rutorrent (list) but keep all data intact.

### Additional context

Thanks for a great app! :)

**Comment by stickz** [comment]
@dstyp This is related to the docker container. Could you make an issue report there? I will respond and tell you how to fix it.
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues

I don't want people getting confused and thinking this is an ruTorrent bug or not being able to find the solution to the problem.

**Comment by dstyp** [comment]
> @dstyp This is related to the docker container. Could you make an issue report there? I will respond and tell you how to fix it. https://github.com/crazy-max/docker-rtorrent-rutorrent/issues
> 
> I don't want people getting confused and thinking this is an ruTorrent bug or not being able to find the solution to the problem.

Oh, is it? Ok sorry about this. Closing this then.
