### ISSUE TITLE
ubuntu 18.04 fresh install rutorrent 4.2.10, with following errors.

### ISSUE THREAD

**Issue by SMooxx** [Novik/ruTorrent#2636]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

web browser:firefox
rutorrent : v4.2.10
php: php 7.2
OS:ubuntu 18.04

###############################
###############################

mkdir -p /var/www
cd /var/www

echo -n "RuTorrent: "; check_url $ru_url && echo "OK" || { echo "FAIL"; early_exit; }

if [ -d "/var/www/rutorrent" ]; then
  rm -r /var/www/rutorrent
fi

if [ $rudevflag = 1 ]; then
   rurelease=$(curl -s "https://api.github.com/repos/Novik/ruTorrent/releases/latest" | awk -F '"' '/tag_name/{print $4}')
fi

echo "Installing Rutorrent ($rurelease)" | tee -a $logfile
wget -q https://github.com/Novik/ruTorrent/archive/$rurelease.tar.gz | tee -a $logfile
tar -xzf $rurelease.tar.gz
mv $(tar -tzf $rurelease.tar.gz | head -1) rutorrent
rm $rurelease.tar.gz

echo "Configuring Rutorrent" | tee -a $logfile
rm rutorrent/conf/config.php
cp -f /etc/rtinst/conf/ru.config /var/www/rutorrent/conf/config.php
mkdir -p /var/www/rutorrent/conf/users/$user/plugins

echo "<?php" > /var/www/rutorrent/conf/users/$user/config.php
echo >> /var/www/rutorrent/conf/users/$user/config.php
echo "\$homeDirectory = \"$home\";" >> /var/www/rutorrent/conf/users/$user/config.php
echo "\$topDirectory = \"$home\";" >> /var/www/rutorrent/conf/users/$user/config.php
echo "\$scgi_port = 5000;" >> /var/www/rutorrent/conf/users/$user/config.php
echo "\$XMLRPCMountPoint = \"/RPC2\";" >> /var/www/rutorrent/conf/users/$user/config.php
echo >> /var/www/rutorrent/conf/users/$user/config.php
echo "?>" >> /var/www/rutorrent/conf/users/$user/config.php

cp -f /etc/rtinst/conf/ru.ini /var/www/rutorrent/conf/plugins.ini
if [ $osname = "Raspbian" ]; then
  sed -i '/\[screenshots\]/,+1d' /var/www/rutorrent/conf/plugins.ini
  sed -i '/\[unpack\]/,+1d' /var/www/rutorrent/conf/plugins.ini
  echo '[screenshots]' >> /var/www/rutorrent/conf/plugins.ini
  echo 'enabled = no' >> /var/www/rutorrent/conf/plugins.ini
  echo '[unpack]' >> /var/www/rutorrent/conf/plugins.ini
  echo 'enabled = no' >> /var/www/rutorrent/conf/plugins.ini
fi

### Describe the bug

fresh install on ubuntu 18.04

[08.02.2024 23:55:11] WebUI started.
[08.02.2024 23:55:14] JS error: [http://10.0.1.139/rutorrent/js/jquery.js?v=4210 : 2] Uncaught ReferenceError: clearCanvas is not defined
[08.02.2024 23:55:14] JS error: [http://10.0.1.139/rutorrent/js/jquery.js?v=4210 : 2] Uncaught ReferenceError: clearCanvas is not defined
[08.02.2024 23:55:14] autodl-irssi: __init2: ex: Exception info: No content elem with id autodl-prefs-contents-upload
[08.02.2024 23:55:15] JS error: [http://10.0.1.139/rutorrent/js/jquery.js?v=4210 : 2] Uncaught ReferenceError: clearCanvas is not defined
[08.02.2024 23:55:15] JS error: [http://10.0.1.139/rutorrent/js/jquery.js?v=4210 : 2] Uncaught ReferenceError: clearCanvas is not defined
[09.02.2024 00:01:04] JS error: [http://10.0.1.139/rutorrent/js/jquery.js?v=4210 : 2] Uncaught ReferenceError: clearCanvas is not defined

**Comment by stickz** [comment]
closing this off. rtinst is broken. https://github.com/Novik/ruTorrent/discussions/2482
