### ISSUE TITLE
 XMLRPC Error: Could not find view: rat_1 [setratio]

### ISSUE THREAD

**Issue by Commissar0617** [Novik/ruTorrent#2640]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Firefox 123.0
RUtorrent 3.9
PHP unknown
OS: windows 11

### Tell us how you installed ruTorrent

seedbox provider script

### Describe the bug

 XMLRPC Error: Could not find view: rat_1 [setratio]
when setting a ratio for tracker or torrent

### Steps to reproduce

right click on tracker, set ration group

### Expected behavior

should assign the ratio group

**Comment by stickz** [comment]
Please inform you seed box provider we no longer support ruTorrent version 3. They need to upgrade to version 4. If they have any questions about the upgrade process or how to make plugins compatible, they can follow up here. Point them this ticket.
