### ISSUE TITLE
JS error: [MyIP/rutorrent/js/webui.js?v=4210 : 1554] Uncaught TypeError: Cannot read properties of undefined (reading 'state')

### ISSUE THREAD

**Issue by antonio8909** [Novik/ruTorrent#2642]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Microsoft Edge 122.0.2365.80
ruTorrent: v4.2.9
PHP: 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
OS: Ubuntu 22.04.4 LTS

### Tell us how you installed ruTorrent

Via swizzin community edition

### Describe the bug

When I try to delete an specific RSS feed it says  JS error: [MyIP/rutorrent/js/webui.js?v=4210 : 1554] Uncaught TypeError: Cannot read properties of undefined (reading 'state') and I can't delete it. I have others RSS feeds that can be deleted without issue. I'm hitting this issue on a specific RSS.

### Steps to reproduce

1. Go to the Feeds section and find the RSS Feed to delete
2. Right-click to get the menu to edit or delete the feed
3. The error appears

### Expected behavior

Being able to access to the menu to edit and delete the feed

**Comment by antonio8909** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'state') from TypeError: Cannot read properties of undefined (reading 'state')
    at Object.isTorrentCommandEnabled (https://MyIP/rutorrent/js/webui.js?v=4210:1554:39)
    at theWebUI.isTorrentCommandEnabled (<anonymous>:2419:41)
    at theWebUI.isTorrentCommandEnabled (<anonymous>:5573:38)
    at theWebUI.createMenu (<anonymous>:5536:11)
    at theWebUI.createMenu (<anonymous>:5659:21)
    at theWebUI.createMenu (<anonymous>:6010:21)
    at theWebUI.createMenu (<anonymous>:6512:21)
    at theWebUI.createMenu (<anonymous>:7542:21)
    at theWebUI.createMenu (<anonymous>:8405:21)
    at theWebUI.createMenu (<anonymous>:8745:21)

**Comment by TrimmingFool** [comment]
@antonio8909 Do you have an idea why this is only a problem for one specific RSS feed? I don't know how to reproduce this.

My guess would be, that for some reason there is `id === null` here:

https://github.com/Novik/ruTorrent/blob/2d67a00b4fde90b4a652c130ed76ac2fc4383fb3/plugins/rss/init.js#L468-L477


If you are able, it would be great if you could use the debugger to say if the `id` is `null` or some rss-url for this call.

You could either set a breakpoint on exceptions:
https://developer.chrome.com/docs/devtools/javascript/breakpoints#exceptions
OR
https://developer.chrome.com/docs/devtools/search
Go to rss createMenu function (by searching for `'context menu for rss item'` via `Ctrl-Shift-F`) and set a break point on the `plugin.createMenu.call(theWebUI, e, id);`  line

**Comment by antonio8909** [comment]
Hi @TrimmingFool 

I don't know the reason why it's failing just in that RSS. I'd try on older ruTorrent releases in another server (3.10, for example) and it works fine :/

I hope this helps!!

![image](https://github.com/Novik/ruTorrent/assets/5004766/870e4f12-8d77-44bb-a0ef-1e218813bf0e)

Thank you very much

**Comment by stickz** [comment]
Thanks @antonio8909. This is all the information we require.

@TrimmingFool Do you agree we should rewrite this code block? It's redundant and causing errors to appear.
https://github.com/Novik/ruTorrent/blob/2d67a00b4fde90b4a652c130ed76ac2fc4383fb3/plugins/rutracker_check/init.js#L48-L63

```js
plugin.isTorrentCommandEnabled = theWebUI.isTorrentCommandEnabled;
theWebUI.isTorrentCommandEnabled = function(act,hash) 
{
	if(act=="checktorrent")
                return(true);

	return(plugin.isTorrentCommandEnabled.call(this,act,hash));
}
```

We already know this should be returning true. The value of `act` does not fall within the scope of the case statement.
https://github.com/Novik/ruTorrent/blob/2d67a00b4fde90b4a652c130ed76ac2fc4383fb3/js/webui.js#L1551-L1584

**Comment by TrimmingFool** [comment]
Sorry for the delay. Actually, the assumption which is broken here is that all links are in `theWebUI.rssItems`.
@stickz So, if we want to keep the workaround with the regex for now,
it should replace the `if (id in this.rssItems) { ` check. (I'm not sure but the check `if (id in theWebUI.getTable('rss').rowSel) {` might be a better workaround.)

@antonio8909 
That is exactly what I wanted, thank you! I would still like to find the actual bug. Could you please provide the output of this array expression (during the breakpoint in the console):

```javascript
[
hash in theWebUI.rssItems,
theWebUI.getTable('rss').rowSel[hash],
hash in theWebUI.getTable('rss').rowIDs,
hash === theWebUI.getTable('rss').getFirstSelected() ,
theWebUI.getTable('rss').getFirstSelected() == null,
Object.keys(theWebUI.rssItems).length,
theWebUI.getTable('rss').rowIDs.length
]
```

**Comment by antonio8909** [comment]
I'm so sorry @TrimmingFool 

I saw yesterday that the hotfix was available and I quickly applied it to manage again my RSS feeds so I can't reproduce again the bug.

My deepest apologies.

**Comment by TrimmingFool** [comment]
@antonio8909 It's not a big deal. Maybe the root cause for this will disappear with https://github.com/Novik/ruTorrent/issues/2637 when the table uses `guid` instead of `href`.
