### ISSUE TITLE
Adding some RSS links still does not work [v4.3.0-stable]

### ISSUE THREAD

**Issue by luckylittle** [Novik/ruTorrent#2646]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chromium `113.0.5750.0`
ruTorrent: [v4.3.0-stable](https://github.com/Novik/ruTorrent/releases/tag/v4.3.0)
PHP: php-`7.2.24` + php-fpm-`7.2.24`
HTTPD: lighttpd-`1.4.67` + lighttpd-fastcgi-`1.4.67`
OS: Red Hat Enterprise Linux release `8.9` (Ootpa)

### Tell us how you installed ruTorrent

[ansible-role-zero-footprint-ruT-seedbox](https://github.com/luckylittle/ansible-role-zero-footprint-ruT-seedbox)

### Describe the bug

I have upgraded yesterday from v4.0-beta2.1 to v4.3 stable and my RSS feeds disappeared, everything else is working fine. I then tried to manually re-add one feed and it did not work, so I've spent hours investigating what's wrong with my lighttpd/php setup only to find the following bug reports:
* https://github.com/Novik/ruTorrent/issues/2500 
* https://github.com/Novik/ruTorrent/issues/2501

This gave me an idea to try different feeds and some of them worked, to my surprise. Below is a summary of the ones that work and don't work. They all worked previously by the way!

Error in Chrome 500 Internal Server Error:

```
/plugins/rss/action.php 500
send @ jquery.js?v=430:2
ajax @ jquery.js?v=430:2
Ajax @ rtorrent.js?v=430:1237
requestWithTimeout @ webui.js?v=430:2419
theWebUI.processRSS @ VM82:3629
theWebUI.addRSS @ VM82:3635
onclick @ (index):1
```

Error in `/var/log/lighttpd/error.log`

```
(http-header-glue.c.1342) read() 12 11: Connection reset by peer
(gw_backend.c.2428) response not received, request sent: 1551 on socket: unix:/run/php-fpm/www.sock for /plugins/rss/action.php?, closing connection
```

Error in `/var/log/php-fpm/error.log`

```
WARNING: [pool www] child 1952049 exited on signal 11 (SIGSEGV) after 5813.732129 seconds from start
NOTICE: [pool www] child 1953757 started
```

### Steps to reproduce

1. Right click on **All Feeds**
2. **Add RSS Feed**
3. Feed URL: `https://<HOSTNAME>/api/v1/rss?key=<PASSKEY>`
4. Custom alias: `<NAME>`

### Expected behavior

Feed is added and automatically gets updated as per the update interval.

### Additional context

RSS feeds that worked:
* `https://<REDACTED>/rss.php?feed=dl&cat=45%2C44%2C22%2C43%2C27%2C4%2C40%2C19%2C6%2C31%2C49%2C7%2C48%2C46&passkey=<PASSKEY>&torrentonly=yes`
* `https://<REDACTED>/rss.php?sort=0&type=d&key=<PASSKEY>&ddl`
* `https://<REDACTED>/rss/<ID>.<PASSKEY>`

Not working RSS feeds:
* `https://<REDACTED>/rssdl.php?passkey=<PASSKEY>`
* `https://<REDACTED>/t.rss?u=<REDACTED>;tp=<PASSKEY>;48;22;5;download;free`
* `https://<REDACTED>/feeds.php?feed=<REDACTED>&user=<REDACTED>&auth=<REDACTED>&passkey=<PASSKEY>&authkey=<REDACTED>&name=<REDACTED>`
* `https://<REDACTED>/rss.php?cat=7&passkey=<PASSKEY>&limit=50`
* `https://<REDACTED>/t.rss?15;6;19;12;28;45;47;95;30;43;102;20;42;29;16;41;32;3;1;13;48;22;21;24;23;82;11;25;44;5;34;96;9;31;2;33;4;46;17;14;26;7;10;18;8;27;free;download;u=<REDACTED>;tp=<PASSKEY>;<REDACTED>;private;do-not-share
<REDACTED>`
* `https://<REDACTED>/api/v1/rss?passkey=<PASSKEY>`

**Comment by stickz** [comment]
Thank you @luckylittle for the detailed bug report. 

Before we dig into it further, could you let us know if you have the `dom` and `libxml` extensions? https://github.com/Novik/ruTorrent/blob/4e47301f36d04d219b76c71ed4fd8d37e8b62e4f/plugins/rss/rss_reader.php#L123

Also, we have PHP 7.4 listed as a minimum requirement for ruTorrent on our wiki. We can guarantee compatibility all the way up PHP 8.2 due to extensive testing. Are you able to upgrade your PHP version, to see if the problem persists?
https://github.com/Novik/ruTorrent/wiki#minimum-requirements

**Comment by luckylittle** [comment]
@stickz 
Many thanks, indeed I was missing those extensions. Installing them did the trick and now I can add all of the RSS feeds that were not working previously. Can the minimum requirements be updated with these extensions?
Fix: `sudo dnf install php-mbstring php-dom php-libxml`

**Comment by stickz** [comment]
@luckylittle 
I've updated the wiki to include these php extensions. I also added php extension warnings for RSS plugin. Users will receive a warning when they startup their web interface. It will inform them the php extensions were not found.
