### ISSUE TITLE
MaterialDesign theme broken on v4.3.0

### ISSUE THREAD

**Issue by jakobbg** [Novik/ruTorrent#2647]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web browser: Chrome on Mac (v 123.0.6312.87)
ruTorrent: v4.3.0
PHP: Version 8.3.4
OS: FreeBSD 14.0-RELEASE-p6 

### Tell us how you installed ruTorrent

Downloaded from Github, switched tag.

### Describe the bug

Left pane has white background, visibility is … low :-) See attached.

<img width="1211" alt="Skjermbilde 2024-04-02 kl  00 02 23" src="https://github.com/Novik/ruTorrent/assets/142172/98a63c52-a96b-426c-9b60-516f6ea957dd">

### Steps to reproduce

1. Choose theme MaterialDesign
2. Observe left pane with white background and low visibility

### Expected behavior

Left pane with black background.

### Additional context

n/a

**Comment by stickz** [comment]
@jakobbg Thank you for the bug report. Please verify you have cleared your web browser cache. This looks like a stale cache.
I tested it on my machine on ruTorrent v4.3 with PHP 8.1. The background of the left pane was black after clearing cache.
