### ISSUE TITLE
Material Design menus are not welll visible

### ISSUE THREAD

**Issue by ChriZathens** [Novik/ruTorrent#2655]
### Is your feature request related to a problem?

Material Design menus are not easily visible before hovering
Several menus, including settings are really hard to read in Material Design theme
![Capture](https://github.com/Novik/ruTorrent/assets/8545172/29f388ad-9e7c-4eb4-b733-352668b1d2c5)
### Describe the solution you'd like

A more visible font color would be nice

### Additional context

Posting this as a feature request, because people with different screen/resolutions may not really have that much of a problem.. Or perhaps it has to do with the fact that I am getting old... :)

**Comment by stickz** [comment]
@ChriZathens `ruTorrent v4.3.1` releasing shortly with the fixes you've requested for the Material Design theme.

**Comment by ChriZathens** [comment]
> @ChriZathens `ruTorrent v4.3.1` releasing shortly with the fixes you've requested for the Material Design theme.

Thanks a lot!
Much appreciated 👍
