### ISSUE TITLE
Some Uncaught TypeError since 4.3.x update

### ISSUE THREAD

**Issue by fana13** [Novik/ruTorrent#2657]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Microsoft Edge Version 124.0.2478.80 
ruTorrent v4.3.0 or 4.3.1

### What were you trying to do?

Open webUI page or click on left labels
I tried to open it on private browser session and tried with another Firefox browser too

### What us the error message?

JS error: [https://xxx/rutorrent/ : 7865] Uncaught TypeError: Cannot read properties of undefined (reading 'push')
JS error: [https://xxx/rutorrent/ : 4612] Uncaught TypeError: theWebUI.updateLabel is not a function
JS error: [https://xxx/rutorrent/ : 6571] Uncaught TypeError: Cannot read properties of undefined (reading 'flabel_cont')
![screenshot](https://github.com/Novik/ruTorrent/assets/14030280/21384d10-1ec9-49be-9541-efd9400c6ab8)

### Give us the stack trace.

> JS error: [https://xxx/rutorrent/ : 7865] Uncaught TypeError: Cannot read properties of undefined (reading 'push') from TypeError: Cannot read properties of undefined (reading 'push')
    at <anonymous>:7865:30
    at <anonymous>:8190:3
    at m (https://xxx/rutorrent/js/jquery.js?v=431:2:880)
    at Function.globalEval (https://xxx/rutorrent/js/jquery.js?v=431:2:3031)
    at text script (https://xxx/rutorrent/js/jquery.js?v=431:2:80933)
    at https://xxx/rutorrent/js/jquery.js?v=431:2:77288
    at l (https://xxx/rutorrent/js/jquery.js?v=431:2:77405)
    at XMLHttpRequest.<anonymous> (https://xxx/rutorrent/js/jquery.js?v=431:2:80204)
plugins.js?v=431:174  Plugin "rss" failed to load: TypeError: theWebUI.createSelectableLabelElement is not a function
    at plugin.onLangLoaded (<anonymous>:5669:14)
    at rPlugin.langLoaded (plugins.js?v=431:172:8)
    at <anonymous>:80:23
    at m (jquery.js?v=431:2:880)
    at Function.globalEval (jquery.js?v=431:2:3031)
    at text script (jquery.js?v=431:2:80933)
    at jquery.js?v=431:2:77288
    at l (jquery.js?v=431:2:77405)
    at XMLHttpRequest.<anonymous> (jquery.js?v=431:2:80204)
rPlugin.langLoaded @ plugins.js?v=431:174
VM41:6571  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'flabel_cont')
    at theWebUI.activeExtTegId (<anonymous>:6571:26)
    at theWebUI.loadTorrents (<anonymous>:6766:25)
    at domUpdates (webui.js?v=431:1739:11)
app.js:1713 init Object
webui.js?v=431:2451 Uncaught TypeError: theWebUI.updateLabel is not a function from TypeError: theWebUI.updateLabel is not a function
    at theWebUI.updateRSSLabels (<anonymous>:4612:11)
    at theWebUI.addRSSItems (<anonymous>:4762:8)
    at Object.<anonymous> (https://xxx/rutorrent/js/rtorrent.js?v=431:1301:22)
    at c (https://xxx/rutorrent/js/jquery.js?v=431:2:25266)
    at Object.fireWith [as resolveWith] (https://xxx/rutorrent/js/jquery.js?v=431:2:26015)
    at l (https://xxx/rutorrent/js/jquery.js?v=431:2:77721)
    at XMLHttpRequest.<anonymous> (https://xxx/rutorrent/js/jquery.js?v=431:2:80204)

**Comment by TrimmingFool** [comment]
@fana13 Hi, it looks like you did not clear your browsers cache but ideally this should not be necessary. Do you have `$cachedPluginLoading = true` in `conf/config.php`?

@TrimmingFool Maybe there should be some version associated with the cache here, or for `CachedEcho` in general?
https://github.com/Novik/ruTorrent/blob/97b431479022ceb1cc81df6b7e234e606bd3e13c/php/getplugins.php#L555-L557

Additionally, caching the `getplugins.php` output does not really work well since at the moment it also contains the output of `init.php`  (see https://github.com/Novik/ruTorrent/issues/2499#issuecomment-1646517506).
If we avoid outputting javascript to `$jResult` in `init.php`  for all plugins, caching would not be a problem.

**Comment by stickz** [comment]
@fana13 It's required to clear your web browser cache when upgrading to `v4.3.x`. Please do that now and let us know the results.

**Comment by fana13** [comment]
Firstable, thanks for your help.
Web browser cache was already clear, that's the first thing i do.

> Do you have $cachedPluginLoading = true in conf/config.php?

No, i did that and i've got same issue

> If you have plugin caching enabled, disable it temporarily to see if the problem is resolved.

I've disabled all plugins one by one and found the wrong plugins, thanks for the tips.

> JS error: [https://xxx/rutorrent/ : 5235] Uncaught TypeError: Cannot read properties of undefined (reading 'push')

It's tracklabels plugin the guilty

> JS error: [https://xxx/rutorrent/ : 3850] Uncaught TypeError: theWebUI.updateLabel is not a function

It's rss plugin the guilty

> JS error: [https://okbebe.myftp.org/rutorrent/ : 4341] Uncaught TypeError: Cannot read properties of undefined (reading 'flabel_cont')

It's extsearch the guilty

**Comment by TrimmingFool** [comment]
>  Web browser cache was already clear, that's the first thing i do.

Please try with cache disabled, see here: https://developer.chrome.com/docs/devtools/network/reference/#change_loading_behavior

The stack trace you provided clearly shows that the plugins are still on an older version. `theWebUI.updateLabel`  and `theWebUI.createSelectableLabelElement` do no longer exist in 4.3.1.

**Comment by fana13** [comment]
Cache disabled in devtools, refresh and same issue

**Comment by TrimmingFool** [comment]
Try searching for `https://github.com/Novik/ruTorrent/wiki/PluginRSS` via `Ctrl + Shift + F` in the `Debugger` tab.

If you updated ruTorrent correctly you should find this: 
```javascript
function () { var plugin = new rPlugin( 'rss',4.3,'Novik','This plugin is designed to fetch torrents via rss download links.',256,'https://github.com/Novik/ruTorrent/wiki/PluginRSS' );
```

**Comment by fana13** [comment]
You're right i see 4.2

> (function () { var plugin = new rPlugin( 'rss',4.2,'Novik','This plugin is designed to fetch torrents via rss download links.',33024,'https://github.com/Novik/ruTorrent/wiki/PluginRSS' );

I don't know why but the plugins folder keep some previous data
I deleted the folder, update rutorrent and now it works !
Thanks for your time and your help guys.
