### ISSUE TITLE
Revert back to previous badge design for better accessibility

### ISSUE THREAD

**Issue by ewenjo** [Novik/ruTorrent#2660]
### Is your feature request related to a problem?

The badge showing the number and size of torrents is very hard to read after the recent updates. 

In my opinion, there's too much padding on the active element and the bold black text on gray background does not contrast nearly well enough.

### Describe the solution you'd like

Redesign or revert back to the previous version

### Additional context

Before 
![image](https://github.com/Novik/ruTorrent/assets/35172239/c9c4665b-1f22-4299-b2e4-a33e7c3a6040)

After
![image](https://github.com/Novik/ruTorrent/assets/35172239/a0c42c05-7dd7-4273-9e99-7e74b9bb887e)

**Comment by stickz** [comment]
What theme are you using? I tested material design and it looks fine.

**Comment by ewenjo** [comment]
> What theme are you using? I tested material design and it looks fine.
I'm using Oblivion

**Comment by stickz** [comment]
I have resolved your problem as requested. I will release `ruTorrent v4.3.2` when more changes are ready.
