### ISSUE TITLE
Views panel always shown, even when disabled from Settings

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [Novik/ruTorrent#2675]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 126.0.6478.61
ruTorrent: v4.3.3
PHP: PHP 8.2.20
OS: Ubuntu 22.04 LTS

### Tell us how you installed ruTorrent

Manual install (upgrade from v4.2.10)

### Describe the bug

The Views panel is always shown, even when disabled from Settings.

### Steps to reproduce

1. Go to Settings > Format
2. Enable or Disable the Views panel

### Expected behavior

When disabled from Settings, the Views panel should no longer be displayed.

**Comment by stickz** [comment]
Thank you for the bug report about the `v4.3` regression. I have resolved the problem and will release a hotfix in the near future.
