### ISSUE TITLE
Feature Request: Improved directory selection in Add Torrent dialog

### ISSUE THREAD

**Issue by albino1** [Novik/ruTorrent#2679]
### Is your feature request related to a problem?

Currently when you try to change a directory in the Add Torrent dialog you get a long list of subfolders with a tiny box and only 8 or 9 actually visible and no real way to quickly navigate them.  There's no standard browser style file selector, and typing to jump down the list only works for each individual letter press.  For example, if you have a subfolder that begins with `star` and you type `s` it jumps to the folders starting with `s`, but when you then hit `t` instead of going to `st` it now jumps down to folders starting with `t`, followed by up to folders starting with `a` and then back down to `r`.

If you only have a few subfolders this isn't a huge deal, but if you have hundreds or thousands it can be a real pain to navigate the tiny box, especially because so few are displayed at any one time.

### Describe the solution you'd like

The solution I would like to see is either a fully implemented standard file selection box, or at a minimum, the ability to type quickly subsequent letters without jumping up and down the subfolder list on each key press.  Maybe even just an autofill on the line if that's simple enough.

Thanks.

**Comment by stickz** [comment]
Hi @albino1. We are working on re-doing the add torrent dialog in #2674. Once completed, I plan to make the textbook bigger, so you can type in the file path manually. Will this address your problem?

**Comment by albino1** [comment]
Certainly a bigger textbox would help as currently you can only see a handful of rows, which makes it difficult and slow to navigate with the mouse wheel, arrow keys, or by dragging the slider.  I do think even something as simple as having the ability to type out `term` and get to folder starting with `term`, instead of ending up on `m`, would go a long ways towards making it more usable though.

**Comment by stickz** [comment]
Completed in version 5 released.
