### ISSUE TITLE
RSS feed with uppercase accented letter À causes display issues

### ISSUE THREAD

**Issue by gandalf764** [Novik/ruTorrent#2689]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 126.0.6478.127
ruTorrent 4.1.5
OS: Debian 

### Tell us how you installed ruTorrent

https://swizzin.ltd/

### Describe the bug

When an RSS feed contains the uppercase accented letter À, all RSS feeds disappear from the rTorrent interface. Although the feeds continue to function in the background, the display is blocked, making it impossible to edit them.

### Steps to reproduce

Add an RSS feed that includes the uppercase accented letter À in one of its items.
Observe that all RSS feeds disappear from the rTorrent interface.

### Expected behavior

RSS feeds should be displayed correctly even if an item contains the uppercase accented letter À. The presence of this character should not block the entire RSS feed display.

### Additional context

This issue causes significant inconvenience as it prevents users from viewing and editing their RSS feeds when an item with the character À is present. Ensuring the display remains functional regardless of the characters in the feed items is crucial for usability.

**Comment by stickz** [comment]
Hello @gandalf764, your version of ruTorrent is outdated. I would recommend upgrading to the latest version.

**Comment by gandalf764** [comment]
I have already tried reinstalling everything to the latest version when I
was troubleshooting the disappearing RSS feeds issue, but it did not
resolve the problem. Therefore, the bug with the uppercase accented letter
À is still present in the latest version of ruTorrent.

---

Feel free to let me know if you need any further adjustments or additional
information!

Il lun 8 lug 2024, 23:36 stickz ***@***.***> ha scritto:

**Comment by stickz** [comment]
> I have already tried reinstalling everything to the latest version when I was troubleshooting the disappearing RSS feeds issue, but it did not resolve the problem. Therefore, the bug with the uppercase accented letter À is still present in the latest version of ruTorrent.

It's required to be on the latest version of ruTorrent to diagnose this issue. It says in your environment in the original issue report you're running ruTorrent v4.1.5. Is this correct?

**Comment by gandalf764** [comment]
Yes, I am currently using version 4.1.5, but to verify that the issue
hasn't been resolved, I installed the latest version of ruTorrent on
another computer using swizzi n.ltd. However, the problem persisted, so I
felt it necessary to report the bug here.

---

Il mar 9 lug 2024, 00:01 stickz ***@***.***> ha scritto:

**Comment by stickz** [comment]
> Yes, I am currently using version 4.1.5, but to verify that the issue hasn't been resolved, I installed the latest version of ruTorrent on another computer using swizzi n.ltd. However, the problem persisted, so I felt it necessary to report the bug here.
> […](#)

Okay, I'm going to close off this issue report, since we don't support version 4.1.5 anymore. Please feel free to open up a new issue report, once running version 4.3.5, so we can properly diagnose and resolve this issue.
