### ISSUE TITLE
Persistent add and create torrent options

### ISSUE THREAD

**Issue by liquid187** [Novik/ruTorrent#2728]
### Is your feature request related to a problem?

it saves time and is used by every user anyway

### Describe the solution you'd like

Is there a way to make the check mark for add torrent fast resum stay permanently? The same with greate new torrent private torrent? Previously it worked by adding a line to the relevant js files. checked=''checked''. This no longer works with the new version.

**Comment by stickz** [comment]
@jevenski We are going straight to `v5.1` next from the master branch. This issue report is authorized for the next release.

**Comment by jevenski** [comment]
> @jevenski We are going straight to `v5.1` next from the master branch. This issue report is authorized for the next release.

Copy that. This issue is going to my next task to accomplish.

**Comment by allixx** [comment]
Can we go even deeper and explore possibility of adding "Presets" feature for "Add torrent" dialog? A preset will contain state of checkboxes, specific download directory, and label. Added presets will be available for choosing via drop-down menu or individual dynamic button in the dialog.

Currently I'm hard-coding those "preset" buttons in personal fork and am finding it very convenient.

**Comment by stickz** [comment]
> Can we go even deeper and explore possibility of adding "Presets" feature for "Add torrent" dialog? A preset will contain state of checkboxes, specific download directory, and label. Added presets will be available for choosing via drop-down menu or individual dynamic button in the dialog.
> 
> Currently I'm hard-coding those "preset" buttons in personal fork and am finding it very convenient.

We need to keep this simple for the first implementation. My suggestion is as follows:
1. Remember the last set of checkboxes for "Add torrent".
2. Remember the last set of trackers, checkboxes and piece size for "Create Torrent".

We can explore the possibility of tracker list presets for "Create Torrent" in `v5.2`.

@jevenski Create torrent already has an `rCache` class with `rtrackers.dat`. It's writing the recent trackers to the webserver and remembering them. We just need to populate the textarea/textbox again, when we refresh the page. https://github.com/Novik/ruTorrent/blob/master/plugins/create/action.php

**Comment by jevenski** [comment]
Yeah, I saw that. I've implemented default options for add torrent using the `theWebUI.settings` object. It has a built in mechanism to read and set WebUI settings so it's relatively easy. Users will be able to check the options on/off in the settings dialog and the options will be set by default. 

As for the create torrent part, I'm still in the middle of figuring out a proper way to utilize the existing class to remember default options and populate the new dialog. Can we just mix the default options within the same class and `.dat` file, or is it a better solution to create a separate class and `.dat` for them?

**Comment by stickz** [comment]
> 
> As for the create torrent part, I'm still in the middle of figuring out a proper way to utilize the existing class to remember default options and populate the new dialog. Can we just mix the default options within the same class and `.dat` file, or is it a better solution to create a separate class and `.dat` for them?

Yes, if you rename the class and the functions to mix the settings all into the same `.dat` file. It makes sense to do this, to avoid loading two `.dat` for the same plugin. All public members are serialized and restored to their original value when `load()` is called. Here's an example implementation you can use with the appropriate getters and setters.

```php
class createTorrentSettings
{
	public $hash = "rcreatetorrent.dat";
	public $modified = false;
	public $recentTrackers = array();
        public $dialogCheckboxes = array();
        public $pieceSize = "4MB";
}
```
This example would require 2 additional request parameters to `action.php`.
1) A list of dialog checkboxes with their true or false state.
2) A piece size parameter for the dropdown menu.

**Comment by stickz** [comment]
@jevenski Please pollute the `settings` object for now in `webui.js`. Any value added to this JS object will automatically save. No PHP code required! I'm going to create a new `PluginSettings.dat` file in ruTorrent `v5.2` to improve performance by:
1) Threading plugin setting loading async without waiting for `getplugins.php`.
2) Eliminate hundreds of lines of code size `getplugins.php` needs to echo.

**Here's an example:**
```
"webui.create_torrent.start_seeding":   0,
"webui.create_torrent.private_torrent": 0,
"webui.create_torrent.hydrid_torrent":  0,
```

**Here's the current settings object:**
https://github.com/Novik/ruTorrent/blob/830b3d698eb6cb3b176b83d1de6a64101cd4b7de/js/webui.js#L134-L193
