### ISSUE TITLE
Mediainfo plug-in text selection and Copy formatting

### ISSUE THREAD

**Issue by chancemon** [Novik/ruTorrent#2729]
### What would you like changed about the web client?

Prior to version 5.0 of the mediainfo plug-in, generated text from the plug-in could be manually selected using the cursor.  
Additionally the pasted output of text copied using the Copy button is missing needed formatting.

### Describe the solution you'd like and propose possible alternatives.

Restore cursor text selection and fix formatting of text copied via the Copy button.

### Provide information and resources about the environment hosting the web client.

Affecting version 5.0.0.

Bug verified in Chrome 129 & Firefox 131.

Installed on Gentoo Linux (rolling release, so no applicable version). Using an ebuild that is functionally identical to https://gitweb.gentoo.org/repo/gentoo.git/tree/www-apps/rutorrent/rutorrent-4.3.7.ebuild

**Comment by mjakopa** [comment]
I concur that this is indeed an issue, since it's now impossible to get mediainfo information in a meaningful way using ruTorrent. The copy button is a welcome addition, but retaining the formatting is a must.

**Comment by stickz** [comment]
> I concur that this is indeed an issue, since it's now impossible to get mediainfo information in a meaningful way using ruTorrent. The copy button is a welcome addition, but retaining the formatting is a must.

We're fixing this shortly and releasing a hotfix.
