### ISSUE TITLE
Table sorting is not saved

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#2735]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 129.0.6668.101
ruTorrent: master: https://github.com/Novik/ruTorrent/commit/b125b6901d23085c784c7fb9d4a3c1e8b55e62c7
PHP: PHP 7.4.3
OS: Ubuntu 20.04.5 LTS
web server: lighttpd/1.4.55

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent

### Describe the bug

New installation v5.1-beta1. Select torrent sorting for example by name. Refresh the page and sorting returns to default.

### Steps to reproduce

New installation v5.1-beta1
1. sort torrents by name
2. refresh page [F5]
3. instead of sorting by name torrents are sorted by default

### Expected behavior

As in older versions, sorting is saved permanently.

**Comment by stickz** [comment]
Thanks so much @koblack for testing our release control version! 
@jevenski This is confirmed as a regression that was introduced before `v5.1-beta 1`.

**Comment by stickz** [comment]
@jevenski This was caused by one formatting changes you made to one of the JavaScript files in #2724. I reverted them, cherry picked the backport for the delete key fix then released Beta 2. https://github.com/Novik/ruTorrent/releases/tag/v5.1-beta2
