### ISSUE TITLE
JS error: [ : 883] Uncaught TypeError: plugin.refresh is not a function

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#2751]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Web Browser: Google Chrome 130.0.6723.70
ruTorrent: master: https://github.com/Novik/ruTorrent/commit/1244f9f77fe6bddc40583c9b4e6408adc84c4538

### What were you trying to do?

Try add or remove icon for tracker on side panel.

### What us the error message?

JS error: [ : 883] Uncaught TypeError: plugin.refresh is not a function

### Give us the stack trace.

Uncaught TypeError: plugin.refresh is not a function from TypeError: plugin.refresh is not a function
    at request.onloadend (<anonymous>:883:779)

**Comment by stickz** [comment]
@jevenski I've marked this as a confirmed bug with priority critical. It's calling a function here which is non existent. This is a blocker before I can post `v5.1 Beta 3` and ultimately the stable release of `v5.1`.
https://github.com/Novik/ruTorrent/blob/1244f9f77fe6bddc40583c9b4e6408adc84c4538/plugins/tracklabels/init.js#L248
