### ISSUE TITLE
rssurlrewrite: unable to select feed

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#2832]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 131.0.6778.140
ruTorrent: develop: https://github.com/Novik/ruTorrent/commit/5061f71aea623037454f97bdc3bfaf32bc2a766e
PHP: PHP 7.4.3
OS: Ubuntu 20.04.6 LTS
web server: lighttpd/1.4.55

### Tell us how you installed ruTorrent

git clone --branch develop https://github.com/Novik/ruTorrent

### Describe the bug

After cd972d75203de1866b60082ad343aa7a7cb01971
Unable to select RSS feed when creating a new rule using rssurlrewrite manager.

![example](https://github.com/user-attachments/assets/521c21bb-5d73-4cee-a41c-8eb8fed6fff7)

### Steps to reproduce

1. add more than one RSS feed
2. add a new rule using rssurlrewrite manager
3. try to select target feed

### Expected behavior

Like before cd972d75203de1866b60082ad343aa7a7cb01971

![example](https://github.com/user-attachments/assets/d00363f1-2797-4310-b5cb-fd0879b00f1a)

**Comment by stickz** [comment]
@jevenski Could we post a hotfix on `v5.1` for this problem? It's looks like a regression from the plugins dropdown menu on mobile.

**Comment by jevenski** [comment]
Yes, indeed. Will take a look into this one.
