### ISSUE TITLE
PluginRSS: Episode Tracking

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#297]
_From [craig.ba...@gmail.com](https://code.google.com/u/111843903376184693718/) on February 25, 2010 01:38:55_

What steps will reproduce the problem? Setup an RSS feed that provides multiple duplicate episode entries,
irrelevant of group - that appear multiple times over the course of a month. What is the expected output? What do you see instead? Due to the match appearing more than once, you end up downloading duplicate
episodes of a show. Also - because the episode may show 2, 3 or even 4
times a month OR week - the "Match only..." drop-down does not help.

Due to the releases being from different groups - there's no way to
explicitly define the RegEx against a group due to fear's of missing an
episode. (Maybe one month a particular group misses an episode from a
specific show).

This is using the current 3.0 Beta SVN.

The solution would be to add season/episode tracking to the filters.
uTorrent already does this behind the scene's, along with other Python
based broadcatching clients.

For example - you could setup a simple filter that looks for the show LOST.
Whenever a match is made, the plugin would mark the season and episode of
that show. Whenever the next match is made, the episode would increment by
one. Whenever a season increment is found, it would increment the season
counter by one.

uTorrent provides no GUI (as far as I'm aware) for this - but does it
behind the scenes. TorrentWatch-X provides this, and gives you the ability
to modify the current season and episode counters for each filter. rssdler
(a python script) does this too, however it modifies the filter expression
automatically dependant on the matched episode. This way is a little more
clunky as it requires you to use a specific RegEx expression.

The best approach I think is TorrentWatch-x's - as it allows you to modify
the values. However, if written well - there's no reason why it couldn't be
done behind the scenes like uTorrent.

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=299_

**Comment by JohnCaboose** [comment]
I would love this feature, please implement it soon. <3

**Comment by KaffeMyers** [comment]
Trying the development build Novik-ruTorrent-7255d2b.tar.gz, can't see this feature present. 

+1 for this feature built in!
