### ISSUE TITLE
Feature Request:  Browse items via the keyboard (arrow keys)

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#416]
_From [Wonslung@gmail.com](https://code.google.com/u/Wonslung@gmail.com/) on May 22, 2010 04:41:52_

This is a Feature Request for: I would like to be able to browse items via the arrow keys in such a way that it highlights the very 
next item when you hit DOWN ARROW or UP ARROW.

This would be nice for the entire PROGRAM, but especially nice for the RSS Manager Filter list

Frankly, this would be awesome on the torrent list as well.  Imagine having the General tab 
selected, and also having a torrent highlighted....pushing "down arrow" would allow you to 
quickly access more information about items in the program.  The power of this improves greatly 
when you cross it with the "local search" feature.

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=413_

**Comment by bingoxo** [comment]
can this be reconsidered ?
