### ISSUE TITLE
[Win] Add torrent files to ruTorrent from explorer

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#423]
_From [hapy.les...@gmail.com](https://code.google.com/u/104120494460694758578/) on June 03, 2010 16:25:39_

Это  удобняшка.  Надоело мне добавлять файлы через веб интерфейс, особенно 
с непонятными названиями торент файлов, когда их переваливает за 5 штук. 
Намного удобнее что бы они добавлялись как и на обычном клиенте(обычным 
кликом на торент файле). Для этого написал простую програмку на С# которая 
делает тоже самое что POST запрос.

описание аттачей: 

1) 1.reg Пример как зарегать прогу (асоциация расширения) + привязать этот 
класс надо на .torrent расширение
2) rtorrent.rar - архив проэкта вместе с ехе файлами (VS.NET 2010 Express)
3) rtorrent.exe  - готовый бинарник

**Attachment:** [1.reg rtorrent.rar rtorrent.exe](http://code.google.com/p/rutorrent/issues/detail?id=425)

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=425_

**Comment by TMTYD** [comment]
thx
