### ISSUE TITLE
Send to Seedbox workflow for Mac

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#451]
_From [andsens@gmail.com](https://code.google.com/u/andsens@gmail.com/) on July 21, 2010 23:48:19_

Hey guys,

I like your software quite a lot and made it a bit easier for myself to add torrents manually.
This will only work on mac. The shell script contained inside the workflow also works for linux though.
I thought I'd share this with you in the hope that it will save somebody else some time.

/andsens
andsens@gmail.com

**Attachment:** [Send to Seedbox.zip](http://code.google.com/p/rutorrent/issues/detail?id=453)

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=453_

**Comment by DASPRiD** [comment]
If you are using Firefox, you can use this addon which directly sends torrents to RuTorrent (and other clients), even from private trackers: https://dasprids.de/mozilla-addons/tfluxadd/tfluxadd-latest.xpi
