### ISSUE TITLE
JS error, "this.dBody"

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#586]
_From [optiix...@gmail.com](https://code.google.com/u/106131281743149472332/) on May 20, 2011 02:33:50_

What steps will reproduce the problem? 1. Surfing to www/rutorrent. What environment are you using? 1. My ruTorrent version is: 3.2
2. My rTorrent version is: 0.8.8
3. My libTorrent version is: 0.12.8
4. I use web-server: lighttpd on OS: Ubuntu 10.10
5. I use browser: Firefox

I followed this guide from the beginning: http://filesharefreak.com/2010/02/13/how-to-install-rtorrent-rutorrent-using-socket-ssl-authentication-on-ubuntu-or-debian/ . Then some links and so were broken so I found info on r-/libTorrents own homepage and RuTorrents own page and got it working from there with just "rtorrent" in console.

This is the second time I try this. Last time I got the same error in Ubuntu 11.04. (I downgraded not cuz of this. It was becuase problems between Ubuntu 11.04 and XBMC (The movie died every time I started it inside XBMC with Ubuntu 11.04!)

Enough about that. This is what the RuTorrent says on it's page: [20.05.2011 02:13:12] JS error: [http://192.168.1.51/rutorrent/js/stable.js : 1701] this.dBody is undefined
[20.05.2011 02:13:23] JS error: [http://192.168.1.51/rutorrent/js/stable.js : 1701] this.dBody is undefined

It happens every time I press like the "Downloading" or "Completed" button. THEN, after I've been trying the homepage (clicking Downloading and Completed a couple of times just to see so it's not just laggy. Rtorrent wont start from console again. It give me this msg: rtorrent: Error in option file: ~/.rtorrent.rc:123: Could not prepare socket for listening: Address already in use. This is proberbly becuase an instance already running. Im farly new to linux...

Is there just some error in this java file that the dev-team will be helpfull to fix? If it now even is a programming error due to rtorrent 0.88? :|

Hope I didnt flum out on you to much. I just wanted to give you guys all the info so that It would be easier to sort this error out!

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=588_

**Comment by henning-schild** [comment]
`this.dBody is undefined` seems to be when your browser still has on old version of that file cached, might have to clear browser caches when the server changes its version of rutorrent
