### ISSUE TITLE
Download multiple torrents from ruTorrent

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#796]
_From [kolorkode](https://code.google.com/u/kolorkode/) on February 02, 2013 13:11:45_

Requesting Feature

Download multiple torrents at once via zip file.
Please see http://forums.rutorrent.org/index.php?topic=4183.0

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=798_

**Comment by alexcoe** [comment]
The thridparty filemanager plugin supports this.
