### ISSUE TITLE
Diskspace plugin ain´t showing correct info!

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#806]
_From [pontus.o...@gmail.com](https://code.google.com/u/101992265081868507572/) on March 11, 2013 16:55:30_

What steps will reproduce the problem? 1. Install ruTorrent + rTorrent on RHEL 6.3!
2. Unpack the plugins-3.5.tar.gz and move them to right folder! 3. What is the expected output? What do you see instead? My diskspace? I only see 10&#37; and a disk that is 50GB large, my disk is 2TB large! What environment are you using? 1. My ruTorrent version is... 3.5
2. My rTorrent version is... 0.9.2
3. I use web-server Apache it version is 2.2.15 on OS RHEL 6.3
4. I use browser Firefox it version is 19.0.2 on OS OS X 10.8.2 Are some errors present in the web-server log? Are some errors present in the browser error console? Please provide any additional information below.

**Attachment:** [2013-03-11 16.31.19.jpg](http://code.google.com/p/rutorrent/issues/detail?id=808)

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=808_

**Comment by TMTYD** [comment]
Hi the diskspace plugin shows me the wrong mount point, how can I fix this?

It shows me 3.5 gb of 4.7gb which is the mount point of / dev / md1, but my location is / dev / sda6 and / dev / sdb6, how can I change this?

**Comment by TMTYD** [comment]
no fix for this ?
