### ISSUE TITLE
Alphabetical Labels with AutoTools

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#888]
_From [sveinn.d...@gmail.com](https://code.google.com/u/112264433611949366785/) on January 31, 2014 16:30:40_

What steps will reproduce the problem? 1. Upload torrent to server, using AutoTools to watch, label, and move file when completed.
2. Label list in sidebar and context-menu are created as expected, but is sorted by date created, not alphabetically. What is the expected output? What do you see instead? I expect lists to be in alphabetical order, not by date created. What environment are you using? 1. ruTorrent 3.6
2. rTorrent 0.9.3/0.13.3
3. Nginx 1.2.1 on Debian 3.2.51-1 x86_64
4. Chrome 32.0.1700.102 on OS X 10.9.1 Are some errors present in the web-server log? No. Are some errors present in the browser error console? No. Please provide any additional information below. Worked as expected on an older setup (using manual watch-folders in the rtorrent config).

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=892_

**Comment by WindfallProphet** [comment]
Are the labels stored plain-text anywhere? Could I sort them alphabetically manually?
