### ISSUE TITLE
Can't delete torrent and torrent data

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#910]
_From [jacopoca...@gmail.com](https://code.google.com/u/114892175578583987176/) on June 23, 2014 09:11:21_

What steps will reproduce the problem? 1. Click on a torrent row
2. Click the X button on the tool bar or Right click on the torrent and Delete and erase data What is the expected output? What do you see instead? rtorrent doesn't delete the .torrent or the .meta What environment are you using? 1. My ruTorrent version is 3.6 svn 2404
2. My rTorrent version is 0.9.4
3. I use web-server Apache it version is 2.4.7 on Ubuntu 14.04
4. I use browser Chrome 35.0.1916.153 on OS X 10.9.3

Rtorrent error on console:
Event 'event.download.erased' failed: Could not find '='.

Issue notified also https://github.com/rakshasa/rtorrent/issues/201 but I really don't understand the answer

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=914_

**Comment by EnduringGuerila** [comment]
When I try to delete torrent and files on ruTorrent, I get this error now (in rtorrent):

Event 'event.download.erased' failed: Bad return code.

The torrent gets deleted from the ruTorrent list but the files remain
