### ISSUE TITLE
Label characters encoded incorrectly

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#913]
_From [kran...@gmail.com](https://code.google.com/u/106280890180929114372/) on June 25, 2014 16:58:32_

When using label (d.custom1) to store, for instance, target directory -- the resulting path gets encoded incorrectly.

Example:
/var/downloads/rTorrent/finished/tvshows/

becomes 
&#37;2Fvar&#37;2Fdownloads&#37;2FrTorrent&#37;2Ffinished&#37;2Ftvshows&#37;2F/

Which means the torrent's data gets moved to a /home/username/&#37;2Fvar&#37;2Fdownloads&#37;2FrTorrent&#37;2Ffinished&#37;2Ftvshows&#37;2F/ and rTorrent doesn't find it and is unable to seed. What steps will reproduce the problem? 1. Use the following method for moving torrents to custom dir when finished (in rtorrent.rc):

system.method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_custom1= ;execute=mv,-u,$d.get_base_path=,$d.get_custom1="
1. Set label of torrent in ruTorrent to a valid path.
2. Wait for torrent to finish downloading. What is the expected output? What do you see instead? What environment are you using? 1. My ruTorrent version is 3.6
3. My rTorrent version is 1.9.2
4. I use web-server lighttpd on Ubuntu
5. I use browser Chrome it version is 35 on Windows 7 64-bit. Same problem with IE11 on same machine.

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=917_

**Comment by Jolly-Pirate** [comment]
I created a fix for it https://github.com/Jolly-Pirate/rtorrent-snippets/tree/master/fix-urlencoded-label
