### ISSUE TITLE
Change filename from conf/config.php

### ISSUE THREAD

**Issue by Nightreaver** [Novik/ruTorrent#954]
So, you moved to github which is very cool, thanks for that!

To make the update process a more conflict less it would be nice to rename the conf/config.php to something like default_config.php or so.

Without that everytime I pull I will get a conflict or get my settings overwritten which is not so cool.

I think this the reason why other projects handle this by having the default file named anything with default so its save against overwriting.

would be a nice improvement, but just a suggestion.

thanks

**Comment by alexcoe** [comment]
If you checkout with SVN you can view and chose which conflicts exist.
