### ISSUE TITLE
adding torrent is said successful when it's not if using same hash

### ISSUE THREAD

**Issue by euri10** [Novik/ruTorrent#958]
trying to add a torrent whose hash is the same as one already loaded, rutorrent says that torrent has been loaded successfully, but it doesn't appear and rightly so as rtorrent didn't add it for that reason : (16:16:28) Could not create download: Info hash already used by another torrent.

that would be more accurate NOT to have this successfully added message in rutorrent and if possible the reason :)

thanks

**Comment by pyroscope** [comment]
It is quite easy to check for load success, by calling `d.name` or something similar harmless against the *calculated* hash of the just loaded metafile. Besides using `load.verbose`, so the curses log also shows the problem.
