### ISSUE TITLE
Edit several torrent from same tacker at once

### ISSUE THREAD

**Issue by andresayang** [Novik/ruTorrent#964]
Hi,
I had a trouble with one of my tracker and was oblige to update the tracker address.
Could it be possible to add this possibility ? => edit several torrent at once, if they are from the same tacker ?

Thanks.

**Comment by Novik** [comment]
Sorry, but this is a not task of front end and its implemenatation is not so easy. Each torrent may have several groups of trackers, each group - several trackers. And here we have a lot of questions, for example - is one torrent equal to another if its have some trackers, but in the different groups? Etc.
