### ISSUE TITLE
Ban peers

### ISSUE THREAD

**Issue by Flayor** [Novik/ruTorrent#967]
Hi

How can you ban a list of peers already doing?

thank you

**Comment by Novik** [comment]
I tried to fix that, but really i can't understand, how rtorrent interpret command `p.banned.set`.
If i use it as standalone, then it doesn't work at all. If i use p.disconnect after it, then we have disconnect behavior only. Really this is a question to the rtorrent author.

**Comment by Flayor** [comment]
ok thank you I will contact him :)
