### ISSUE TITLE
Cannot delete torrent and torrent data

### ISSUE THREAD

**Issue by jwshields** [Novik/ruTorrent#968]
rtorrent: 0.9.2/0.13.2
ruTorrent: git commit a52086b75b9b7f35842165b4b99c593a4ba71684

I have found a number of other topics relating to this. the issue is still present.

https://github.com/Novik/ruTorrent/issues/910
- not a valid fix as I have options in rtorrent that the -D flag will not work with

https://github.com/Novik/ruTorrent/issues/622#issuecomment-53097242
- I receive the first of the two errors which are listed, but my files still are not removed

**Comment by SephirothTP** [comment]
Hi

The bug was fixed in rtorrent 0.9.4/0.13.4.

Please update with the github depot.

And retry
