### ISSUE TITLE
create plugin makes private torrent

### ISSUE THREAD

**Issue by tritonas00** [Novik/ruTorrent#971]
I set transmissioncreate as create method.

The generated torrent seems to have private bit, even if i dont set it in the options.

If i do it manually (transmission-create file) the torrent is ok.

Also the same happens with mktorrent.

What i miss here?

Tried on TPB

**Comment by rikiry** [comment]
That's nothing. .go to 'home/USSER-NAME/.rtorrennt.rc' and chenge this'DTH=AUTO'  with set 'DTH=yes'

**Comment by tritonas00** [comment]
Thanks dh t= on did the trick.

**Comment by kiboni** [comment]
HI,

Please help, DHT = on won't work with me :/

I use rutorrent v3.6 and v3.6 plugins, when i create torrent without checking "private torrent" box and upload on ExtraTorrent it's shows Private Torrent.... http://i.imgur.com/ClXyT6N.jpg  ?

**Comment by rikiry** [comment]
ok, may be u not setup .rtorrent.rc file...or not setup external torrent maker in rtorrent/conf.php . useing like 'mktorrent'.

**Comment by tritonas00** [comment]
well, i use the latest rutorrent and plugins from git, its internal script to create torrents and DHT = on in .rtorrent.rc (all in archlinux)

i uploaded in kickass fine, no problem.

**Comment by kiboni** [comment]
my .rorrent.rc file is located at /home/admin/.rtorrent.rc , did't create external torrent maker, just wanna use internal like @tritonas00 . Also used latest (v3.6) rutorrent with plugins from git but i have this annoying bug.  Don't know is the problem is in "create" plugin or .rtorrent.rc configuration file...  Please send me .rtorrent.rc to check am i set everything right.

Now it's set with:
 dht = on
peer_exchange = yes
use_udp_trackers = yes

**Comment by tritonas00** [comment]
min_peers = 40
max_peers = 800
max_memory_usage = 1512M
min_peers_seed = 10
max_peers_seed = 52
max_uploads = 8
directory = /home/.../Torrents
session = /home/..../.session/
port_range = ...-...
check_hash = yes
use_udp_trackers = yes
dht = on
dht_port = 6881
peer_exchange = yes
scgi_port = 127.0.0.1:5050

**Comment by kiboni** [comment]
Tnx, i tried all but seems it's not rtorrent.rc problem... I doubt on 'create' plugin.

will try with some external create plugin, if you know some tutorial 'how to' pls post.

**Comment by kiboni** [comment]
omg, i just use external (mktorrent) plugin to create and still torrents are private??? what a hell!

**Comment by tritonas00** [comment]
there is no problem in kickass.

ok, i created an account in extratorrent to upload something and i will give you feedback

**Comment by rikiry** [comment]
your .rtorrent.rc file is not correctly configuration for performing public torrent  create. ..
for more support contract me..

**Comment by rikiry** [comment]
webmaster@teentorrent.com

**Comment by rikiry** [comment]
ok...
Change this...
under /home/USSER-NAME/.rtorrent.rc

dht_port = 6881
with
#dht_port=6881

**Comment by kiboni** [comment]
try but not working either :/

btw my .rtorrent.rc file is located here /root/rtorrent.rc    when i try to move him in /home/username/  rtorrent client won't start.

I sent you email.

**Comment by rikiry** [comment]
1... Wht is your Server/Vps type?
2.... R u really complete rtorrent instalation or rutorrent installation?

**Comment by tritonas00** [comment]
well, i created a torrent with internal and uploaded just fine in extra torrent, no complains for private torrent

so there is something wrong with your configuration somewhere :(

**Comment by tritonas00** [comment]
well, PLEASE IGNORE my above post, i can confirm that the torrent shows as private there:( (there is a P flag)

in kickass there is no problem

**Comment by kiboni** [comment]
Hey Guys,

I manage to fix issue but i needed to edit some lines in create plugin. It's not problem .rtorrent.rc configuration file, bug is in create plugin v3.6.
To disable making private torrents edit/comment this lines: 

createtorrent.php:
 #if(isset($request['private']))
 #$torrent->is_private(true);

correct.php:
#if(isset($request['private']))
#$torrent->is_private(true);

action.php:
#'private'=>$_REQUEST['private']

**Comment by tritonas00** [comment]
so the create plugin needs to be fixed.

thanks kiboni!

**Comment by Micdu70** [comment]
Create plugin fixed. :)

**Comment by tritonas00** [comment]
Indeed! Thank you very much!
