### ISSUE TITLE
Unpack plugin: Append to pathname when unpacking 

### ISSUE THREAD

**Issue by beltoft** [Novik/ruTorrent#973]
Append to pathname when unpacking is not working

No matter if Torrent Name or Torrent Label is ticked the torrent will be unpacked to dir specified above

**Comment by Novik** [comment]
Sorry, but i can't reproduce this. Try to use development version of ruTorrent.

**Comment by He4dShOt** [comment]
It seems it was a permissions problem for me, that nevere happend with the old version. I had to set the profle mask like this: "$profileMask = 0770;"

**Comment by Novik** [comment]
> "$profileMask = 0770;" 

In this case web-server and rtorrent user must have one primary group.

**Comment by He4dShOt** [comment]
Yes, they do.

**Comment by beltoft** [comment]
1: how do I install the dev version?

2: where do I set the profile mask?

**Comment by Novik** [comment]
Try to read project's wiki.

**Comment by beltoft** [comment]
tried to change profilemask to 0770 and got a lot of plugin errors so i changed it back to 0777

cant find anything about dev version in wiki

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/archive/master.zip
or use git.
