### ISSUE TITLE
ruTorrent Error: 200 - parsererror,getuisettings - Arch Linux

### ISSUE THREAD

**Issue by coxley** [Novik/ruTorrent#974]
Using rtorrent 0.9.4 on ArchLinux.
ruTorrent version is 3.6 - brand new git clone.
Nginx as webserver.
/RPC2 path configured properly and am able to use xmlrpc to fetch status. Example:

```
$ xmlrpc localhost/RPC2 system.client_version            
Result:

String: '0.9.4'
```

FastCGI setup appropriately with PHP-FPM.

Issue: I get a single error in the rutorrent log, which is `Bad response from server: (200 [parsererror,getuisettings])`

Screenshot here: 
![rutorrent_error](https://cloud.githubusercontent.com/assets/8285973/5211179/e40c0f82-75a9-11e4-95ef-df078683c9ea.png)

I wouldn't create an issue without doing the proper research and I've done a lot of RTFM the past couple days on and off. I haven't seen anyone else with the same error as me unless it was accompanied with some php error after the bad response.

**Comment by piratx** [comment]
Where is that line? grep won't help, need to search all files manually.. :)

**Comment by baoyankun** [comment]
I am having the same problem.
...and yes, there are no rTorrent/share/users/USERNAME/settings/uisettings.json and rTorrent/share/settings/uisettings.json.

I can confirm the fix by @coxley works!
Just another change, because I'm using php5-fpm, I need to replace
```
fastcgi_pass   127.0.0.1:9000;
```
with
```
fastcgi_pass unix:/var/run/php5-fpm.sock;
```

Thanks!

**Comment by Maelstrome26** [comment]
Can confirm I hit this issue as well, but with PHP7. Had to make sure the file path was correct as it's changed in PHP7:

`fastcgi_pass   unix:/var/run/php/php7.0-fpm.sock;`

**Comment by gawbul** [comment]
@Maelstromeous Same issue for me too, although I was using Apache, and needed to enable some additional config/modules (using reverse proxy so `proxy_fcgi`)

**Comment by sam-banks** [comment]
I can confirm that coxley's change resolved the issue for me also - thanks!

**Comment by jwittlincohen** [comment]
I recently ran into this issue after an upgrade from Debian Wheezy to Debian Jessie.  The solution was slightly different for me as me as my /etc/nginx/sites-enabled/default config referenced /etc/nginx/conf.d/php.

Adding the following lines fixed the issue:

  fastcgi_param SCRIPT_FILENAME $request_filename;
  fastcgi_read_timeout 300;

The complete config file appears as follows:

location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $request_filename;
          fastcgi_read_timeout 300;
