### ISSUE TITLE
Official Debian/Ubuntu package

### ISSUE THREAD

**Issue by mcandre** [Novik/ruTorrent#988]
Could we please get an official Debian/Ubuntu package up for ruTorrent to make it easier to setup?

**Comment by SephirothTP** [comment]
You can juste install apache2, php5 and get rutorrent's folder to /var/www ....

how hard can it be ....

**Comment by mcandre** [comment]
ruTorrent is not the only software I setup. Multiply the time it takes to manually install one package, by a dozen or so packages, and it quickly adds up to many hours, per device.

If we could bundle a basic .deb package for ruTorrent, it would make installation much easier for Linux newbies, and we could stand to increase adoption rate as well.

**Comment by SephirothTP** [comment]
The deb is not a solution
Many step it's not possible with .deb
Contact me to support@flayor.com
I can help you to the install

**Comment by mcandre** [comment]
I don't want to have to email anyone for instructions. I want to `apt-get
install rutorrent` and get on with my life.

It's okay though, `sudo apt-get install transmission-daemon` works out of
the box.

On Fri, Jan 9, 2015 at 6:07 PM, SephirothTP <notifications@github.com>
wrote:

> The deb is not a solution
> Many step it's not possible with .deb
> Contact me to support@flayor.com
> I can help you to the install
>
>
>
> > Le 10 janv. 2015 à 00:58, Andrew Pennebaker <notifications@github.com>
> a écrit :
> >
> > ruTorrent is not the only software I setup. Multiply the time it takes
> to manually install one package, by a dozen or so packages, and it quickly
> adds up to many hours, per device.
> >
> > If we could bundle a basic .deb package for ruTorrent, it would make
> installation much easier for Linux newbies, and we could stand to increase
> adoption rate as well.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Novik/ruTorrent/issues/988#issuecomment-69424003>.
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us

**Comment by SephirothTP** [comment]
It's not possible to install with deb.

For the conf in rtorrent etc ....

Many script exist on github for the auto install....

**Comment by Kerwood** [comment]
Jesus christ mcandre. If its so time consuming, make a shell script or find a script that already suits your needs.. 
https://github.com/Kerwood/rtorrent.auto.install/

**Comment by mcandre** [comment]
It might not seem like a lot of time to wrap rTorrent in a package, but I try out a lot of software each day, and the minutes all add up to wasted time.

It's cool, I went with transmission anyway.
