### ISSUE TITLE
EXT Search no results for pretome

### ISSUE THREAD

**Issue by danielnolan** [Novik/ruTorrent#992]
I submitted a patch to update the url for pretome.info https://github.com/Novik/ruTorrent/pull/987. Even after updating the url when I search, no results are returned. I have tried to use toLog() in the PretoMe.php engine file to see if there are results coming back, but I can't seem to get rutorrent to write to the log.

**Comment by Novik** [comment]
Sorry, but I can't help, because I doesn't have account on PretoMe.

> I have tried to use toLog() in the PretoMe.php engine file to see if there are results coming back

It write results to /tmp/errors.log (by default). But you can use php standard function `error_log` and check web-server's error log for results.
