### ISSUE TITLE
Creating and Deleting problems

### ISSUE THREAD

**Issue by DeNeDe** [Novik/ruTorrent#993]
I'm using rTorrent/libtorrent 0.13.3 with ruTorrent 3.6 and i've noticed yesterday that when I want to create a .torrent file it always give me PHP Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 20240 bytes) in Unknown on line 0
I have two servers, 1# with 64GB RAM and #2 with 96GB RAM. In php.ini memory_limit is set at 256MB.
Just discovered this because I've never used it for creating, just downloading torrents.
Also another issue that i've seen is that when I want to delete a torrent from the list, it doesn't delete the data (using Remove and... Delete the data), I always need to go in ftp and delete it myself.

edit:
updated to 0.9.4/0.13.4 and still same issues..
using rutorrent from github master

**Comment by Novik** [comment]
> Allowed memory size of 262144 bytes exhausted (tried to allocate 20240 bytes
> In php.ini memory_limit is set at 256MB

And? What is your point? This is a normal behavior. Increase memory_limit if you want to create something.

> Also another issue that i've seen is that when I want to delete a torrent from the list

Try to set variable $erasedebug_enabled to  true in the plugins conf.php, delete something, wait 5-10 min and paste here contents of file /tmp/errors.log.

**Comment by DeNeDe** [comment]
Memory is set to 256MB.. it's already to high. No script should eat that much. and in fact it doesn't even eat 256MB. after 20240 bytes it crashes and it has allocated 262144 bytes.
see the difference? it doesn't even reach the limit.

**Comment by Novik** [comment]
> Allowed memory size of 262144 bytes 

262144 bytes = 256K, not MB. See the difference? Configure your php by yhe normal way.

**Comment by DeNeDe** [comment]
it says MB on phpinfo so you might maybe want to try and fix your plugins ;)

**Comment by Novik** [comment]
Yet once. PHP say to you - "Allowed memory size of 262144 bytes". This is 256K. Plugins hasn't relation to this.
Try to RTFM.
http://php.net/manual/en/faq.using.php#faq.using.shorthandbytes
Just a point - you must write in ini file "256M", not "256MB".

**Comment by DeNeDe** [comment]
it is written M. it's not like i've started using webserver 2 hours ago. I know what i'm doing.

**Comment by Novik** [comment]
In this case you can't see in log words like "Allowed memory size of 262144 bytes". Sorry, but i can't say to you something more.

> I know what i'm doing.

This is a great.
