### ISSUE TITLE
Failed to load plugins wich need external applications if partition is mounted with noexec flag

### ISSUE THREAD

**Issue by DipSwitch** [Novik/ruTorrent#997]
OpenMediaVault mounts it's NAS filesystem with the noexec flag. So if I where to install ruTorrent on in a Shared Folder this would make ruTorrent unable to load it's plugins due to the usage of `test.sh`

![image](https://cloud.githubusercontent.com/assets/476484/5889359/024c6df6-a422-11e4-9336-9e81dd052681.png)

This could be avoided by letting `/bin/sh` load and execute `test.sh` instead of executing `test.sh` itself.

**Comment by Greqs** [comment]
Try:

chmod 777 -R /var/www/rutorrent/share

If your rutorrent share folder is in above location

**Comment by DipSwitch** [comment]
That doesn't work since it's not permitted to start test.sh

root@epicserver:/rutorrent/php # su www-data -c ./test.sh
sh: 1: ./test.sh: Permission denied
root@epicserver:/rutorrent/php # ./test.sh
bash: ./test.sh: Permission denied
root@epicserver:/rutorrent/php # su www-data -c 'sh ./test.sh && echo $?'
0

**Comment by DipSwitch** [comment]
dipswitch@epicserver:~/dev/ruTorrent $ mount | grep md0p1
/dev/md0p1 on /media/218a6a64-a854-454b-9ce0-703f8d90b008 type ext4 (rw,noexec,relatime,user_xattr,acl,barrier=1,stripe=384,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group,_netdev)

**Comment by DipSwitch** [comment]
Oke, after a fresh look I found out why the test wouldn't succeed without a double call to `sh`

    $req = new rXMLRPCRequest(new rXMLRPCCommand("execute", array( "sh", addslash($path)."test.sh", $exe, $st, $add)));

There was not suppose to be a dot between `$st` and `$add` since they where two arguments. And since we don't want sh to execute a command via the shell interpreter we don't have to `escapeshellarg` the arguments... So now they `log.error=...` prints:

	sh -c /usr/bin/id -u ; /usr/bin/id -G ; echo ~

	---
	Captured output:
	1002
	100 33 37 1001
	/media/218a6a64-a854-454b-9ce0-703f8d90b008/torrents
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh php /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/989902797  '/usr/bin/php'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh curl /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/1574361650  '/usr/bin/curl'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh pgrep /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/476520996  '/usr/bin/pgrep'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh unzip /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/822823404  '/usr/bin/unzip'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh unrar /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/1324848663  '/usr/bin/unrar'
	--- Success ---

The plugins load and there is no execution denial on the `test.sh` file although there is a `noexec` options on the mounted file system.
